#!/usr/bin/env python3
"""Lower the pinned Camera_Update body to target-width C++."""

from __future__ import annotations

import argparse
import hashlib
import pathlib


EXPECTED_SOURCE_SHA256 = (
    "4c6d134cebc3049e2c367e7918ceb5c4edc1a54baa646326617fdd1f2db14b0f"
)
START_TOKEN = "typedef struct Oot3dCameraShake"
END_TOKEN = "#undef OOT3D_F32"


def replace_exact(source: str, original: str, replacement: str, count: int = 1) -> str:
    actual = source.count(original)
    if actual != count:
        raise RuntimeError(
            f"expected {count} occurrence(s) of source fragment, found {actual}: "
            f"{original!r}"
        )
    return source.replace(original, replacement, count)


def lower(source: str) -> str:
    start = source.find(START_TOKEN)
    end = source.find(END_TOKEN)
    if start < 0 or end < 0 or end <= start:
        raise RuntimeError("Camera_Update maintained body boundaries not found")
    body = source[start:end].rstrip()

    body = replace_exact(
        body,
        "Oot3dVec3s Camera_Update(void* cameraPointer) {\n"
        "    const uintptr_t camera = (uintptr_t)(u32)(uintptr_t)cameraPointer;",
        "Oot3dVec3s Camera_UpdateImpl(std::uint32_t camera) {",
    )
    body = replace_exact(
        body,
        "        memcpy(\n"
        "            (void*)OOT3D_ADDR(camera, 0xDC),\n"
        "            &currentPlayer,\n"
        "            0x12\n"
        "        );",
        "        WriteGuestMemory(\n"
        "            OOT3D_ADDR(camera, 0xDC), &currentPlayer, 0x12);",
    )
    body = replace_exact(
        body,
        "        void (*cameraFunction)(void*) =\n"
        "            (void (*)(void*))(\n"
        "                uintptr_t\n"
        "            )OOT3D_U32(DAT_002d8c20, functionIndex * 4);\n\n"
        "        cameraFunction((void*)camera);",
        "        const std::uint32_t cameraFunction =\n"
        "            OOT3D_U32(DAT_002d8c20, functionIndex * 4);\n\n"
        "        InvokeDynamicCameraFunction(cameraFunction, camera);",
    )
    body = replace_exact(
        body,
        "                if (FUN_002d064c(play + 0xA98, floorPoly, bgId) == 0) {",
        "                if (FUN_002d064c(play + 0xA98, bgCamIndex, bgId) == 0) {",
    )

    pod_replacements = {
        "viewAt = *(Oot3dActorVec3f*)OOT3D_ADDR(camera, 0x80);":
            "viewAt = ReadGuestPod<Oot3dActorVec3f>(\n"
            "            OOT3D_ADDR(camera, 0x80));",
        "viewEye = *(Oot3dActorVec3f*)OOT3D_ADDR(camera, 0x8C);":
            "viewEye = ReadGuestPod<Oot3dActorVec3f>(\n"
            "            OOT3D_ADDR(camera, 0x8C));",
        "viewUp = *(Oot3dActorVec3f*)OOT3D_ADDR(camera, 0x98);":
            "viewUp = ReadGuestPod<Oot3dActorVec3f>(\n"
            "            OOT3D_ADDR(camera, 0x98));",
        "*(Oot3dActorVec3f*)OOT3D_ADDR(camera, 0x98) = viewUp;":
            "WriteGuestPod(OOT3D_ADDR(camera, 0x98), viewUp);",
        "*(Oot3dActorVec3f*)OOT3D_ADDR(camera, 0xB0) = shake.eyeOffset;":
            "WriteGuestPod(OOT3D_ADDR(camera, 0xB0), shake.eyeOffset);",
    }
    for original, replacement in pod_replacements.items():
        body = replace_exact(body, original, replacement)

    pointer_replacements = {
        "(const Oot3dActorVec3f*)OOT3D_ADDR(camera, 0xDC)":
            "GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0xDC))",
        "(const Oot3dActorVec3f*)OOT3D_ADDR(camera, 0x80)":
            "GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0x80))",
        "(const Oot3dActorVec3f*)OOT3D_ADDR(camera, 0x8C)":
            "GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0x8C))",
        "(Oot3dPlayState*)play": "GuestPtr<Oot3dPlayState>(play)",
        "(void*)(play + 0xA98)": "GuestPtr<void>(play + 0xA98)",
        "(u32*)(cameraState + 0xA8)": "GuestPtr<u32>(cameraState + 0xA8)",
        "(Oot3dActor*)player": "GuestPtr<Oot3dActor>(player)",
        "(const Oot3dActor*)player": "GuestPtr<const Oot3dActor>(player)",
        "(const void*)player": "GuestPtr<const void>(player)",
        "(const void*)play": "GuestPtr<const void>(play)",
        "(void*)camera": "GuestPtr<void>(camera)",
    }
    for original, replacement in pointer_replacements.items():
        actual = body.count(original)
        if actual == 0:
            raise RuntimeError(f"expected pointer cast missing: {original!r}")
        body = body.replace(original, replacement)

    body = replace_exact(body, "fabsf(", "std::fabs(")
    body = replace_exact(body, "sqrtf(", "TargetSqrt(")
    body = replace_exact(
        body,
        "0.00003051851f",
        "std::bit_cast<float>(0x38000100U)",
        3,
    )

    prologue = """// Generated by generate_import.py from the immutable d5c2927 package.
// The source hash and target body identity are recorded in import_manifest.json.
#include "oot3d/camera_update_owner.h"

#include <cmath>
#include <cstdint>

#if defined(_MSC_VER)
#pragma fenv_access(on)
#else
#pragma STDC FENV_ACCESS ON
#endif

namespace Oot3dSourceCameraUpdate {
namespace {

#define DAT_002d88a8 (ActiveLiterals().Words[0])
#define DAT_002d88b4 (GuestPtr<u32>(ActiveLiterals().Words[1]))
#define DAT_002d88bc (ActiveLiterals().Words[2])
#define DAT_002d88c8 (ActiveLiterals().Words[3])
#define DAT_002d8c20 (ActiveLiterals().Words[4])
#define DAT_002d8c28 (ActiveLiterals().Words[5])
#define DAT_002d8c2c (ActiveLiterals().Words[6])
#define DAT_002d8c30 (ActiveLiterals().Words[7])
#define DAT_002d8c38 (ActiveLiterals().Words[8])
#define DAT_002d8c40 (ActiveLiterals().Words[9])

#define OOT3D_ADDR(base, offset) \\
    (static_cast<std::uint32_t>(base) + static_cast<std::uint32_t>(offset))
#define OOT3D_U8(base, offset) \\
    GuestRef<u8>(OOT3D_ADDR((base), (offset)))
#define OOT3D_S16(base, offset) \\
    GuestRef<s16>(OOT3D_ADDR((base), (offset)))
#define OOT3D_U16(base, offset) \\
    GuestRef<u16>(OOT3D_ADDR((base), (offset)))
#define OOT3D_S32(base, offset) \\
    GuestRef<s32>(OOT3D_ADDR((base), (offset)))
#define OOT3D_U32(base, offset) \\
    GuestRef<u32>(OOT3D_ADDR((base), (offset)))
#define OOT3D_F32(base, offset) \\
    GuestRef<float>(OOT3D_ADDR((base), (offset)))

"""
    epilogue = """

#undef OOT3D_F32
#undef OOT3D_U32
#undef OOT3D_S32
#undef OOT3D_U16
#undef OOT3D_S16
#undef OOT3D_U8
#undef OOT3D_ADDR
#undef DAT_002d8c40
#undef DAT_002d8c38
#undef DAT_002d8c30
#undef DAT_002d8c2c
#undef DAT_002d8c28
#undef DAT_002d8c20
#undef DAT_002d88c8
#undef DAT_002d88bc
#undef DAT_002d88b4
#undef DAT_002d88a8

} // namespace

void Camera_Update(
    std::uint32_t resultAddress, std::uint32_t cameraAddress) {
    const Oot3dVec3s result = Camera_UpdateImpl(cameraAddress);
    WriteGuestMemory(resultAddress, &result, sizeof(result));
}

} // namespace Oot3dSourceCameraUpdate
"""
    return prologue + body + epilogue


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    source_bytes = args.source.read_bytes()
    digest = hashlib.sha256(source_bytes).hexdigest()
    if digest != EXPECTED_SOURCE_SHA256:
        raise RuntimeError(
            f"source hash mismatch: expected {EXPECTED_SOURCE_SHA256}, got {digest}"
        )
    output = lower(source_bytes.decode("utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
