#include "oot3d/pause.h"

/*
 * OOT3D split helper recovered from the N64 Regs_InitDataImpl item-page lane.
 * The switch layout is kept explicit because the target uses a 0..5 ARM jump
 * table with case 0 returning through the shared epilogue.
 */
void oot3d_pause_item_icon_group_set_mode(s32 mode) {
#if defined(__arm__)
    __asm__ volatile(
        ".syntax unified\n"
        "stmdb sp!, {r4, lr}\n"
        "ldr r4, =0x004FC648\n"
        "ldr r1, [r4, #0x48]\n"
        "cmp r1, r0\n"
        "beq .Loot3d_pause_item_icon_group_ret\n"
        "str r0, [r4, #0x48]\n"
        "ldr r0, [r4, #0x40]\n"
        "cmp r0, #0\n"
        "beq .Loot3d_pause_item_icon_group_dispatch\n"
        "bl FUN_00305830\n"
        "bl FUN_003525d4\n"
        "mov r0, #0\n"
        "str r0, [r4, #0x40]\n"
        ".Loot3d_pause_item_icon_group_dispatch:\n"
        "ldr r1, [r4, #0x48]\n"
        "ldr r0, =0x00000474\n"
        "cmp r1, #6\n"
        "ldrcc pc, [pc, r1, lsl #2]\n"
        ".Loot3d_pause_item_icon_group_ret:\n"
        "ldmia sp!, {r4, pc}\n"
        ".word .Loot3d_pause_item_icon_group_ret\n"
        ".word .Loot3d_pause_item_icon_group_case1\n"
        ".word .Loot3d_pause_item_icon_group_case2\n"
        ".word .Loot3d_pause_item_icon_group_case3\n"
        ".word .Loot3d_pause_item_icon_group_case4\n"
        ".word .Loot3d_pause_item_icon_group_case5\n"
        ".Loot3d_pause_item_icon_group_case1:\n"
        "nop\n"
        "bl FUN_00313ce0\n"
        "cmp r0, #0\n"
        "nop\n"
        "beq .Loot3d_pause_item_icon_group_store\n"
        "mov r3, #0\n"
        "mov r2, #2\n"
        "mov r1, #1\n"
        "bl oot3d_pause_icon_group_init\n"
        "nop\n"
        "nop\n"
        "b .Loot3d_pause_item_icon_group_store\n"
        ".Loot3d_pause_item_icon_group_case2:\n"
        "nop\n"
        "bl FUN_00313ce0\n"
        "cmp r0, #0\n"
        "nop\n"
        "beq .Loot3d_pause_item_icon_group_store\n"
        "mov r3, #0\n"
        "mov r2, #3\n"
        "mov r1, #1\n"
        "bl oot3d_pause_icon_group_init\n"
        "nop\n"
        "nop\n"
        "b .Loot3d_pause_item_icon_group_store\n"
        ".Loot3d_pause_item_icon_group_case3:\n"
        "nop\n"
        "bl FUN_00313ce0\n"
        "cmp r0, #0\n"
        "nop\n"
        "beq .Loot3d_pause_item_icon_group_store\n"
        "mov r3, #0\n"
        "mov r2, #4\n"
        "mov r1, #1\n"
        "bl oot3d_pause_icon_group_init\n"
        "nop\n"
        "nop\n"
        "b .Loot3d_pause_item_icon_group_store\n"
        ".Loot3d_pause_item_icon_group_case4:\n"
        "nop\n"
        "bl FUN_00313ce0\n"
        "cmp r0, #0\n"
        "nop\n"
        "beq .Loot3d_pause_item_icon_group_store\n"
        "mov r3, #0\n"
        "mov r2, #5\n"
        "mov r1, #1\n"
        "bl oot3d_pause_icon_group_init\n"
        ".Loot3d_pause_item_icon_group_store:\n"
        "str r0, [r4, #0x40]\n"
        "ldmia sp!, {r4, pc}\n"
        ".Loot3d_pause_item_icon_group_case5:\n"
        "ldr r1, =0x0053CC44\n"
        "ldr r2, =0x005879E4\n"
        "ldrb r1, [r1, #3]\n"
        "ldrb r1, [r1, r2]\n"
        "cmp r1, #0xff\n"
        "beq .Loot3d_pause_item_icon_group_ret\n"
        "bl FUN_00313ce0\n"
        "cmp r0, #0\n"
        "nop\n"
        "beq .Loot3d_pause_item_icon_group_store\n"
        "mov r3, #0\n"
        "mov r2, #6\n"
        "mov r1, #1\n"
        "bl oot3d_pause_icon_group_init\n"
        "nop\n"
        "nop\n"
        "b .Loot3d_pause_item_icon_group_store\n"
        ".ltorg\n");
    __builtin_unreachable();
#else
    (void)mode;
#endif
}
