#include "oot3d/pause.h"

/*
 * OOT3D split helper recovered from the N64 Regs_InitDataImpl item detail lane.
 * The duplicated close-prompt blocks and literal loads are preserved because
 * they are observable in the target ARM layout.
 */
void oot3d_pause_item_update_context_detail(void) {
#if defined(__arm__)
    __asm__ volatile(
        ".syntax unified\n"
        "stmdb sp!, {r4, r5, r6, lr}\n"
        "ldr r6, .Loot3d_pause_item_update_context_detail_lit_input\n"
        "ldr r0, [r6]\n"
        "tst r0, #1\n"
        "bne .Loot3d_pause_item_update_context_detail_body\n"
        "add r0, r6, #0\n"
        "bl FUN_003679b4\n"
        "cmp r0, #0\n"
        "beq .Loot3d_pause_item_update_context_detail_body\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_prompt\n"
        "bl FUN_0036788c\n"
        "ldr r2, .Loot3d_pause_item_update_context_detail_lit_code_base\n"
        "ldr r1, .Loot3d_pause_item_update_context_detail_lit_archive\n"
        "mov r0, r0\n"
        "add r0, r6, #0\n"
        "mov r0, r0\n"
        ".Loot3d_pause_item_update_context_detail_body:\n"
        "ldr r12, .Loot3d_pause_item_update_context_detail_lit_state\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_sram\n"
        "ldr r5, .Loot3d_pause_item_update_context_detail_lit_message\n"
        "ldr r2, .Loot3d_pause_item_update_context_detail_lit_save\n"
        "ldr r1, [r12, #0x30]\n"
        "ldrh r0, [r0, #0x92]\n"
        "ldr r3, .Loot3d_pause_item_update_context_detail_lit_item_masks\n"
        "cmp r1, #5\n"
        "mov r4, #0xff\n"
        "beq .Loot3d_pause_item_update_context_detail_case5\n"
        "cmp r1, #6\n"
        "beq .Loot3d_pause_item_update_context_detail_case6\n"
        "cmp r1, #7\n"
        "bne .Loot3d_pause_item_update_context_detail_selected\n"
        "add r0, r0, r2\n"
        "ldr r1, [r3, #8]\n"
        "ldrb r0, [r0, #0xc0]\n"
        "tst r0, r1\n"
        "movne r4, #0x76\n"
        "b .Loot3d_pause_item_update_context_detail_selected\n"
        ".Loot3d_pause_item_update_context_detail_case5:\n"
        "add r0, r0, r2\n"
        "ldr r1, [r3]\n"
        "ldrb r0, [r0, #0xc0]\n"
        "tst r0, r1\n"
        "movne r4, #0x74\n"
        "b .Loot3d_pause_item_update_context_detail_selected\n"
        ".Loot3d_pause_item_update_context_detail_case6:\n"
        "add r0, r0, r2\n"
        "ldr r1, [r3, #4]\n"
        "ldrb r0, [r0, #0xc0]\n"
        "tst r0, r1\n"
        "movne r4, #0x75\n"
        ".Loot3d_pause_item_update_context_detail_selected:\n"
        "ldr r0, [r12, #0x34]\n"
        "cmp r0, r4\n"
        "beq .Loot3d_pause_item_update_context_detail_return\n"
        "cmp r4, #0xff\n"
        "str r4, [r12, #0x34]\n"
        "bne .Loot3d_pause_item_update_context_detail_load_detail\n"
        "mvn r0, #0\n"
        "bl oot3d_pause_detail_set_item_id\n"
        "ldr r0, [r6]\n"
        "tst r0, #1\n"
        "bne .Loot3d_pause_item_update_context_detail_clear_detail\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_input\n"
        "bl FUN_003679b4\n"
        "cmp r0, #0\n"
        "nop\n"
        "beq .Loot3d_pause_item_update_context_detail_clear_detail\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_prompt\n"
        "bl FUN_0036788c\n"
        "ldr r2, .Loot3d_pause_item_update_context_detail_lit_code_base\n"
        "ldr r1, .Loot3d_pause_item_update_context_detail_lit_archive\n"
        "mov r0, r0\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_input\n"
        "nop\n"
        "mov r0, r0\n"
        ".Loot3d_pause_item_update_context_detail_clear_detail:\n"
        "mov r0, r5\n"
        "ldmia sp!, {r4, r5, r6, lr}\n"
        "b FUN_002e9a1c\n"
        ".Loot3d_pause_item_update_context_detail_load_detail:\n"
        "mov r0, r4\n"
        "bl oot3d_pause_detail_set_item_id\n"
        "add r1, r4, #0x700\n"
        "mov r2, #1\n"
        "mov r0, r5\n"
        "bl oot3d_pause_detail_load_resource\n"
        "ldr r0, [r6]\n"
        "tst r0, #1\n"
        "bne .Loot3d_pause_item_update_context_detail_set_loaded\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_input\n"
        "bl FUN_003679b4\n"
        "cmp r0, #0\n"
        "nop\n"
        "beq .Loot3d_pause_item_update_context_detail_set_loaded\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_prompt\n"
        "bl FUN_0036788c\n"
        "ldr r2, .Loot3d_pause_item_update_context_detail_lit_code_base\n"
        "ldr r1, .Loot3d_pause_item_update_context_detail_lit_archive\n"
        "mov r0, r0\n"
        "ldr r0, .Loot3d_pause_item_update_context_detail_lit_input\n"
        "nop\n"
        "mov r0, r0\n"
        ".Loot3d_pause_item_update_context_detail_set_loaded:\n"
        "mov r0, #1\n"
        "strb r0, [r5, #0xd]\n"
        ".Loot3d_pause_item_update_context_detail_return:\n"
        "ldmia sp!, {r4, r5, r6, pc}\n"
        ".Loot3d_pause_item_update_context_detail_lit_input:\n"
        ".word 0x0055A21C\n"
        ".Loot3d_pause_item_update_context_detail_lit_prompt:\n"
        ".word 0x005BE5B8\n"
        ".Loot3d_pause_item_update_context_detail_lit_code_base:\n"
        ".word 0x00100000\n"
        ".Loot3d_pause_item_update_context_detail_lit_archive:\n"
        ".word 0x0048B210\n"
        ".Loot3d_pause_item_update_context_detail_lit_message:\n"
        ".word 0x005C1878\n"
        ".Loot3d_pause_item_update_context_detail_lit_sram:\n"
        ".word 0x00588E58\n"
        ".Loot3d_pause_item_update_context_detail_lit_state:\n"
        ".word 0x00506CB0\n"
        ".Loot3d_pause_item_update_context_detail_lit_save:\n"
        ".word 0x00587958\n"
        ".Loot3d_pause_item_update_context_detail_lit_item_masks:\n"
        ".word 0x0053CB24\n"
        ".ltorg\n");
    __builtin_unreachable();
#else
    (void)oot3d_pause_item_update_context_detail;
#endif
}
