/*
 * Generated from native OOT3D ZSI scene data.
 * Aggregates source-like scene index tables for decompilation support.
 */
#ifndef OOT3D_GENERATED_SCENE_INDEX_REGISTRY_H
#define OOT3D_GENERATED_SCENE_INDEX_REGISTRY_H

#include "oot3d/scene.h"

extern const Oot3dSceneIndex oot3d_scene_index_bdan_boss_info;
extern const Oot3dSceneIndex oot3d_scene_index_bdan_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_bdan_info;
extern const Oot3dSceneIndex oot3d_scene_index_bmori1_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_bmori1_info;
extern const Oot3dSceneIndex oot3d_scene_index_bowling_info;
extern const Oot3dSceneIndex oot3d_scene_index_daiyousei_izumi_info;
extern const Oot3dSceneIndex oot3d_scene_index_ddan_boss_info;
extern const Oot3dSceneIndex oot3d_scene_index_ddan_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_ddan_info;
extern const Oot3dSceneIndex oot3d_scene_index_entra_day_info;
extern const Oot3dSceneIndex oot3d_scene_index_entra_night_info;
extern const Oot3dSceneIndex oot3d_scene_index_entra_ruins_info;
extern const Oot3dSceneIndex oot3d_scene_index_fire_bs_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganon_boss_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganon_demo_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganon_final_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganon_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganon_sonogo_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganon_tou_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganontika_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganontika_info;
extern const Oot3dSceneIndex oot3d_scene_index_ganontikasonogo_info;
extern const Oot3dSceneIndex oot3d_scene_index_gerudoway_info;
extern const Oot3dSceneIndex oot3d_scene_index_hairal_niwa_info;
extern const Oot3dSceneIndex oot3d_scene_index_hairal_niwa_n_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakaana2_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakaana_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakaana_ouke_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakadan_boss_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakadan_ch_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakadan_ch_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakadan_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakadan_info;
extern const Oot3dSceneIndex oot3d_scene_index_hakasitarelay_info;
extern const Oot3dSceneIndex oot3d_scene_index_hidan_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_hidan_info;
extern const Oot3dSceneIndex oot3d_scene_index_hiral_demo_info;
extern const Oot3dSceneIndex oot3d_scene_index_hut_info;
extern const Oot3dSceneIndex oot3d_scene_index_hylia_labo_info;
extern const Oot3dSceneIndex oot3d_scene_index_ice_doukutu_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_ice_doukutu_info;
extern const Oot3dSceneIndex oot3d_scene_index_jyasinzou_boss_info;
extern const Oot3dSceneIndex oot3d_scene_index_jyasinzou_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_jyasinzou_info;
extern const Oot3dSceneIndex oot3d_scene_index_k_home3_info;
extern const Oot3dSceneIndex oot3d_scene_index_k_home4_info;
extern const Oot3dSceneIndex oot3d_scene_index_k_home5_info;
extern const Oot3dSceneIndex oot3d_scene_index_k_home_info;
extern const Oot3dSceneIndex oot3d_scene_index_kakariko_home3_info;
extern const Oot3dSceneIndex oot3d_scene_index_kakariko_impa_info;
extern const Oot3dSceneIndex oot3d_scene_index_kakariko_info;
extern const Oot3dSceneIndex oot3d_scene_index_kakusiana_info;
extern const Oot3dSceneIndex oot3d_scene_index_kenjyanoma_info;
extern const Oot3dSceneIndex oot3d_scene_index_kinsuta_info;
extern const Oot3dSceneIndex oot3d_scene_index_kokiri_info;
extern const Oot3dSceneIndex oot3d_scene_index_labo_info;
extern const Oot3dSceneIndex oot3d_scene_index_link_info;
extern const Oot3dSceneIndex oot3d_scene_index_mahouya_info;
extern const Oot3dSceneIndex oot3d_scene_index_market_alley_info;
extern const Oot3dSceneIndex oot3d_scene_index_market_alley_n_info;
extern const Oot3dSceneIndex oot3d_scene_index_market_day_info;
extern const Oot3dSceneIndex oot3d_scene_index_market_night_info;
extern const Oot3dSceneIndex oot3d_scene_index_market_ruins_info;
extern const Oot3dSceneIndex oot3d_scene_index_men_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_men_info;
extern const Oot3dSceneIndex oot3d_scene_index_miharigoya_info;
extern const Oot3dSceneIndex oot3d_scene_index_mizusin_boss_info;
extern const Oot3dSceneIndex oot3d_scene_index_mizusin_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_mizusin_info;
extern const Oot3dSceneIndex oot3d_scene_index_moriboss_info;
extern const Oot3dSceneIndex oot3d_scene_index_nakaniwa_info;
extern const Oot3dSceneIndex oot3d_scene_index_shop_alley_info;
extern const Oot3dSceneIndex oot3d_scene_index_shop_drag_info;
extern const Oot3dSceneIndex oot3d_scene_index_shop_face_info;
extern const Oot3dSceneIndex oot3d_scene_index_shop_golon_info;
extern const Oot3dSceneIndex oot3d_scene_index_shop_info;
extern const Oot3dSceneIndex oot3d_scene_index_shop_night_info;
extern const Oot3dSceneIndex oot3d_scene_index_shrine_info;
extern const Oot3dSceneIndex oot3d_scene_index_shrine_n_info;
extern const Oot3dSceneIndex oot3d_scene_index_shrine_r_info;
extern const Oot3dSceneIndex oot3d_scene_index_souko_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot00_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot01_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot02_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot03_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot04_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot05_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot06_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot07_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot08_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot09_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot10_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot11_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot12_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot13_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot15_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot16_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot17_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot18_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot20_info;
extern const Oot3dSceneIndex oot3d_scene_index_spot99_info;
extern const Oot3dSceneIndex oot3d_scene_index_stable_info;
extern const Oot3dSceneIndex oot3d_scene_index_syatekijyou_info;
extern const Oot3dSceneIndex oot3d_scene_index_takaraya_info;
extern const Oot3dSceneIndex oot3d_scene_index_tent_info;
extern const Oot3dSceneIndex oot3d_scene_index_tokinoma_info;
extern const Oot3dSceneIndex oot3d_scene_index_turibori_info;
extern const Oot3dSceneIndex oot3d_scene_index_ydan_boss_info;
extern const Oot3dSceneIndex oot3d_scene_index_ydan_dd_info;
extern const Oot3dSceneIndex oot3d_scene_index_ydan_info;
extern const Oot3dSceneIndex oot3d_scene_index_yousei_izumi_tate_info;
extern const Oot3dSceneIndex oot3d_scene_index_yousei_izumi_yoko_info;
extern const Oot3dSceneIndex oot3d_scene_index_zoora_info;

extern const Oot3dSceneIndexRegistryEntry oot3d_scene_index_registry[];
extern const u32 oot3d_scene_index_registry_count;

#endif
