#!/usr/bin/env python3
"""Lower the pinned Player_Update body to target-width C++."""

from __future__ import annotations

import argparse
import hashlib
import pathlib


EXPECTED_SOURCE_SHA256 = (
    "ea21b2da2b5472c3f1242edf076376f05a45d2954dce43573a5e4e33aa4c2408"
)
START_TOKEN = "void Player_Update(int param_1,int param_2)"

REQUIRED_SOURCE_FRAGMENTS = (
    "iVar3 = Object_GetIndex(param_2 + 0x3a58,DAT_001e1dcc);",
    "iVar4 = Actor_Spawn(param_2 + 0x208c,param_2,DAT_001e1de8,0,",
    "Player_UpdateCommon(param_1,param_2,local_input);",
    "*(undefined4 *)(param_1 + 0x29e4) = 0xffffffff;",
)

OUTPUT = r'''// Generated by generate_import.py from the immutable d5c2927 package.
// The source hash and target body identity are recorded in import_manifest.json.
#include "oot3d/player_update_owner.h"

#include <array>
#include <cstdint>

namespace Oot3dSourcePlayerUpdate {
namespace {

template <typename T>
T Read(std::uint32_t address) {
    return ReadGuestPod<T>(address);
}

template <typename T>
void Write(std::uint32_t address, T value) {
    WriteGuestPod(address, value);
}

} // namespace

void Player_Update(std::uint32_t player, std::uint32_t play) {
    const auto& literal = ActiveLiterals().Words;
    const std::uint32_t globalState = literal[0];

    if (Read<std::int16_t>(globalState + 0x4EU) < 0) {
        const std::int32_t objectIndex =
            Object_GetIndex(play + 0x3A58U, literal[1]);
        if (objectIndex < 0) {
            // code.bin 0x001E1B90 is STRH with the LT condition.
            Write<std::uint16_t>(globalState + 0x4EU, 0U);
        } else {
            const std::uint32_t spawnOffset = literal[3];
            if ((Read<std::uint32_t>(literal[2] + 0x108U) & 1U) == 0U &&
                oot3d_static_init_guard_acquire(literal[4]) != 0) {
                Write<std::uint32_t>(spawnOffset, literal[5]);
                Write<std::uint32_t>(spawnOffset + 4U, literal[5]);
                Write<std::uint32_t>(spawnOffset + 8U, literal[6]);
            }

            const std::uint16_t objectFlags =
                static_cast<std::uint16_t>(
                    Read<std::uint16_t>(globalState + 0x4EU) & 0x7FFFU);
            Write<std::uint16_t>(globalState + 0x4EU, objectFlags);

            const std::int16_t shapeYaw =
                Read<std::int16_t>(player + 0xBEU);
            const float cosine = oot3d_cos_idx8(shapeYaw);
            const float sine = oot3d_sin_idx8(shapeYaw);
            const float offsetX = Read<float>(spawnOffset);
            const float offsetY = Read<float>(spawnOffset + 4U);
            const float offsetZ = Read<float>(spawnOffset + 8U);

            float spawnX = TargetMultiply(offsetX, cosine);
            spawnX =
                TargetMultiplyAccumulate(spawnX, offsetZ, sine);
            spawnX =
                TargetAdd(spawnX, Read<float>(player + 0x28U));
            const float spawnY = TargetAdd(
                Read<float>(player + 0x2CU), offsetY);
            float spawnZ = TargetMultiply(offsetZ, cosine);
            spawnZ =
                TargetMultiplySubtract(spawnZ, offsetX, sine);
            spawnZ =
                TargetAdd(spawnZ, Read<float>(player + 0x30U));

            const std::uint32_t spawnPosition = literal[7];
            Write<float>(spawnPosition, spawnX);
            Write<float>(spawnPosition + 4U, spawnY);
            Write<float>(spawnPosition + 8U, spawnZ);

            const std::int32_t params = static_cast<std::int16_t>(
                static_cast<std::uint16_t>(objectFlags | 0x8000U));
            const std::uint32_t actor = Actor_Spawn(
                play + 0x208CU, play,
                static_cast<std::int32_t>(literal[8]),
                spawnX, spawnY, spawnZ, 0, shapeYaw, 0, params, 1);
            if (actor != 0U) {
                Write<std::uint8_t>(actor + 3U, 0U);
            }
        }
    }

    const std::uint32_t attachedActor =
        Read<std::uint32_t>(player + 0x12B0U);
    if (attachedActor != 0U &&
        Read<std::uint32_t>(attachedActor + 0x13CU) == 0U) {
        Write<std::uint32_t>(player + 0x12B0U, 0U);
    }

    const std::uint32_t linkedActor =
        Read<std::uint32_t>(player + 0x1224U);
    if (linkedActor != 0U &&
        Read<std::uint32_t>(linkedActor + 0x13CU) == 0U) {
        FUN_0036b02c(play, player);
    }

    std::array<std::uint32_t, 12> input{};
    if ((Read<std::uint32_t>(player + 0x1710U) & literal[9]) == 0U) {
        ReadGuestMemory(
            play + 0x14U, input.data(),
            input.size() * sizeof(input[0]));
        if (Read<std::uint8_t>(player + 0x227AU) != 0U) {
            const std::uint32_t inputMask =
                Read<std::uint32_t>(literal[10]) |
                Read<std::uint32_t>(literal[11]) | 0x2000U;
            input[0] &= ~inputMask;
            input[1] &= ~inputMask;
        }
    }

    Player_UpdateCommon(player, play, input);

    const std::uint32_t outputState =
        Read<std::uint32_t>(literal[12]);
    Write<std::int16_t>(
        outputState + 0x43CU,
        static_cast<std::int16_t>(
            TargetFloatToSigned(Read<float>(player + 0x28U))));
    Write<std::int16_t>(
        outputState + 0x43EU,
        static_cast<std::int16_t>(
            TargetFloatToSigned(Read<float>(player + 0x2CU))));
    Write<std::int16_t>(
        outputState + 0x440U,
        static_cast<std::int16_t>(
            TargetFloatToSigned(Read<float>(player + 0x30U))));
    Write<std::uint16_t>(
        outputState + 0x442U,
        Read<std::uint16_t>(player + 0x36U));
    Write<std::uint32_t>(player + 0x29E4U, 0xFFFFFFFFU);
    Write<std::uint32_t>(player + 0x29E8U, 0U);
}

} // namespace Oot3dSourcePlayerUpdate
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    source_bytes = args.source.read_bytes()
    digest = hashlib.sha256(source_bytes).hexdigest()
    if digest != EXPECTED_SOURCE_SHA256:
        raise RuntimeError(
            f"source hash mismatch: expected {EXPECTED_SOURCE_SHA256}, got {digest}"
        )
    source = source_bytes.decode("utf-8")
    body_start = source.rfind(START_TOKEN)
    if body_start < 0:
        raise RuntimeError("Player_Update maintained body not found")
    body = source[body_start:]
    if body.count(START_TOKEN) != 1:
        raise RuntimeError("unique Player_Update definition not found")
    for fragment in REQUIRED_SOURCE_FRAGMENTS:
        if body.count(fragment) != 1:
            raise RuntimeError(
                f"required Player_Update source fragment not unique: {fragment!r}"
            )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(OUTPUT, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
