/* Generated by scripts/build_startup_initializer_source.py. */
/* Native order and literal-pool reads come from the reviewed EUR code.bin. */
#include "oot3d/memory.h"
#include "oot3d/startup.h"
#include "oot3d/static_init.h"
#include "oot3d/target_native_prelude.h"

extern u32 DAT_00412150;
extern u32 DAT_00412154;
extern u32 DAT_00412158;
extern u32 DAT_0041215C;
extern u32 DAT_00412160;
extern u32 DAT_00412164;
extern u32 DAT_00412168;
extern u32 DAT_0041216C;
extern u32 DAT_00412170;
extern u32 DAT_00412190;
extern u32 DAT_004121BC;
extern u32 DAT_004121C0;
extern u32 DAT_00412204;
extern u32 DAT_0041223C;
extern u32 DAT_00412240;
extern u32 DAT_00412244;
extern u32 DAT_00412298;
extern u32 DAT_0041229C;
extern u32 DAT_004122A0;
extern u32 DAT_004122F8;
extern u32 DAT_004122FC;
extern u32 DAT_00412304;
extern u32 DAT_00412318;
extern u32 DAT_0041239C;
extern u32 DAT_004123A0;
extern u32 DAT_004123A8;
extern u32 DAT_004123B0;
extern u32 DAT_004123B8;
extern u32 DAT_004123BC;
extern u32 DAT_004123D0;
extern u32 DAT_00412410;
extern u32 DAT_00412414;
extern u32 DAT_00412418;
extern u32 DAT_0041241C;
extern u32 DAT_00412440;
extern u32 DAT_00412444;
extern u32 DAT_00412448;
extern u32 DAT_0041255C;
extern u32 DAT_00412588;
extern u32 DAT_00412630;
extern u32 DAT_00412634;
extern u32 DAT_00412640;
extern u32 DAT_00412644;
extern u32 DAT_00412648;
extern u32 DAT_0041264C;
extern u32 DAT_00412650;
extern u32 DAT_00412654;
extern u32 DAT_00412658;
extern u32 DAT_0041265C;
extern u32 DAT_00412660;
extern u32 DAT_00412674;
extern u32 DAT_00412678;
extern u32 DAT_004126A8;
extern u32 DAT_004126AC;
extern u32 DAT_004126E4;
extern u32 DAT_004126E8;
extern u32 DAT_004126EC;
extern u32 DAT_004126F0;
extern u32 DAT_00412714;
extern u32 DAT_00412718;
extern u32 DAT_00412730;
extern u32 DAT_00412734;
extern u32 DAT_004127C4;
extern u32 DAT_004127C8;
extern u32 DAT_004127CC;
extern u32 DAT_004127D0;
extern u32 DAT_004127DC;
extern u32 DAT_004127E4;
extern u32 DAT_004127EC;
extern u32 DAT_004127F0;
extern u32 DAT_00412864;
extern u32 DAT_00412868;
extern u32 DAT_0041286C;
extern u32 DAT_00412870;
extern u32 DAT_004128E0;
extern u32 DAT_004128E4;
extern u32 DAT_004128E8;
extern u32 DAT_004128EC;
extern u32 DAT_004128F0;
extern u32 DAT_0041293C;
extern u32 DAT_00412940;
extern u32 DAT_00412944;
extern u32 DAT_00412948;
extern u32 DAT_00412984;
extern u32 DAT_00412988;
extern u32 DAT_0041298C;
extern u32 DAT_00412990;
extern u32 DAT_004129D0;
extern u32 DAT_004129D4;
extern u32 DAT_004129D8;
extern u32 DAT_004129DC;
extern u32 DAT_00412A00;
extern u32 DAT_00412A04;
extern u32 DAT_00412A28;
extern u32 DAT_00412A2C;
extern u32 DAT_00412AE4;
extern u32 DAT_00412AE8;
extern u32 DAT_00412AEC;
extern u32 DAT_00412AF0;
extern u32 DAT_00412AF4;
extern u32 DAT_00412AF8;
extern u32 DAT_00412AFC;
extern u32 DAT_00412B00;
extern u32 DAT_00412B04;
extern u32 DAT_00412B08;
extern u32 DAT_00412B0C;
extern u32 DAT_00412B94;
extern u32 DAT_00412BA0;
extern u32 DAT_00412BA4;
extern u32 DAT_00412BA8;
extern u32 DAT_00412BB0;
extern u32 DAT_00412BB4;
extern u32 DAT_00412BB8;
extern u32 DAT_00412BBC;
extern u32 DAT_00412BC0;
extern u32 DAT_00412CB0;
extern u32 DAT_00412CBC;
extern u32 DAT_00412CC4;
extern u32 DAT_00412CC8;
extern u32 DAT_00412CCC;
extern u32 DAT_00412CD0;
extern u32 DAT_00412CD4;
extern u32 DAT_00412CD8;
extern u32 DAT_00412CE0;
extern u32 DAT_00412CE8;
extern u32 DAT_00412CFC;
extern u32 DAT_00412D20;
extern u32 DAT_00412D24;
extern u32 DAT_00412DBC;
extern u32 DAT_00412DC8;
extern u32 DAT_00412DD0;
extern u32 DAT_00412DD4;
extern u32 DAT_00412E14;
extern u32 DAT_00412EAC;
extern u32 DAT_00412EB0;
extern u32 DAT_00412EB4;
extern u32 DAT_00412EB8;
extern u32 DAT_00412EF8;
extern u32 DAT_00412EFC;
extern u32 DAT_00412F00;
extern u32 DAT_00412F04;
extern u32 DAT_00412F44;
extern u32 DAT_00412F48;
extern u32 DAT_00412F4C;
extern u32 DAT_00412F50;
extern u32 DAT_00412F80;
extern u32 DAT_00412F84;
extern u32 DAT_00412FA0;
extern u32 DAT_00412FB4;
extern u32 DAT_00412FC8;
extern u32 DAT_00412FDC;
extern u32 DAT_00413004;
extern u32 DAT_00413008;
extern u32 DAT_00413024;
extern u32 DAT_00413028;
extern u32 DAT_00413070;
extern u32 DAT_00413074;
extern u32 DAT_00413078;
extern u32 DAT_0041307C;
extern u32 DAT_004130BC;
extern u32 DAT_004130C0;
extern u32 DAT_004130C4;
extern u32 DAT_004130C8;
extern u32 DAT_00413120;
extern u32 DAT_00413124;
extern u32 DAT_00413130;
extern u32 DAT_00413138;
extern u32 DAT_0041313C;
extern u32 DAT_00413140;
extern u32 DAT_00413168;
extern u32 DAT_0041316C;
extern u32 DAT_00413170;
extern u32 DAT_00413174;
extern u32 DAT_00413178;
extern u32 DAT_004131A4;
extern u32 DAT_004131A8;
extern u32 DAT_004131D4;
extern u32 DAT_004131F8;
extern u32 DAT_0041322C;
extern u32 DAT_00413230;
extern u32 DAT_00413234;
extern u32 DAT_00413274;
extern u32 DAT_00413278;
extern u32 DAT_0041327C;
extern u32 DAT_00413280;
extern u32 DAT_0041332C;
extern u32 DAT_00413330;
extern u32 DAT_00413334;
extern u32 DAT_00413338;
extern u32 DAT_0041333C;
extern u32 DAT_00413340;
extern u32 DAT_00413344;
extern u32 DAT_00413348;
extern u32 DAT_004133CC;
extern u32 DAT_004133D0;
extern u32 DAT_00413430;
extern u32 DAT_00413434;
extern u32 DAT_00413438;
extern u32 DAT_0041343C;
extern u32 DAT_00413450;
extern u32 DAT_00413464;
extern u32 DAT_00413478;
extern u32 DAT_0041347C;
extern u32 DAT_00413490;
extern u32 DAT_004134A4;
extern u32 DAT_004134A8;
extern u32 DAT_004134CC;
extern u32 DAT_004134D0;
extern u32 DAT_004134F4;
extern u32 DAT_004134F8;
extern u32 DAT_00413544;
extern u32 DAT_00413548;
extern u32 DAT_0041354C;
extern u32 DAT_00413550;
extern u32 DAT_00413568;
extern u32 DAT_0041356C;
extern u32 DAT_004135AC;
extern u32 DAT_004135B0;
extern u32 DAT_004135B4;
extern u32 DAT_004135B8;
extern u32 DAT_004135CC;
extern u32 DAT_004135D0;
extern u32 DAT_004135F4;
extern u32 DAT_004135F8;
extern u32 DAT_0041361C;
extern u32 DAT_00413620;
extern u32 DAT_00413644;
extern u32 DAT_00413648;
extern u32 DAT_0041364C;
extern u32 DAT_00413650;
extern u32 DAT_00413678;
extern u32 DAT_0041367C;
extern u32 DAT_004136C0;
extern u32 DAT_004136DC;
extern u32 DAT_00413700;
extern u32 DAT_00413704;
extern u32 DAT_00413784;
extern u32 DAT_00413788;
extern u32 DAT_0041378C;
extern u32 DAT_00413790;
extern u32 DAT_00413794;
extern u32 DAT_00413798;
extern u32 DAT_0041379C;
extern u32 DAT_004137A0;
extern u32 DAT_004137E0;
extern u32 DAT_004137E4;
extern u32 DAT_004137E8;
extern u32 DAT_004137EC;
extern u32 DAT_00413808;
extern u32 DAT_0041380C;
extern u32 DAT_00413854;
extern u32 DAT_00413898;
extern u32 DAT_0041389C;
extern u32 DAT_004138A4;
extern u32 DAT_004138BC;
extern u32 DAT_004138C0;
extern u32 DAT_004138E4;
extern u32 DAT_004138E8;
extern u32 DAT_004138EC;
extern u32 DAT_004138F0;
extern u32 DAT_00413970;
extern u32 DAT_00413974;
extern u32 DAT_004139B4;
extern u32 DAT_004139B8;
extern u32 DAT_004139BC;
extern u32 DAT_004139C0;
extern u32 DAT_00413A00;
extern u32 DAT_00413A04;
extern u32 DAT_00413A08;
extern u32 DAT_00413A0C;
extern u32 DAT_00413A20;
extern u32 DAT_00413A24;
extern u32 DAT_00413A64;
extern u32 DAT_00413A68;
extern u32 DAT_00413A6C;
extern u32 DAT_00413A70;
extern u32 DAT_00413AB0;
extern u32 DAT_00413AB4;
extern u32 DAT_00413AB8;
extern u32 DAT_00413ABC;
extern u32 DAT_00413B70;
extern u32 DAT_00413B74;
extern u32 DAT_00413C14;
extern u32 DAT_00413C18;
extern u32 DAT_00413C1C;
extern u32 DAT_00413D14;
extern u32 DAT_00413D20;
extern u32 DAT_00413D24;
extern u32 DAT_00413D28;
extern u32 DAT_00413D2C;
extern u32 DAT_00413D34;
extern u32 DAT_00413D48;
extern u32 DAT_00413D4C;
extern u32 DAT_00413DEC;
extern u32 DAT_00413DF0;
extern u32 DAT_00413DF4;
extern u32 DAT_00413DF8;
extern u32 DAT_00413E1C;
extern u32 DAT_00413E20;
extern u32 DAT_00413E60;
extern u32 DAT_00413E64;
extern u32 DAT_00413E68;
extern u32 DAT_00413E6C;
extern u32 DAT_00413EAC;
extern u32 DAT_00413EB0;
extern u32 DAT_00413EB4;
extern u32 DAT_00413EB8;
extern u32 DAT_00413EF8;
extern u32 DAT_00413EFC;
extern u32 DAT_00413F00;
extern u32 DAT_00413F04;
extern u32 DAT_00413F38;
extern u32 DAT_00413F3C;
extern u32 DAT_00413F40;
extern u32 DAT_00413F44;
extern u32 DAT_00414030;
extern u32 DAT_00414034;
extern u32 DAT_00414038;
extern u32 DAT_0041403C;
extern u32 DAT_00414048;
extern u32 DAT_0041404C;
extern u32 DAT_00414054;
extern u32 DAT_00414058;
extern u32 DAT_0041405C;
extern u32 DAT_00414060;
extern u32 DAT_0041408C;
extern u32 DAT_004140A8;
extern u32 DAT_004140AC;
extern u32 DAT_004140D0;
extern u32 DAT_004140F4;
extern u32 DAT_004140F8;
extern u32 DAT_00414134;
extern u32 DAT_00414138;
extern u32 DAT_0041413C;
extern u32 DAT_00414140;
extern u32 DAT_00414170;
extern u32 DAT_00414174;
extern u32 DAT_00414178;
extern u32 DAT_00414208;
extern u32 DAT_0041420C;
extern u32 DAT_00414210;
extern u32 DAT_00414214;
extern u32 DAT_00414218;
extern u32 DAT_0041421C;
extern u32 DAT_00414220;
extern u32 DAT_00414224;
extern u32 DAT_00414274;
extern u32 DAT_00414278;
extern u32 DAT_0041427C;
extern u32 DAT_00414280;
extern u32 DAT_00414284;
extern u32 DAT_004142C4;
extern u32 DAT_004142C8;
extern u32 DAT_004142CC;
extern u32 DAT_004142D0;
extern u32 DAT_004142F4;
extern u32 DAT_004142F8;
extern u32 DAT_004142FC;
extern u32 DAT_00414300;
extern u32 DAT_0041434C;
extern u32 DAT_00414358;
extern u32 DAT_0041437C;
extern u32 DAT_00414398;
extern u32 DAT_0041439C;
extern u32 DAT_004143DC;
extern u32 DAT_004143E0;
extern u32 DAT_004143E4;
extern u32 DAT_004143E8;
extern u32 DAT_00414468;
extern u32 DAT_0041446C;
extern u32 DAT_00414470;
extern u32 DAT_00414474;
extern u32 DAT_00414478;
extern u32 DAT_0041447C;
extern u32 DAT_00414480;
extern u32 DAT_00414484;
extern u32 DAT_004145C4;
extern u32 DAT_004145C8;
extern u32 DAT_004145CC;
extern u32 DAT_004145D0;
extern u32 DAT_004145D4;
extern u32 DAT_004145D8;
extern u32 DAT_004145DC;
extern u32 DAT_004145E0;
extern u32 DAT_00414688;
extern u32 DAT_0041468C;
extern u32 DAT_00414690;
extern u32 DAT_00414694;
extern u32 DAT_00414698;
extern u32 DAT_004146A0;
extern u32 DAT_004146A4;
extern u32 DAT_004146AC;
extern u32 DAT_004146B0;
extern u32 DAT_004146B8;
extern u32 DAT_004146BC;
extern u32 DAT_004146C4;
extern u32 DAT_004146C8;
extern u32 DAT_00414708;
extern u32 DAT_0041470C;
extern u32 DAT_00414710;
extern u32 DAT_00414750;
extern u32 DAT_00414754;
extern u32 DAT_00414758;
extern u32 DAT_00414788;
extern u32 DAT_004147D0;
extern u32 DAT_004147D4;
extern u32 DAT_004147D8;
extern u32 DAT_004147DC;
extern u32 DAT_00414804;
extern u32 DAT_00414830;
extern u32 DAT_00414834;
extern u32 DAT_00414860;
extern u32 DAT_0041486C;
extern u32 DAT_00414870;

/* Native process initializer at 0x00412098. */
void oot3d_startup_initializer_00412098(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;

  uVar2 = DAT_0041215C;
  puVar1 = ((u32 *)(uint32_t)DAT_00412154);
  *((u32 *)(uint32_t)DAT_00412154) = *((u32 *)(uint32_t)DAT_00412150);
  puVar1[1] = 0;
  puVar1 = ((u32 *)(uint32_t)DAT_00412158);
  ((u32 *)(uint32_t)DAT_00412158)[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  *puVar1 = uVar2;
  puVar1[4] = 0;
  puVar1 = ((u32 *)(uint32_t)DAT_00412168);
  ((u32 *)(uint32_t)DAT_00412168)[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  *puVar1 = uVar2;
  puVar1[4] = 0;
  puVar1 = ((u32 *)(uint32_t)DAT_0041216C);
  ((u32 *)(uint32_t)DAT_0041216C)[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  *puVar1 = uVar2;
  puVar1[4] = 0;
  puVar1 = ((u32 *)(uint32_t)DAT_00412170);
  uVar4 = DAT_00412164;
  uVar3 = DAT_00412160;
  ((u32 *)(uint32_t)DAT_00412170)[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  *puVar1 = uVar2;
  puVar1[4] = 0;
  return;
}

/* Native process initializer at 0x00412174. */
void oot3d_startup_initializer_00412174(void)

{
  undefined4 uVar1;

  uVar1 = oot3d_startup_initialize_zeroed_state(DAT_00412190);
  return;
}

/* Native process initializer at 0x0041219C. */
void oot3d_startup_initializer_0041219c(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_004121C0);
  uVar1 = DAT_004121BC;
  *((u32 *)(uint32_t)DAT_004121C0) = DAT_004121BC;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x004121C4. */
void oot3d_startup_initializer_004121c4(void)

{
  bool bVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00412204);
  *((u32 *)(uint32_t)DAT_00412204) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  return;
}

/* Native process initializer at 0x00412210. */
void oot3d_startup_initializer_00412210(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  uVar1 = DAT_00412240;
  *((u32 *)(uint32_t)DAT_0041223C) = 0;
  puVar2 = ((u32 *)(uint32_t)DAT_00412244);
  *((u32 *)(uint32_t)DAT_00412244) = 0;
  puVar2[1] = 0;
  puVar2[2] = uVar1;
  puVar2[3] = 0;
  puVar2[4] = 0x8000;
  return;
}

/* Native process initializer at 0x00412248. */
void oot3d_startup_initializer_00412248(void)

{
  bool bVar1;
  undefined4 *puVar2;

  *((u32 *)(uint32_t)DAT_0041229C) = *(undefined4 *)(((s32)DAT_00412298) + 4);
  puVar2 = ((u32 *)(uint32_t)DAT_004122A0);
  *((u32 *)(uint32_t)DAT_004122A0) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  return;
}

/* Native process initializer at 0x004122AC. */
void oot3d_startup_initializer_004122ac(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  undefined4 uVar3;

  uVar3 = DAT_00412304;
  uVar2 = DAT_004122FC;
  puVar1 = ((u32 *)(uint32_t)DAT_004122F8);
  *((u32 *)(uint32_t)DAT_004122F8) = 0;
  puVar1[2] = 0;
  puVar1[4] = 0;
  puVar1[7] = 0;
  puVar1[6] = uVar2;
  puVar1[9] = 0;
  puVar1[0xb] = 0;
  puVar1[0xc] = 0;
  puVar1[0xd] = 0;
  puVar1[0xe] = 0;
  *(undefined1 *)(puVar1 + 0xf) = 0;
  puVar1[0x10] = 0;
  *(undefined1 *)(puVar1 + 0x11) = 0;
  return;
}

/* Native process initializer at 0x00412308. */
void oot3d_startup_initializer_00412308(void)

{
  *((u32 *)(uint32_t)DAT_00412318) = 0;
  return;
}

/* Native process initializer at 0x0041231C. */
void oot3d_startup_initializer_0041231c(void)

{
  bool bVar1;
  undefined4 *puVar2;
  u8 *puVar3;
  u8 *puVar4;
  u8 *puVar5;

  puVar2 = ((u32 *)(uint32_t)DAT_0041239C);
  *((u32 *)(uint32_t)DAT_0041239C) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  *(undefined4 *)((u8 *)(uint32_t)DAT_004123A8) = 0;
  puVar3 = ((u8 *)(uint32_t)DAT_004123B0);
  *(undefined4 *)((u8 *)(uint32_t)DAT_004123B0) = 0;
  puVar3[4] = 1;
  puVar5 = ((u8 *)(uint32_t)DAT_004123BC);
  puVar4 = ((u8 *)(uint32_t)DAT_004123B8);
  puVar3 = ((u8 *)(uint32_t)DAT_004123A0);
  *(undefined4 *)((u8 *)(uint32_t)DAT_004123B8) = 0;
  return;
}

/* Native process initializer at 0x004123C0. */
void oot3d_startup_initializer_004123c0(void)

{
  *((u32 *)(uint32_t)DAT_004123D0) = 0;
  return;
}

/* Native process initializer at 0x004123D4. */
void oot3d_startup_initializer_004123d4(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00412414);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00412414) + 0x28,((u8 *)(uint32_t)DAT_00412410),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00412418),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_0041241C),0x28);
  return;
}

/* Native process initializer at 0x00412420. */
void oot3d_startup_initializer_00412420(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 *puVar3;

  puVar3 = ((u32 *)(uint32_t)DAT_00412448);
  uVar2 = DAT_00412444;
  uVar1 = DAT_00412440;
  *((u32 *)(uint32_t)DAT_00412448) = DAT_00412440;
  puVar3[1] = uVar1;
  puVar3[2] = uVar2;
  return;
}

/* Native process initializer at 0x0041244C. */
void oot3d_startup_initializer_0041244c(void)

{
  undefined4 *puVar1;

  puVar1 = ((u32 *)(uint32_t)DAT_0041255C);
  ((u32 *)(uint32_t)DAT_0041255C)[0x3e] = ((u32 *)(uint32_t)DAT_0041255C)[1];
  puVar1[0x44] = *puVar1;
  puVar1[0x4a] = puVar1[2];
  puVar1[0x50] = puVar1[3];
  puVar1[0x56] = puVar1[4];
  puVar1[0x5c] = puVar1[5];
  puVar1[0x62] = puVar1[5];
  puVar1[0x68] = puVar1[6];
  puVar1[0x6e] = puVar1[7];
  puVar1[0x74] = puVar1[8];
  puVar1[0x7a] = puVar1[9];
  puVar1[0x80] = puVar1[10];
  puVar1[0x86] = puVar1[0xb];
  puVar1[0x8c] = puVar1[0xc];
  puVar1[0x92] = puVar1[0xd];
  puVar1[0x98] = puVar1[0xe];
  puVar1[0x9e] = puVar1[0xf];
  puVar1[0xa4] = puVar1[0x10];
  puVar1[0xaa] = puVar1[0x11];
  puVar1[0xb0] = puVar1[0x12];
  puVar1[0xb6] = puVar1[0x13];
  puVar1[0xbc] = puVar1[0x14];
  puVar1[0xc2] = puVar1[0x15];
  puVar1[200] = puVar1[0x16];
  puVar1[0xce] = puVar1[0x17];
  puVar1[0xd4] = puVar1[0x18];
  puVar1[0xda] = puVar1[0x19];
  puVar1[0xe0] = puVar1[0x1a];
  puVar1[0xf2] = puVar1[0x12];
  puVar1[0xf8] = puVar1[10];
  puVar1[0xe6] = puVar1[0x1b];
  puVar1[0xec] = *puVar1;
  puVar1[0xfe] = puVar1[0x1c];
  puVar1[0x104] = puVar1[7];
  return;
}

/* Native process initializer at 0x00412560. */
void oot3d_startup_initializer_00412560(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00412588);
  puVar1 = ((u32 *)(uint32_t)DAT_00412588) + 1;
  ((u32 *)(uint32_t)DAT_00412588)[10] = *puVar1;
  puVar2[0x10] = *puVar1;
  puVar2[0x16] = *puVar2;
  puVar2[0x1c] = puVar2[2];
  return;
}

/* Native process initializer at 0x0041258C. */
void oot3d_startup_initializer_0041258c(void)

{
  oot3d_startup_construct_array(DAT_00412634,DAT_00412630,4,4);
  oot3d_startup_construct_array(DAT_00412644,DAT_00412640,0x10,0x14);
  oot3d_startup_construct_array(DAT_0041264C,DAT_00412648,2,0x40);
  oot3d_startup_construct_array(DAT_00412650,DAT_00412640,0x10,4);
  oot3d_startup_construct_array(DAT_00412654,DAT_00412640,0x10,4);
  oot3d_startup_construct_array(DAT_0041265C,DAT_00412658,8,4);
  oot3d_startup_construct_array(DAT_00412660,DAT_00412658,8,4);
  return;
}

/* Native process initializer at 0x00412664. */
void oot3d_startup_initializer_00412664(void)

{
  *((u32 *)(uint32_t)DAT_00412678) = DAT_00412674;
  return;
}

/* Native process initializer at 0x0041267C. */
void oot3d_startup_initializer_0041267c(void)

{
  int iVar1;

  iVar1 = oot3d_startup_construct_array(DAT_004126A8,DAT_004126AC,8,0x14);
  *(undefined4 *)(iVar1 + 0xa0) = 0;
  *(undefined4 *)(iVar1 + 0xa4) = 0;
  *(undefined4 *)(iVar1 + 0xa8) = 0;
  return;
}

/* Native process initializer at 0x004126B0. */
void oot3d_startup_initializer_004126b0(void)

{
  int iVar1;

  iVar1 = oot3d_startup_construct_array(DAT_004126E4,DAT_004126EC,DAT_004126E8,0x18);
  oot3d_startup_construct_array(iVar1 + 0x7fe0,DAT_004126F0,0x28c,0x19);
  return;
}

/* Native process initializer at 0x004126F4. */
void oot3d_startup_initializer_004126f4(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00412718);
  uVar1 = DAT_00412714;
  *((u32 *)(uint32_t)DAT_00412718) = DAT_00412714;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x0041271C. */
void oot3d_startup_initializer_0041271c(void)

{
  oot3d_startup_construct_array(DAT_00412734,DAT_00412730,0x20,0xc);
  return;
}

/* Native process initializer at 0x00412738. */
void oot3d_startup_initializer_00412738(void)

{
  undefined4 *puVar1;
  u8 *puVar2;

  oot3d_startup_construct_array(DAT_004127CC,DAT_004127C8,DAT_004127C4,6);
  puVar1 = ((u32 *)(uint32_t)DAT_004127D0);
  *((u32 *)(uint32_t)DAT_004127D0) = 0;
  puVar1[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  *(undefined1 *)(puVar1 + 4) = 0;
  puVar2 = ((u8 *)(uint32_t)DAT_004127DC);
  *(undefined4 *)((u8 *)(uint32_t)DAT_004127DC) = 0;
  puVar2[4] = 1;
  puVar1 = ((u32 *)(uint32_t)DAT_004127E4);
  *((u32 *)(uint32_t)DAT_004127E4) = 0;
  puVar1[2] = 0xffffffff;
  puVar1[1] = 0;
  *((u32 *)(uint32_t)DAT_004127F0) = DAT_004127EC;
  return;
}

/* Native process initializer at 0x004127F4. */
void oot3d_startup_initializer_004127f4(void)

{
  u8 *puVar1;
  u8 *puVar2;
  u8 *puVar3;
  uint value;
  uint uVar4;
  undefined4 uStack_10;

  puVar2 = ((u8 *)(uint32_t)DAT_00412868);
  puVar1 = ((u8 *)(uint32_t)DAT_00412864);
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412864) = 0;
  uStack_10 = 0;
  value = oot3d_startup_duplicate_handle(&uStack_10,*(undefined4 *)puVar2);
  uVar4 = value >> 0x1b;
  if ((value & 0x80000000) != 0) {
    uVar4 = uVar4 - 0x20;
  }
  if ((uVar4 != 0xfffffff9 && uVar4 != 0) && uVar4 != 1) {
    oot3d_startup_handle_result(value);
  }
  puVar3 = ((u8 *)(uint32_t)DAT_00412870);
  puVar2 = ((u8 *)(uint32_t)DAT_0041286C);
  *(undefined4 *)puVar1 = uStack_10;
  puVar1[4] = 0;
  puVar1[5] = 0;
  return;
}

/* Native process initializer at 0x00412874. */
void oot3d_startup_initializer_00412874(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  oot3d_startup_construct_array(DAT_004128E4,DAT_004128E0,0x40,300);
  puVar2 = ((u32 *)(uint32_t)DAT_004128EC);
  uVar1 = DAT_004128E8;
  *((u32 *)(uint32_t)DAT_004128EC) = DAT_004128E8;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  puVar2 = ((u32 *)(uint32_t)DAT_004128F0);
  *((u32 *)(uint32_t)DAT_004128F0) = uVar1;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  puVar2[3] = uVar1;
  puVar2[4] = uVar1;
  puVar2[5] = uVar1;
  puVar2[6] = uVar1;
  puVar2[7] = uVar1;
  puVar2[8] = uVar1;
  return;
}

/* Native process initializer at 0x004128F4. */
void oot3d_startup_initializer_004128f4(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 *puVar3;
  undefined4 uVar4;

  uVar4 = DAT_00412948;
  puVar3 = ((u32 *)(uint32_t)DAT_00412944);
  uVar2 = DAT_00412940;
  uVar1 = DAT_0041293C;
  *((u32 *)(uint32_t)DAT_00412944) = DAT_0041293C;
  puVar3[1] = uVar1;
  puVar3[2] = uVar2;
  puVar3[3] = uVar1;
  puVar3[4] = uVar1;
  puVar3[5] = uVar1;
  oot3d_startup_construct_array(puVar3 + 0x2f,uVar4,0x48,0x96);
  return;
}

/* Native process initializer at 0x0041294C. */
void oot3d_startup_initializer_0041294c(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  oot3d_startup_construct_array(DAT_00412988,DAT_00412984,0x5c,200);
  puVar2 = ((u32 *)(uint32_t)DAT_00412990);
  uVar1 = DAT_0041298C;
  *((u32 *)(uint32_t)DAT_00412990) = DAT_0041298C;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00412994. */
void oot3d_startup_initializer_00412994(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004129D4);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_004129D4) + 0x28,((u8 *)(uint32_t)DAT_004129D0),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_004129D8),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_004129DC),0x28);
  return;
}

/* Native process initializer at 0x004129E0. */
void oot3d_startup_initializer_004129e0(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00412A04);
  uVar1 = DAT_00412A00;
  *((u32 *)(uint32_t)DAT_00412A04) = DAT_00412A00;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00412A08. */
void oot3d_startup_initializer_00412a08(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00412A2C);
  uVar1 = DAT_00412A28;
  *((u32 *)(uint32_t)DAT_00412A2C) = DAT_00412A28;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00412A30. */
void oot3d_startup_initializer_00412a30(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;

  uVar3 = DAT_00412AF0;
  puVar1 = ((u32 *)(uint32_t)DAT_00412AE8);
  uVar4 = DAT_00412AE4;
  *((u32 *)(uint32_t)DAT_00412AE8) = DAT_00412AE4;
  puVar1[1] = uVar4;
  uVar2 = DAT_00412AEC;
  puVar1[2] = uVar4;
  puVar1[0x18] = uVar2;
  puVar1[0x19] = uVar2;
  puVar1[0x1a] = uVar4;
  oot3d_startup_construct_array(DAT_00412AF4,uVar3,0x40,0x67);
  oot3d_startup_construct_array(DAT_00412AFC,DAT_00412AF8,0x48,0x3c);
  oot3d_startup_construct_array(DAT_00412B04,DAT_00412B00,0x40,0x82);
  puVar1 = ((u32 *)(uint32_t)DAT_00412B08);
  *((u32 *)(uint32_t)DAT_00412B08) = uVar4;
  puVar1[1] = uVar4;
  puVar1[2] = uVar4;
  uVar2 = DAT_00412B0C;
  puVar1[3] = uVar4;
  puVar1[4] = uVar4;
  puVar1[5] = uVar2;
  return;
}

/* Native process initializer at 0x00412B10. */
void oot3d_startup_initializer_00412b10(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;

  oot3d_startup_construct_00401318(DAT_00412B94);
  oot3d_startup_construct_array(DAT_00412BA4,DAT_00412BA0,0x10,0x12);
  oot3d_startup_construct_00401430(DAT_00412BA8);
  uVar4 = DAT_00412BC0;
  uVar2 = DAT_00412BB4;
  puVar1 = ((u32 *)(uint32_t)DAT_00412BB0);
  *((u32 *)(uint32_t)DAT_00412BB0) = 0x3c;
  puVar1[1] = 4000;
  puVar1[2] = 100;
  puVar1[3] = uVar2;
  uVar3 = DAT_00412BBC;
  uVar2 = DAT_00412BB8;
  puVar1[4] = DAT_00412BB8;
  puVar1[5] = uVar3;
  puVar1[6] = uVar4;
  puVar1[7] = uVar2;
  return;
}

/* Native process initializer at 0x00412BC4. */
void oot3d_startup_initializer_00412bc4(void)

{
  undefined4 *puVar1;
  u8 *puVar2;

  *(undefined4 *)((u8 *)(uint32_t)DAT_00412CB0) = 0;
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412CBC) = 0;
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412CC4) = 0;
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412CC8) = 0;
  *((longlong *)(uint32_t)DAT_00412CD0) = (ulonglong)DAT_00412CCC * 10;
  puVar2 = ((u8 *)(uint32_t)DAT_00412CD8);
  puVar1 = ((u32 *)(uint32_t)DAT_00412CD4);
  ((u32 *)(uint32_t)DAT_00412CD4)[1] = 0;
  puVar1[2] = 0;
  *puVar1 = (u32)(uint32_t)(puVar2);
  puVar1[3] = 0;
  puVar2 = ((u8 *)(uint32_t)DAT_00412CE0);
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412CE0) = 0;
  *(undefined4 *)(puVar2 + 0x38) = 0xffffffff;
  *(undefined4 *)(puVar2 + 0x3c) = 0xffffffff;
  *(undefined4 *)(puVar2 + 0x40) = 0;
  *(undefined4 *)(puVar2 + 0x44) = 0;
  *(undefined4 *)(puVar2 + -100) = 0;
  *(undefined4 *)(puVar2 + 0x20) = 0;
  puVar2[0x24] = 1;
  puVar2 = ((u8 *)(uint32_t)DAT_00412CE8);
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412CE8) = 0;
  *(undefined4 *)(puVar2 + 4) = 0;
  return;
}

/* Native process initializer at 0x00412CEC. */
void oot3d_startup_initializer_00412cec(void)

{
  *((u32 *)(uint32_t)DAT_00412CFC) = 0;
  return;
}

/* Native process initializer at 0x00412D00. */
void oot3d_startup_initializer_00412d00(void)

{
  undefined4 *puVar1;

  puVar1 = ((u32 *)(uint32_t)DAT_00412D20);
  *((u32 *)(uint32_t)DAT_00412D20) = DAT_00412D24;
  puVar1[1] = 0;
  *(undefined1 *)(puVar1 + 2) = 0;
  return;
}

/* Native process initializer at 0x00412D30. */
void oot3d_startup_initializer_00412d30(void)

{
  undefined4 *puVar1;
  u8 *puVar2;
  int iVar3;

  puVar1 = ((u32 *)(uint32_t)DAT_00412DBC);
  *((u32 *)(uint32_t)DAT_00412DBC) = 0;
  puVar1[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  *(undefined1 *)(puVar1 + 4) = 0;
  puVar2 = ((u8 *)(uint32_t)DAT_00412DC8);
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412DC8) = 0;
  puVar2[4] = 1;
  *(undefined4 *)((u8 *)(uint32_t)DAT_00412DD0) = 0;
  iVar3 = ((s32)DAT_00412DD4);
  *(undefined4 *)(((s32)DAT_00412DD4) + 4) = 0;
  *(undefined2 *)(iVar3 + 8) = 0;
  *(undefined4 *)(iVar3 + 0xc) = 0;
  *(undefined2 *)(iVar3 + 0x10) = 0;
  *(undefined4 *)(iVar3 + 0x14) = 0;
  *(undefined4 *)(iVar3 + 0x1c) = 0xffffffff;
  *(undefined4 *)(iVar3 + 0x18) = 0;
  *(undefined4 *)(iVar3 + 0x2c) = 0;
  *(undefined4 *)(iVar3 + 0x30) = 0;
  return;
}

/* Native process initializer at 0x00412DDC. */
void oot3d_startup_initializer_00412ddc(void)

{
  undefined4 *puVar1;

  puVar1 = ((u32 *)(uint32_t)DAT_00412E14);
  *((u32 *)(uint32_t)DAT_00412E14) = 0;
  puVar1[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  puVar1[4] = 0xffffffff;
  *(undefined1 *)(puVar1 + 0x4c6) = 0;
  *(undefined1 *)((int)puVar1 + 0x1319) = 1;
  return;
}

/* Native process initializer at 0x00412E20. */
void oot3d_startup_initializer_00412e20(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  undefined4 uVar3;

  puVar2 = ((u32 *)(uint32_t)DAT_00412EB4);
  uVar1 = DAT_00412EB0;
  *((u32 *)(uint32_t)DAT_00412EB4) = DAT_00412EAC;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  puVar2[3] = uVar1;
  puVar2[4] = uVar1;
  puVar2[5] = uVar1;
  uVar3 = DAT_00412EB8;
  puVar2[6] = DAT_00412EB8;
  puVar2[7] = uVar3;
  puVar2[8] = uVar1;
  puVar2[9] = uVar1;
  puVar2[10] = uVar1;
  puVar2[0xb] = uVar1;
  puVar2[0xc] = uVar1;
  puVar2[0xd] = uVar1;
  puVar2[0xe] = uVar1;
  puVar2[0xf] = uVar1;
  puVar2[0x10] = uVar1;
  puVar2[0x11] = uVar1;
  return;
}

/* Native process initializer at 0x00412EBC. */
void oot3d_startup_initializer_00412ebc(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00412EFC);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00412EFC) + 0x28,((u8 *)(uint32_t)DAT_00412EF8),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00412F00),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00412F04),0x28);
  return;
}

/* Native process initializer at 0x00412F08. */
void oot3d_startup_initializer_00412f08(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00412F48);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00412F48) + 0x28,((u8 *)(uint32_t)DAT_00412F44),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00412F4C),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00412F50),0x28);
  return;
}

/* Native process initializer at 0x00412F54. */
void oot3d_startup_initializer_00412f54(void)

{
  oot3d_startup_construct_array(DAT_00412F84,DAT_00412F80,4,0x10);
  return;
}

/* Native process initializer at 0x00412F90. */
void oot3d_startup_initializer_00412f90(void)

{
  *((u32 *)(uint32_t)DAT_00412FA0) = 0;
  return;
}

/* Native process initializer at 0x00412FA4. */
void oot3d_startup_initializer_00412fa4(void)

{
  *((u32 *)(uint32_t)DAT_00412FB4) = 0;
  return;
}

/* Native process initializer at 0x00412FB8. */
void oot3d_startup_initializer_00412fb8(void)

{
  *((u32 *)(uint32_t)DAT_00412FC8) = 0;
  return;
}

/* Native process initializer at 0x00412FCC. */
void oot3d_startup_initializer_00412fcc(void)

{
  *((u32 *)(uint32_t)DAT_00412FDC) = 0;
  return;
}

/* Native process initializer at 0x00412FE0. */
void oot3d_startup_initializer_00412fe0(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;

  uVar2 = DAT_00413008;
  puVar1 = ((u32 *)(uint32_t)DAT_00413004);
  *((u32 *)(uint32_t)DAT_00413004) = 0;
  puVar1[1] = (u32)(uint32_t)(puVar1 + 1);
  puVar1[2] = (u32)(uint32_t)(puVar1 + 1);
  return;
}

/* Native process initializer at 0x00413010. */
void oot3d_startup_initializer_00413010(void)

{
  oot3d_startup_construct_array(DAT_00413024,DAT_00413028,0x1c,3);
  return;
}

/* Native process initializer at 0x0041302C. */
void oot3d_startup_initializer_0041302c(void)

{
  float *pfVar1;
  float *pfVar2;
  float fVar3;
  float fVar4;

  fVar4 = oot3d_u32_to_float(DAT_0041307C);
  pfVar2 = ((float *)(uint32_t)DAT_00413078);
  pfVar1 = ((float *)(uint32_t)DAT_00413070);
  fVar3 = *((float *)(uint32_t)DAT_00413070) * oot3d_u32_to_float(DAT_00413074);
  *((float *)(uint32_t)DAT_00413078) = fVar3;
  pfVar2[2] = fVar3;
  fVar4 = *pfVar1 * fVar4;
  pfVar2[3] = fVar4;
  pfVar2[5] = fVar3;
  pfVar2[6] = fVar3;
  pfVar2[8] = fVar4;
  pfVar2[9] = fVar4;
  pfVar2[0xb] = fVar4;
  return;
}

/* Native process initializer at 0x00413080. */
void oot3d_startup_initializer_00413080(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 *puVar3;

  puVar3 = ((u32 *)(uint32_t)DAT_004130C4);
  uVar2 = DAT_004130C0;
  uVar1 = DAT_004130BC;
  *((u32 *)(uint32_t)DAT_004130C4) = DAT_004130BC;
  puVar3[1] = uVar2;
  puVar3[2] = uVar1;
  uVar2 = DAT_004130C8;
  puVar3[3] = uVar1;
  puVar3[4] = uVar2;
  puVar3[5] = uVar1;
  return;
}

/* Native process initializer at 0x004130CC. */
void oot3d_startup_initializer_004130cc(void)

{
  oot3d_startup_construct_array(DAT_00413124,DAT_00413120,0xa0,0x20);
  oot3d_startup_construct_00403078(DAT_00413130);
  oot3d_startup_construct_004031f8(DAT_00413138);
  *((u32 *)(uint32_t)DAT_00413140) = DAT_0041313C;
  return;
}

/* Native process initializer at 0x00413144. */
void oot3d_startup_initializer_00413144(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00413170);
  uVar1 = DAT_0041316C;
  *((u32 *)(uint32_t)DAT_00413170) = DAT_00413168;
  puVar2[1] = uVar1;
  uVar1 = DAT_00413178;
  puVar2[-2] = DAT_00413174;
  puVar2[-1] = uVar1;
  return;
}

/* Native process initializer at 0x0041317C. */
void oot3d_startup_initializer_0041317c(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;

  uVar2 = DAT_004131A8;
  puVar1 = ((u32 *)(uint32_t)DAT_004131A4);
  ((u32 *)(uint32_t)DAT_004131A4)[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  *puVar1 = uVar2;
  return;
}

/* Native process initializer at 0x004131B4. */
void oot3d_startup_initializer_004131b4(void)

{
  undefined1 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004131D4);
  *((u8 *)(uint32_t)DAT_004131D4) = 0x7f;
  puVar1[1] = 0x7f;
  puVar1[2] = 0x7f;
  puVar1[3] = 0x7f;
  puVar1[4] = 0x7f;
  return;
}

/* Native process initializer at 0x004131D8. */
void oot3d_startup_initializer_004131d8(void)

{
  undefined4 *puVar1;

  puVar1 = ((u32 *)(uint32_t)DAT_004131F8);
  *((u32 *)(uint32_t)DAT_004131F8) = 0xbe0;
  puVar1[1] = 0xe60;
  puVar1[2] = 0x820;
  return;
}

/* Native process initializer at 0x004131FC. */
void oot3d_startup_initializer_004131fc(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  undefined4 uVar3;

  uVar3 = DAT_00413234;
  puVar2 = ((u32 *)(uint32_t)DAT_00413230);
  uVar1 = DAT_0041322C;
  *((u32 *)(uint32_t)DAT_00413230) = DAT_0041322C;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  oot3d_startup_construct_array(puVar2 + 3,uVar3,0x4c,200);
  return;
}

/* Native process initializer at 0x00413238. */
void oot3d_startup_initializer_00413238(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00413278);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00413278) + 0x28,((u8 *)(uint32_t)DAT_00413274),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_0041327C),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00413280),0x28);
  return;
}

/* Native process initializer at 0x00413284. */
void oot3d_startup_initializer_00413284(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 *puVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  undefined4 uVar7;
  undefined4 uVar8;

  puVar4 = ((u32 *)(uint32_t)DAT_00413338);
  uVar3 = DAT_00413334;
  uVar2 = DAT_00413330;
  uVar1 = DAT_0041332C;
  *((u32 *)(uint32_t)DAT_00413338) = DAT_0041332C;
  puVar4[1] = uVar2;
  uVar6 = DAT_00413340;
  uVar5 = DAT_0041333C;
  puVar4[2] = uVar3;
  puVar4[3] = uVar1;
  uVar7 = DAT_00413344;
  puVar4[4] = uVar5;
  uVar8 = DAT_00413348;
  puVar4[5] = uVar6;
  puVar4[6] = uVar1;
  puVar4[7] = uVar7;
  puVar4[8] = uVar8;
  puVar4[9] = uVar3;
  puVar4[10] = uVar2;
  puVar4[0xb] = uVar3;
  puVar4[0xc] = uVar3;
  puVar4[0xd] = uVar7;
  puVar4[0xe] = uVar8;
  puVar4[0xf] = uVar3;
  puVar4[0x10] = uVar5;
  puVar4[0x11] = uVar6;
  return;
}

/* Native process initializer at 0x0041334C. */
void oot3d_startup_initializer_0041334c(void)

{
  undefined1 *puVar1;
  undefined4 uVar2;

  uVar2 = DAT_004133D0;
  puVar1 = ((u8 *)(uint32_t)DAT_004133CC);
  *(undefined4 *)(((u8 *)(uint32_t)DAT_004133CC) + 4) = 0;
  *(undefined4 *)(puVar1 + 0xc) = 0;
  *(undefined4 *)(puVar1 + 0x10) = 0;
  *(undefined4 *)(puVar1 + 0x14) = 0;
  *(undefined4 *)(puVar1 + 0x18) = 0;
  *(undefined4 *)(puVar1 + 0x1c) = 0;
  *(undefined4 *)(puVar1 + 0x20) = 0;
  *(undefined4 *)(puVar1 + 0x5c) = 0;
  *(undefined4 *)(puVar1 + 8) = uVar2;
  *(undefined4 *)(puVar1 + 0x60) = 0;
  *(undefined4 *)(puVar1 + 100) = 0;
  *(undefined4 *)(puVar1 + 0x68) = 0xffffffff;
  *(undefined4 *)(puVar1 + 0x7c) = 0;
  *(undefined4 *)(puVar1 + 0x80) = 0;
  *(undefined4 *)(puVar1 + 0x84) = 0;
  *(undefined4 *)(puVar1 + 0x88) = 0;
  *(undefined4 *)(puVar1 + 0x8c) = 0;
  *(undefined4 *)(puVar1 + 0x90) = 0;
  *(undefined4 *)(puVar1 + 0x94) = 0xffffffff;
  *(undefined4 *)(puVar1 + 0xa8) = 0;
  *(undefined4 *)(puVar1 + 0xac) = 0;
  *(undefined4 *)(puVar1 + 0xb0) = 0;
  *(undefined4 *)(puVar1 + 0xb4) = 0;
  *(undefined4 *)(puVar1 + 0xb8) = 0;
  *puVar1 = 0;
  return;
}

/* Native process initializer at 0x004133DC. */
void oot3d_startup_initializer_004133dc(void)

{
  float *pfVar1;
  float *pfVar2;
  float fVar3;
  float fVar4;

  fVar4 = oot3d_u32_to_float(DAT_0041343C);
  pfVar2 = ((float *)(uint32_t)DAT_00413438);
  pfVar1 = ((float *)(uint32_t)DAT_00413430);
  fVar3 = *((float *)(uint32_t)DAT_00413430) * oot3d_u32_to_float(DAT_00413434);
  *((float *)(uint32_t)DAT_00413438) = fVar3;
  fVar4 = *pfVar1 * fVar4;
  pfVar2[1] = fVar4;
  pfVar2[3] = fVar4;
  pfVar2[4] = fVar4;
  pfVar2[6] = fVar3;
  pfVar2[9] = fVar4;
  pfVar2[0xc] = fVar3;
  pfVar2[0xf] = fVar4;
  pfVar2[0x12] = fVar3;
  pfVar2[0x13] = fVar3;
  pfVar2[0x15] = fVar4;
  pfVar2[0x16] = fVar3;
  return;
}

/* Native process initializer at 0x00413440. */
void oot3d_startup_initializer_00413440(void)

{
  *((u32 *)(uint32_t)DAT_00413450) = 0;
  return;
}

/* Native process initializer at 0x00413454. */
void oot3d_startup_initializer_00413454(void)

{
  *((u32 *)(uint32_t)DAT_00413464) = 0;
  return;
}

/* Native process initializer at 0x00413468. */
void oot3d_startup_initializer_00413468(void)

{
  *((u32 *)(uint32_t)DAT_0041347C) = DAT_00413478;
  return;
}

/* Native process initializer at 0x00413480. */
void oot3d_startup_initializer_00413480(void)

{
  *((u32 *)(uint32_t)DAT_00413490) = 0;
  return;
}

/* Native process initializer at 0x00413494. */
void oot3d_startup_initializer_00413494(void)

{
  *((u32 *)(uint32_t)DAT_004134A8) = DAT_004134A4;
  return;
}

/* Native process initializer at 0x004134AC. */
void oot3d_startup_initializer_004134ac(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_004134D0);
  uVar1 = DAT_004134CC;
  *((u32 *)(uint32_t)DAT_004134D0) = DAT_004134CC;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x004134D4. */
void oot3d_startup_initializer_004134d4(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_004134F8);
  uVar1 = DAT_004134F4;
  *((u32 *)(uint32_t)DAT_004134F8) = DAT_004134F4;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x004134FC. */
void oot3d_startup_initializer_004134fc(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  undefined4 uVar3;
  undefined4 uVar4;

  uVar4 = DAT_00413550;
  puVar2 = ((u32 *)(uint32_t)DAT_00413548);
  uVar1 = DAT_00413544;
  *((u32 *)(uint32_t)DAT_00413548) = DAT_00413544;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  uVar3 = DAT_0041354C;
  puVar2[3] = uVar1;
  puVar2[4] = uVar1;
  puVar2[5] = uVar3;
  oot3d_startup_construct_array(puVar2 + 9,uVar4,0x44,100);
  return;
}

/* Native process initializer at 0x00413554. */
void oot3d_startup_initializer_00413554(void)

{
  oot3d_startup_construct_array(DAT_00413568,DAT_0041356C,0x1c,3);
  return;
}

/* Native process initializer at 0x00413570. */
void oot3d_startup_initializer_00413570(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004135B0);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_004135B0) + 0x28,((u8 *)(uint32_t)DAT_004135AC),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_004135B4),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_004135B8),0x28);
  return;
}

/* Native process initializer at 0x004135BC. */
void oot3d_startup_initializer_004135bc(void)

{
  oot3d_memcpy_end(((void *)(uint32_t)DAT_004135D0),((void *)(uint32_t)DAT_004135CC),0x28);
  return;
}

/* Native process initializer at 0x004135D4. */
void oot3d_startup_initializer_004135d4(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_004135F8);
  uVar1 = DAT_004135F4;
  *((u32 *)(uint32_t)DAT_004135F8) = DAT_004135F4;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x004135FC. */
void oot3d_startup_initializer_004135fc(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00413620);
  uVar1 = DAT_0041361C;
  *((u32 *)(uint32_t)DAT_00413620) = DAT_0041361C;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00413624. */
void oot3d_startup_initializer_00413624(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 *puVar3;

  puVar3 = ((u32 *)(uint32_t)DAT_00413650);
  uVar2 = DAT_0041364C;
  uVar1 = DAT_00413648;
  *((u32 *)(uint32_t)DAT_00413650) = DAT_00413644;
  puVar3[1] = uVar1;
  puVar3[2] = uVar2;
  return;
}

/* Native process initializer at 0x00413654. */
void oot3d_startup_initializer_00413654(void)

{
  int iVar1;
  undefined4 uVar2;

  iVar1 = ((s32)DAT_0041367C);
  uVar2 = *((u32 *)(uint32_t)DAT_00413678);
  *(undefined4 *)(((s32)DAT_0041367C) + 4) = uVar2;
  *(undefined4 *)(iVar1 + 8) = uVar2;
  *(undefined4 *)(iVar1 + 0xc) = uVar2;
  *(undefined4 *)(iVar1 + 0x18) = uVar2;
  *(undefined4 *)(iVar1 + 0x1c) = uVar2;
  return;
}

/* Native process initializer at 0x00413680. */
void oot3d_startup_initializer_00413680(void)

{
  bool bVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_004136C0);
  *((u32 *)(uint32_t)DAT_004136C0) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  return;
}

/* Native process initializer at 0x004136CC. */
void oot3d_startup_initializer_004136cc(void)

{
  *((u32 *)(uint32_t)DAT_004136DC) = 0;
  return;
}

/* Native process initializer at 0x004136E0. */
void oot3d_startup_initializer_004136e0(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00413704);
  uVar1 = DAT_00413700;
  *((u32 *)(uint32_t)DAT_00413704) = DAT_00413700;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00413708. */
void oot3d_startup_initializer_00413708(void)

{
  float *pfVar1;
  float *pfVar2;
  u8 *source;
  u8 *puVar3;
  float fVar4;
  float fVar5;

  puVar3 = ((u8 *)(uint32_t)DAT_00413798);
  fVar5 = oot3d_u32_to_float(DAT_00413790);
  pfVar2 = ((float *)(uint32_t)DAT_0041378C);
  pfVar1 = ((float *)(uint32_t)DAT_00413784);
  fVar4 = *((float *)(uint32_t)DAT_00413784) * oot3d_u32_to_float(DAT_00413788);
  *((float *)(uint32_t)DAT_0041378C) = fVar4;
  pfVar2[2] = fVar4;
  source = ((u8 *)(uint32_t)DAT_00413794);
  fVar5 = *pfVar1 * fVar5;
  pfVar2[3] = fVar5;
  pfVar2[5] = fVar4;
  pfVar2[6] = fVar4;
  pfVar2[8] = fVar5;
  pfVar2[9] = fVar5;
  pfVar2[0xb] = fVar5;
  oot3d_memcpy_end(puVar3 + 0x28,source,0x28);
  oot3d_memcpy_end(puVar3 + 0x50,((u8 *)(uint32_t)DAT_0041379C),0x28);
  oot3d_memcpy_end(puVar3 + 0x78,((u8 *)(uint32_t)DAT_004137A0),0x28);
  return;
}

/* Native process initializer at 0x004137A4. */
void oot3d_startup_initializer_004137a4(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004137E4);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_004137E4) + 0x28,((u8 *)(uint32_t)DAT_004137E0),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_004137E8),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_004137EC),0x28);
  return;
}

/* Native process initializer at 0x004137F0. */
void oot3d_startup_initializer_004137f0(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;

  uVar2 = DAT_0041380C;
  puVar1 = ((u32 *)(uint32_t)DAT_00413808);
  *((u32 *)(uint32_t)DAT_00413808) = 0;
  return;
}

/* Native process initializer at 0x00413814. */
void oot3d_startup_initializer_00413814(void)

{
  bool bVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00413854);
  *((u32 *)(uint32_t)DAT_00413854) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  return;
}

/* Native process initializer at 0x00413860. */
void oot3d_startup_initializer_00413860(void)

{
  u8 *puVar1;
  u8 *puVar2;

  oot3d_startup_construct_00404480(DAT_00413898);
  puVar2 = ((u8 *)(uint32_t)DAT_004138A4);
  puVar1 = ((u8 *)(uint32_t)DAT_0041389C);
  *(undefined4 *)((u8 *)(uint32_t)DAT_004138A4) = 0;
  *(undefined4 *)(puVar2 + 4) = 0;
  return;
}

/* Native process initializer at 0x004138AC. */
void oot3d_startup_initializer_004138ac(void)

{
  *((u32 *)(uint32_t)DAT_004138C0) = DAT_004138BC;
  return;
}

/* Native process initializer at 0x004138C4. */
void oot3d_startup_initializer_004138c4(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 *puVar3;

  puVar3 = ((u32 *)(uint32_t)DAT_004138F0);
  uVar2 = DAT_004138EC;
  uVar1 = DAT_004138E8;
  *((u32 *)(uint32_t)DAT_004138F0) = DAT_004138E4;
  puVar3[1] = uVar1;
  puVar3[2] = uVar2;
  return;
}

/* Native process initializer at 0x004138F4. */
void oot3d_startup_initializer_004138f4(void)

{
  void *source;
  int iVar1;

  iVar1 = ((s32)DAT_00413974);
  source = ((void *)(uint32_t)DAT_00413970);
  oot3d_memcpy_end((void *)(((s32)DAT_00413974) + 0x28),((void *)(uint32_t)DAT_00413970),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x50),(void *)((int)source + 0x28),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x78),(void *)((int)source + 0x50),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x140),source,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x168),(void *)((int)source + 0x28),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 400),(void *)((int)source + 0x50),0x28);
  return;
}

/* Native process initializer at 0x00413978. */
void oot3d_startup_initializer_00413978(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004139B8);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_004139B8) + 0x28,((u8 *)(uint32_t)DAT_004139B4),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_004139BC),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_004139C0),0x28);
  return;
}

/* Native process initializer at 0x004139C4. */
void oot3d_startup_initializer_004139c4(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00413A04);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00413A04) + 0x28,((u8 *)(uint32_t)DAT_00413A00),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00413A08),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00413A0C),0x28);
  return;
}

/* Native process initializer at 0x00413A10. */
void oot3d_startup_initializer_00413a10(void)

{
  oot3d_memcpy_end(((void *)(uint32_t)DAT_00413A24),((void *)(uint32_t)DAT_00413A20),0x28);
  return;
}

/* Native process initializer at 0x00413A28. */
void oot3d_startup_initializer_00413a28(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00413A68);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00413A68) + 0x28,((u8 *)(uint32_t)DAT_00413A64),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00413A6C),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00413A70),0x28);
  return;
}

/* Native process initializer at 0x00413A74. */
void oot3d_startup_initializer_00413a74(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00413AB4);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00413AB4) + 0x28,((u8 *)(uint32_t)DAT_00413AB0),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00413AB8),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00413ABC),0x28);
  return;
}

/* Native process initializer at 0x00413AC0. */
void oot3d_startup_initializer_00413ac0(void)

{
  void *source;
  int iVar1;
  void *source_00;
  void *source_01;

  iVar1 = ((s32)DAT_00413B74);
  source = ((void *)(uint32_t)DAT_00413B70);
  oot3d_memcpy_end((void *)(((s32)DAT_00413B74) + 0x28),((void *)(uint32_t)DAT_00413B70),0x28);
  source_00 = (void *)((int)source + 0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x50),source_00,0x28);
  source_01 = (void *)((int)source + 0x50);
  oot3d_memcpy_end((void *)(iVar1 + 0x78),source_01,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x140),source,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x168),source_00,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 400),source_01,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 600),source,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x280),source_00,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x2a8),source_01,0x28);
  return;
}

/* Native process initializer at 0x00413B78. */
void oot3d_startup_initializer_00413b78(void)

{
  void *source;
  int iVar1;
  void *source_00;

  iVar1 = ((s32)DAT_00413C18);
  source = ((void *)(uint32_t)DAT_00413C14);
  oot3d_memcpy_end((void *)(((s32)DAT_00413C18) + 0x28),((void *)(uint32_t)DAT_00413C14),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x50),(void *)((int)source + 0x28),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x78),(void *)((int)source + 0x50),0x28);
  source_00 = ((void *)(uint32_t)DAT_00413C1C);
  oot3d_memcpy_end((void *)(iVar1 + 0x140),((void *)(uint32_t)DAT_00413C1C),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 600),source,0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x280),(void *)((int)source + 0x28),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x2a8),(void *)((int)source + 0x50),0x28);
  oot3d_memcpy_end((void *)(iVar1 + 0x370),source_00,0x28);
  return;
}

/* Native process initializer at 0x00413C20. */
void oot3d_startup_initializer_00413c20(void)

{
  bool bVar1;
  undefined4 *puVar2;
  int iVar3;

  puVar2 = ((u32 *)(uint32_t)DAT_00413D14);
  *((u32 *)(uint32_t)DAT_00413D14) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  puVar2 = ((u32 *)(uint32_t)DAT_00413D20);
  *((u32 *)(uint32_t)DAT_00413D20) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  puVar2 = ((u32 *)(uint32_t)DAT_00413D28);
  iVar3 = ((s32)DAT_00413D24);
  *((u32 *)(uint32_t)DAT_00413D28) = *(undefined4 *)(((s32)DAT_00413D24) + 4);
  puVar2[1] = *(undefined4 *)(iVar3 + 4);
  puVar2 = ((u32 *)(uint32_t)DAT_00413D2C);
  *((u32 *)(uint32_t)DAT_00413D2C) = 0;
  puVar2[2] = 0xffffffff;
  puVar2[1] = 0;
  puVar2[0xb] = 0;
  puVar2[0xc] = 0;
  puVar2[0xd] = 0;
  puVar2[0xe] = 0;
  puVar2[0xf] = 0;
  puVar2[0x10] = 0;
  puVar2[0x11] = 0;
  *(undefined1 *)(puVar2 + 0x12) = 0;
  puVar2[0x13] = 0;
  *(undefined1 *)(puVar2 + 0x14) = 0;
  puVar2[0x16] = 0;
  puVar2[0x17] = 0;
  puVar2[0x1a] = 0;
  puVar2[0x1b] = 0;
  *(undefined1 *)(puVar2 + 0x1c) = 1;
  *((u32 *)(uint32_t)DAT_00413D34) = *(undefined4 *)(iVar3 + 4);
  return;
}

/* Native process initializer at 0x00413D38. */
void oot3d_startup_initializer_00413d38(void)

{
  *((u32 *)(uint32_t)DAT_00413D4C) = DAT_00413D48;
  return;
}

/* Native process initializer at 0x00413D50. */
void oot3d_startup_initializer_00413d50(void)

{
  int iVar1;
  undefined4 *puVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  int iVar5;
  undefined4 *puVar6;
  undefined4 *puVar7;

  puVar2 = ((u32 *)(uint32_t)DAT_00413DEC);
  ((u32 *)(uint32_t)DAT_00413DEC)[0x9d] = 0;
  puVar2[0x9e] = 0;
  puVar6 = puVar2 + 0xa0;
  puVar7 = puVar2 + 0x328;
  iVar5 = 0;
  puVar2[0x9f] = 0xffffffff;
  do {
    if (puVar6 == (undefined4 *)0x0) {
      uVar4 = 0;
    }
    else {
      uVar4 = oot3d_startup_construct_00401268(puVar6,iVar5);
    }
    puVar2[iVar5 + 0x670] = uVar4;
    puVar6 = puVar6 + 0x1b;
    if (puVar7 == (undefined4 *)0x0) {
      uVar4 = 0;
    }
    else {
      uVar4 = oot3d_startup_construct_00401668(puVar7,iVar5);
    }
    iVar1 = iVar5 + 0x670;
    iVar5 = iVar5 + 1;
    puVar7 = puVar7 + 0x23;
    *(undefined4 *)(puVar2[iVar1] + 0x68) = uVar4;
    uVar3 = DAT_00413DF8;
    uVar4 = DAT_00413DF4;
  } while (iVar5 < 0x18);
  *puVar2 = DAT_00413DF0;
  return;
}

/* Native process initializer at 0x00413DFC. */
void oot3d_startup_initializer_00413dfc(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00413E20);
  uVar1 = DAT_00413E1C;
  *((u32 *)(uint32_t)DAT_00413E20) = DAT_00413E1C;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00413E24. */
void oot3d_startup_initializer_00413e24(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00413E64);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00413E64) + 0x28,((u8 *)(uint32_t)DAT_00413E60),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00413E68),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00413E6C),0x28);
  return;
}

/* Native process initializer at 0x00413E70. */
void oot3d_startup_initializer_00413e70(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00413EB0);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00413EB0) + 0x28,((u8 *)(uint32_t)DAT_00413EAC),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00413EB4),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00413EB8),0x28);
  return;
}

/* Native process initializer at 0x00413EBC. */
void oot3d_startup_initializer_00413ebc(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00413EFC);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00413EFC) + 0x28,((u8 *)(uint32_t)DAT_00413EF8),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_00413F00),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00413F04),0x28);
  return;
}

/* Native process initializer at 0x00413F08. */
void oot3d_startup_initializer_00413f08(void)

{
  oot3d_startup_construct_array(DAT_00413F3C,DAT_00413F38,0x6c,1);
  oot3d_startup_construct_array(DAT_00413F44,DAT_00413F40,0x6c,1);
  return;
}

/* Native process initializer at 0x00413F48. */
void oot3d_startup_initializer_00413f48(void)

{
  bool bVar1;
  undefined4 *puVar2;
  undefined4 uVar3;

  oot3d_startup_construct_array(DAT_00414034,DAT_00414030,0x10,0x20);
  *((u32 *)(uint32_t)DAT_00414038) = 0;
  puVar2 = ((u32 *)(uint32_t)DAT_0041403C);
  *((u32 *)(uint32_t)DAT_0041403C) = 0;
  (void)Oot3dAtomic_ExchangeU32((volatile u32*)puVar2, 1u);
  puVar2[1] = 0;
  puVar2[2] = 0;
  oot3d_startup_initialize_heap(DAT_0041404C,0x10,DAT_00414048,0x100,4,0);
  oot3d_startup_initialize_heap(DAT_00414058,8,DAT_00414054,0x80,4,0);
  uVar3 = oot3d_startup_initialize_heap(DAT_00414060,8,DAT_0041405C,0x80,4,0);
  return;
}

/* Native process initializer at 0x00414064. */
void oot3d_startup_initializer_00414064(void)

{
  undefined1 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_0041408C);
  *((u8 *)(uint32_t)DAT_0041408C) = 0;
  *(undefined4 *)(puVar1 + 0x40) = 0;
  *(undefined4 *)(puVar1 + 0x44) = 0;
  *(undefined4 *)(puVar1 + 0x48) = 0xffffffff;
  return;
}

/* Native process initializer at 0x00414098. */
void oot3d_startup_initializer_00414098(void)

{
  *((u32 *)(uint32_t)DAT_004140AC) = DAT_004140A8;
  return;
}

/* Native process initializer at 0x004140B0. */
void oot3d_startup_initializer_004140b0(void)

{
  undefined1 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004140D0);
  *((u8 *)(uint32_t)DAT_004140D0) = 0x7f;
  puVar1[1] = 0x7f;
  puVar1[2] = 0x7f;
  puVar1[3] = 0x7f;
  puVar1[4] = 0x7f;
  return;
}

/* Native process initializer at 0x004140D4. */
void oot3d_startup_initializer_004140d4(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_004140F8);
  uVar1 = DAT_004140F4;
  *((u32 *)(uint32_t)DAT_004140F8) = DAT_004140F4;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x004140FC. */
void oot3d_startup_initializer_004140fc(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  oot3d_startup_construct_array(DAT_00414138,DAT_00414134,0x4c,200);
  puVar2 = ((u32 *)(uint32_t)DAT_00414140);
  uVar1 = DAT_0041413C;
  *((u32 *)(uint32_t)DAT_00414140) = DAT_0041413C;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00414144. */
void oot3d_startup_initializer_00414144(void)

{
  void *source;

  source = ((void *)(uint32_t)DAT_00414170);
  oot3d_memcpy_end(((void *)(uint32_t)DAT_00414174),((void *)(uint32_t)DAT_00414170),0x28);
  oot3d_memcpy_end(((void *)(uint32_t)DAT_00414178),source,0x28);
  return;
}

/* Native process initializer at 0x0041417C. */
void oot3d_startup_initializer_0041417c(void)

{
  float *pfVar1;
  float *pfVar2;
  u8 *source;
  u8 *puVar3;
  float fVar4;
  float fVar5;

  puVar3 = ((u8 *)(uint32_t)DAT_0041421C);
  fVar5 = oot3d_u32_to_float(DAT_00414214);
  pfVar2 = ((float *)(uint32_t)DAT_00414210);
  pfVar1 = ((float *)(uint32_t)DAT_00414208);
  fVar4 = *((float *)(uint32_t)DAT_00414208) * oot3d_u32_to_float(DAT_0041420C);
  *((float *)(uint32_t)DAT_00414210) = fVar4;
  pfVar2[2] = fVar4;
  source = ((u8 *)(uint32_t)DAT_00414218);
  fVar5 = *pfVar1 * fVar5;
  pfVar2[3] = fVar5;
  pfVar2[5] = fVar4;
  pfVar2[6] = fVar4;
  pfVar2[9] = fVar5;
  pfVar2[0xc] = fVar4;
  pfVar2[0xf] = fVar5;
  pfVar2[0x12] = fVar4;
  pfVar2[0x14] = fVar5;
  pfVar2[0x15] = fVar5;
  pfVar2[0x17] = fVar5;
  oot3d_memcpy_end(puVar3 + 0x28,source,0x28);
  oot3d_memcpy_end(puVar3 + 0x50,((u8 *)(uint32_t)DAT_00414220),0x28);
  oot3d_memcpy_end(puVar3 + 0x78,((u8 *)(uint32_t)DAT_00414224),0x28);
  return;
}

/* Native process initializer at 0x00414228. */
void oot3d_startup_initializer_00414228(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00414278);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_00414278) + 0x28,((u8 *)(uint32_t)DAT_00414274),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_0041427C),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_00414280),0x28);
  oot3d_memcpy_end(puVar1 + 0x140,((u8 *)(uint32_t)DAT_00414284),0x28);
  return;
}

/* Native process initializer at 0x00414288. */
void oot3d_startup_initializer_00414288(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004142C8);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_004142C8) + 0x28,((u8 *)(uint32_t)DAT_004142C4),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_004142CC),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_004142D0),0x28);
  return;
}

/* Native process initializer at 0x004142D4. */
void oot3d_startup_initializer_004142d4(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 *puVar3;

  puVar3 = ((u32 *)(uint32_t)DAT_00414300);
  uVar2 = DAT_004142FC;
  uVar1 = DAT_004142F8;
  *((u32 *)(uint32_t)DAT_00414300) = DAT_004142F4;
  puVar3[1] = uVar1;
  puVar3[2] = uVar2;
  return;
}

/* Native process initializer at 0x00414304. */
void oot3d_startup_initializer_00414304(void)

{
  undefined4 *puVar1;

  puVar1 = ((u32 *)(uint32_t)DAT_0041434C);
  *((u32 *)(uint32_t)DAT_0041434C) = 0;
  *(undefined1 *)(puVar1 + 1) = 1;
  puVar1 = ((u32 *)(uint32_t)DAT_00414358);
  *((u32 *)(uint32_t)DAT_00414358) = 0;
  puVar1[2] = 0xffffffff;
  puVar1[1] = 0;
  return;
}

/* Native process initializer at 0x00414360. */
void oot3d_startup_initializer_00414360(void)

{
  undefined4 uVar1;

  uVar1 = oot3d_startup_construct_00402fc0(DAT_0041437C);
  return;
}

/* Native process initializer at 0x00414388. */
void oot3d_startup_initializer_00414388(void)

{
  oot3d_memcpy_end(((void *)(uint32_t)DAT_0041439C),((void *)(uint32_t)DAT_00414398),0x28);
  return;
}

/* Native process initializer at 0x004143A0. */
void oot3d_startup_initializer_004143a0(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004143E0);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_004143E0) + 0x28,((u8 *)(uint32_t)DAT_004143DC),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_004143E4),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_004143E8),0x28);
  return;
}

/* Native process initializer at 0x004143EC. */
void oot3d_startup_initializer_004143ec(void)

{
  float *pfVar1;
  float *pfVar2;
  u8 *source;
  u8 *puVar3;
  float fVar4;
  float fVar5;

  puVar3 = ((u8 *)(uint32_t)DAT_0041447C);
  fVar4 = oot3d_u32_to_float(DAT_00414474);
  pfVar2 = ((float *)(uint32_t)DAT_00414470);
  pfVar1 = ((float *)(uint32_t)DAT_00414468);
  fVar5 = *((float *)(uint32_t)DAT_00414468) * oot3d_u32_to_float(DAT_0041446C);
  *((float *)(uint32_t)DAT_00414470) = fVar5;
  fVar4 = *pfVar1 * fVar4;
  pfVar2[3] = fVar4;
  pfVar2[6] = fVar5;
  source = ((u8 *)(uint32_t)DAT_00414478);
  fVar5 = -*pfVar1;
  pfVar2[7] = fVar5;
  pfVar2[9] = fVar4;
  pfVar2[10] = fVar5;
  oot3d_memcpy_end(puVar3 + 0x28,source,0x28);
  oot3d_memcpy_end(puVar3 + 0x50,((u8 *)(uint32_t)DAT_00414480),0x28);
  oot3d_memcpy_end(puVar3 + 0x78,((u8 *)(uint32_t)DAT_00414484),0x28);
  return;
}

/* Native process initializer at 0x00414488. */
void oot3d_startup_initializer_00414488(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  int iVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  undefined4 *puVar6;
  undefined4 uVar7;

  puVar1 = ((u32 *)(uint32_t)DAT_004145CC);
  uVar7 = DAT_004145C8;
  if (((*((u32 *)(uint32_t)DAT_004145C4) & 1) == 0) &&
     (iVar3 = oot3d_static_init_guard_acquire(((u32 *)(uint32_t)DAT_004145C4)), iVar3 != 0)) {
    *puVar1 = uVar7;
    puVar1[1] = uVar7;
    puVar1[2] = uVar7;
  }
  puVar2 = ((u32 *)(uint32_t)DAT_004145D0);
  uVar4 = puVar1[1];
  uVar5 = puVar1[2];
  puVar6 = ((u32 *)(uint32_t)DAT_004145D0) + 3;
  *((u32 *)(uint32_t)DAT_004145D0) = *puVar1;
  puVar2[1] = uVar4;
  puVar2[2] = uVar5;
  if (((*((u32 *)(uint32_t)DAT_004145D4) & 1) == 0) &&
     (iVar3 = oot3d_static_init_guard_acquire(((u32 *)(uint32_t)DAT_004145D4)), puVar1 = ((u32 *)(uint32_t)DAT_004145DC),
     uVar4 = DAT_004145D8, iVar3 != 0)) {
    *((u32 *)(uint32_t)DAT_004145DC) = DAT_004145D8;
    puVar1[1] = uVar7;
    puVar1[2] = uVar7;
    puVar1[3] = uVar7;
    puVar1[4] = uVar4;
    puVar1[5] = uVar7;
    puVar1[6] = uVar7;
    puVar1[7] = uVar7;
    puVar1[8] = uVar4;
  }
  puVar1 = ((u32 *)(uint32_t)DAT_004145DC);
  *puVar6 = *((u32 *)(uint32_t)DAT_004145DC);
  puVar2[4] = puVar1[1];
  puVar2[5] = puVar1[2];
  puVar2[6] = puVar1[3];
  puVar2[7] = puVar1[4];
  puVar2[8] = puVar1[5];
  puVar2[9] = puVar1[6];
  puVar2[10] = puVar1[7];
  puVar6 = ((u32 *)(uint32_t)DAT_004145E0);
  puVar2[0xb] = puVar1[8];
  *puVar6 = 0;
  puVar6[1] = 0;
  return;
}

/* Native process initializer at 0x004145E4. */
void oot3d_startup_initializer_004145e4(void)

{
  u8 *puVar1;
  u8 *puVar2;
  int iVar3;

  iVar3 = oot3d_startup_construct_array(DAT_00414688,((u8 *)(uint32_t)DAT_0041468C),8,7);
  *(undefined4 *)(iVar3 + 0x38) = 0;
  *(undefined4 *)(iVar3 + 0x3c) = 0;
  *(undefined4 *)(iVar3 + 0x40) = 0;
  *(u8 **)((u8 *)(uint32_t)DAT_00414694) = ((u8 *)(uint32_t)DAT_00414690);
  *(u8 **)((u8 *)(uint32_t)DAT_004146A4) = ((u8 *)(uint32_t)DAT_004146A0);
  *(u8 **)((u8 *)(uint32_t)DAT_004146B0) = ((u8 *)(uint32_t)DAT_004146AC);
  *(u8 **)((u8 *)(uint32_t)DAT_004146BC) = ((u8 *)(uint32_t)DAT_004146B8);
  puVar2 = ((u8 *)(uint32_t)DAT_004146C8);
  puVar1 = ((u8 *)(uint32_t)DAT_00414698);
  *(u8 **)((u8 *)(uint32_t)DAT_004146C8) = ((u8 *)(uint32_t)DAT_004146C4);
  return;
}

/* Native process initializer at 0x004146D0. */
void oot3d_startup_initializer_004146d0(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;

  uVar2 = DAT_00414710;
  puVar1 = ((u32 *)(uint32_t)DAT_00414708);
  ((u32 *)(uint32_t)DAT_00414708)[1] = 0;
  puVar1[2] = 0;
  puVar1[3] = 0;
  puVar1[4] = 0;
  puVar1[5] = 0;
  puVar1[6] = 0;
  puVar1[0x15] = 0;
  *puVar1 = DAT_0041470C;
  return;
}

/* Native process initializer at 0x00414718. */
void oot3d_startup_initializer_00414718(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 *puVar3;

  puVar3 = ((u32 *)(uint32_t)DAT_00414758);
  uVar2 = DAT_00414754;
  uVar1 = DAT_00414750;
  *((u32 *)(uint32_t)DAT_00414758) = DAT_00414750;
  puVar3[1] = uVar2;
  puVar3[2] = uVar1;
  puVar3[3] = uVar1;
  puVar3[4] = uVar1;
  puVar3[5] = uVar1;
  return;
}

/* Native process initializer at 0x0041475C. */
void oot3d_startup_initializer_0041475c(void)

{
  return;
}

/* Native process initializer at 0x00414760. */
void oot3d_startup_initializer_00414760(void)

{
  undefined1 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_00414788);
  *((u8 *)(uint32_t)DAT_00414788) = 0;
  *(undefined4 *)(puVar1 + 0x30) = 0;
  *(undefined4 *)(puVar1 + 0x34) = 0;
  *(undefined4 *)(puVar1 + 0x38) = 0xffffffff;
  return;
}

/* Native process initializer at 0x00414794. */
void oot3d_startup_initializer_00414794(void)

{
  u8 *puVar1;

  puVar1 = ((u8 *)(uint32_t)DAT_004147D4);
  oot3d_memcpy_end(((u8 *)(uint32_t)DAT_004147D4) + 0x28,((u8 *)(uint32_t)DAT_004147D0),0x28);
  oot3d_memcpy_end(puVar1 + 0x50,((u8 *)(uint32_t)DAT_004147D8),0x28);
  oot3d_memcpy_end(puVar1 + 0x78,((u8 *)(uint32_t)DAT_004147DC),0x28);
  return;
}

/* Native process initializer at 0x004147E0. */
void oot3d_startup_initializer_004147e0(void)

{
  undefined4 *puVar1;

  puVar1 = ((u32 *)(uint32_t)DAT_00414804);
  *((u32 *)(uint32_t)DAT_00414804) = 0;
  puVar1[1] = 0;
  puVar1[2] = 0xffffffff;
  return;
}

/* Native process initializer at 0x00414810. */
void oot3d_startup_initializer_00414810(void)

{
  undefined4 uVar1;
  undefined4 *puVar2;

  puVar2 = ((u32 *)(uint32_t)DAT_00414834);
  uVar1 = DAT_00414830;
  *((u32 *)(uint32_t)DAT_00414834) = DAT_00414830;
  puVar2[1] = uVar1;
  puVar2[2] = uVar1;
  return;
}

/* Native process initializer at 0x00414838. */
void oot3d_startup_initializer_00414838(void)

{
  oot3d_startup_construct_003fd23c(DAT_00414860);
  *((u32 *)(uint32_t)DAT_00414870) = DAT_0041486C;
  return;
}

void oot3d_call_process_initializers(void) {
    oot3d_startup_initializer_004133dc();
    oot3d_startup_initializer_00412738();
    oot3d_startup_initializer_00414304();
    oot3d_startup_initializer_004146d0();
    oot3d_startup_initializer_004137f0();
    oot3d_startup_initializer_00413b78();
    oot3d_startup_initializer_00412d30();
    oot3d_startup_initializer_004123d4();
    oot3d_startup_initializer_004140d4();
    oot3d_startup_initializer_004134ac();
    oot3d_startup_initializer_004138c4();
    oot3d_startup_initializer_00413dfc();
    oot3d_startup_initializer_004134d4();
    oot3d_startup_initializer_00414718();
    oot3d_startup_initializer_004136e0();
    oot3d_startup_initializer_004131fc();
    oot3d_startup_initializer_004134fc();
    oot3d_startup_initializer_004140fc();
    oot3d_startup_initializer_00412874();
    oot3d_startup_initializer_00412e20();
    oot3d_startup_initializer_004128f4();
    oot3d_startup_initializer_0041294c();
    oot3d_startup_initializer_00413010();
    oot3d_startup_initializer_00413554();
    oot3d_startup_initializer_00413570();
    oot3d_startup_initializer_00412ebc();
    oot3d_startup_initializer_004138f4();
    oot3d_startup_initializer_0041302c();
    oot3d_startup_initializer_00414794();
    oot3d_startup_initializer_00413708();
    oot3d_startup_initializer_00413978();
    oot3d_startup_initializer_004139c4();
    oot3d_startup_initializer_00413e24();
    oot3d_startup_initializer_00413e70();
    oot3d_startup_initializer_00414388();
    oot3d_startup_initializer_004135bc();
    oot3d_startup_initializer_00413a10();
    oot3d_startup_initializer_00413ebc();
    oot3d_startup_initializer_00414144();
    oot3d_startup_initializer_0041417c();
    oot3d_startup_initializer_004137a4();
    oot3d_startup_initializer_00414228();
    oot3d_startup_initializer_004143a0();
    oot3d_startup_initializer_00414288();
    oot3d_startup_initializer_004143ec();
    oot3d_startup_initializer_00413a28();
    oot3d_startup_initializer_00413a74();
    oot3d_startup_initializer_004126b0();
    oot3d_startup_initializer_0041475c();
    oot3d_startup_initializer_00414810();
    oot3d_startup_initializer_00412f08();
    oot3d_startup_initializer_00412420();
    oot3d_startup_initializer_004135d4();
    oot3d_startup_initializer_00412994();
    oot3d_startup_initializer_004129e0();
    oot3d_startup_initializer_004135fc();
    oot3d_startup_initializer_00412a08();
    oot3d_startup_initializer_00413080();
    oot3d_startup_initializer_0041244c();
    oot3d_startup_initializer_00413624();
    oot3d_startup_initializer_004126f4();
    oot3d_startup_initializer_00412560();
    oot3d_startup_initializer_00413f08();
    oot3d_startup_initializer_00412a30();
    oot3d_startup_initializer_0041271c();
    oot3d_startup_initializer_00413238();
    oot3d_startup_initializer_004142d4();
    oot3d_startup_initializer_00413ac0();
    oot3d_startup_initializer_00413654();
    oot3d_startup_initializer_00412174();
    oot3d_startup_initializer_00413284();
    oot3d_startup_initializer_0041219c();
    oot3d_startup_initializer_004147e0();
    oot3d_startup_initializer_00412bc4();
    oot3d_startup_initializer_00413680();
    oot3d_startup_initializer_004121c4();
    oot3d_startup_initializer_00412210();
    oot3d_startup_initializer_00412248();
    oot3d_startup_initializer_00413144();
    oot3d_startup_initializer_00412098();
    oot3d_startup_initializer_00413f48();
    oot3d_startup_initializer_004122ac();
    oot3d_startup_initializer_00414488();
    oot3d_startup_initializer_00413814();
    oot3d_startup_initializer_004127f4();
    oot3d_startup_initializer_00412308();
    oot3d_startup_initializer_004123c0();
    oot3d_startup_initializer_00413860();
    oot3d_startup_initializer_004138ac();
    oot3d_startup_initializer_0041258c();
    oot3d_startup_initializer_00412f54();
    oot3d_startup_initializer_00412b10();
    oot3d_startup_initializer_004130cc();
    oot3d_startup_initializer_00412664();
    oot3d_startup_initializer_00414838();
    oot3d_startup_initializer_0041334c();
    oot3d_startup_initializer_00412cec();
    oot3d_startup_initializer_00413c20();
    oot3d_startup_initializer_00413454();
    oot3d_startup_initializer_0041317c();
    oot3d_startup_initializer_00413480();
    oot3d_startup_initializer_00412d00();
    oot3d_startup_initializer_004131d8();
    oot3d_startup_initializer_00414064();
    oot3d_startup_initializer_00412ddc();
    oot3d_startup_initializer_00413d50();
    oot3d_startup_initializer_0041231c();
    oot3d_startup_initializer_00412fcc();
    oot3d_startup_initializer_00413468();
    oot3d_startup_initializer_00412fa4();
    oot3d_startup_initializer_004136cc();
    oot3d_startup_initializer_004145e4();
    oot3d_startup_initializer_00414098();
    oot3d_startup_initializer_00414360();
    oot3d_startup_initializer_0041267c();
    oot3d_startup_initializer_00413494();
    oot3d_startup_initializer_00413440();
    oot3d_startup_initializer_00412f90();
    oot3d_startup_initializer_00414760();
    oot3d_startup_initializer_00412fb8();
    oot3d_startup_initializer_00413d38();
    oot3d_startup_initializer_004131b4();
    oot3d_startup_initializer_004140b0();
    oot3d_startup_initializer_00412fe0();
}
