#!/usr/bin/env python3
"""Build recovered OOT3D fog material-scalar source definitions.

The generated files describe the native code.bin fog resource used by
Gameplay_Draw/FUN_00464B2C and the material scalar binder. They are decompiled
source/data definitions, not runtime replacement values.
"""

from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path
from typing import Any


ROOT = Path("tools/oot3d/decomp_support")
DEFAULT_CODE_BIN = Path(r"E:\ppssppvr\oot3d_decomp\work\extract\exefs\code.bin")
DEFAULT_OUT_JSON = ROOT / "analysis" / "fog_material_scalar_source.json"
DEFAULT_OUT_MD = ROOT / "analysis" / "fog_material_scalar_source.md"
DEFAULT_OUT_HEADER = ROOT / "include" / "oot3d" / "fog_material_scalar.h"
DEFAULT_OUT_SOURCE = ROOT / "src" / "code" / "z_fog_material_scalar.c"

CODE_BASE = 0x00100000
TEMPLATE_ADDR = 0x004FA8B8
INV_255_ADDR = 0x00464D58
TEMPLATE_PTR_LITERAL_ADDR = 0x00464D5C
ALLOCATOR_SLOT_LITERAL_ADDR = 0x00464DA0
ALLOC_SIZE_LITERAL_ADDR = 0x00464DA4
DISABLE_DISTANCE_LITERAL_ADDR = 0x00464DA8
DEFAULT_ALPHA_ADDR = 0x0047FDF0
LUT_COUNTER_LITERAL_ADDR = 0x0047FDF4
LUT_COUNTER_ALIAS_LITERAL_ADDR = 0x0047FE40
ALLOCATOR_SLOT_ADDR = 0x0055A1E4
LUT_COUNTER_ADDR = 0x0054CC2C
RUNTIME_SIZE = 0x668
TEMPLATE_SIZE = 0x54
PLAY_FOG_SOURCE_OFFSET = 0x5FC8
PLAY_VIEW_SOURCE_OFFSET = 0x01DC
PLAY_FINAL_FOG_COLOR_OFFSET = 0x0A82
PLAY_FOG_FAR_OFFSET = 0x0A78
PLAY_FOG_NEAR_OFFSET = 0x0A7C
PLAY_MATERIAL_RUNTIME_LIST0_OFFSET = 0x4C30
PLAY_MATERIAL_RUNTIME_LIST1_OFFSET = 0x500C
GAMEPLAY_FOG_MATERIAL_UPDATE_CALLSITE = 0x002E2674
GAMEPLAY_MATERIAL_RUNTIME_LIST0_BIND_CALLSITE = 0x002E2C20
GAMEPLAY_MATERIAL_RUNTIME_LIST1_BIND_CALLSITE = 0x002E2C34
GAMEPLAY_FOG_ALPHA_IMMEDIATE = 0xFF
MATERIAL_PACKET_ENABLE_OFFSET = 0x0A
MATERIAL_PACKET_FOG_R_OFFSET = 0x6C
MATERIAL_PACKET_FOG_G_OFFSET = 0x70
MATERIAL_PACKET_FOG_B_OFFSET = 0x74
MATERIAL_PACKET_LUT_GENERATION_OFFSET = 0x7C
MATERIAL_PACKET_LUT_TABLE_OFFSET = 0x80
MATERIAL_RUNTIME_LIST_COUNT_OFFSET = 0x06
MATERIAL_RUNTIME_LIST_ENTRY_STRIDE = 0x3C
MATERIAL_RUNTIME_LIST_ENTRY_OBJECT_OFFSET = 0x0C
MATERIAL_RUNTIME_OBJECT_PACKET_OWNER_OFFSET = 0x14
MATERIAL_PACKET_OWNER_PACKET_OFFSET = 0x10
FOG_LUT_ENTRY_COUNT = 0x80
FOG_CURVE_SAMPLE_COUNT = FOG_LUT_ENTRY_COUNT + 1

PACK_BASE_ZERO_ADDR = 0x002CDB54
PACK_BASE_SCALE_ADDR = 0x002CDB58
PACK_BASE_MAX_ADDR = 0x002CDB5C
PACK_SLOPE_ZERO_ADDR = 0x002CDBE4
PACK_SLOPE_BIAS_ADDR = 0x002CDBE8
PACK_SLOPE_SCALE_ADDR = 0x002CDBEC
PACK_SLOPE_MAX_ADDR = 0x002CDBF0
PACK_SLOPE_SPLIT_ADDR = 0x002CDBF4
PACK_SLOPE_OFFSET_ADDR = 0x002CDBF8
BUILD_CURVE_STEP_ADDR = 0x002CDD70
BUILD_CURVE_FAR_VALUE_ADDR = 0x002CDD74
BUILD_CURVE_NEAR_VALUE_ADDR = 0x002CDD78
VIEW_COPY_DETERMINANT_ZERO_ADDR = 0x002D485C
VIEW_COPY_INVERSE_SCALE_ADDR = 0x002D4860


FUNCTIONS = {
    "Oot3d_FogCopyViewTermsToRuntime": 0x002D4554,
    "Oot3d_FogBuildCurveArrays": 0x002CDBFC,
    "Oot3d_FogPackBase": 0x002CDB0C,
    "Oot3d_FogPackSlope": 0x002CDB60,
    "Oot3d_FogSourceBindMaterialState": 0x00368704,
    "Oot3d_FogSourceMarkMaterialStateEnabled": 0x0036879C,
    "Oot3d_FogSourceGetRuntimeState": 0x003687A8,
    "Oot3d_MaterialScalarBindRuntimeList": 0x002D960C,
    "Oot3d_GameplayDraw": 0x002E25F0,
    "Oot3d_GameplayUpdateFogMaterialSource": 0x00464B2C,
    "Oot3d_FogCompareViewWords": 0x004706CC,
    "Oot3d_FogRuntimeApplyTemplateAndBuildLut": 0x0047FD44,
    "Oot3d_FogRuntimeInitFromTemplate": 0x0047FDF8,
    "Oot3d_FogRuntimeRelease": 0x0047FE2C,
    "Oot3d_FogRebuildPackedPicaTable": 0x004C062C,
    "Oot3d_MaterialStateCopyFogRgb": 0x004C05C0,
}


def fmt_u32(value: int) -> str:
    return f"0x{value & 0xFFFFFFFF:08X}"


def f32_from_u32(value: int) -> float:
    return struct.unpack("<f", struct.pack("<I", value & 0xFFFFFFFF))[0]


def c_float(value: float) -> str:
    text = f"{value:.9g}"
    if "e" not in text and "E" not in text and "." not in text:
        text += ".0"
    return f"{text}f"


def u32_at(data: bytes, address: int) -> int:
    offset = address - CODE_BASE
    if offset < 0 or offset + 4 > len(data):
        raise ValueError(f"address {fmt_u32(address)} is outside code.bin")
    return struct.unpack_from("<I", data, offset)[0]


def words_at(data: bytes, address: int, byte_size: int) -> list[int]:
    offset = address - CODE_BASE
    if offset < 0 or offset + byte_size > len(data):
        raise ValueError(f"range {fmt_u32(address)}+{byte_size:#x} is outside code.bin")
    return [struct.unpack_from("<I", data, offset + index)[0] for index in range(0, byte_size, 4)]


def template_fields(words: list[int]) -> dict[str, Any]:
    return {
        "raw_words": [fmt_u32(word) for word in words],
        "fog_color_rgba": [f32_from_u32(words[index]) for index in (9, 10, 11, 12)],
        "near_z_s32": words[13],
        "far_z_s32": words[14],
        "curve_scale_s32": words[15],
        "flags_word_40": fmt_u32(words[16]),
        "rebuild_disabled_u8_at_41": (words[16] >> 8) & 0xFF,
        "curve_mode_u8_at_42": (words[16] >> 16) & 0xFF,
        "tail_words_from_44": [fmt_u32(word) for word in words[17:]],
    }


def build_report(code_bin: Path) -> dict[str, Any]:
    data = code_bin.read_bytes()
    template_words = words_at(data, TEMPLATE_ADDR, TEMPLATE_SIZE)
    inv_255_word = u32_at(data, INV_255_ADDR)
    default_alpha_word = u32_at(data, DEFAULT_ALPHA_ADDR)
    pack_literal_addresses = {
        "pack_base_zero": PACK_BASE_ZERO_ADDR,
        "pack_base_scale": PACK_BASE_SCALE_ADDR,
        "pack_base_max": PACK_BASE_MAX_ADDR,
        "pack_slope_zero": PACK_SLOPE_ZERO_ADDR,
        "pack_slope_bias": PACK_SLOPE_BIAS_ADDR,
        "pack_slope_scale": PACK_SLOPE_SCALE_ADDR,
        "pack_slope_max": PACK_SLOPE_MAX_ADDR,
        "pack_slope_split": PACK_SLOPE_SPLIT_ADDR,
        "pack_slope_offset": PACK_SLOPE_OFFSET_ADDR,
        "build_curve_step": BUILD_CURVE_STEP_ADDR,
        "build_curve_far_value": BUILD_CURVE_FAR_VALUE_ADDR,
        "build_curve_near_value": BUILD_CURVE_NEAR_VALUE_ADDR,
        "view_copy_determinant_zero": VIEW_COPY_DETERMINANT_ZERO_ADDR,
        "view_copy_inverse_scale": VIEW_COPY_INVERSE_SCALE_ADDR,
        "update_disable_distance": DISABLE_DISTANCE_LITERAL_ADDR,
    }
    pack_literals = {
        name: {
            "address": fmt_u32(address),
            "word": fmt_u32(u32_at(data, address)),
            "float": f32_from_u32(u32_at(data, address)),
        }
        for name, address in pack_literal_addresses.items()
    }
    report = {
        "format": "oot3d_fog_material_scalar_source_v1",
        "policy": "native_code_bin_decompilation_not_runtime_replacement_data",
        "code_bin": str(code_bin),
        "code_base": fmt_u32(CODE_BASE),
        "functions": {name: fmt_u32(address) for name, address in FUNCTIONS.items()},
        "static_addresses": {
            "template": fmt_u32(TEMPLATE_ADDR),
            "inv_255_literal": fmt_u32(INV_255_ADDR),
            "template_ptr_literal": fmt_u32(TEMPLATE_PTR_LITERAL_ADDR),
            "allocator_slot_literal": fmt_u32(ALLOCATOR_SLOT_LITERAL_ADDR),
            "alloc_size_literal": fmt_u32(ALLOC_SIZE_LITERAL_ADDR),
            "disable_distance_literal": fmt_u32(DISABLE_DISTANCE_LITERAL_ADDR),
            "default_alpha_literal": fmt_u32(DEFAULT_ALPHA_ADDR),
            "lut_counter_literal": fmt_u32(LUT_COUNTER_LITERAL_ADDR),
            "lut_counter_alias_literal": fmt_u32(LUT_COUNTER_ALIAS_LITERAL_ADDR),
            "allocator_slot": fmt_u32(ALLOCATOR_SLOT_ADDR),
            "lut_counter": fmt_u32(LUT_COUNTER_ADDR),
        },
        "literal_values": {
            "inv_255_word": fmt_u32(inv_255_word),
            "inv_255_float": f32_from_u32(inv_255_word),
            "template_ptr_literal_value": fmt_u32(u32_at(data, TEMPLATE_PTR_LITERAL_ADDR)),
            "allocator_slot_literal_value": fmt_u32(u32_at(data, ALLOCATOR_SLOT_LITERAL_ADDR)),
            "allocation_size_literal_value": u32_at(data, ALLOC_SIZE_LITERAL_ADDR),
            "disable_distance_literal_value": u32_at(data, DISABLE_DISTANCE_LITERAL_ADDR),
            "default_alpha_word": fmt_u32(default_alpha_word),
            "default_alpha_float": f32_from_u32(default_alpha_word),
            "lut_counter_literal_value": fmt_u32(u32_at(data, LUT_COUNTER_LITERAL_ADDR)),
            "lut_counter_alias_literal_value": fmt_u32(u32_at(data, LUT_COUNTER_ALIAS_LITERAL_ADDR)),
        },
        "curve_pack_literals": pack_literals,
        "playstate_offsets": {
            "fog_source_offset": fmt_u32(PLAY_FOG_SOURCE_OFFSET),
            "view_source_offset": fmt_u32(PLAY_VIEW_SOURCE_OFFSET),
            "final_fog_rgb_offset": fmt_u32(PLAY_FINAL_FOG_COLOR_OFFSET),
            "fog_far_float_offset": fmt_u32(PLAY_FOG_FAR_OFFSET),
            "fog_near_u16_offset": fmt_u32(PLAY_FOG_NEAR_OFFSET),
            "material_runtime_list0_offset": fmt_u32(PLAY_MATERIAL_RUNTIME_LIST0_OFFSET),
            "material_runtime_list1_offset": fmt_u32(PLAY_MATERIAL_RUNTIME_LIST1_OFFSET),
        },
        "gameplay_draw_material_scalar_order": {
            "function": fmt_u32(FUNCTIONS["Oot3d_GameplayDraw"]),
            "fog_material_update_callsite": fmt_u32(GAMEPLAY_FOG_MATERIAL_UPDATE_CALLSITE),
            "material_runtime_list0_bind_callsite": fmt_u32(GAMEPLAY_MATERIAL_RUNTIME_LIST0_BIND_CALLSITE),
            "material_runtime_list1_bind_callsite": fmt_u32(GAMEPLAY_MATERIAL_RUNTIME_LIST1_BIND_CALLSITE),
            "update_function": fmt_u32(FUNCTIONS["Oot3d_GameplayUpdateFogMaterialSource"]),
            "runtime_list_bind_function": fmt_u32(FUNCTIONS["Oot3d_MaterialScalarBindRuntimeList"]),
            "source_value_from_play_offset": fmt_u32(PLAY_FOG_SOURCE_OFFSET),
            "view_value_from_play_offset": fmt_u32(PLAY_VIEW_SOURCE_OFFSET),
            "fog_rgb_value_from_play_offset": fmt_u32(PLAY_FINAL_FOG_COLOR_OFFSET),
            "fog_far_float_from_play_offset": fmt_u32(PLAY_FOG_FAR_OFFSET),
            "fog_near_u16_from_play_offset": fmt_u32(PLAY_FOG_NEAR_OFFSET),
            "fog_alpha_immediate": GAMEPLAY_FOG_ALPHA_IMMEDIATE,
            "runtime_list0_from_play_offset": fmt_u32(PLAY_MATERIAL_RUNTIME_LIST0_OFFSET),
            "runtime_list1_from_play_offset": fmt_u32(PLAY_MATERIAL_RUNTIME_LIST1_OFFSET),
            "semantic": (
                "Gameplay_Draw calls FUN_00464B2C with the active play+0x5FC8 source, "
                "play+0x01DC view, play+0x0A82..0x0A84 RGB, alpha 0xFF, and fog "
                "near/far inputs, then binds play+0x4C30 and play+0x500C through FUN_002D960C."
            ),
        },
        "material_packet_offsets": {
            "enable": fmt_u32(MATERIAL_PACKET_ENABLE_OFFSET),
            "fog_r": fmt_u32(MATERIAL_PACKET_FOG_R_OFFSET),
            "fog_g": fmt_u32(MATERIAL_PACKET_FOG_G_OFFSET),
            "fog_b": fmt_u32(MATERIAL_PACKET_FOG_B_OFFSET),
            "lut_generation": fmt_u32(MATERIAL_PACKET_LUT_GENERATION_OFFSET),
            "lut_table": fmt_u32(MATERIAL_PACKET_LUT_TABLE_OFFSET),
        },
        "runtime_layout": {
            "allocation_size": RUNTIME_SIZE,
            "template_ptr": "+0x000",
            "fog_rgb": "+0x004..+0x00C",
            "alpha": "+0x010",
            "near_z": "+0x014",
            "far_z": "+0x018",
            "lut_generation": "+0x024",
            "view_derived_terms_from_FUN_002D4554": "+0x028..+0x064",
            "lut_builder_terms": "+0x050,+0x054,+0x060,+0x064",
            "fog_lut_base_values": "+0x068..+0x267",
            "fog_lut_deltas": "+0x268..+0x467",
            "packed_pica_lut_table": "+0x468..+0x667",
        },
        "source_layout": {
            "runtime_ptr": "+0x00",
            "view_words": "+0x04..+0x43",
            "enabled": "+0x44",
            "dirty": "+0x45",
            "size_known_from_accesses": "0x48",
        },
        "runtime_material_list_layout": {
            "bind_function": fmt_u32(FUNCTIONS["Oot3d_MaterialScalarBindRuntimeList"]),
            "runtime_object_packet_resolver_function": fmt_u32(FUNCTIONS["Oot3d_FogSourceGetRuntimeState"]),
            "playstate_material_runtime_list0_offset": fmt_u32(PLAY_MATERIAL_RUNTIME_LIST0_OFFSET),
            "playstate_material_runtime_list1_offset": fmt_u32(PLAY_MATERIAL_RUNTIME_LIST1_OFFSET),
            "list_count_u8_offset": fmt_u32(MATERIAL_RUNTIME_LIST_COUNT_OFFSET),
            "entry_stride": MATERIAL_RUNTIME_LIST_ENTRY_STRIDE,
            "entry_runtime_object_pointer_offset": fmt_u32(MATERIAL_RUNTIME_LIST_ENTRY_OBJECT_OFFSET),
            "runtime_object_packet_owner_pointer_offset": fmt_u32(MATERIAL_RUNTIME_OBJECT_PACKET_OWNER_OFFSET),
            "packet_owner_material_packet_pointer_offset": fmt_u32(MATERIAL_PACKET_OWNER_PACKET_OFFSET),
            "semantic": (
                "FUN_002D960C walks runtime material lists, resolves each non-null runtime object "
                "through FUN_003687A8, and applies the play+0x5FC8 fog source through FUN_00368704."
            ),
        },
        "template": template_fields(template_words),
    }
    return report


def write_header(path: Path) -> None:
    lines = [
        "#ifndef OOT3D_FOG_MATERIAL_SCALAR_H",
        "#define OOT3D_FOG_MATERIAL_SCALAR_H",
        "",
        "#include \"oot3d/types.h\"",
        "",
        "#define OOT3D_FOG_MATERIAL_TEMPLATE_ADDR 0x004FA8B8u",
        "#define OOT3D_FOG_MATERIAL_INV_255_ADDR 0x00464D58u",
        "#define OOT3D_FOG_MATERIAL_ALLOCATOR_SLOT_ADDR 0x0055A1E4u",
        "#define OOT3D_FOG_MATERIAL_LUT_COUNTER_ADDR 0x0054CC2Cu",
        "#define OOT3D_FOG_MATERIAL_RUNTIME_SIZE 0x668u",
        "#define OOT3D_FOG_MATERIAL_TEMPLATE_WORD_COUNT 21u",
        "#define OOT3D_FOG_LUT_ENTRY_COUNT 128u",
        "#define OOT3D_FOG_CURVE_SAMPLE_COUNT 129u",
        "#define OOT3D_FOG_VIEW_WORD_COUNT 16u",
        "#define OOT3D_FOG_VIEW_DERIVED_TERM_COUNT 16u",
        "#define OOT3D_PLAY_FOG_MATERIAL_SOURCE_OFFSET 0x5FC8u",
        "#define OOT3D_PLAY_VIEW_SOURCE_OFFSET 0x01DCu",
        "#define OOT3D_PLAY_FINAL_FOG_RGB_OFFSET 0x0A82u",
        "#define OOT3D_PLAY_FOG_FAR_OFFSET 0x0A78u",
        "#define OOT3D_PLAY_FOG_NEAR_OFFSET 0x0A7Cu",
        "#define OOT3D_PLAY_MATERIAL_RUNTIME_LIST0_OFFSET 0x4C30u",
        "#define OOT3D_PLAY_MATERIAL_RUNTIME_LIST1_OFFSET 0x500Cu",
        "#define OOT3D_GAMEPLAY_FOG_MATERIAL_UPDATE_CALLSITE 0x002E2674u",
        "#define OOT3D_GAMEPLAY_MATERIAL_RUNTIME_LIST0_BIND_CALLSITE 0x002E2C20u",
        "#define OOT3D_GAMEPLAY_MATERIAL_RUNTIME_LIST1_BIND_CALLSITE 0x002E2C34u",
        "#define OOT3D_GAMEPLAY_FOG_ALPHA_IMMEDIATE 0xFFu",
        "#define OOT3D_MATERIAL_PACKET_ENABLE_OFFSET 0x0Au",
        "#define OOT3D_MATERIAL_PACKET_FOG_R_OFFSET 0x6Cu",
        "#define OOT3D_MATERIAL_PACKET_FOG_G_OFFSET 0x70u",
        "#define OOT3D_MATERIAL_PACKET_FOG_B_OFFSET 0x74u",
        "#define OOT3D_MATERIAL_PACKET_LUT_GENERATION_OFFSET 0x7Cu",
        "#define OOT3D_MATERIAL_PACKET_LUT_TABLE_OFFSET 0x80u",
        "#define OOT3D_MATERIAL_RUNTIME_LIST_COUNT_OFFSET 0x06u",
        "#define OOT3D_MATERIAL_RUNTIME_LIST_ENTRY_STRIDE 0x3Cu",
        "#define OOT3D_MATERIAL_RUNTIME_LIST_ENTRY_OBJECT_OFFSET 0x0Cu",
        "#define OOT3D_MATERIAL_RUNTIME_OBJECT_PACKET_OWNER_OFFSET 0x14u",
        "#define OOT3D_MATERIAL_PACKET_OWNER_PACKET_OFFSET 0x10u",
        "",
        "typedef float (*Oot3dFogCurveTransform)(float value, void* user);",
        "typedef u8* (*Oot3dMaterialScalarAddressResolver)(u32 runtimeAddress, size_t minimumSize, void* user);",
        "",
        "enum {",
        "    OOT3D_FOG_UPDATE_ALLOCATED = 1 << 0,",
        "    OOT3D_FOG_UPDATE_COLOR_CHANGED = 1 << 1,",
        "    OOT3D_FOG_UPDATE_VIEW_CHANGED = 1 << 2,",
        "    OOT3D_FOG_UPDATE_NEAR_FAR_CHANGED = 1 << 3,",
        "    OOT3D_FOG_UPDATE_ENABLED_CHANGED = 1 << 4,",
        "    OOT3D_FOG_UPDATE_REBUILT = 1 << 5,",
        "};",
        "",
        "typedef struct {",
        "    u32 rawWords[OOT3D_FOG_MATERIAL_TEMPLATE_WORD_COUNT];",
        "} Oot3dFogMaterialTemplateWords;",
        "",
        "typedef struct {",
        "    float fogColorR;",
        "    float fogColorG;",
        "    float fogColorB;",
        "    float fogColorA;",
        "    s32 nearZ;",
        "    s32 farZ;",
        "    s32 curveScale;",
        "    u8 rebuildDisabled;",
        "    u8 curveMode;",
        "} Oot3dFogMaterialTemplateDecoded;",
        "",
        "typedef struct {",
        "    u32 updateFunction;",
        "    u32 bindFunction;",
        "    u32 runtimeListBindFunction;",
        "    u32 runtimeObjectMaterialPacketResolverFunction;",
        "    u32 runtimeInitFunction;",
        "    u32 runtimeApplyFunction;",
        "    u32 packedTableRebuildFunction;",
        "    u32 viewCopyFunction;",
        "    u32 viewCompareFunction;",
        "    u32 fogCurveBuilderFunction;",
        "    u32 fogPackBaseFunction;",
        "    u32 fogPackSlopeFunction;",
        "    u32 materialStateCopyFogRgbFunction;",
        "    u32 templateAddress;",
        "    u32 allocationSize;",
        "    u32 allocatorSlotAddress;",
        "    u32 lutGenerationCounterAddress;",
        "    u32 playFogSourceOffset;",
        "    u32 playMaterialRuntimeList0Offset;",
        "    u32 playMaterialRuntimeList1Offset;",
        "    u32 runtimeMaterialListCountOffset;",
        "    u32 runtimeMaterialListEntryStride;",
        "    u32 runtimeMaterialListEntryObjectOffset;",
        "    u32 runtimeObjectPacketOwnerOffset;",
        "    u32 packetOwnerMaterialPacketOffset;",
        "    u32 inv255Word;",
        "    float inv255;",
        "} Oot3dFogMaterialScalarMetadata;",
        "",
        "typedef struct {",
        "    u32 gameplayDrawFunction;",
        "    u32 fogMaterialUpdateCallsite;",
        "    u32 materialRuntimeList0BindCallsite;",
        "    u32 materialRuntimeList1BindCallsite;",
        "    u32 playFogSourceOffset;",
        "    u32 playViewSourceOffset;",
        "    u32 playFinalFogRgbOffset;",
        "    u32 playFogFarFloatOffset;",
        "    u32 playFogNearU16Offset;",
        "    u32 playMaterialRuntimeList0Offset;",
        "    u32 playMaterialRuntimeList1Offset;",
        "    u8 fogAlphaImmediate;",
        "    u8 pad[3];",
        "} Oot3dGameplayFogMaterialOrder;",
        "",
        "typedef struct {",
        "    float packBaseZero;",
        "    float packBaseScale;",
        "    u32 packBaseMax;",
        "    float packSlopeZero;",
        "    float packSlopeBias;",
        "    float packSlopeScale;",
        "    float packSlopeMax;",
        "    float packSlopeSplit;",
        "    float packSlopeOffset;",
        "    float buildCurveStep;",
        "    float buildCurveFarValue;",
        "    float buildCurveNearValue;",
        "    float viewCopyDeterminantZero;",
        "    float viewCopyInverseScale;",
        "    float updateDisableDistance;",
        "} Oot3dFogMaterialCurveConstants;",
        "",
        "typedef struct {",
        "    u32 runtimeAddr;",
        "    u32 viewWords[OOT3D_FOG_VIEW_WORD_COUNT];",
        "    u8 enabled;",
        "    u8 dirty;",
        "    u8 pad46[2];",
        "} Oot3dFogMaterialSourceLayout;",
        "",
        "typedef struct {",
        "    u32 templateAddr;",
        "    float fogColorR;",
        "    float fogColorG;",
        "    float fogColorB;",
        "    float fogColorA;",
        "    float nearZ;",
        "    float farZ;",
        "    u32 unknown1C;",
        "    u32 unknown20;",
        "    u32 lutGeneration;",
        "    float viewDerivedTerms[OOT3D_FOG_VIEW_DERIVED_TERM_COUNT];",
        "    float fogLutBase[OOT3D_FOG_LUT_ENTRY_COUNT];",
        "    float fogLutDelta[OOT3D_FOG_LUT_ENTRY_COUNT];",
        "    u32 packedPicaFogLut[OOT3D_FOG_LUT_ENTRY_COUNT];",
        "} Oot3dFogMaterialRuntimeLayout;",
        "",
        "typedef struct {",
        "    Oot3dFogMaterialSourceLayout* source;",
        "    Oot3dFogMaterialRuntimeLayout* runtime;",
        "    u32 runtimeAddress;",
        "    const float* view;",
        "    float nearZ;",
        "    float farZ;",
        "    u8 fogR;",
        "    u8 fogG;",
        "    u8 fogB;",
        "    u8 fogA;",
        "    u32* lutGenerationCounter;",
        "    const u8* runtimeList0;",
        "    const u8* runtimeList1;",
        "    Oot3dMaterialScalarAddressResolver resolver;",
        "    void* resolverUser;",
        "    const Oot3dFogMaterialTemplateDecoded* templateData;",
        "    u32 packedPicaFogLutAddress;",
        "    Oot3dFogCurveTransform transform;",
        "    void* transformUser;",
        "} Oot3dGameplayFogMaterialFrameInput;",
        "",
        "typedef struct {",
        "    int sourceUpdateFlags;",
        "    int runtimeList0BoundCount;",
        "    int runtimeList1BoundCount;",
        "} Oot3dGameplayFogMaterialFrameResult;",
        "",
        "extern const Oot3dFogMaterialTemplateWords gOot3dFogMaterialTemplateWords_004FA8B8;",
        "extern const Oot3dFogMaterialTemplateDecoded gOot3dFogMaterialTemplateDecoded_004FA8B8;",
        "extern const Oot3dFogMaterialScalarMetadata gOot3dFogMaterialScalarMetadata;",
        "extern const Oot3dGameplayFogMaterialOrder gOot3dGameplayFogMaterialOrder;",
        "extern const Oot3dFogMaterialCurveConstants gOot3dFogMaterialCurveConstants;",
        "",
        "void Oot3d_FogCopyViewWords(u32 dst[OOT3D_FOG_VIEW_WORD_COUNT], const float src[OOT3D_FOG_VIEW_WORD_COUNT]);",
        "int Oot3d_FogViewWordsChanged(const u32 lhs[OOT3D_FOG_VIEW_WORD_COUNT],",
        "                               const u32 rhs[OOT3D_FOG_VIEW_WORD_COUNT]);",
        "void Oot3d_FogCopyViewWordsToRuntime(Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                      const u32 viewWords[OOT3D_FOG_VIEW_WORD_COUNT]);",
        "void Oot3d_FogCopyViewTermsToRuntime(Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                      const float view[OOT3D_FOG_VIEW_WORD_COUNT]);",
        "u32 Oot3d_FogPackBase(float value);",
        "u32 Oot3d_FogPackSlope(float value);",
        "int Oot3d_FogBuildCurveArrays(Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                  const Oot3dFogMaterialTemplateDecoded* templateData,",
        "                                  Oot3dFogCurveTransform transform, void* transformUser);",
        "int Oot3d_FogRebuildPackedPicaTable(Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                     const Oot3dFogMaterialTemplateDecoded* templateData,",
        "                                     Oot3dFogCurveTransform transform, void* transformUser);",
        "void Oot3d_FogRuntimeInitFromTemplate(Oot3dFogMaterialRuntimeLayout* runtime, u32 templateAddress);",
        "int Oot3d_FogRuntimeApplyTemplateAndBuildLut(Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                             const Oot3dFogMaterialTemplateDecoded* templateData,",
        "                                             u32* lutGenerationCounter,",
        "                                             Oot3dFogCurveTransform transform, void* transformUser);",
        "void Oot3d_MaterialStateCopyFogRgb(u8* materialPacket, const Oot3dFogMaterialRuntimeLayout* runtime);",
        "void Oot3d_FogSourceMarkMaterialStateEnabled(u8* materialPacket);",
        "void Oot3d_FogBindRuntimeToMaterialPacket(u8* materialPacket, const Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                             u32 packedPicaFogLutAddress);",
        "u32 Oot3d_MaterialScalarReadLeU32(const u8* bytes);",
        "u8 Oot3d_MaterialScalarRuntimeListCount(const u8* runtimeList);",
        "u32 Oot3d_MaterialScalarRuntimeListObjectAddress(const u8* runtimeList, u32 index);",
        "u32 Oot3d_MaterialScalarRuntimeObjectPacketAddress(const u8* runtimeObject,",
        "                                                   Oot3dMaterialScalarAddressResolver resolver,",
        "                                                   void* resolverUser);",
        "u8* Oot3d_MaterialScalarResolvePacketFromRuntimeObject(u32 runtimeObjectAddress,",
        "                                                       Oot3dMaterialScalarAddressResolver resolver,",
        "                                                       void* resolverUser);",
        "int Oot3d_MaterialScalarBindRuntimeList(Oot3dFogMaterialSourceLayout* source,",
        "                                         Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                         const u8* runtimeList,",
        "                                         Oot3dMaterialScalarAddressResolver resolver,",
        "                                         void* resolverUser,",
        "                                         const Oot3dFogMaterialTemplateDecoded* templateData,",
        "                                         u32 packedPicaFogLutAddress,",
        "                                         Oot3dFogCurveTransform transform, void* transformUser);",
        "int Oot3d_GameplayUpdateFogMaterialSource(Oot3dFogMaterialSourceLayout* source,",
        "                                          Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                          u32 runtimeAddress,",
        "                                          const float view[OOT3D_FOG_VIEW_WORD_COUNT],",
        "                                          float nearZ, float farZ,",
        "                                          u8 fogR, u8 fogG, u8 fogB, u8 fogA,",
        "                                          u32* lutGenerationCounter,",
        "                                          Oot3dFogCurveTransform transform, void* transformUser);",
        "int Oot3d_GameplayApplyFogMaterialFrameOrder(const Oot3dGameplayFogMaterialFrameInput* input,",
        "                                            Oot3dGameplayFogMaterialFrameResult* result);",
        "int Oot3d_FogSourceBindMaterialState(Oot3dFogMaterialSourceLayout* source,",
        "                                      Oot3dFogMaterialRuntimeLayout* runtime,",
        "                                      const Oot3dFogMaterialTemplateDecoded* templateData,",
        "                                      u8* materialPacket, u32 packedPicaFogLutAddress,",
        "                                      Oot3dFogCurveTransform transform, void* transformUser);",
        "",
        "#endif",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_source(path: Path, report: dict[str, Any]) -> None:
    words = [int(word, 16) for word in report["template"]["raw_words"]]
    fog = report["template"]["fog_color_rgba"]
    curve = report["curve_pack_literals"]
    lines = [
        "/* Generated by build_fog_material_scalar_source.py. */",
        "",
        "#include \"oot3d/fog_material_scalar.h\"",
        "",
        "const Oot3dFogMaterialTemplateWords gOot3dFogMaterialTemplateWords_004FA8B8 = {",
        "    {",
    ]
    for index in range(0, len(words), 4):
        chunk = words[index : index + 4]
        lines.append("        " + ", ".join(f"{fmt_u32(word)}u" for word in chunk) + ",")
    lines.extend(
        [
            "    },",
            "};",
            "",
            "const Oot3dFogMaterialTemplateDecoded gOot3dFogMaterialTemplateDecoded_004FA8B8 = {",
            f"    {c_float(fog[0])},",
            f"    {c_float(fog[1])},",
            f"    {c_float(fog[2])},",
            f"    {c_float(fog[3])},",
            f"    {int(report['template']['near_z_s32'])},",
            f"    {int(report['template']['far_z_s32'])},",
            f"    {int(report['template']['curve_scale_s32'])},",
            f"    {int(report['template']['rebuild_disabled_u8_at_41'])}u,",
            f"    {int(report['template']['curve_mode_u8_at_42'])}u,",
            "};",
            "",
            "const Oot3dFogMaterialCurveConstants gOot3dFogMaterialCurveConstants = {",
            f"    {c_float(float(curve['pack_base_zero']['float']))},",
            f"    {c_float(float(curve['pack_base_scale']['float']))},",
            f"    {int(curve['pack_base_max']['word'], 16)}u,",
            f"    {c_float(float(curve['pack_slope_zero']['float']))},",
            f"    {c_float(float(curve['pack_slope_bias']['float']))},",
            f"    {c_float(float(curve['pack_slope_scale']['float']))},",
            f"    {c_float(float(curve['pack_slope_max']['float']))},",
            f"    {c_float(float(curve['pack_slope_split']['float']))},",
            f"    {c_float(float(curve['pack_slope_offset']['float']))},",
            f"    {c_float(float(curve['build_curve_step']['float']))},",
            f"    {c_float(float(curve['build_curve_far_value']['float']))},",
            f"    {c_float(float(curve['build_curve_near_value']['float']))},",
            f"    {c_float(float(curve['view_copy_determinant_zero']['float']))},",
            f"    {c_float(float(curve['view_copy_inverse_scale']['float']))},",
            f"    {c_float(float(curve['update_disable_distance']['float']))},",
            "};",
            "",
            "const Oot3dFogMaterialScalarMetadata gOot3dFogMaterialScalarMetadata = {",
            f"    {fmt_u32(FUNCTIONS['Oot3d_GameplayUpdateFogMaterialSource'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogSourceBindMaterialState'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_MaterialScalarBindRuntimeList'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogSourceGetRuntimeState'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogRuntimeInitFromTemplate'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogRuntimeApplyTemplateAndBuildLut'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogRebuildPackedPicaTable'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogCopyViewTermsToRuntime'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogCompareViewWords'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogBuildCurveArrays'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogPackBase'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_FogPackSlope'])}u,",
            f"    {fmt_u32(FUNCTIONS['Oot3d_MaterialStateCopyFogRgb'])}u,",
            f"    {fmt_u32(TEMPLATE_ADDR)}u,",
            f"    {RUNTIME_SIZE}u,",
            f"    {fmt_u32(ALLOCATOR_SLOT_ADDR)}u,",
            f"    {fmt_u32(LUT_COUNTER_ADDR)}u,",
            f"    {fmt_u32(PLAY_FOG_SOURCE_OFFSET)}u,",
            f"    {fmt_u32(PLAY_MATERIAL_RUNTIME_LIST0_OFFSET)}u,",
            f"    {fmt_u32(PLAY_MATERIAL_RUNTIME_LIST1_OFFSET)}u,",
            f"    {fmt_u32(MATERIAL_RUNTIME_LIST_COUNT_OFFSET)}u,",
            f"    {fmt_u32(MATERIAL_RUNTIME_LIST_ENTRY_STRIDE)}u,",
            f"    {fmt_u32(MATERIAL_RUNTIME_LIST_ENTRY_OBJECT_OFFSET)}u,",
            f"    {fmt_u32(MATERIAL_RUNTIME_OBJECT_PACKET_OWNER_OFFSET)}u,",
            f"    {fmt_u32(MATERIAL_PACKET_OWNER_PACKET_OFFSET)}u,",
            f"    {report['literal_values']['inv_255_word']}u,",
            f"    {c_float(float(report['literal_values']['inv_255_float']))},",
            "};",
            "",
            "const Oot3dGameplayFogMaterialOrder gOot3dGameplayFogMaterialOrder = {",
            f"    {fmt_u32(FUNCTIONS['Oot3d_GameplayDraw'])}u,",
            f"    {fmt_u32(GAMEPLAY_FOG_MATERIAL_UPDATE_CALLSITE)}u,",
            f"    {fmt_u32(GAMEPLAY_MATERIAL_RUNTIME_LIST0_BIND_CALLSITE)}u,",
            f"    {fmt_u32(GAMEPLAY_MATERIAL_RUNTIME_LIST1_BIND_CALLSITE)}u,",
            f"    {fmt_u32(PLAY_FOG_SOURCE_OFFSET)}u,",
            f"    {fmt_u32(PLAY_VIEW_SOURCE_OFFSET)}u,",
            f"    {fmt_u32(PLAY_FINAL_FOG_COLOR_OFFSET)}u,",
            f"    {fmt_u32(PLAY_FOG_FAR_OFFSET)}u,",
            f"    {fmt_u32(PLAY_FOG_NEAR_OFFSET)}u,",
            f"    {fmt_u32(PLAY_MATERIAL_RUNTIME_LIST0_OFFSET)}u,",
            f"    {fmt_u32(PLAY_MATERIAL_RUNTIME_LIST1_OFFSET)}u,",
            f"    {GAMEPLAY_FOG_ALPHA_IMMEDIATE}u,",
            "    { 0u, 0u, 0u },",
            "};",
            "",
            "static u32 Oot3d_FogFloatBits(float value) {",
            "    union {",
            "        float f;",
            "        u32 u;",
            "    } bits;",
            "    bits.f = value;",
            "    return bits.u;",
            "}",
            "",
            "static int Oot3d_FogIsFinite(float value) {",
            "    return (Oot3d_FogFloatBits(value) & 0x7F800000u) != 0x7F800000u;",
            "}",
            "",
            "static float Oot3d_FogFloatFromBits(u32 value) {",
            "    union {",
            "        u32 u;",
            "        float f;",
            "    } bits;",
            "    bits.u = value;",
            "    return bits.f;",
            "}",
            "",
            "void Oot3d_FogCopyViewWords(u32 dst[OOT3D_FOG_VIEW_WORD_COUNT], const float src[OOT3D_FOG_VIEW_WORD_COUNT]) {",
            "    u32 index;",
            "",
            "    if (dst == 0 || src == 0) {",
            "        return;",
            "    }",
            "    for (index = 0u; index < OOT3D_FOG_VIEW_WORD_COUNT; index++) {",
            "        dst[index] = Oot3d_FogFloatBits(src[index]);",
            "    }",
            "}",
            "",
            "int Oot3d_FogViewWordsChanged(const u32 lhs[OOT3D_FOG_VIEW_WORD_COUNT],",
            "                               const u32 rhs[OOT3D_FOG_VIEW_WORD_COUNT]) {",
            "    u32 index;",
            "",
            "    if (lhs == 0 || rhs == 0) {",
            "        return 1;",
            "    }",
            "    for (index = 0u; index < OOT3D_FOG_VIEW_WORD_COUNT; index++) {",
            "        if (lhs[index] != rhs[index]) {",
            "            return 1;",
            "        }",
            "    }",
            "    return 0;",
            "}",
            "",
            "void Oot3d_FogCopyViewWordsToRuntime(Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                      const u32 viewWords[OOT3D_FOG_VIEW_WORD_COUNT]) {",
            "    float view[OOT3D_FOG_VIEW_WORD_COUNT];",
            "    u32 index;",
            "",
            "    if (runtime == 0 || viewWords == 0) {",
            "        return;",
            "    }",
            "    for (index = 0u; index < OOT3D_FOG_VIEW_WORD_COUNT; index++) {",
            "        view[index] = Oot3d_FogFloatFromBits(viewWords[index]);",
            "    }",
            "    Oot3d_FogCopyViewTermsToRuntime(runtime, view);",
            "}",
            "",
            "void Oot3d_FogCopyViewTermsToRuntime(Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                      const float view[OOT3D_FOG_VIEW_WORD_COUNT]) {",
            "    float f1;",
            "    float f2;",
            "    float f3;",
            "    float f4;",
            "    float f5;",
            "    float f6;",
            "    float f7;",
            "    float f8;",
            "    float f9;",
            "    float f10;",
            "    float f11;",
            "    float f12;",
            "    float f13;",
            "    float f14;",
            "    float f15;",
            "    float f16;",
            "    float f17;",
            "    float f18;",
            "    float f19;",
            "    float f20;",
            "    float f21;",
            "    float f22;",
            "    float f23;",
            "    float f24;",
            "    float f25;",
            "    float f26;",
            "    float f27;",
            "    float f28;",
            "    float f29;",
            "    float f30;",
            "",
            "    if (runtime == 0 || view == 0) {",
            "        return;",
            "    }",
            "",
            "    f8 = view[5];",
            "    f18 = view[10];",
            "    f28 = view[11];",
            "    f5 = view[4];",
            "    f6 = view[6];",
            "    f20 = view[15];",
            "    f9 = view[7];",
            "    f27 = view[8];",
            "    f26 = view[9];",
            "    f23 = view[13];",
            "    f29 = view[14];",
            "    f30 = f9 * f18;",
            "    f2 = view[0];",
            "    f25 = view[12];",
            "    f3 = view[1];",
            "    f16 = f8 * f28;",
            "    f21 = f9 * f27;",
            "    f22 = f5 * f18;",
            "    f7 = view[2];",
            "    f24 = f8 * f27;",
            "    f17 = f6 * f26;",
            "    f4 = view[3];",
            "    f1 = (((((f8 * f18 * f20 + f6 * f28 * f23 + f9 * f26 * f29) * f2 +",
            "              f3 * (f5 * f28 * f29 + f6 * f27 * f20 + f30 * f25) +",
            "              f7 * (f5 * f26 * f20 + f16 * f25 + f21 * f23) +",
            "              f4 * (f22 * f23 + f24 * f29 + f17 * f25)) -",
            "             f2 * (f16 * f29 + f17 * f20 + f30 * f23)) -",
            "            f3 * (f22 * f20 + f6 * f28 * f25 + f21 * f29)) -",
            "           f7 * (f5 * f28 * f23 + f24 * f20 + f9 * f26 * f25)) -",
            "          f4 * (f5 * f26 * f29 + f8 * f18 * f25 + f6 * f27 * f23);",
            "",
            "    if (f1 == gOot3dFogMaterialCurveConstants.viewCopyDeterminantZero) {",
            "        return;",
            "    }",
            "",
            "    f1 = gOot3dFogMaterialCurveConstants.viewCopyInverseScale / f1;",
            "    f17 = f17 - f8 * f18;",
            "    f15 = f9 * f23 - f8 * f20;",
            "    f12 = f26 * f20 - f28 * f23;",
            "    f11 = f18 * f25 - f27 * f29;",
            "    f10 = f18 * f20 - f28 * f29;",
            "    f13 = f26 * f25 - f27 * f23;",
            "    f22 = f22 - f6 * f27;",
            "    f18 = f18 * f23 - f26 * f29;",
            "    f14 = f6 * f20 - f9 * f29;",
            "    f27 = f27 * f20 - f28 * f25;",
            "    f19 = f5 * f20 - f9 * f25;",
            "    f16 = f16 - f9 * f26;",
            "    f24 = f24 - f5 * f26;",
            "    f26 = f6 * f25 - f5 * f29;",
            "    f20 = f8 * f29 - f6 * f23;",
            "    f21 = f21 - f5 * f28;",
            "    f30 = f30 - f6 * f28;",
            "    f23 = f5 * f23 - f8 * f25;",
            "",
            "    runtime->viewDerivedTerms[0] = ((f8 * f10 - f6 * f12) - f9 * f18) * f1;",
            "    runtime->viewDerivedTerms[1] = ((f7 * f12 + f4 * f18) - f3 * f10) * f1;",
            "    runtime->viewDerivedTerms[2] = (f3 * f14 + f7 * f15 + f4 * f20) * f1;",
            "    runtime->viewDerivedTerms[3] = (f3 * f30 + f7 * f16 + f4 * f17) * f1;",
            "    runtime->viewDerivedTerms[4] = ((f6 * f27 + f9 * f11) - f5 * f10) * f1;",
            "    runtime->viewDerivedTerms[5] = ((f2 * f10 - f7 * f27) - f4 * f11) * f1;",
            "    runtime->viewDerivedTerms[6] = ((f7 * f19 + f4 * f26) - f2 * f14) * f1;",
            "    runtime->viewDerivedTerms[7] = ((f7 * f21 + f4 * f22) - f2 * f30) * f1;",
            "    runtime->viewDerivedTerms[8] = ((f5 * f12 - f8 * f27) - f9 * f13) * f1;",
            "    runtime->viewDerivedTerms[9] = ((f3 * f27 + f4 * f13) - f2 * f12) * f1;",
            "    runtime->viewDerivedTerms[10] = ((f4 * f23 - f2 * f15) - f3 * f19) * f1;",
            "    runtime->viewDerivedTerms[11] = ((f4 * f24 - f2 * f16) - f3 * f21) * f1;",
            "    runtime->viewDerivedTerms[12] = ((f5 * f18 - f8 * f11) + f6 * f13) * f1;",
            "    runtime->viewDerivedTerms[13] = ((f3 * f11 - f7 * f13) - f2 * f18) * f1;",
            "    runtime->viewDerivedTerms[14] = ((-f7 * f23 - f2 * f20) - f3 * f26) * f1;",
            "    runtime->viewDerivedTerms[15] = ((-f7 * f24 - f2 * f17) - f3 * f22) * f1;",
            "}",
            "",
            "u32 Oot3d_FogPackBase(float value) {",
            "    float scaled;",
            "",
            "    if (!(gOot3dFogMaterialCurveConstants.packBaseZero < value) || !Oot3d_FogIsFinite(value)) {",
            "        return 0u;",
            "    }",
            "",
            "    scaled = value * gOot3dFogMaterialCurveConstants.packBaseScale;",
            "    if (Oot3d_FogFloatBits(scaled) < 0x45000000u) {",
            "        return (u32)scaled;",
            "    }",
            "    return gOot3dFogMaterialCurveConstants.packBaseMax;",
            "}",
            "",
            "u32 Oot3d_FogPackSlope(float value) {",
            "    float encoded;",
            "",
            "    if (value == gOot3dFogMaterialCurveConstants.packSlopeZero || !Oot3d_FogIsFinite(value)) {",
            "        return 0u;",
            "    }",
            "",
            "    encoded = (value + gOot3dFogMaterialCurveConstants.packSlopeBias) *",
            "              gOot3dFogMaterialCurveConstants.packSlopeScale;",
            "    if (encoded < gOot3dFogMaterialCurveConstants.packSlopeZero) {",
            "        encoded = gOot3dFogMaterialCurveConstants.packSlopeZero;",
            "    } else if (Oot3d_FogFloatBits(encoded) > 0x45FFFFFFu) {",
            "        encoded = gOot3dFogMaterialCurveConstants.packSlopeMax;",
            "    }",
            "",
            "    if (encoded < gOot3dFogMaterialCurveConstants.packSlopeSplit) {",
            "        return (u32)(encoded + gOot3dFogMaterialCurveConstants.packSlopeOffset);",
            "    }",
            "    return (u32)(encoded - gOot3dFogMaterialCurveConstants.packSlopeOffset);",
            "}",
            "",
            "int Oot3d_FogBuildCurveArrays(Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                  const Oot3dFogMaterialTemplateDecoded* templateData,",
            "                                  Oot3dFogCurveTransform transform, void* transformUser) {",
            "    float curve[OOT3D_FOG_CURVE_SAMPLE_COUNT];",
            "    u32 index;",
            "",
            "    if (runtime == 0 || templateData == 0) {",
            "        return 0;",
            "    }",
            "",
            "    for (index = 0u; index < OOT3D_FOG_CURVE_SAMPLE_COUNT; index++) {",
            "        float step = (float)index * gOot3dFogMaterialCurveConstants.buildCurveStep;",
            "        float z = -((runtime->viewDerivedTerms[11] + runtime->viewDerivedTerms[10] * step) /",
            "                    (runtime->viewDerivedTerms[15] + runtime->viewDerivedTerms[14] * step));",
            "        float nearZ = runtime->nearZ;",
            "        float farZ = runtime->farZ;",
            "        float value = gOot3dFogMaterialCurveConstants.buildCurveNearValue;",
            "",
            "        if (nearZ > z) {",
            "            value = gOot3dFogMaterialCurveConstants.buildCurveNearValue;",
            "        } else if (farZ < z) {",
            "            value = gOot3dFogMaterialCurveConstants.buildCurveFarValue;",
            "        } else if (templateData->curveMode == 0u) {",
            "            value = (farZ - z) / (farZ - nearZ);",
            "        } else if (templateData->curveMode == 1u) {",
            "            if (transform == 0) {",
            "                return 0;",
            "            }",
            "            value = transform((float)-templateData->curveScale * ((z - nearZ) / (farZ - nearZ)), transformUser);",
            "        } else if (templateData->curveMode == 2u) {",
            "            float normalized;",
            "            if (transform == 0) {",
            "                return 0;",
            "            }",
            "            normalized = (z - nearZ) / (farZ - nearZ);",
            "            value = transform((float)-templateData->curveScale * normalized * normalized, transformUser);",
            "        } else {",
            "            value = gOot3dFogMaterialCurveConstants.buildCurveFarValue;",
            "        }",
            "",
            "        curve[index] = value;",
            "    }",
            "",
            "    for (index = 0u; index < OOT3D_FOG_LUT_ENTRY_COUNT; index++) {",
            "        runtime->fogLutBase[index] = curve[index];",
            "        runtime->fogLutDelta[index] = curve[index + 1u] - curve[index];",
            "    }",
            "",
            "    return 1;",
            "}",
            "",
            "int Oot3d_FogRebuildPackedPicaTable(Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                     const Oot3dFogMaterialTemplateDecoded* templateData,",
            "                                     Oot3dFogCurveTransform transform, void* transformUser) {",
            "    u32 index;",
            "",
            "    if (!Oot3d_FogBuildCurveArrays(runtime, templateData, transform, transformUser)) {",
            "        return 0;",
            "    }",
            "",
            "    for (index = 0u; index < OOT3D_FOG_LUT_ENTRY_COUNT; index++) {",
            "        runtime->packedPicaFogLut[index] =",
            "            Oot3d_FogPackSlope(runtime->fogLutDelta[index]) |",
            "            (Oot3d_FogPackBase(runtime->fogLutBase[index]) << 13);",
            "    }",
            "",
            "    return 1;",
            "}",
            "",
            "void Oot3d_FogRuntimeInitFromTemplate(Oot3dFogMaterialRuntimeLayout* runtime, u32 templateAddress) {",
            "    if (runtime == 0) {",
            "        return;",
            "    }",
            "",
            "    runtime->templateAddr = templateAddress;",
            "    runtime->nearZ = 10.0f;",
            "    runtime->farZ = 100.0f;",
            "    runtime->unknown1C = 0u;",
            "    runtime->unknown20 = 0u;",
            "    runtime->lutGeneration = 0xFFFFFFFFu;",
            "}",
            "",
            "int Oot3d_FogRuntimeApplyTemplateAndBuildLut(Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                             const Oot3dFogMaterialTemplateDecoded* templateData,",
            "                                             u32* lutGenerationCounter,",
            "                                             Oot3dFogCurveTransform transform, void* transformUser) {",
            "    if (runtime == 0 || templateData == 0) {",
            "        return 0;",
            "    }",
            "",
            "    runtime->fogColorR = templateData->fogColorR;",
            "    runtime->fogColorG = templateData->fogColorG;",
            "    runtime->fogColorB = templateData->fogColorB;",
            "    runtime->fogColorA = 1.0f;",
            "    runtime->nearZ = (float)templateData->nearZ;",
            "    runtime->farZ = (float)templateData->farZ;",
            "",
            "    if (templateData->rebuildDisabled == 0u) {",
            "        if (lutGenerationCounter != 0) {",
            "            runtime->lutGeneration = *lutGenerationCounter;",
            "        }",
            "        if (!Oot3d_FogRebuildPackedPicaTable(runtime, templateData, transform, transformUser)) {",
            "            return 0;",
            "        }",
            "        if (lutGenerationCounter != 0) {",
            "            *lutGenerationCounter = *lutGenerationCounter + 1u;",
            "        }",
            "    }",
            "",
            "    return 1;",
            "}",
            "",
            "void Oot3d_MaterialStateCopyFogRgb(u8* materialPacket, const Oot3dFogMaterialRuntimeLayout* runtime) {",
            "    if (materialPacket == 0 || runtime == 0) {",
            "        return;",
            "    }",
            "",
            "    *(float*)(materialPacket + OOT3D_MATERIAL_PACKET_FOG_R_OFFSET) = runtime->fogColorR;",
            "    *(float*)(materialPacket + OOT3D_MATERIAL_PACKET_FOG_G_OFFSET) = runtime->fogColorG;",
            "    *(float*)(materialPacket + OOT3D_MATERIAL_PACKET_FOG_B_OFFSET) = runtime->fogColorB;",
            "}",
            "",
            "void Oot3d_FogSourceMarkMaterialStateEnabled(u8* materialPacket) {",
            "    if (materialPacket != 0) {",
            "        materialPacket[OOT3D_MATERIAL_PACKET_ENABLE_OFFSET] = 1u;",
            "    }",
            "}",
            "",
            "void Oot3d_FogBindRuntimeToMaterialPacket(u8* materialPacket, const Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                             u32 packedPicaFogLutAddress) {",
            "    if (materialPacket == 0 || runtime == 0) {",
            "        return;",
            "    }",
            "",
            "    *(u32*)(materialPacket + OOT3D_MATERIAL_PACKET_LUT_GENERATION_OFFSET) = runtime->lutGeneration;",
            "    *(u32*)(materialPacket + OOT3D_MATERIAL_PACKET_LUT_TABLE_OFFSET) = packedPicaFogLutAddress;",
            "    Oot3d_MaterialStateCopyFogRgb(materialPacket, runtime);",
            "    Oot3d_FogSourceMarkMaterialStateEnabled(materialPacket);",
            "}",
            "",
            "u32 Oot3d_MaterialScalarReadLeU32(const u8* bytes) {",
            "    if (bytes == 0) {",
            "        return 0u;",
            "    }",
            "    return (u32)bytes[0] | ((u32)bytes[1] << 8) | ((u32)bytes[2] << 16) | ((u32)bytes[3] << 24);",
            "}",
            "",
            "u8 Oot3d_MaterialScalarRuntimeListCount(const u8* runtimeList) {",
            "    if (runtimeList == 0) {",
            "        return 0u;",
            "    }",
            "    return runtimeList[OOT3D_MATERIAL_RUNTIME_LIST_COUNT_OFFSET];",
            "}",
            "",
            "u32 Oot3d_MaterialScalarRuntimeListObjectAddress(const u8* runtimeList, u32 index) {",
            "    const u8* entry;",
            "",
            "    if (runtimeList == 0 || index >= Oot3d_MaterialScalarRuntimeListCount(runtimeList)) {",
            "        return 0u;",
            "    }",
            "    entry = runtimeList + index * OOT3D_MATERIAL_RUNTIME_LIST_ENTRY_STRIDE;",
            "    return Oot3d_MaterialScalarReadLeU32(entry + OOT3D_MATERIAL_RUNTIME_LIST_ENTRY_OBJECT_OFFSET);",
            "}",
            "",
            "u32 Oot3d_MaterialScalarRuntimeObjectPacketAddress(const u8* runtimeObject,",
            "                                                   Oot3dMaterialScalarAddressResolver resolver,",
            "                                                   void* resolverUser) {",
            "    u32 ownerAddress;",
            "    u8* owner;",
            "",
            "    if (runtimeObject == 0 || resolver == 0) {",
            "        return 0u;",
            "    }",
            "    ownerAddress = Oot3d_MaterialScalarReadLeU32(",
            "        runtimeObject + OOT3D_MATERIAL_RUNTIME_OBJECT_PACKET_OWNER_OFFSET);",
            "    if (ownerAddress == 0u) {",
            "        return 0u;",
            "    }",
            "    owner = resolver(ownerAddress, OOT3D_MATERIAL_PACKET_OWNER_PACKET_OFFSET + 4u, resolverUser);",
            "    if (owner == 0) {",
            "        return 0u;",
            "    }",
            "    return Oot3d_MaterialScalarReadLeU32(owner + OOT3D_MATERIAL_PACKET_OWNER_PACKET_OFFSET);",
            "}",
            "",
            "u8* Oot3d_MaterialScalarResolvePacketFromRuntimeObject(u32 runtimeObjectAddress,",
            "                                                       Oot3dMaterialScalarAddressResolver resolver,",
            "                                                       void* resolverUser) {",
            "    u8* runtimeObject;",
            "    u32 packetAddress;",
            "",
            "    if (runtimeObjectAddress == 0u || resolver == 0) {",
            "        return 0;",
            "    }",
            "    runtimeObject = resolver(runtimeObjectAddress,",
            "                             OOT3D_MATERIAL_RUNTIME_OBJECT_PACKET_OWNER_OFFSET + 4u,",
            "                             resolverUser);",
            "    if (runtimeObject == 0) {",
            "        return 0;",
            "    }",
            "    packetAddress = Oot3d_MaterialScalarRuntimeObjectPacketAddress(runtimeObject, resolver, resolverUser);",
            "    if (packetAddress == 0u) {",
            "        return 0;",
            "    }",
            "    return resolver(packetAddress, OOT3D_MATERIAL_PACKET_LUT_TABLE_OFFSET + 4u, resolverUser);",
            "}",
            "",
            "int Oot3d_MaterialScalarBindRuntimeList(Oot3dFogMaterialSourceLayout* source,",
            "                                         Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                         const u8* runtimeList,",
            "                                         Oot3dMaterialScalarAddressResolver resolver,",
            "                                         void* resolverUser,",
            "                                         const Oot3dFogMaterialTemplateDecoded* templateData,",
            "                                         u32 packedPicaFogLutAddress,",
            "                                         Oot3dFogCurveTransform transform, void* transformUser) {",
            "    u32 index;",
            "    u32 bound = 0u;",
            "    const u32 count = Oot3d_MaterialScalarRuntimeListCount(runtimeList);",
            "",
            "    if (source == 0 || runtime == 0 || runtimeList == 0 || resolver == 0) {",
            "        return 0;",
            "    }",
            "",
            "    for (index = 0u; index < count; index++) {",
            "        const u32 runtimeObjectAddress = Oot3d_MaterialScalarRuntimeListObjectAddress(runtimeList, index);",
            "        u8* materialPacket;",
            "",
            "        if (runtimeObjectAddress == 0u) {",
            "            continue;",
            "        }",
            "        materialPacket = Oot3d_MaterialScalarResolvePacketFromRuntimeObject(",
            "            runtimeObjectAddress, resolver, resolverUser);",
            "        if (materialPacket != 0 &&",
            "            Oot3d_FogSourceBindMaterialState(source, runtime, templateData, materialPacket,",
            "                                             packedPicaFogLutAddress, transform, transformUser)) {",
            "            bound++;",
            "        }",
            "    }",
            "    return (int)bound;",
            "}",
            "",
            "int Oot3d_GameplayUpdateFogMaterialSource(Oot3dFogMaterialSourceLayout* source,",
            "                                          Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                          u32 runtimeAddress,",
            "                                          const float view[OOT3D_FOG_VIEW_WORD_COUNT],",
            "                                          float nearZ, float farZ,",
            "                                          u8 fogR, u8 fogG, u8 fogB, u8 fogA,",
            "                                          u32* lutGenerationCounter,",
            "                                          Oot3dFogCurveTransform transform, void* transformUser) {",
            "    Oot3dFogMaterialTemplateDecoded templateData = gOot3dFogMaterialTemplateDecoded_004FA8B8;",
            "    u32 viewWords[OOT3D_FOG_VIEW_WORD_COUNT];",
            "    float red;",
            "    float green;",
            "    float blue;",
            "    float alpha;",
            "    int flags = 0;",
            "    u32 index;",
            "",
            "    if (source == 0 || runtime == 0 || view == 0 || runtimeAddress == 0u) {",
            "        return 0;",
            "    }",
            "",
            "    red = (float)fogR * gOot3dFogMaterialScalarMetadata.inv255;",
            "    green = (float)fogG * gOot3dFogMaterialScalarMetadata.inv255;",
            "    blue = (float)fogB * gOot3dFogMaterialScalarMetadata.inv255;",
            "    alpha = (float)fogA * gOot3dFogMaterialScalarMetadata.inv255;",
            "    templateData.fogColorR = red;",
            "    templateData.fogColorG = green;",
            "    templateData.fogColorB = blue;",
            "    templateData.fogColorA = alpha;",
            "    templateData.nearZ = (s32)nearZ;",
            "    templateData.farZ = (s32)farZ;",
            "    Oot3d_FogCopyViewWords(viewWords, view);",
            "",
            "    if (source->runtimeAddr == 0u) {",
            "        source->runtimeAddr = runtimeAddress;",
            "        source->enabled = 1u;",
            "        source->dirty = 0u;",
            "        for (index = 0u; index < OOT3D_FOG_VIEW_WORD_COUNT; index++) {",
            "            source->viewWords[index] = viewWords[index];",
            "        }",
            "        Oot3d_FogRuntimeInitFromTemplate(runtime, OOT3D_FOG_MATERIAL_TEMPLATE_ADDR);",
            "        Oot3d_FogCopyViewTermsToRuntime(runtime, view);",
            "        if (!Oot3d_FogRuntimeApplyTemplateAndBuildLut(runtime, &templateData, lutGenerationCounter,",
            "                                                      transform, transformUser)) {",
            "            return 0;",
            "        }",
            "        return OOT3D_FOG_UPDATE_ALLOCATED | OOT3D_FOG_UPDATE_COLOR_CHANGED |",
            "               OOT3D_FOG_UPDATE_VIEW_CHANGED | OOT3D_FOG_UPDATE_NEAR_FAR_CHANGED |",
            "               OOT3D_FOG_UPDATE_ENABLED_CHANGED | OOT3D_FOG_UPDATE_REBUILT;",
            "    }",
            "",
            "    if (runtime->fogColorR != red || runtime->fogColorG != green || runtime->fogColorB != blue) {",
            "        runtime->fogColorR = red;",
            "        runtime->fogColorG = green;",
            "        runtime->fogColorB = blue;",
            "        flags |= OOT3D_FOG_UPDATE_COLOR_CHANGED;",
            "    }",
            "",
            "    if (Oot3d_FogViewWordsChanged(source->viewWords, viewWords)) {",
            "        for (index = 0u; index < OOT3D_FOG_VIEW_WORD_COUNT; index++) {",
            "            source->viewWords[index] = viewWords[index];",
            "        }",
            "        source->dirty = 1u;",
            "        flags |= OOT3D_FOG_UPDATE_VIEW_CHANGED;",
            "    }",
            "",
            "    if ((float)(s32)runtime->nearZ != nearZ) {",
            "        runtime->nearZ = (float)(s32)nearZ;",
            "        source->dirty = 1u;",
            "        flags |= OOT3D_FOG_UPDATE_NEAR_FAR_CHANGED;",
            "    }",
            "    if ((float)(s32)runtime->farZ != farZ) {",
            "        runtime->farZ = (float)(s32)farZ;",
            "        source->dirty = 1u;",
            "        flags |= OOT3D_FOG_UPDATE_NEAR_FAR_CHANGED;",
            "    }",
            "",
            "    {",
            "        u8 enabled = (farZ - nearZ != gOot3dFogMaterialCurveConstants.updateDisableDistance) ? 1u : 0u;",
            "        if (source->enabled != enabled) {",
            "            source->enabled = enabled;",
            "            flags |= OOT3D_FOG_UPDATE_ENABLED_CHANGED;",
            "        }",
            "    }",
            "",
            "    return flags;",
            "}",
            "",
            "int Oot3d_GameplayApplyFogMaterialFrameOrder(const Oot3dGameplayFogMaterialFrameInput* input,",
            "                                            Oot3dGameplayFogMaterialFrameResult* result) {",
            "    int sourceFlags;",
            "    int list0Bound;",
            "    int list1Bound;",
            "",
            "    if (result != 0) {",
            "        result->sourceUpdateFlags = 0;",
            "        result->runtimeList0BoundCount = 0;",
            "        result->runtimeList1BoundCount = 0;",
            "    }",
            "    if (input == 0 || input->source == 0 || input->runtime == 0 || input->view == 0 ||",
            "        input->runtimeAddress == 0u) {",
            "        return 0;",
            "    }",
            "",
            "    sourceFlags = Oot3d_GameplayUpdateFogMaterialSource(",
            "        input->source, input->runtime, input->runtimeAddress, input->view, input->nearZ, input->farZ,",
            "        input->fogR, input->fogG, input->fogB, input->fogA, input->lutGenerationCounter,",
            "        input->transform, input->transformUser);",
            "    list0Bound = Oot3d_MaterialScalarBindRuntimeList(",
            "        input->source, input->runtime, input->runtimeList0, input->resolver, input->resolverUser,",
            "        input->templateData, input->packedPicaFogLutAddress, input->transform, input->transformUser);",
            "    list1Bound = Oot3d_MaterialScalarBindRuntimeList(",
            "        input->source, input->runtime, input->runtimeList1, input->resolver, input->resolverUser,",
            "        input->templateData, input->packedPicaFogLutAddress, input->transform, input->transformUser);",
            "",
            "    if (result != 0) {",
            "        result->sourceUpdateFlags = sourceFlags;",
            "        result->runtimeList0BoundCount = list0Bound;",
            "        result->runtimeList1BoundCount = list1Bound;",
            "    }",
            "    return sourceFlags != 0 || list0Bound != 0 || list1Bound != 0;",
            "}",
            "",
            "int Oot3d_FogSourceBindMaterialState(Oot3dFogMaterialSourceLayout* source,",
            "                                      Oot3dFogMaterialRuntimeLayout* runtime,",
            "                                      const Oot3dFogMaterialTemplateDecoded* templateData,",
            "                                      u8* materialPacket, u32 packedPicaFogLutAddress,",
            "                                      Oot3dFogCurveTransform transform, void* transformUser) {",
            "    if (source == 0 || runtime == 0 || materialPacket == 0 || source->runtimeAddr == 0u) {",
            "        return 0;",
            "    }",
            "",
            "    if (source->enabled == 0u) {",
            "        materialPacket[OOT3D_MATERIAL_PACKET_ENABLE_OFFSET] = 0u;",
            "        return 1;",
            "    }",
            "",
            "    if (source->dirty != 0u) {",
            "        const Oot3dFogMaterialTemplateDecoded* activeTemplate =",
            "            templateData != 0 ? templateData : &gOot3dFogMaterialTemplateDecoded_004FA8B8;",
            "        Oot3d_FogCopyViewWordsToRuntime(runtime, source->viewWords);",
            "        if (!Oot3d_FogRebuildPackedPicaTable(runtime, activeTemplate, transform, transformUser)) {",
            "            return 0;",
            "        }",
            "        source->dirty = 0u;",
            "    }",
            "",
            "    Oot3d_FogBindRuntimeToMaterialPacket(materialPacket, runtime, packedPicaFogLutAddress);",
            "    return 1;",
            "}",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_json(path: Path, report: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2) + "\n", encoding="ascii")


def write_markdown(path: Path, report: dict[str, Any]) -> None:
    lines = [
        "# OOT3D Fog Material Scalar Source",
        "",
        "This is a code.bin decompilation artifact. It describes the native fog material-scalar resource used by `Gameplay_Draw` and the material scalar binder; it is not runtime replacement data.",
        "",
        f"- code.bin: `{report['code_bin']}`",
        f"- code base: `{report['code_base']}`",
        f"- template address: `{report['static_addresses']['template']}`",
        f"- runtime allocation size: `{report['runtime_layout']['allocation_size']:#x}`",
        f"- PlayState fog source offset: `{report['playstate_offsets']['fog_source_offset']}`",
        f"- PlayState view source offset: `{report['playstate_offsets']['view_source_offset']}`",
        f"- PlayState final fog RGB offset: `{report['playstate_offsets']['final_fog_rgb_offset']}`",
        f"- PlayState fog far offset: `{report['playstate_offsets']['fog_far_float_offset']}`",
        f"- PlayState fog near offset: `{report['playstate_offsets']['fog_near_u16_offset']}`",
        f"- PlayState material runtime list 0 offset: `{report['playstate_offsets']['material_runtime_list0_offset']}`",
        f"- PlayState material runtime list 1 offset: `{report['playstate_offsets']['material_runtime_list1_offset']}`",
        "",
        "## Native Function Route",
        "",
        "| Name | Address |",
        "|---|---:|",
    ]
    for name, address in report["functions"].items():
        lines.append(f"| `{name}` | `{address}` |")
    lines.extend(
        [
            "",
            "## Gameplay Draw Material-Scalar Order",
            "",
            "| Field | Value |",
            "|---|---|",
        ]
    )
    for key, value in report["gameplay_draw_material_scalar_order"].items():
        lines.append(f"| `{key}` | `{value}` |")
    lines.extend(
        [
            "",
            "## Static Literals",
            "",
            "| Field | Value |",
            "|---|---|",
        ]
    )
    for key, value in report["literal_values"].items():
        lines.append(f"| `{key}` | `{value}` |")
    lines.extend(
        [
            "",
            "## Curve and Packing Literals",
            "",
            "| Field | Address | Word | Float |",
            "|---|---:|---:|---:|",
        ]
    )
    for key, value in report["curve_pack_literals"].items():
        lines.append(f"| `{key}` | `{value['address']}` | `{value['word']}` | `{value['float']}` |")
    template = report["template"]
    lines.extend(
        [
            "",
            "## Template Decode",
            "",
            f"- Fog RGBA: `{template['fog_color_rgba']}`",
            f"- Near Z: `{template['near_z_s32']}`",
            f"- Far Z: `{template['far_z_s32']}`",
            f"- Curve scale: `{template['curve_scale_s32']}`",
            f"- LUT rebuild disabled byte `+0x41`: `{template['rebuild_disabled_u8_at_41']}`",
            f"- Curve mode byte `+0x42`: `{template['curve_mode_u8_at_42']}`",
            "",
            "## Runtime Layout",
            "",
            "| Field | Offset |",
            "|---|---|",
        ]
    )
    for key, value in report["runtime_layout"].items():
        lines.append(f"| `{key}` | `{value}` |")
    lines.extend(
        [
            "",
            "## Source Layout",
            "",
            "| Field | Offset |",
            "|---|---|",
        ]
    )
    for key, value in report["source_layout"].items():
        lines.append(f"| `{key}` | `{value}` |")
    lines.extend(
        [
            "",
            "## Runtime Material List Layout",
            "",
            "| Field | Value |",
            "|---|---|",
        ]
    )
    for key, value in report["runtime_material_list_layout"].items():
        lines.append(f"| `{key}` | `{value}` |")
    lines.extend(
        [
            "",
            "## Material Packet Offsets",
            "",
            "| Field | Offset |",
            "|---|---|",
        ]
    )
    for key, value in report["material_packet_offsets"].items():
        lines.append(f"| `{key}` | `{value}` |")
    lines.extend(
        [
            "",
            "## Decompiled Executable Coverage",
            "",
            "- `Oot3d_FogPackBase`, `Oot3d_FogPackSlope`, `Oot3d_FogBuildCurveArrays`, `Oot3d_FogRebuildPackedPicaTable`, `Oot3d_FogCopyViewTermsToRuntime`, `Oot3d_FogRuntimeInitFromTemplate`, `Oot3d_FogRuntimeApplyTemplateAndBuildLut`, `Oot3d_GameplayUpdateFogMaterialSource`, `Oot3d_FogSourceBindMaterialState`, `Oot3d_MaterialScalarBindRuntimeList`, `Oot3d_MaterialScalarResolvePacketFromRuntimeObject`, `Oot3d_MaterialStateCopyFogRgb`, and `Oot3d_FogSourceMarkMaterialStateEnabled` are emitted as C code in `src/code/z_fog_material_scalar.c`.",
            "- `Oot3d_GameplayUpdateFogMaterialSource` mirrors the native `00464B2C` source update using caller-provided runtime storage plus the native 32-bit runtime address; this preserves the OOT3D source/runtime layout without requiring host pointers in native fields.",
            "- `Oot3d_MaterialScalarBindRuntimeList` mirrors native `002D960C`: it walks the runtime material lists at `play+0x4C30` and `play+0x500C`, resolves each runtime object with the native `003687A8` packet owner chain, and applies the `play+0x5FC8` fog source through `00368704`.",
            "- `Oot3d_GameplayApplyFogMaterialFrameOrder` mirrors the recovered `Gameplay_Draw` order for this material-scalar route: update source through `00464B2C`, then bind list 0 and list 1 through `002D960C`. Its inputs are caller-provided native data, not emulator replacement RGB.",
            "- Curve mode `0` is fully covered by the native code.bin logic used by the title-intro template.",
            "- Curve modes `1` and `2` call native `FUN_002BB8DC`; the generated C requires an explicit `Oot3dFogCurveTransform` callback for those modes until that function is decompiled.",
        ]
    )
    lines.extend(
        [
            "",
            "## Validation Link",
            "",
            "The slot-6 title intro writer trace maps this route to source `0x08959C90` and runtime object `0x0821065C`. The first complete object fog RGB observed in that trace is `[20,15,33]`, while aligned PICA reports `[20,14,33]`; the one-LSB green difference remains a quantization/ordering item.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--code-bin", type=Path, default=DEFAULT_CODE_BIN)
    parser.add_argument("--output-json", type=Path, default=DEFAULT_OUT_JSON)
    parser.add_argument("--output-md", type=Path, default=DEFAULT_OUT_MD)
    parser.add_argument("--output-header", type=Path, default=DEFAULT_OUT_HEADER)
    parser.add_argument("--output-source", type=Path, default=DEFAULT_OUT_SOURCE)
    args = parser.parse_args()

    report = build_report(args.code_bin)
    write_json(args.output_json, report)
    write_markdown(args.output_md, report)
    write_header(args.output_header)
    write_source(args.output_source, report)
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
