#!/usr/bin/env python3
"""Build the OOT3D open-title frame runtime bridge audit.

This is the aggregation layer for the title intro milestone: it samples the
native CMAD camera, player-action motion consumer, EnMag/logo state, and
cutscene-owned environment state in one runtime frame object. The audit is
non-destructive: maintained runtime sources are inspected in place instead of
being regenerated by this helper.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "analysis"

ORCHESTRATION = ANALYSIS / "title_intro_opening_orchestration.json"
ACTOR_AUDIT = ANALYSIS / "title_intro_opening_actor_runtime_audit.json"
CAMERA_AUDIT = ANALYSIS / "title_intro_opening_camera_runtime_audit.json"
LOGO_AUDIT = ANALYSIS / "title_intro_opening_logo_runtime_audit.json"
SET_TIME_TABLE = ANALYSIS / "scene_cutscene_set_time_table.json"

OUT_JSON = ANALYSIS / "title_intro_opening_frame_runtime_audit.json"
OUT_MD = ANALYSIS / "title_intro_opening_frame_runtime_audit.md"
OUT_HEADER = ROOT / "include" / "oot3d" / "title_intro_opening_frame_runtime.h"
OUT_SOURCE = ROOT / "src" / "code" / "z_title_intro_opening_frame_runtime.c"
INTRO_RUNTIME_HEADER = ROOT / "include" / "oot3d" / "scene_cutscene_intro_runtime.h"
INTRO_RUNTIME_SOURCE = ROOT / "src" / "code" / "z_scene_cutscene_intro_runtime.c"
REPO_ROOT = ROOT.parents[2]
DEMO_HOST = REPO_ROOT / "tools" / "oot3d" / "native_demo_host" / "oot3d_native_fast3d_demo.cpp"
RENDER_SOURCE = REPO_ROOT / "runtime/three_ds_recomp" / "src" / "ship" / "oot3d" / "Oot3dNativeRenderScene.cpp"
ASSETS_SOURCE = REPO_ROOT / "runtime/three_ds_recomp" / "src" / "ship" / "oot3d" / "Oot3dNativeAssets.cpp"
OPERATIONAL_INPUTS = REPO_ROOT / "tools" / "oot3d" / "operational_inputs.json"

def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def write_json(path: Path, data: Any) -> None:
    write_text(path, json.dumps(data, indent=2) + "\n")


HEADER = """#ifndef OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_H
#define OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_H

#include "oot3d/title_intro_opening_actor_runtime.h"
#include "oot3d/title_intro_opening_camera_runtime.h"
#include "oot3d/title_intro_opening_logo_runtime.h"
#include "oot3d/title_intro_opening_orchestration.h"
#include "oot3d/scene_cutscene_camera_blob_table.h"
#include "oot3d/types.h"

typedef enum {
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_OK = 0,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_NULL_STATE,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_NULL_OUTPUT,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_UNINITIALIZED,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_MISSING_ORCHESTRATION,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_CAMERA_ERROR,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_ACTOR_ERROR,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_LOGO_ERROR,
    OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_COMPLETE,
} Oot3dTitleIntroOpeningFrameRuntimeStatus;

typedef struct Oot3dTitleIntroOpeningFrameRuntimeState {
    u16 orchestrationIndex;
    s32 frame;
    s32 nativeEndFrame;
    s32 cameraSegmentStartFrame;
    s32 cameraSegmentEndFrame;
    u8 initialized;
    u8 complete;
    Oot3dTitleIntroOpeningLogoState logoState;
} Oot3dTitleIntroOpeningFrameRuntimeState;

typedef struct Oot3dTitleIntroOpeningFrameRuntimeStep {
    u16 orchestrationIndex;
    s32 frame;
    s32 nativeEndFrame;
    s32 cameraSegmentStartFrame;
    s32 cameraSegmentEndFrame;
    u8 cameraSegmentActive;
    u8 complete;
    const Oot3dTitleIntroOpeningOrchestrationRow* orchestration;
    const Oot3dSceneCutsceneCameraBlobSegmentRow* cameraSegment;
    Oot3dTitleIntroOpeningCameraRuntimeStatus cameraStatus;
    Oot3dTitleIntroOpeningCameraSample camera;
    Oot3dTitleIntroOpeningActorSampleStatus actorMotionStatus;
    u8 actorMotionActive;
    Oot3dTitleIntroOpeningActorMotionSample actorMotion;
    Oot3dTitleIntroOpeningLogoRuntimeStatus logoStepStatus;
    u8 logoStepApplied;
    Oot3dTitleIntroOpeningLogoStepResult logoStep;
    Oot3dTitleIntroOpeningLogoRuntimeStatus logoDrawStatus;
    Oot3dTitleIntroOpeningLogoDrawSnapshot logoDraw;
} Oot3dTitleIntroOpeningFrameRuntimeStep;

Oot3dTitleIntroOpeningFrameRuntimeStatus Oot3d_TitleIntroOpeningFrameRuntimeInit(
    Oot3dTitleIntroOpeningFrameRuntimeState* state,
    u16 orchestrationIndex,
    u8 forceRisingButtonLogoState
);

Oot3dTitleIntroOpeningFrameRuntimeStatus Oot3d_TitleIntroOpeningFrameRuntimeStep(
    Oot3dTitleIntroOpeningFrameRuntimeState* state,
    const Oot3dCutsceneCameraViewPerturbation* perturbation,
    const Oot3dTitleIntroOpeningLogoStepInput* logoInput,
    Oot3dTitleIntroOpeningFrameRuntimeStep* outStep
);

#endif
"""


SOURCE = """#include "oot3d/title_intro_opening_frame_runtime.h"

#include <string.h>

Oot3dTitleIntroOpeningFrameRuntimeStatus Oot3d_TitleIntroOpeningFrameRuntimeInit(
    Oot3dTitleIntroOpeningFrameRuntimeState* state,
    u16 orchestrationIndex,
    u8 forceRisingButtonLogoState
) {
    const Oot3dTitleIntroOpeningOrchestrationRow* orchestration;
    const Oot3dSceneCutsceneCameraBlobSegmentRow* cameraSegment = 0;
    Oot3dTitleIntroOpeningLogoRuntimeStatus logoStatus;

    if (state == 0) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_NULL_STATE;
    }
    orchestration = Oot3d_TitleIntroOpeningGetOrchestrationRow(orchestrationIndex);
    if (orchestration == 0) {
        memset(state, 0, sizeof(*state));
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_MISSING_ORCHESTRATION;
    }
    memset(state, 0, sizeof(*state));
    state->orchestrationIndex = orchestrationIndex;
    state->nativeEndFrame = orchestration->nativeEndFrame;
    state->cameraSegmentStartFrame = 0;
    state->cameraSegmentEndFrame = orchestration->nativeEndFrame;
    if (orchestration->cameraBlobSegmentSourceIndex < oot3d_scene_cutscene_camera_blob_segment_row_count) {
        cameraSegment = &oot3d_scene_cutscene_camera_blob_segment_rows[orchestration->cameraBlobSegmentSourceIndex];
        state->cameraSegmentStartFrame = cameraSegment->startFrame;
        state->cameraSegmentEndFrame = cameraSegment->endFrame;
    }
    if (forceRisingButtonLogoState != 0u) {
        logoStatus = Oot3d_TitleIntroOpeningLogoRuntimeInitForceRisingButton(&state->logoState);
    } else {
        logoStatus = Oot3d_TitleIntroOpeningLogoRuntimeInitDefault(&state->logoState);
    }
    if (logoStatus != OOT3D_TITLE_INTRO_OPENING_LOGO_RUNTIME_OK) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_LOGO_ERROR;
    }
    state->initialized = 1u;
    return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_OK;
}

Oot3dTitleIntroOpeningFrameRuntimeStatus Oot3d_TitleIntroOpeningFrameRuntimeStep(
    Oot3dTitleIntroOpeningFrameRuntimeState* state,
    const Oot3dCutsceneCameraViewPerturbation* perturbation,
    const Oot3dTitleIntroOpeningLogoStepInput* logoInput,
    Oot3dTitleIntroOpeningFrameRuntimeStep* outStep
) {
    const Oot3dTitleIntroOpeningOrchestrationRow* orchestration;
    const Oot3dSceneCutsceneCameraBlobSegmentRow* cameraSegment = 0;

    if (state == 0) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_NULL_STATE;
    }
    if (outStep == 0) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_NULL_OUTPUT;
    }
    if (state->initialized == 0u) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_UNINITIALIZED;
    }
    memset(outStep, 0, sizeof(*outStep));
    orchestration = Oot3d_TitleIntroOpeningGetOrchestrationRow(state->orchestrationIndex);
    if (orchestration == 0) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_MISSING_ORCHESTRATION;
    }
    outStep->orchestration = orchestration;
    outStep->orchestrationIndex = state->orchestrationIndex;
    outStep->nativeEndFrame = state->nativeEndFrame;
    outStep->cameraSegmentStartFrame = state->cameraSegmentStartFrame;
    outStep->cameraSegmentEndFrame = state->cameraSegmentEndFrame;
    if (orchestration->cameraBlobSegmentSourceIndex < oot3d_scene_cutscene_camera_blob_segment_row_count) {
        cameraSegment = &oot3d_scene_cutscene_camera_blob_segment_rows[orchestration->cameraBlobSegmentSourceIndex];
        outStep->cameraSegment = cameraSegment;
    }
    if (state->complete != 0u) {
        outStep->frame = state->frame;
        outStep->complete = 1u;
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_COMPLETE;
    }

    state->frame++;
    outStep->frame = state->frame;
    if (state->frame > state->nativeEndFrame) {
        state->complete = 1u;
        outStep->complete = 1u;
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_COMPLETE;
    }
    if (state->cameraSegmentStartFrame <= state->frame && state->frame <= state->cameraSegmentEndFrame) {
        outStep->cameraSegmentActive = 1u;
    }

    if (outStep->cameraSegmentActive != 0u) {
        outStep->cameraStatus = Oot3d_TitleIntroOpeningCameraRuntimeSample(
            state->orchestrationIndex,
            (float)state->frame,
            perturbation,
            &outStep->camera
        );
        if (outStep->cameraStatus != OOT3D_TITLE_INTRO_OPENING_CAMERA_RUNTIME_OK) {
            return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_CAMERA_ERROR;
        }
    }

    outStep->actorMotionStatus = Oot3d_TitleIntroOpeningActorRuntimeSamplePlayerMotion(
        state->frame,
        &outStep->actorMotion
    );
    if (outStep->actorMotionStatus == OOT3D_TITLE_INTRO_OPENING_ACTOR_SAMPLE_OK) {
        outStep->actorMotionActive = 1u;
    } else if (outStep->actorMotionStatus != OOT3D_TITLE_INTRO_OPENING_ACTOR_SAMPLE_NO_ACTIVE_CUE) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_ACTOR_ERROR;
    }

    outStep->logoStepStatus = Oot3d_TitleIntroOpeningLogoRuntimeStep(
        &state->logoState,
        logoInput,
        &outStep->logoStep
    );
    if (outStep->logoStepStatus == OOT3D_TITLE_INTRO_OPENING_LOGO_RUNTIME_OK) {
        outStep->logoStepApplied = outStep->logoStep.applied;
    } else if (outStep->logoStepStatus != OOT3D_TITLE_INTRO_OPENING_LOGO_RUNTIME_NO_MATCHING_STEP) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_LOGO_ERROR;
    }

    outStep->logoDrawStatus = Oot3d_TitleIntroOpeningLogoRuntimeBuildDrawSnapshot(
        state->orchestrationIndex,
        &state->logoState,
        &outStep->logoDraw
    );
    if (outStep->logoDrawStatus != OOT3D_TITLE_INTRO_OPENING_LOGO_RUNTIME_OK) {
        return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_LOGO_ERROR;
    }

    return OOT3D_TITLE_INTRO_OPENING_FRAME_RUNTIME_OK;
}
"""


def build_markdown(audit: dict[str, Any]) -> str:
    native_time = audit.get("native_time_transition", {})
    native_kankyo = audit.get("native_kankyo_schedule_transition", {})
    native_kankyo_lines = [
        "",
        "## Native Kankyo Schedule Transition",
        "",
        f"- Available: {native_kankyo.get('available')}",
        f"- Source: `{native_kankyo.get('source_kind', '')}`",
        f"- Schedule mode: `{native_kankyo.get('schedule_mode')}`",
        f"- Schedule table: `{format_optional_hex(native_kankyo.get('schedule_table_address'))}`",
    ]
    selections = native_kankyo.get("selections", {})
    for label, selection in selections.items():
        if not selection:
            native_kankyo_lines.append(f"- `{label}`: `<missing>`")
            continue
        native_kankyo_lines.append(
            f"- `{label}` angle `{selection.get('active_angle')}` selects entry "
            f"`{selection.get('entry_index')}` profile "
            f"`{selection.get('current_profile_index')} -> "
            f"{selection.get('next_profile_index')}` alpha "
            f"`{selection.get('blend_alpha')}`."
        )
    native_time_lines = [
        "",
        "## Native Time Transition",
        "",
        f"- Available: {native_time.get('available')}",
        f"- Source: `{native_time.get('source_kind', '')}`",
        f"- Set-time frames: `{native_time.get('set_time_start_frames', [])}`",
        f"- Base increment: `{native_time.get('base_increment')}`",
        f"- Night delta: `{native_time.get('night_time_delta')}`",
        f"- Day delta: `{native_time.get('day_time_delta')}`",
        f"- Night-to-day transitions: `{native_time.get('night_to_day_transition_count')}`",
    ]
    for transition in native_time.get("night_to_day_transitions", []):
        native_time_lines.append(
            f"- Set-time `{transition.get('set_time_start_frame')}` reaches day on frame "
            f"`{transition.get('first_day_frame')}` with dayTime "
            f"`{transition.get('day_time_after')}` and skyboxTime "
            f"`{transition.get('skybox_time_after')}`."
        )
    lines = [
        "# OOT3D Open Title Frame Runtime Audit",
        "",
        "This audit adds a frame-level bridge that samples the already promoted native camera, actor-motion, and EnMag/logo runtimes together.",
        "",
        "## Summary",
        "",
        f"- OK: {audit['ok']}",
        f"- Orchestration index: {audit['orchestration']['orchestration_index']}",
        f"- Native end frame: {audit['orchestration']['native_end_frame']}",
        f"- Current camera segment frames: {audit['orchestration']['camera_segment_start_frame']}..{audit['orchestration']['camera_segment_end_frame']}",
        "- Next implementation slice: complete the remaining material/effect backend for emulator-parity rendering; camera, Link/Epona actors, logo draw, time, direct light-setting handoff, and kankyo schedule selection are renderer-visible.",
        "",
        "## Checks",
        "",
        "| Check | Status |",
        "| --- | --- |",
    ]
    for key, value in audit["checks"].items():
        lines.append(f"| `{key}` | `{value}` |")
    lines.extend(native_time_lines)
    lines.extend(native_kankyo_lines)
    lines.extend(
        [
            "",
            "## Scope",
            "",
            "- Camera comes from the open-title CMAD camera runtime.",
            "- Actor motion comes from the native player-action consumer runtime.",
            "- Logo state comes from the native EnMag alpha/timer runtime and draw snapshot.",
            "- Logo `envFlag3`/`envFlag4` inputs are stepped by the opening frame runtime through the OOT3D intro cutscene runtime; the demo host no longer supplies those flags.",
            "- The demo renderer consumes time and `CS_CMD_SET_LIGHTING` environment state from the title frame runtime.",
            "- The runtime advances decoded `CS_CMD_SETTIME` through the native 0x0045DD50 time progression constants, and the renderer consumes `skyboxTime` as the kankyo schedule active angle.",
            "- The report decodes the native kankyo profile schedule from original `code.bin`; the opening intro starts in a night/moon profile blend and reaches the day profile through the runtime `skyboxTime` angle.",
            "- Source36 direct-player handoff to source22 is resolved from native transition/entrance data; the renderer can select the target setup/index light record from that cutscene row.",
            "- Link and paired Epona visual transforms are owned by the actor runtime sample; the demo host consumes those samples instead of recomputing them from player-action/QDB rows.",
            "- Frame-500 render probe evidence (`build-codex/title_intro_frame500_logo_probe.json`) shows camera, Link, Epona, and EnMag/logo draw bound to the render scene; frame-2401 probe evidence shows `CS_CMD_SET_LIGHTING` raw 9 -> target 8 consumed by the direct target light-setting branch.",
            "- Interactive button input for the later title-screen transition remains outside the autoplay opening-frame scope until its native input owner is promoted.",
            "",
        ]
    )
    return "\n".join(lines)


def audit_ok(data: dict[str, Any]) -> bool:
    if "ok" in data:
        return bool(data["ok"])
    return bool(data.get("summary", {}).get("ok"))


def int_value(value: Any, default: int = 0) -> int:
    try:
        if isinstance(value, str) and value.lower().startswith("0x"):
            return int(value, 16)
        if value is None:
            return default
        return int(value)
    except (TypeError, ValueError):
        return default


def format_optional_hex(value: Any) -> str:
    parsed = int_value(value, -1)
    if parsed < 0:
        return str(value)
    return f"0x{parsed:08X}"


def constant_from_header(header_text: str, name: str) -> int | None:
    pattern = re.compile(rf"\b{name}\s*=\s*(0x[0-9A-Fa-f]+|\d+)")
    match = pattern.search(header_text)
    if match is None:
        return None
    return int(match.group(1), 0)


def constant_from_cpp(source_text: str, name: str) -> int | None:
    pattern = re.compile(rf"\b{name}\s*=\s*(0x[0-9A-Fa-f]+|\d+)")
    match = pattern.search(source_text)
    if match is None:
        return None
    return int(match.group(1), 0)


def resolve_operational_path(manifest: dict[str, Any], entry_id: str) -> Path | None:
    variables = manifest.get("variables", {})
    for entry in manifest.get("entries", []):
        if entry.get("id") != entry_id:
            continue
        path = str(entry.get("path", ""))
        for key, value in variables.items():
            path = path.replace("${" + key + "}", str(value))
        return Path(path)
    return None


def runtime_offset(runtime_address: int, code_base: int, code_size: int) -> int | None:
    if runtime_address < code_base:
        return None
    offset = runtime_address - code_base
    if offset < 0 or offset >= code_size:
        return None
    return offset


def can_read(data: bytes, offset: int | None, size: int) -> bool:
    return offset is not None and offset >= 0 and offset + size <= len(data)


def read_le_u16_at_runtime(data: bytes, runtime_address: int, code_base: int) -> int | None:
    offset = runtime_offset(runtime_address, code_base, len(data))
    if not can_read(data, offset, 2):
        return None
    return int.from_bytes(data[offset:offset + 2], "little")


def read_le_u32_at_runtime(data: bytes, runtime_address: int, code_base: int) -> int | None:
    offset = runtime_offset(runtime_address, code_base, len(data))
    if not can_read(data, offset, 4):
        return None
    return int.from_bytes(data[offset:offset + 4], "little")


def read_u8_at_runtime(data: bytes, runtime_address: int, code_base: int) -> int | None:
    offset = runtime_offset(runtime_address, code_base, len(data))
    if not can_read(data, offset, 1):
        return None
    return data[offset]


def native_time_is_night(day_time: int, day_start: int, day_length: int) -> bool:
    return ((day_time - day_start) & 0xFFFFFFFF) >= day_length


def native_time_base_increment(game_speed: int, time_rate: int) -> int:
    if time_rate == 0:
        return int(float(game_speed) * 0.0 * (1.0 / 3.0) - 0.5)
    return int(0.5 + (float(game_speed) * float(time_rate) * (1.0 / 3.0)))


def build_native_time_transition_summary(
    orchestration_row: dict[str, Any],
    set_time_table: dict[str, Any],
    intro_header_text: str,
) -> dict[str, Any]:
    cutscene_source_index = int_value(orchestration_row.get("cutscene_source_index"), -1)
    setup_index = int_value(orchestration_row.get("setup_index"), -1)
    native_end_frame = int_value(orchestration_row.get("native_end_frame"), -1)
    constants = {
        "day_start": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_DAY_START"),
        "day_length": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_DAY_LENGTH"),
        "skybox_wrap_threshold": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_SKYBOX_WRAP_THRESHOLD"),
        "night_double_limit": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_NIGHT_DOUBLE_LIMIT"),
        "time_rate_default": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_TIME_RATE_DEFAULT"),
        "game_speed_default": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_GAME_SPEED_DEFAULT"),
        "game_speed_init_address": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_GAME_SPEED_INIT_ADDRESS"),
        "game_speed_store_address": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_GAME_SPEED_STORE_ADDRESS"),
        "time_rate_source_address": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_TIME_RATE_SOURCE_ADDRESS"),
        "time_rate_init_function": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_TIME_RATE_INIT_FUNCTION"),
        "time_update_function": constant_from_header(
            intro_header_text, "OOT3D_CUTSCENE_INTRO_NATIVE_ENV_TIME_UPDATE_FUNCTION"),
    }
    if any(value is None for value in constants.values()):
        return {
            "available": False,
            "source_status": "native_time_constants_missing_from_scene_cutscene_intro_runtime_header",
            "constants": constants,
        }

    rows = [
        row for row in set_time_table.get("rows", [])
        if int_value(row.get("cutscene_source_index"), -1) == cutscene_source_index
    ]
    if not rows:
        rows = [
            row for row in set_time_table.get("set_time_rows", [])
            if int_value(row.get("cutscene_source_index"), -1) == cutscene_source_index
        ]
    rows_by_frame = {
        int_value(row.get("start_frame"), -1): row
        for row in rows
    }
    start_frames = sorted(rows_by_frame)
    if 0 not in rows_by_frame:
        return {
            "available": False,
            "source_status": "source_cutscene_has_no_initial_set_time_row",
            "cutscene_source_index": cutscene_source_index,
            "set_time_start_frames": start_frames,
            "constants": constants,
        }

    day_time = int_value(rows_by_frame[0].get("day_time"))
    skybox_time = int_value(rows_by_frame[0].get("skybox_time"))
    rate = int_value(constants["time_rate_default"])
    game_speed = int_value(constants["game_speed_default"])
    base_increment = native_time_base_increment(game_speed, rate)
    day_start = int_value(constants["day_start"])
    day_length = int_value(constants["day_length"])
    night_double_limit = int_value(constants["night_double_limit"])
    skybox_wrap_threshold = int_value(constants["skybox_wrap_threshold"])
    first_set_time_day_time = day_time
    first_set_time_skybox_time = skybox_time
    first_runtime_delta = base_increment
    if native_time_is_night(first_set_time_day_time, day_start, day_length) and rate < night_double_limit:
        first_runtime_delta *= 2
    first_runtime_day_time = (first_set_time_day_time + first_runtime_delta) & 0xFFFF
    first_runtime_skybox_time = first_set_time_skybox_time
    if first_runtime_skybox_time < first_runtime_day_time or first_runtime_day_time < skybox_wrap_threshold:
        first_runtime_skybox_time = first_runtime_day_time

    transitions: list[dict[str, Any]] = []
    pending_set_frame = 0
    was_night = native_time_is_night(day_time, day_start, day_length)
    for frame in range(1, native_end_frame + 1):
        if frame in rows_by_frame:
            row = rows_by_frame[frame]
            day_time = int_value(row.get("day_time"))
            skybox_time = int_value(row.get("skybox_time"))
            pending_set_frame = frame
            was_night = native_time_is_night(day_time, day_start, day_length)

        night_before = was_night
        delta = base_increment
        if night_before and rate < night_double_limit:
            delta *= 2
        day_before = day_time
        skybox_before = skybox_time
        day_time = (day_time + delta) & 0xFFFF
        if skybox_time < day_time or day_time < skybox_wrap_threshold:
            skybox_time = day_time
        was_night = native_time_is_night(day_time, day_start, day_length)
        if night_before and not was_night:
            transitions.append({
                "set_time_start_frame": pending_set_frame,
                "first_day_frame": frame,
                "day_time_before": day_before,
                "day_time_after": day_time,
                "skybox_time_before": skybox_before,
                "skybox_time_after": skybox_time,
                "native_time_delta": delta,
            })

    return {
        "available": True,
        "source_kind": "oot3d_cs_cmd_settime_native_time_progression_0045dd50",
        "source_status": (
            "simulated from decoded source36 CS_CMD_SETTIME rows, game speed initialized "
            "by code.bin 0x00450B68/0x00450B80, and constants promoted from "
            "scene_cutscene_intro_runtime.h; renderer then consumes skyboxTime as the "
            "native kankyo schedule active angle"
        ),
        "cutscene_source_index": cutscene_source_index,
        "setup_index": setup_index,
        "game_speed": game_speed,
        "native_end_frame": native_end_frame,
        "set_time_start_frames": start_frames,
        "first_set_time_day_time": first_set_time_day_time,
        "first_set_time_skybox_time": first_set_time_skybox_time,
        "first_runtime_day_time": first_runtime_day_time,
        "first_runtime_skybox_time": first_runtime_skybox_time,
        "base_increment": base_increment,
        "time_rate": rate,
        "night_time_delta": base_increment * 2 if rate < night_double_limit else base_increment,
        "day_time_delta": base_increment,
        "night_to_day_transition_count": len(transitions),
        "night_to_day_transitions": transitions,
        "final_day_time": day_time,
        "final_skybox_time": skybox_time,
        "constants": constants,
    }


def select_kankyo_schedule_entry(entries: list[dict[str, Any]], active_angle: int) -> dict[str, Any] | None:
    for entry in entries:
        start_angle = int_value(entry.get("start_angle"))
        end_angle = int_value(entry.get("end_angle"))
        if start_angle <= active_angle and (active_angle < end_angle or end_angle == 0xFFFF):
            blend_flag = int_value(entry.get("blend_flag"))
            blend_alpha = 0
            if blend_flag != 0 and end_angle != start_angle:
                weight = 1.0 - float(end_angle - active_angle) / float(end_angle - start_angle)
                weight = max(0.0, min(1.0, weight))
                blend_alpha = max(0, min(255, int(weight * 255.0 + 0.5)))
            selected = dict(entry)
            selected["active_angle"] = active_angle
            selected["blend_alpha"] = blend_alpha
            return selected
    return None


def build_native_kankyo_schedule_transition_summary(
    native_time: dict[str, Any],
    render_text: str,
    assets_text: str,
    operational_inputs: dict[str, Any],
) -> dict[str, Any]:
    code_path = resolve_operational_path(operational_inputs, "oot3d_code_bin")
    if code_path is None:
        return {
            "available": False,
            "source_status": "oot3d_code_bin_entry_missing_from_operational_inputs",
        }
    if not code_path.is_file():
        return {
            "available": False,
            "source_status": "oot3d_code_bin_not_found",
            "code_bin_path": str(code_path),
        }

    constants = {
        "code_base": constant_from_cpp(assets_text, "RuntimeTransitionTableCodeBase"),
        "schedule_table_pointer_address": constant_from_cpp(
            render_text, "kCodeBinKankyoScheduleTablePointerAddress"),
        "schedule_mode_stride_bytes": constant_from_cpp(
            render_text, "kCodeBinKankyoScheduleModeStrideBytes"),
        "schedule_entry_size_bytes": constant_from_cpp(
            render_text, "kCodeBinKankyoScheduleEntrySizeBytes"),
        "schedule_entry_count": constant_from_cpp(
            render_text, "kCodeBinKankyoScheduleEntryCount"),
        "fallback_state_address": constant_from_cpp(
            assets_text, "RuntimeTransitionGlobalFallbackStateAddress"),
        "fallback_mode_offset": constant_from_cpp(
            assets_text, "RuntimeTransitionGlobalFallbackModeOffset"),
    }
    if any(value is None for value in constants.values()):
        return {
            "available": False,
            "source_status": "native_kankyo_schedule_or_fallback_constants_missing",
            "code_bin_path": str(code_path),
            "constants": constants,
        }

    code = code_path.read_bytes()
    code_base = int_value(constants["code_base"])
    schedule_table_address = read_le_u32_at_runtime(
        code, int_value(constants["schedule_table_pointer_address"]), code_base)
    fallback_mode = read_u8_at_runtime(
        code,
        int_value(constants["fallback_state_address"]) + int_value(constants["fallback_mode_offset"]),
        code_base,
    )
    if schedule_table_address is None or fallback_mode is None:
        return {
            "available": False,
            "source_status": "native_kankyo_schedule_pointer_or_fallback_mode_unreadable",
            "code_bin_path": str(code_path),
            "constants": constants,
            "schedule_table_address": schedule_table_address,
            "fallback_mode": fallback_mode,
        }

    mode_table_address = (
        schedule_table_address +
        fallback_mode * int_value(constants["schedule_mode_stride_bytes"])
    )
    entries: list[dict[str, Any]] = []
    for entry_index in range(int_value(constants["schedule_entry_count"])):
        entry_address = (
            mode_table_address +
            entry_index * int_value(constants["schedule_entry_size_bytes"])
        )
        start_angle = read_le_u16_at_runtime(code, entry_address + 0x00, code_base)
        end_angle = read_le_u16_at_runtime(code, entry_address + 0x02, code_base)
        blend_flag = read_u8_at_runtime(code, entry_address + 0x04, code_base)
        current_profile = read_u8_at_runtime(code, entry_address + 0x05, code_base)
        next_profile = read_u8_at_runtime(code, entry_address + 0x06, code_base)
        if None in (start_angle, end_angle, blend_flag, current_profile, next_profile):
            return {
                "available": False,
                "source_status": "native_kankyo_schedule_entry_unreadable",
                "code_bin_path": str(code_path),
                "constants": constants,
                "schedule_table_address": schedule_table_address,
                "mode_table_address": mode_table_address,
                "failed_entry_index": entry_index,
            }
        entries.append({
            "entry_index": entry_index,
            "entry_address": entry_address,
            "start_angle": start_angle,
            "end_angle": end_angle,
            "blend_flag": blend_flag,
            "current_profile_index": current_profile,
            "next_profile_index": next_profile,
        })

    initial_angle = int_value(native_time.get("first_runtime_skybox_time"), -1)
    day_transitions = native_time.get("night_to_day_transitions", [])
    first_day_angle = (
        int_value(day_transitions[0].get("skybox_time_after"), -1)
        if day_transitions else -1
    )
    second_day_angle = (
        int_value(day_transitions[1].get("skybox_time_after"), -1)
        if len(day_transitions) > 1 else -1
    )
    selections = {
        "first_runtime_skybox_time": select_kankyo_schedule_entry(entries, initial_angle)
        if initial_angle >= 0 else None,
        "first_day_transition_skybox_time": select_kankyo_schedule_entry(entries, first_day_angle)
        if first_day_angle >= 0 else None,
        "second_day_transition_skybox_time": select_kankyo_schedule_entry(entries, second_day_angle)
        if second_day_angle >= 0 else None,
    }

    return {
        "available": True,
        "source_kind": "oot3d_code_bin_native_kankyo_schedule_table",
        "source_status": (
            "decoded from original ExeFS code.bin through the renderer's native kankyo "
            "pointer constants; mode comes from the same runtime global fallback state the "
            "renderer uses before a cutscene-specific mode overrides it"
        ),
        "code_bin_path": str(code_path),
        "code_base": code_base,
        "schedule_table_pointer_address": int_value(constants["schedule_table_pointer_address"]),
        "schedule_table_address": schedule_table_address,
        "fallback_state_address": int_value(constants["fallback_state_address"]),
        "fallback_mode_offset": int_value(constants["fallback_mode_offset"]),
        "schedule_mode": fallback_mode,
        "mode_table_address": mode_table_address,
        "schedule_mode_stride_bytes": int_value(constants["schedule_mode_stride_bytes"]),
        "schedule_entry_size_bytes": int_value(constants["schedule_entry_size_bytes"]),
        "schedule_entry_count": int_value(constants["schedule_entry_count"]),
        "entries": entries,
        "selections": selections,
        "constants": constants,
    }


def main() -> None:
    orchestration = read_json(ORCHESTRATION)
    actor = read_json(ACTOR_AUDIT)
    camera = read_json(CAMERA_AUDIT)
    logo = read_json(LOGO_AUDIT)
    set_time = read_json(SET_TIME_TABLE)
    header_text = read_text(OUT_HEADER)
    source_text = read_text(OUT_SOURCE)
    intro_header_text = read_text(INTRO_RUNTIME_HEADER)
    intro_source_text = read_text(INTRO_RUNTIME_SOURCE)
    demo_text = read_text(DEMO_HOST)
    render_text = read_text(RENDER_SOURCE)
    assets_text = read_text(ASSETS_SOURCE)
    operational_inputs = read_json(OPERATIONAL_INPUTS)
    row = orchestration["orchestration_rows"][0]
    camera_reference = camera["reference_rows"][0]
    native_time = build_native_time_transition_summary(row, set_time, intro_header_text)
    native_kankyo = build_native_kankyo_schedule_transition_summary(
        native_time, render_text, assets_text, operational_inputs)
    native_kankyo_selections = native_kankyo.get("selections", {})
    native_kankyo_initial = native_kankyo_selections.get("first_runtime_skybox_time") or {}
    native_kankyo_first_day = native_kankyo_selections.get("first_day_transition_skybox_time") or {}
    native_kankyo_second_day = native_kankyo_selections.get("second_day_transition_skybox_time") or {}
    checks = {
        "orchestration_audit_ok": audit_ok(orchestration),
        "actor_runtime_audit_ok": audit_ok(actor),
        "camera_runtime_audit_ok": audit_ok(camera),
        "logo_runtime_audit_ok": audit_ok(logo),
        "header_exposes_init_and_step": "Oot3d_TitleIntroOpeningFrameRuntimeStep" in header_text,
        "header_exposes_cutscene_lighting_state": "environmentLightSettingResolved" in header_text,
        "source_samples_camera_runtime": "Oot3d_TitleIntroOpeningCameraRuntimeSample" in source_text,
        "source_samples_actor_motion_runtime": "Oot3d_TitleIntroOpeningActorRuntimeSamplePlayerMotion" in source_text,
        "source_steps_logo_runtime": "Oot3d_TitleIntroOpeningLogoRuntimeStep" in source_text,
        "source_builds_logo_draw_snapshot": "Oot3d_TitleIntroOpeningLogoRuntimeBuildDrawSnapshot" in source_text,
        "source_owns_logo_env_flag_cutscene_runtime": "logoInputCutsceneRuntime" in source_text,
        "source_applies_transition_handoff": "Oot3d_TitleIntroOpeningFrameRuntimeAdvanceLogoInputHandoff" in source_text,
        "source_propagates_cutscene_light_setting": "environmentLightSettingRawIndex" in source_text
        and "environmentLightSettingTarget" in source_text,
        "demo_renderer_consumes_runtime_environment": "TitleIntroRuntimeEnvironmentInput" in demo_text,
        "demo_renderer_consumes_logo_draw": "ApplyTitleIntroOpeningFrameRuntimeLogoDraw" in demo_text,
        "demo_host_uses_actor_runtime_visual_transforms": "SampleTitleIntroOpeningFrameRuntimeLinkCue" in demo_text
        and "SampleTitleIntroOpeningFrameRuntimePairedMountCue" in demo_text,
        "demo_host_exposes_light_setting_setup": "RuntimeEnvironmentRenderedLightSettingSetupIndex" in demo_text,
        "renderer_consumes_direct_target_light_setting": "direct_target_light_setting_record" in render_text,
        "native_time_constants_exposed": native_time.get("available") is True,
        "source_advances_native_time_after_settime":
            "Oot3d_CutsceneIntroRuntimeProcessSetTime(state, outStep);" in intro_source_text
            and "Oot3d_CutsceneIntroRuntimeAdvanceNativeEnvironmentTime(state, nativeCutscene, outStep);" in intro_source_text
            and intro_source_text.find("Oot3d_CutsceneIntroRuntimeProcessSetTime(state, outStep);") <
                intro_source_text.find("Oot3d_CutsceneIntroRuntimeAdvanceNativeEnvironmentTime(state, nativeCutscene, outStep);"),
        "source36_settime_rows_include_frame0_and301":
            native_time.get("set_time_start_frames") == [0, 301],
        "native_time_reaches_day_once_after_final_source36_settime":
            native_time.get("night_to_day_transition_count", 0) == 1
            and int_value(native_time.get("night_to_day_transitions", [{}])[0].get(
                "set_time_start_frame"), -1) == 301,
        "renderer_kankyo_schedule_uses_runtime_skybox_time":
            "runtimeEnvironment->SkyboxTime" in render_text
            and "NativeKankyoScheduleActiveAngle" in render_text
            and "NativeRenderSelectKankyoCmbNames" in render_text,
        "native_kankyo_schedule_decoded_from_code_bin":
            native_kankyo.get("available") is True,
        "native_kankyo_schedule_uses_renderer_runtime_fallback_mode":
            native_kankyo.get("schedule_mode") is not None
            and "NativeRuntimeTransitionGlobalFallbackMode" in render_text,
        "native_kankyo_initial_angle_blends_distinct_profiles":
            int_value(native_kankyo_initial.get("blend_flag")) != 0
            and int_value(native_kankyo_initial.get("current_profile_index"), -1) !=
                int_value(native_kankyo_initial.get("next_profile_index"), -1)
            and int_value(native_kankyo_initial.get("blend_alpha")) > 0,
        "native_kankyo_day_angle_resolves_stable_profile":
            int_value(native_kankyo_first_day.get("current_profile_index"), -1) ==
                int_value(native_kankyo_first_day.get("next_profile_index"), -2)
            and int_value(native_kankyo_first_day.get("blend_alpha"), -1) == 0,
        "title_intro_time_transition_drives_kankyo_profile_change":
            int_value(native_kankyo_initial.get("next_profile_index"), -1) ==
                int_value(native_kankyo_first_day.get("current_profile_index"), -2)
            and int_value(native_kankyo_initial.get("current_profile_index"), -1) !=
                int_value(native_kankyo_first_day.get("current_profile_index"), -1),
    }
    audit = {
        "ok": all(checks.values()),
        "source": {
            "orchestration": str(ORCHESTRATION.relative_to(ROOT)).replace("\\", "/"),
            "actor_audit": str(ACTOR_AUDIT.relative_to(ROOT)).replace("\\", "/"),
            "camera_audit": str(CAMERA_AUDIT.relative_to(ROOT)).replace("\\", "/"),
            "logo_audit": str(LOGO_AUDIT.relative_to(ROOT)).replace("\\", "/"),
            "set_time_table": str(SET_TIME_TABLE.relative_to(ROOT)).replace("\\", "/"),
            "intro_runtime": str(INTRO_RUNTIME_SOURCE.relative_to(ROOT)).replace("\\", "/"),
            "operational_inputs": str(OPERATIONAL_INPUTS.relative_to(REPO_ROOT)).replace("\\", "/"),
            "render_source": str(RENDER_SOURCE.relative_to(REPO_ROOT)).replace("\\", "/"),
            "assets_source": str(ASSETS_SOURCE.relative_to(REPO_ROOT)).replace("\\", "/"),
        },
        "orchestration": {
            "orchestration_index": row["orchestration_index"],
            "scene_id": row["scene_id"],
            "setup_index": row["setup_index"],
            "cutscene_source_index": row["cutscene_source_index"],
            "native_end_frame": row["native_end_frame"],
            "camera_segment_start_frame": camera_reference["segment_start_frame"],
            "camera_segment_end_frame": camera_reference["segment_end_frame"],
        },
        "native_time_transition": native_time,
        "native_kankyo_schedule_transition": native_kankyo,
        "checks": checks,
        "unresolved": [
            "Interactive title-screen button input remains outside the autoplay opening-frame scope until its native input owner is promoted.",
            "Remaining emulator-parity work is now in material/effect backend fidelity and any scene-resource handoff needed beyond the proven source36->source22 light-setting target.",
        ],
    }
    write_json(OUT_JSON, audit)
    write_text(OUT_MD, build_markdown(audit))
    print(f"wrote {OUT_MD.relative_to(ROOT)} ok={audit['ok']}")


if __name__ == "__main__":
    main()
