#!/usr/bin/env python3
"""Extract unique N64 source functions for ranked porting lanes."""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import sys
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "analysis"
DEFAULT_N64_ROOT = ROOT.parent / "external" / "oot"

sys.path.insert(0, str(ROOT / "scripts"))
from rank_n64_port_candidates import iter_c_functions, rel  # noqa: E402


def slug(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_")


def read_plan(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def function_map(n64_root: Path, n64_path: str) -> dict[str, str]:
    path = n64_root / n64_path
    if not path.is_file():
        raise FileNotFoundError(f"N64 source not found: {path}")
    return dict(iter_c_functions(path))


def hit_flags(hit: dict[str, object]) -> list[str]:
    flags = []
    for key, label in (
        ("promotion_ready", "promote"),
        ("matching_seed", "match-seed"),
        ("fanout_review", "fanout-review"),
        ("name_conflict", "name-conflict-review"),
        ("reviewed_defer", "reviewed-defer"),
    ):
        if hit.get(key):
            flags.append(label)
    return flags


def evidence_summary(hit: dict[str, object]) -> str:
    evidence = hit.get("evidence") or {}
    if not isinstance(evidence, dict):
        return ""

    parts = []
    for key in ("constants", "tokens", "call_tokens", "strings"):
        values = evidence.get(key) or []
        if values:
            parts.append(f"{key}:{','.join(str(value) for value in values[:5])}")

    pointer_targets = hit.get("pointer_targets") or []
    if pointer_targets:
        targets = [f"{row.get('entry')}/{row.get('name')}" for row in pointer_targets[:4] if isinstance(row, dict)]
        if targets:
            parts.append(f"ptr_out:{','.join(targets)}")

    pointer_sources = hit.get("pointer_sources") or []
    if pointer_sources:
        sources = [f"{row.get('entry')}/{row.get('name')}" for row in pointer_sources[:4] if isinstance(row, dict)]
        if sources:
            parts.append(f"ptr_in:{','.join(sources)}")

    return "; ".join(parts)


def select_hits(
    lane: dict[str, object],
    max_hits: int,
    min_score: float,
    include_non_top: bool,
    include_reviewed_defer: bool,
) -> list[dict[str, object]]:
    selected: list[dict[str, object]] = []
    for hit in lane.get("hits", []):
        if not isinstance(hit, dict):
            continue
        if not include_non_top and int(hit.get("candidate_rank", 0)) != 1:
            continue
        if not include_reviewed_defer and hit.get("reviewed_defer"):
            continue
        if float(hit.get("score", 0.0)) < min_score:
            continue
        selected.append(hit)
        if len(selected) >= max_hits:
            break
    return selected


def unique_n64_functions(hits: list[dict[str, object]], max_functions: int) -> OrderedDict[str, list[dict[str, object]]]:
    grouped: OrderedDict[str, list[dict[str, object]]] = OrderedDict()
    for hit in hits:
        n64_name = str(hit.get("n64_name", ""))
        if not n64_name:
            continue
        if n64_name not in grouped:
            if len(grouped) >= max_functions:
                continue
            grouped[n64_name] = []
        grouped[n64_name].append(hit)
    return grouped


def write_lane(
    out_root: Path,
    n64_root: Path,
    lane: dict[str, object],
    hits: list[dict[str, object]],
    max_functions: int,
) -> dict[str, object]:
    rank = int(lane["rank"])
    n64_path = str(lane["n64_path"])
    lane_dir = out_root / f"{rank:02d}_{slug(n64_path)}"
    lane_dir.mkdir(parents=True, exist_ok=True)

    grouped = unique_n64_functions(hits, max_functions)
    bodies = function_map(n64_root, n64_path)

    combined = [
        "/* N64 source extracts for a ranked OOT3D porting lane.",
        " * Generated by scripts/extract_n64_lane_sources.py.",
        " * These extracts are reference input for OOT3D structured ports.",
        " */",
        "",
    ]

    rows = []
    for index, (n64_name, mapped_hits) in enumerate(grouped.items(), start=1):
        body = bodies.get(n64_name)
        if body is None:
            raise KeyError(f"N64 function {n64_name} not found in {n64_root / n64_path}")

        filename = f"{index:02d}_{slug(n64_name)}.c"
        (lane_dir / filename).write_text(body.rstrip() + "\n", encoding="utf-8")
        combined.extend(
            [
                f"/* {n64_path}::{n64_name}",
                " * OOT3D candidate entries: "
                + ", ".join(str(hit.get("oot3d_entry")) for hit in mapped_hits[:12]),
                " */",
                body.rstrip(),
                "",
            ]
        )
        rows.append(
            {
                "n64_name": n64_name,
                "extract": filename,
                "mapped_oot3d": len(mapped_hits),
                "best_score": max(float(hit.get("score", 0.0)) for hit in mapped_hits),
                "entries": [str(hit.get("oot3d_entry")) for hit in mapped_hits],
            }
        )

    (lane_dir / "n64_source_extracts.c").write_text("\n".join(combined).rstrip() + "\n", encoding="utf-8")

    lines = [
        f"# N64 Lane Source Extracts `{n64_path}`",
        "",
        "Generated from `analysis/n64_batch_porting_plan.json`.",
        "",
        f"- Lane rank: `{rank}`",
        f"- Action: `{lane.get('action')}`",
        f"- Lane score: `{lane.get('lane_score')}`",
        f"- Selected OOT3D hits: `{len(hits)}`",
        f"- Unique N64 functions extracted: `{len(grouped)}`",
        f"- N64 source root: `{rel(n64_root, ROOT.parent)}`",
        "",
        "## Extracted N64 Functions",
        "",
        "| N64 function | Extract | OOT3D candidates | Best score | Candidate entries |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for row in rows:
        lines.append(
            f"| `{row['n64_name']}` | `{row['extract']}` | {row['mapped_oot3d']} | "
            f"{row['best_score']:.2f} | {', '.join('`' + entry + '`' for entry in row['entries'][:10])} |"
        )

    lines.extend(
        [
            "",
            "## OOT3D Candidate Mapping",
            "",
            "| OOT3D | Lines | N64 function | Rank | Score | Confidence | Suggested name | Flags | Evidence |",
            "| --- | ---: | --- | ---: | ---: | --- | --- | --- | --- |",
        ]
    )
    for hit in hits:
        flags = hit_flags(hit)
        lines.append(
            f"| `{hit.get('oot3d_entry')}` `{hit.get('oot3d_name')}` | {hit.get('oot3d_lines')} | "
            f"`{hit.get('n64_name')}` | {hit.get('candidate_rank')} | {float(hit.get('score', 0.0)):.2f} | "
            f"`{hit.get('confidence')}` | `{hit.get('suggested_name')}` | "
            f"{', '.join(flags) if flags else '-'} | {evidence_summary(hit) or '-'} |"
        )

    lines.extend(
        [
            "",
            "## Use",
            "",
            "Use these extracts as the source-side batch input. Promote or port only after reviewing",
            "the OOT3D control flow and data layout for the whole lane; fan-out rows are subsystem",
            "evidence, not automatic one-to-one matches.",
        ]
    )
    (lane_dir / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    return {
        "rank": rank,
        "n64_path": n64_path,
        "action": lane.get("action"),
        "lane_score": lane.get("lane_score"),
        "out_dir": rel(lane_dir),
        "selected_hits": len(hits),
        "unique_n64_functions": len(grouped),
        "functions": rows,
    }


def write_index(out_root: Path, out_json: Path, out_md: Path, out_csv: Path, lanes: list[dict[str, object]]) -> None:
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps({"lanes": lanes}, indent=2) + "\n", encoding="utf-8")

    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "rank",
                "n64_path",
                "action",
                "lane_score",
                "out_dir",
                "selected_hits",
                "unique_n64_functions",
            ],
        )
        writer.writeheader()
        for lane in lanes:
            writer.writerow({key: lane.get(key, "") for key in writer.fieldnames})

    lines = [
        "# N64 Lane Source Extract Index",
        "",
        "Generated by `scripts/extract_n64_lane_sources.py` from the batch planner.",
        "",
        "| Rank | N64 source | Action | Selected OOT3D hits | Unique N64 funcs | Extract directory |",
        "| ---: | --- | --- | ---: | ---: | --- |",
    ]
    for lane in lanes:
        lines.append(
            f"| {lane['rank']} | `{lane['n64_path']}` | `{lane['action']}` | "
            f"{lane['selected_hits']} | {lane['unique_n64_functions']} | `{lane['out_dir']}` |"
        )
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {rel(out_root)} ({len(lanes)} lanes)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", type=Path, default=ANALYSIS / "n64_batch_porting_plan.json")
    parser.add_argument("--n64-root", type=Path, default=DEFAULT_N64_ROOT)
    parser.add_argument("--out-dir", type=Path, default=ANALYSIS / "n64_lane_sources")
    parser.add_argument("--top-lanes", type=int, default=8)
    parser.add_argument("--max-hits-per-lane", type=int, default=24)
    parser.add_argument("--max-functions-per-lane", type=int, default=8)
    parser.add_argument("--min-score", type=float, default=170.0)
    parser.add_argument("--include-non-top", action="store_true")
    parser.add_argument("--include-reviewed-defer", action="store_true")
    parser.add_argument("--out-json", type=Path, default=ANALYSIS / "n64_lane_sources.json")
    parser.add_argument("--out-md", type=Path, default=ANALYSIS / "n64_lane_sources.md")
    parser.add_argument("--out-csv", type=Path, default=ANALYSIS / "n64_lane_sources.csv")
    args = parser.parse_args()

    plan = read_plan(args.plan)
    if args.out_dir.exists():
        shutil.rmtree(args.out_dir)
    lanes = []
    for lane in plan.get("lanes", [])[: args.top_lanes]:
        if not isinstance(lane, dict):
            continue
        hits = select_hits(
            lane,
            args.max_hits_per_lane,
            args.min_score,
            args.include_non_top,
            args.include_reviewed_defer,
        )
        if not hits:
            continue
        lanes.append(write_lane(args.out_dir, args.n64_root, lane, hits, args.max_functions_per_lane))

    write_index(args.out_dir, args.out_json, args.out_md, args.out_csv, lanes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
