// Generated by generate_import.py from the immutable d5c2927 package.
// The source hash and target body identity are recorded in import_manifest.json.
#include "oot3d/camera_update_owner.h"

#include <cmath>
#include <cstdint>

#if defined(_MSC_VER)
#pragma fenv_access(on)
#else
#pragma STDC FENV_ACCESS ON
#endif

namespace Oot3dSourceCameraUpdate {
namespace {

#define DAT_002d88a8 (ActiveLiterals().Words[0])
#define DAT_002d88b4 (GuestPtr<u32>(ActiveLiterals().Words[1]))
#define DAT_002d88bc (ActiveLiterals().Words[2])
#define DAT_002d88c8 (ActiveLiterals().Words[3])
#define DAT_002d8c20 (ActiveLiterals().Words[4])
#define DAT_002d8c28 (ActiveLiterals().Words[5])
#define DAT_002d8c2c (ActiveLiterals().Words[6])
#define DAT_002d8c30 (ActiveLiterals().Words[7])
#define DAT_002d8c38 (ActiveLiterals().Words[8])
#define DAT_002d8c40 (ActiveLiterals().Words[9])

#define OOT3D_ADDR(base, offset) \
    (static_cast<std::uint32_t>(base) + static_cast<std::uint32_t>(offset))
#define OOT3D_U8(base, offset) \
    GuestRef<u8>(OOT3D_ADDR((base), (offset)))
#define OOT3D_S16(base, offset) \
    GuestRef<s16>(OOT3D_ADDR((base), (offset)))
#define OOT3D_U16(base, offset) \
    GuestRef<u16>(OOT3D_ADDR((base), (offset)))
#define OOT3D_S32(base, offset) \
    GuestRef<s32>(OOT3D_ADDR((base), (offset)))
#define OOT3D_U32(base, offset) \
    GuestRef<u32>(OOT3D_ADDR((base), (offset)))
#define OOT3D_F32(base, offset) \
    GuestRef<float>(OOT3D_ADDR((base), (offset)))

typedef struct Oot3dCameraShake {
    Oot3dActorVec3f atOffset;
    Oot3dActorVec3f eyeOffset;
    s16 upPitchOffset;
    s16 upYawOffset;
    s16 fovOffset;
    s16 maximum;
} Oot3dCameraShake;

static s16 Oot3dCameraStepAngle(s16 current, s16 target, float scale) {
    const s32 difference = (s16)(target - current);

    if (difference == 0) {
        return target;
    }
    return (s16)(current + (s16)(0.5f + (float)difference * scale));
}

static float Oot3dCameraClampAxis20(float value) {
    const u32 bits = oot3d_float_to_bits(value);

    if (oot3d_float_to_bits(-20.0f) < bits) {
        return -20.0f;
    }
    if (bits > oot3d_float_to_bits(20.0f)) {
        return 20.0f;
    }
    return value;
}

static void Oot3dCameraApplyInputOffset(
    uintptr_t camera,
    Oot3dActorVec3f* viewAt,
    const Oot3dActorVec3f* viewEye
) {
    const s32 mode = OOT3D_S16(camera, 0x18C);
    const uintptr_t play = OOT3D_U32(camera, 0xD4);

    if (FUN_00374be8(play, 10) != 0) {
        FUN_002ded60();
        return;
    }

    switch (mode) {
        case 0:
        case 3:
        case 0x11:
        case 0x13: {
            Oot3dVecSphGeo eyeAt;

            OOT3D_S16(camera, 0x1B2) =
                Oot3dCameraStepAngle(OOT3D_S16(camera, 0x1B2), 0, 0.58f);
            OOT3D_S16(camera, 0x1B4) =
                Oot3dCameraStepAngle(OOT3D_S16(camera, 0x1B4), 0, 0.58f);
            OLib_Vec3fDiffToVecSphGeo(&eyeAt, viewEye, viewAt);
            eyeAt.pitch -= OOT3D_S16(camera, 0x1B2);
            eyeAt.yaw += OOT3D_S16(camera, 0x1B4);
            *viewAt = Camera_AddVecGeoToVec3f(viewEye, &eyeAt);
            FUN_002ded60();
            break;
        }

        case 1:
        case 0xC:
        case 0xF: {
            const uintptr_t input = (uintptr_t)FUN_00306f04();
            float axisX =
                OOT3D_F32(input, 4) * OOT3D_F32(input, 0x44);
            float axisY =
                OOT3D_F32(input, 8) * OOT3D_F32(input, 0x40);
            const float deltaX =
                (axisX - OOT3D_F32(camera, 0xBC)) * 1.4f;
            const float deltaY =
                (axisY - OOT3D_F32(camera, 0xC0)) * 1.4f;
            Oot3dVecSphGeo eyeAt;

            axisX = Oot3dCameraClampAxis20(
                OOT3D_F32(camera, 0xC8) + deltaX
            );
            axisY = Oot3dCameraClampAxis20(
                OOT3D_F32(camera, 0xCC) + deltaY
            );
            OOT3D_F32(camera, 0xC8) = axisX - deltaX;
            OOT3D_F32(camera, 0xCC) = axisY - deltaY;

            if (OOT3D_U8(DAT_002d8c40, 0xE) != 0) {
                axisY = -axisY;
            }
            OOT3D_S16(camera, 0x1B2) = Oot3dCameraStepAngle(
                OOT3D_S16(camera, 0x1B2),
                (s16)(axisX * 182.04445f),
                0.28f
            );
            OOT3D_S16(camera, 0x1B4) = Oot3dCameraStepAngle(
                OOT3D_S16(camera, 0x1B4),
                (s16)(axisY * 182.04445f),
                0.28f
            );

            OLib_Vec3fDiffToVecSphGeo(&eyeAt, viewEye, viewAt);
            eyeAt.pitch -= OOT3D_S16(camera, 0x1B2);
            eyeAt.yaw += OOT3D_S16(camera, 0x1B4);
            *viewAt = Camera_AddVecGeoToVec3f(viewEye, &eyeAt);
            FUN_002d0518();
            break;
        }

        case 6:
        case 7:
        case 9:
        case 0xA:
        case 0xB:
            break;

        case 8:
            if (FUN_00374be8(play, 0x1A) == 0) {
                FUN_002ded60();
            }
            break;

        default:
            FUN_002ded60();
            break;
    }
}

static void Oot3dCameraUpdateDistortion(
    uintptr_t camera,
    uintptr_t play,
    uintptr_t cameraState
) {
    const u16 distortionFlags = OOT3D_U16(camera, 0x19A);
    const uintptr_t view = play + 0x188;

    if (distortionFlags != 0) {
        const uintptr_t playerState = (uintptr_t)(u32)*DAT_002d88b4;
        float phaseAStep;
        float phaseBStep;
        float orientationX;
        float orientationY;
        float orientationZ;
        float scaleX = -0.01f;
        float scaleY = 0.01f;
        float scaleZ = 0.01f;
        float speed = 0.6f;
        float scaleFactor;
        float speedFactor = 0.6666667f;
        s16 phaseA;
        s16 phaseB;

        if (OOT3D_S16(playerState, 0x362) != 0) {
            const float hundredth = 0.01f;

            phaseBStep =
                (float)OOT3D_S16(playerState, 0x35E) * hundredth;
            phaseAStep =
                (float)OOT3D_S16(playerState, 0x360) * hundredth;
            orientationX =
                (float)OOT3D_S16(playerState, 0x364) * hundredth;
            orientationY =
                (float)OOT3D_S16(playerState, 0x366) * hundredth;
            orientationZ =
                (float)OOT3D_S16(playerState, 0x368) * hundredth;
            scaleX =
                (float)OOT3D_S16(playerState, 0x36A) * hundredth;
            scaleY =
                (float)OOT3D_S16(playerState, 0x36C) * hundredth;
            scaleZ =
                (float)OOT3D_S16(playerState, 0x36E) * hundredth;
            speed =
                (float)OOT3D_S16(playerState, 0x370) * hundredth;
            scaleFactor =
                (float)OOT3D_S16(camera, 0x198) /
                (float)OOT3D_S16(playerState, 0x372);
            speedFactor = 1.0f;
        } else if ((distortionFlags & 4) != 0) {
            phaseAStep = 113.333336f;
            phaseBStep = 0.0f;
            orientationX = 0.0f;
            orientationY = 0.0f;
            orientationZ = 0.0f;
            scaleZ = 0.0f;
            scaleFactor = (float)OOT3D_S16(camera, 0x198) * 0.6666667f;
        } else if ((distortionFlags & 8) != 0) {
            phaseAStep = -60.0f;
            phaseBStep = 165.33333f;
            orientationX = 0.0f;
            orientationY = 0.0f;
            orientationZ = 0.0f;
            scaleX = -0.22f;
            scaleY = 0.22f;
            scaleZ = 0.12f;
            speed = 0.1f;
            scaleFactor = (float)OOT3D_S16(camera, 0x198) / 120.0f;
        } else if ((distortionFlags & 2) != 0) {
            float waterDepth =
                OOT3D_F32(camera, 0x15C) - OOT3D_F32(camera, 0x90);

            phaseAStep = -12.333333f;
            phaseBStep = 239.46667f;
            orientationX = 0.0f;
            orientationY = 0.0f;
            orientationZ = 0.0f;
            scaleX = 0.09f;
            scaleY = 0.09f;
            scaleZ = 0.01f;
            speed = 0.08f;
            if (waterDepth <= 150.0f) {
                waterDepth /= 150.0f;
            } else {
                waterDepth = 1.0f;
            }
            scaleFactor =
                (waterDepth * 0.38f + OOT3D_F32(camera, 0x128) * 0.38f) *
                2.0f * 0.33333334f;
            speedFactor = scaleFactor;
        } else if ((distortionFlags & 1) != 0) {
            phaseAStep = 100.0f;
            phaseBStep = 0.0f;
            orientationX = 0.0f;
            orientationY = 0.0f;
            orientationZ = 0.0f;
            scaleFactor = 0.6666667f;
        } else {
            return;
        }

        phaseA = (s16)(
            OOT3D_S16(cameraState, 8) +
            (s16)(0.5f + phaseAStep * 182.04167f)
        );
        phaseB = (s16)(
            OOT3D_S16(cameraState, 0xA) +
            (s16)(0.5f + phaseBStep * 182.04167f)
        );
        OOT3D_S16(cameraState, 8) = phaseA;
        OOT3D_S16(cameraState, 0xA) = phaseB;

        FUN_00343858(
            view,
            oot3d_cos_idx8(phaseA) *
                (orientationX * 0.017453292f) * scaleFactor,
            oot3d_sin_idx8(phaseA) *
                (orientationY * 0.017453292f) * scaleFactor,
            oot3d_sin_idx8(phaseB) *
                (orientationZ * 0.017453292f) * scaleFactor
        );
        FUN_00343840(
            view,
            1.0f + oot3d_sin_idx8(phaseB) * scaleX * scaleFactor,
            1.0f + oot3d_cos_idx8(phaseB) * scaleY * scaleFactor,
            1.0f + oot3d_cos_idx8(phaseA) * scaleZ * scaleFactor
        );
        OOT3D_F32(play, 0x35C) = speed * speedFactor;
        OOT3D_U16(camera, 0x194) |= 0x40;
    } else if ((OOT3D_U16(camera, 0x194) & 0x40) != 0) {
        FUN_004779ec(view);
        OOT3D_U16(camera, 0x194) &= (u16)~0x40;
    }
}

Oot3dVec3s Camera_UpdateImpl(std::uint32_t camera) {
    const uintptr_t play = OOT3D_U32(camera, 0xD4);
    const uintptr_t cameraState = DAT_002d88a8;
    const uintptr_t playerState = (uintptr_t)(u32)*DAT_002d88b4;
    const uintptr_t mainPlayer =
        OOT3D_U32(OOT3D_U32(play, 0xA54), 0xD8);
    Oot3dVec3s result;
    Oot3dActorVec3f viewAt;
    Oot3dActorVec3f viewEye;
    Oot3dActorVec3f viewUp;
    Oot3dVecSphGeo eyeAtAngle;
    Oot3dCameraShake shake;
    float viewFov = 1.0f;

    if (OOT3D_S16(camera, 0x188) == 0) {
        goto return_input_direction;
    }

    OOT3D_S32(cameraState, 0x24) = 0;
    if (OOT3D_U32(camera, 0xD8) != 0) {
        const uintptr_t player = OOT3D_U32(camera, 0xD8);
        Oot3dActorPosRot currentPlayer;
        Oot3dActorVec3f raycastPosition;
        float playerGroundY;
        float playerSpeed;
        s32 bgId;

        Actor_GetWorldPosShapeRot(
            &currentPlayer,
            GuestPtr<const Oot3dActor>(player)
        );
        playerSpeed = OLib_Vec3fDistXZ(
            &currentPlayer.pos,
            GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0xDC))
        );
        OOT3D_F32(camera, 0x120) = playerSpeed;
        OOT3D_F32(camera, 0x128) = OLib_ClampMaxDist(
            playerSpeed /
                (FUN_00479718(player) *
                 (float)OOT3D_S16(playerState, 0x1A4) * 0.01f),
            1.0f
        );
        OOT3D_F32(camera, 0x138) =
            currentPlayer.pos.x - OOT3D_F32(camera, 0xDC);
        OOT3D_F32(camera, 0x13C) =
            currentPlayer.pos.y - OOT3D_F32(camera, 0xE0);
        OOT3D_F32(camera, 0x140) =
            currentPlayer.pos.z - OOT3D_F32(camera, 0xE4);

        if ((OOT3D_U8(DAT_002d88bc, mainPlayer) & 0x10) == 0) {
            raycastPosition = currentPlayer.pos;
            raycastPosition.y += Player_GetHeight(GuestPtr<const void>(player));
            playerGroundY = BgCheck_EntityRaycastFloor5(
                GuestPtr<Oot3dPlayState>(play),
                GuestPtr<void>(play + 0xA98),
                GuestPtr<u32>(cameraState + 0xA8),
                &bgId,
                GuestPtr<Oot3dActor>(player),
                &raycastPosition
            );
        } else {
            const uintptr_t actorFloorPoly = OOT3D_U32(player, 0x7C);

            playerGroundY = OOT3D_F32(player, 0x84);
            OOT3D_U32(cameraState, 0xA8) = (u32)actorFloorPoly;
            bgId = OOT3D_U8(player, 0x81);
        }

        if (playerGroundY == -32000.0f) {
            OOT3D_F32(camera, 0x150) = 0.0f;
            OOT3D_F32(camera, 0x154) = 1.0f;
            OOT3D_F32(camera, 0x158) = 0.0f;
            OOT3D_S32(cameraState, 0x9C)++;
        } else {
            const uintptr_t floorPoly = OOT3D_U32(cameraState, 0xA8);

            OOT3D_F32(camera, 0x150) =
                (float)OOT3D_S16(floorPoly, 0xA) * std::bit_cast<float>(0x38000100U);
            OOT3D_F32(camera, 0x154) =
                (float)OOT3D_S16(floorPoly, 0xC) * std::bit_cast<float>(0x38000100U);
            OOT3D_F32(camera, 0x158) =
                (float)OOT3D_S16(floorPoly, 0xE) * std::bit_cast<float>(0x38000100U);
            OOT3D_S16(camera, 0x18E) = (s16)bgId;
            OOT3D_F32(camera, 0x14C) = playerGroundY;
            OOT3D_S32(cameraState, 0x9C) = 0;
        }

        WriteGuestMemory(
            OOT3D_ADDR(camera, 0xDC), &currentPlayer, 0x12);
        if (OOT3D_S32(cameraState, 0x9C) < 200) {
            u16 stateFlags;

            if (OOT3D_S16(camera, 0x188) == 7) {
                Camera_CheckWater(camera);
                OOT3D_U16(camera, 0x19A) &= (u16)~1;
                if ((OOT3D_U8(play, 0x4C32) == 3) ||
                    (OOT3D_U8(play, 0x4C37) != 0)) {
                    OOT3D_U16(camera, 0x19A) |= 1;
                }
            }

            stateFlags = OOT3D_U16(camera, 0x194);
            if ((stateFlags & 4) == 0) {
                OOT3D_S16(camera, 0x19E) = -1;
            }
            if (((stateFlags & 1) != 0) &&
                ((stateFlags & 4) != 0) &&
                ((stateFlags & 0x400) == 0) &&
                (((stateFlags & 0x200) == 0) ||
                 (OOT3D_U8(mainPlayer, 0x1A7) == 1)) &&
                ((stateFlags & 0x8000) == 0) &&
                (playerGroundY != -32000.0f)) {
                const uintptr_t floorPoly = OOT3D_U32(cameraState, 0xA8);
                s32 bgCamIndex;

                Actor_GetWorldPosShapeRot(
                    &currentPlayer,
                    GuestPtr<const Oot3dActor>(player)
                );
                bgCamIndex = FUN_0047bff8(
                    play + 0xA98,
                    floorPoly,
                    bgId
                );
                if (FUN_002d064c(play + 0xA98, bgCamIndex, bgId) == 0) {
                    bgCamIndex = -1;
                }
                if (bgCamIndex != -1) {
                    OOT3D_S16(camera, 0x1A0) = (s16)bgId;
                    if (bgId == 0x32) {
                        OOT3D_S16(camera, 0x19E) = (s16)bgCamIndex;
                    }
                }
            }

            if ((OOT3D_S16(camera, 0x19E) != -1) &&
                (std::fabs(currentPlayer.pos.y - playerGroundY) < 2.0f) &&
                (((stateFlags & 0x200) == 0) ||
                 (OOT3D_U8(mainPlayer, 0x1A7) == 1))) {
                OOT3D_S16(camera, 0x18E) =
                    OOT3D_S16(camera, 0x1A0);
                Camera_ChangeDataIdx(camera);
                OOT3D_S16(camera, 0x19E) = -1;
            }
        }
    }

    if (OOT3D_S16(camera, 0x188) == 1) {
        goto return_input_direction;
    }

    OOT3D_S16(camera, 0x192) = 0;
    OOT3D_U16(camera, 0x194) =
        (OOT3D_U16(camera, 0x194) & (u16)~0x420) | 0x10;
    if (OOT3D_S32(cameraState, 0x9C) < 200) {
        const u32 setting = OOT3D_U16(camera, 0x18A) & 0xFF;
        const u32 mode = OOT3D_U16(camera, 0x18C) & 0xFF;
        const uintptr_t modes =
            OOT3D_U32(DAT_002d88c8 + setting * 8, 4);
        const s16 functionIndex = OOT3D_S16(modes + mode * 8, 0);
        const std::uint32_t cameraFunction =
            OOT3D_U32(DAT_002d8c20, functionIndex * 4);

        InvokeDynamicCameraFunction(cameraFunction, camera);
    } else if (OOT3D_U32(camera, 0xD8) != 0) {
        OLib_Vec3fDiffToVecSphGeo(
            &eyeAtAngle,
            GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0x80)),
            GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0x8C))
        );
        Camera_CalcAtDefault(GuestPtr<void>(camera), &eyeAtAngle, 0.0f, 0);
    }

    if (OOT3D_S16(camera, 0x188) == 7) {
        const s32 gameMode = OOT3D_S32(DAT_002d8c28, 0x4E4);

        if ((gameMode == 0) || (gameMode == 3)) {
            s16 interfaceField;

            if ((OOT3D_U8(DAT_002d8c2c, play) == 0) ||
                (OOT3D_U16(DAT_002d8c30, play) == 0)) {
                if ((OOT3D_S32(cameraState, 0x28) == 0) ||
                    (OOT3D_S16(camera, 0x1AC) != 0)) {
                    if (OOT3D_U8(DAT_002d8c38, play) == 0) {
                        if (oot3d_get_flag_22a0(GuestPtr<const void>(play)) == 0) {
                            interfaceField =
                                (s16)OOT3D_S32(cameraState, 0x14);
                        } else {
                            interfaceField = 0x3200;
                            OOT3D_S32(cameraState, 0x14) = 0x3200;
                        }
                    } else {
                        interfaceField = -0xE00;
                        OOT3D_S32(cameraState, 0x14) = 0xF200;
                    }
                } else {
                    OOT3D_S32(cameraState, 0x28)--;
                    interfaceField = 0x3200;
                    OOT3D_S32(cameraState, 0x14) = 0x3200;
                }
                Camera_UpdateInterface(interfaceField);
            } else {
                OOT3D_S32(cameraState, 0x14) = 0x3200;
                Camera_UpdateInterface(0x3200);
                OOT3D_S32(cameraState, 0x28) =
                    (s32)(30.0f /
                          (float)OOT3D_S16(playerState, 0x110) +
                          0.5f);
            }
        } else {
            OOT3D_S32(cameraState, 0x14) = 0;
            Camera_UpdateInterface(0);
        }
    }

    if (OOT3D_S16(camera, 0x188) == 3) {
        goto return_input_direction;
    }

    if ((FUN_004787e8(camera, &shake) != 0) &&
        (OOT3D_S16(camera, 0x18A) != 0x38)) {
        viewAt.x = OOT3D_F32(camera, 0x80) + shake.atOffset.x;
        viewAt.y = OOT3D_F32(camera, 0x84) + shake.atOffset.y;
        viewAt.z = OOT3D_F32(camera, 0x88) + shake.atOffset.z;
        viewEye.x = OOT3D_F32(camera, 0x8C) + shake.eyeOffset.x;
        viewEye.y = OOT3D_F32(camera, 0x90) + shake.eyeOffset.y;
        viewEye.z = OOT3D_F32(camera, 0x94) + shake.eyeOffset.z;
        OLib_Vec3fDiffToVecSphGeo(&eyeAtAngle, &viewEye, &viewAt);
        viewUp = Camera_CalcUpFromPitchYawRoll(
            eyeAtAngle.pitch + shake.upPitchOffset,
            eyeAtAngle.yaw + shake.upYawOffset,
            OOT3D_S16(camera, 0x1A2)
        );
        viewFov =
            OOT3D_F32(camera, 0x144) +
            (float)shake.fovOffset * 0.00549325f;
    } else {
        viewAt = ReadGuestPod<Oot3dActorVec3f>(
            OOT3D_ADDR(camera, 0x80));
        viewEye = ReadGuestPod<Oot3dActorVec3f>(
            OOT3D_ADDR(camera, 0x8C));
        OLib_Vec3fDiffToVecSphGeo(&eyeAtAngle, &viewEye, &viewAt);
        viewUp = Camera_CalcUpFromPitchYawRoll(
            eyeAtAngle.pitch,
            eyeAtAngle.yaw,
            OOT3D_S16(camera, 0x1A2)
        );
        viewFov = OOT3D_F32(camera, 0x144);
    }

    if ((OOT3D_U16(camera, 0x1A4) & 4) != 0) {
        OOT3D_U16(camera, 0x1A4) &= (u16)~4;
        viewUp = ReadGuestPod<Oot3dActorVec3f>(
            OOT3D_ADDR(camera, 0x98));
    } else {
        WriteGuestPod(OOT3D_ADDR(camera, 0x98), viewUp);
    }
    WriteGuestPod(OOT3D_ADDR(camera, 0xB0), shake.eyeOffset);

    if (OOT3D_U8(DAT_002d8c40, 0xF) == 0) {
        Oot3dCameraApplyInputOffset(camera, &viewAt, &viewEye);
    }
    Oot3dCameraUpdateDistortion(camera, play, cameraState);

    if ((OOT3D_U16(play, 0x104) == 0x51) &&
        (OOT3D_F32(camera, 0x144) < 59.0f)) {
        FUN_004710f8(play + 0x188, 0.79f);
    } else {
        FUN_004710f8(play + 0x188, 1.0f);
    }
    OOT3D_F32(play, 0x198) = viewFov;
    FUN_002d77dc(play + 0x188, &viewEye, &viewAt, &viewUp);

    {
        float distance = OOT3D_F32(camera, 0xD0);

        if (OOT3D_U8(camera, 0x1B6) != 0) {
            float maximumDistance;

            if (OOT3D_S16(camera, 0x18C) == 6) {
                maximumDistance = 50.0f;
            } else {
                const float deltaX =
                    OOT3D_F32(play, 0x1B8) -
                    OOT3D_F32(play, 0x1C4);
                const float deltaY =
                    OOT3D_F32(play, 0x1BC) -
                    OOT3D_F32(play, 0x1C8);
                const float deltaZ =
                    OOT3D_F32(play, 0x1C0) -
                    OOT3D_F32(play, 0x1CC);

                maximumDistance =
                    TargetSqrt(
                        deltaX * deltaX +
                        deltaY * deltaY +
                        deltaZ * deltaZ
                    ) * 0.75f;
                if (maximumDistance > 50.0f) {
                    maximumDistance = 50.0f;
                }
            }

            FUN_0047ac5c(
                play,
                play + 0x208C,
                GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0x8C)),
                &distance
            );
            if (distance > maximumDistance) {
                distance = maximumDistance;
            }
            distance = FUN_0047cc14(
                play + 0xA98,
                GuestPtr<const Oot3dActorVec3f>(OOT3D_ADDR(camera, 0x8C)),
                distance
            );
        }
        if (distance <= 1.1920929e-7f) {
            distance = 1.1920929e-7f;
        }
        OOT3D_F32(play, 0x1B0) = distance;
    }

    OOT3D_U8(play, 0x362) = OOT3D_U8(camera, 0x1B6);
    OOT3D_S16(camera, 0x182) = eyeAtAngle.pitch;
    OOT3D_S16(camera, 0x184) = eyeAtAngle.yaw;
    OOT3D_S16(camera, 0x186) = 0;
    if (OOT3D_S32(cameraState, 0x24) == 0) {
        OOT3D_S16(camera, 0x17C) = eyeAtAngle.pitch;
        OOT3D_S16(camera, 0x17E) = eyeAtAngle.yaw;
        OOT3D_S16(camera, 0x180) = 0;
    }

return_input_direction:
    result.x = OOT3D_S16(camera, 0x17C);
    result.y = OOT3D_S16(camera, 0x17E);
    result.z = OOT3D_S16(camera, 0x180);
    return result;
}

#undef OOT3D_F32
#undef OOT3D_U32
#undef OOT3D_S32
#undef OOT3D_U16
#undef OOT3D_S16
#undef OOT3D_U8
#undef OOT3D_ADDR
#undef DAT_002d8c40
#undef DAT_002d8c38
#undef DAT_002d8c30
#undef DAT_002d8c2c
#undef DAT_002d8c28
#undef DAT_002d8c20
#undef DAT_002d88c8
#undef DAT_002d88bc
#undef DAT_002d88b4
#undef DAT_002d88a8

} // namespace

void Camera_Update(
    std::uint32_t resultAddress, std::uint32_t cameraAddress) {
    const Oot3dVec3s result = Camera_UpdateImpl(cameraAddress);
    WriteGuestMemory(resultAddress, &result, sizeof(result));
}

} // namespace Oot3dSourceCameraUpdate
