#pragma once

#include <stdint.h>

typedef struct Oot3dTitleIntroAssetSourceRow {
    uint16_t assetIndex;
    const char* role;
    const char* romfsPath;
    uint8_t exists;
    uint32_t fileSize;
    uint16_t zarFileCount;
    uint16_t cmbCount;
    uint16_t csabCount;
    uint16_t cmabCount;
    uint16_t qdbCount;
    uint16_t ctxbCount;
    uint16_t facebCount;
    const char* codeBinStringAddresses;
    const char* primarySummary;
} Oot3dTitleIntroAssetSourceRow;

typedef struct Oot3dTitleIntroQdbSourceRow {
    uint16_t qdbIndex;
    uint16_t assetIndex;
    uint16_t embeddedIndex;
    uint8_t isEponaTitleDemoCandidate;
    uint32_t size;
    uint32_t commandCount;
    int32_t endFrame;
    uint32_t decodedSize;
    uint32_t commandRefStart;
    uint32_t commandRefCount;
    const char* archivePath;
    const char* embeddedName;
    const char* commandIds;
} Oot3dTitleIntroQdbSourceRow;

typedef struct Oot3dTitleIntroQdbCommandRow {
    uint32_t qdbCommandIndex;
    uint16_t assetIndex;
    uint16_t embeddedIndex;
    uint16_t localCommandIndex;
    uint32_t commandOffset;
    uint32_t commandId;
    uint32_t cameraPointCount;
    uint32_t totalSize;
    const char* archivePath;
    const char* embeddedName;
    const char* commandName;
    const char* category;
} Oot3dTitleIntroQdbCommandRow;

typedef struct Oot3dTitleIntroActorCueRow {
    uint32_t actorCueIndex;
    uint16_t qdbIndex;
    uint32_t qdbCommandIndex;
    uint32_t cueCommandId;
    uint16_t cueIndex;
    int16_t cueId;
    int16_t startFrame;
    int16_t endFrame;
    int16_t rotX;
    int16_t rotY;
    int16_t rotZ;
    int32_t startX;
    int32_t startY;
    int32_t startZ;
    int32_t endX;
    int32_t endY;
    int32_t endZ;
    float normalX;
    float normalY;
    float normalZ;
    const char* archivePath;
    const char* embeddedName;
} Oot3dTitleIntroActorCueRow;

typedef struct Oot3dTitleIntroActorInitSourceRow {
    uint16_t actorInitIndex;
    uint32_t actorInitFileOffset;
    uint16_t actorId;
    uint8_t actorCategory;
    uint32_t flags;
    uint16_t objectId;
    uint16_t instanceSize;
    uint32_t initFunction;
    uint32_t destroyFunction;
    uint32_t updateFunction;
    uint32_t drawFunction;
    const char* actorName;
    const char* objectName;
    const char* decodeStatus;
    const char* basis;
} Oot3dTitleIntroActorInitSourceRow;

typedef struct Oot3dTitleIntroActorScaleRow {
    uint16_t scaleIndex;
    const char* actorRole;
    const char* actorName;
    const char* archiveRole;
    uint32_t initFunction;
    uint32_t updateFunction;
    uint32_t drawFunction;
    uint32_t actorSetScaleCallsite;
    uint32_t actorSetScaleFunction;
    uint32_t scaleLiteralAddress;
    float actorScale;
    uint32_t gravityLiteralAddress;
    float gravity;
    uint32_t shadowYOffsetLiteralAddress;
    float shadowYOffset;
    uint32_t shadowScaleLiteralAddress;
    float shadowScale;
    uint32_t focusYOffsetLiteralAddress;
    float focusYOffset;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* decodeStatus;
} Oot3dTitleIntroActorScaleRow;

typedef struct Oot3dTitleIntroActorAnimationRow {
    uint16_t animationIndex;
    const char* actorRole;
    const char* actorName;
    const char* assetRole;
    const char* archivePath;
    uint16_t cmbTypeIndex;
    uint16_t cmbFileIndex;
    const char* cmbName;
    uint32_t animationTablePointerLiteralAddress;
    uint32_t animationTableOuterRuntimeAddress;
    uint16_t animationTableOuterIndex;
    uint32_t initAnimationTableRuntimeAddress;
    uint16_t initAnimationSlot;
    uint16_t initCsabTypeIndex;
    uint16_t initCsabFileIndex;
    const char* initCsabName;
    uint16_t titleVisualCsabTypeIndex;
    uint16_t titleVisualCsabFileIndex;
    const char* titleVisualCsabName;
    uint32_t actorInitFunction;
    uint32_t actorUpdateFunction;
    uint32_t actorDrawFunction;
    uint32_t zarGetCmbByIndexCallsite;
    uint32_t animationPlayOnceCallsite;
    uint32_t titleCueSemanticReferenceFunction;
    const char* titleCueRole;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* decodeStatus;
} Oot3dTitleIntroActorAnimationRow;

typedef struct Oot3dTitleIntroActorMotionAnimationRow {
    uint16_t motionIndex;
    const char* actorRole;
    const char* actorName;
    const char* assetRole;
    const char* archivePath;
    uint16_t horseTypeIndex;
    uint16_t actionFieldOffset;
    uint16_t speedFieldOffset;
    uint16_t animationIndexFieldOffset;
    uint16_t horseTypeFieldOffset;
    uint16_t skelAnimeFieldOffset;
    uint32_t sourceFunction;
    uint32_t tablePointerLiteralAddress;
    uint32_t animationTableOuterRuntimeAddress;
    uint32_t animationTableRuntimeAddress;
    uint32_t zeroSpeedLiteralAddress;
    float zeroSpeed;
    uint32_t walkThresholdLiteralAddress;
    float walkThreshold;
    uint32_t fastThresholdLiteralAddress;
    float fastThreshold;
    uint32_t basePlaySpeedScaleLiteralAddress;
    float basePlaySpeedScale;
    uint32_t idlePlaySpeedScaleLiteralAddress;
    float idlePlaySpeedScale;
    uint32_t walkPlaySpeedScaleLiteralAddress;
    float walkPlaySpeedScale;
    uint32_t trotPlaySpeedScaleLiteralAddress;
    float trotPlaySpeedScale;
    uint32_t fastPlaySpeedScaleLiteralAddress;
    float fastPlaySpeedScale;
    uint32_t audioIdLiteralAddress;
    uint32_t audioId;
    uint32_t audioFreqPointerAddress;
    uint32_t audioFreqRuntimeAddress;
    uint32_t audioVolPointerAddress;
    uint32_t audioVolRuntimeAddress;
    uint32_t animationChangeSameStateCallsite;
    uint32_t animationChangeChangedStateCallsite;
    uint16_t idleAnimationIndex;
    uint16_t idleCsabTypeIndex;
    uint16_t idleCsabFileIndex;
    const char* idleCsabName;
    uint16_t walkAnimationIndex;
    uint16_t walkCsabTypeIndex;
    uint16_t walkCsabFileIndex;
    const char* walkCsabName;
    uint16_t trotAnimationIndex;
    uint16_t trotCsabTypeIndex;
    uint16_t trotCsabFileIndex;
    const char* trotCsabName;
    uint16_t fastAnimationIndex;
    uint16_t fastCsabTypeIndex;
    uint16_t fastCsabFileIndex;
    const char* fastCsabName;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* decodeStatus;
} Oot3dTitleIntroActorMotionAnimationRow;

typedef struct Oot3dTitleIntroHorseStateRouteRow {
    uint16_t stateRouteIndex;
    const char* routeRole;
    const char* actorRole;
    const char* actorName;
    const char* assetRole;
    const char* archivePath;
    uint32_t sourceFunction;
    const char* sourceExport;
    uint16_t horseTypeIndex;
    uint16_t actionFieldOffset;
    uint16_t speedFieldOffset;
    uint16_t animationIndexFieldOffset;
    uint16_t horseTypeFieldOffset;
    uint16_t skelAnimeFieldOffset;
    uint16_t followTimerFieldOffset;
    uint16_t actionValue;
    const char* animationIndices;
    uint32_t tablePointerLiteralAddress;
    uint32_t animationTableOuterRuntimeAddress;
    uint32_t animationTableRuntimeAddress;
    const char* primaryLiteralAddresses;
    const char* primaryLiteralValues;
    float forcedSpeed;
    uint32_t updateArg;
    uint32_t gallopControlBlockRuntimeAddress;
    float gallopPlaySpeedScale;
    float gallopPlaySpeedSwitch;
    float gallopPlaySpeedMin;
    float gallopPlaySpeedMax;
    float gallopBrakeInputMagnitude;
    float gallopDownshiftSpeed;
    uint16_t gallopFastAnimationIndex;
    uint16_t gallopFastCsabTypeIndex;
    uint16_t gallopFastCsabFileIndex;
    const char* gallopFastCsabName;
    uint16_t gallopCarrotAnimationIndex;
    uint16_t gallopCarrotCsabTypeIndex;
    uint16_t gallopCarrotCsabFileIndex;
    const char* gallopCarrotCsabName;
    const char* resolvedCsabs;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* unresolvedFollowup;
    const char* decodeStatus;
} Oot3dTitleIntroHorseStateRouteRow;

typedef struct Oot3dTitleIntroHorseCutsceneActionRouteRow {
    uint16_t actionRouteIndex;
    const char* routeRole;
    const char* actorRole;
    const char* archivePath;
    uint16_t actionId;
    uint16_t substate;
    uint8_t resetPositionOnEntry;
    uint32_t dispatchFunction;
    uint32_t actionMapRuntimeAddress;
    uint32_t initTableRuntimeAddress;
    uint32_t updateTableRuntimeAddress;
    uint32_t initFunction;
    uint32_t updateFunction;
    uint32_t animationTableOuterRuntimeAddress;
    uint32_t animationTableRuntimeAddress;
    uint16_t initialAnimationIndex;
    uint16_t initialCsabTypeIndex;
    uint16_t initialCsabFileIndex;
    uint16_t initialCsabMaxFrame;
    const char* initialCsabName;
    uint32_t initialChangeModeInstructionAddress;
    uint16_t initialChangeMode;
    uint32_t initialMorphLiteralAddress;
    float initialMorphFrames;
    uint16_t alternateAnimationIndex;
    uint16_t alternateCsabTypeIndex;
    uint16_t alternateCsabFileIndex;
    uint16_t alternateCsabMaxFrame;
    const char* alternateCsabName;
    uint16_t completionAnimationIndex;
    uint16_t completionCsabTypeIndex;
    uint16_t completionCsabFileIndex;
    uint16_t completionCsabMaxFrame;
    const char* completionCsabName;
    uint16_t selectorWordIndex;
    uint32_t selectorBits;
    uint32_t playSpeedScaleLiteralAddress;
    float playSpeedScale;
    uint32_t fixedSpeedLiteralAddress;
    float fixedSpeed;
    uint32_t yawStepLiteralAddress;
    uint16_t yawStep;
    float targetEpsilon;
    float completionPlaySpeed;
    float completionMorphFrames;
    uint32_t completionFirstModeInstructionAddress;
    uint16_t completionFirstMode;
    uint32_t completionLoopModeInstructionAddress;
    uint16_t completionLoopMode;
    const char* sourceEvidence;
    const char* decodeStatus;
} Oot3dTitleIntroHorseCutsceneActionRouteRow;

typedef struct Oot3dTitleIntroSkelAnimeTimingRow {
    uint16_t timingIndex;
    const char* timingRole;
    uint16_t changeMode;
    uint16_t updateMode;
    uint32_t setUpdateFunction;
    uint32_t updateFunction;
    uint32_t updateScaleLiteralAddress;
    float updateScale;
    uint32_t globalContextPointerAddress;
    uint16_t globalUpdateRateOffset;
    uint32_t updateRateInitializerFunction;
    uint32_t updateRateInitializerInstructionAddress;
    uint16_t globalUpdateRate;
    const char* terminalBehavior;
    const char* sourceEvidence;
    const char* decodeStatus;
} Oot3dTitleIntroSkelAnimeTimingRow;

typedef struct Oot3dTitleIntroMountedPlayerAnimationFrameRow {
    uint16_t frameRouteIndex;
    const char* frameRole;
    uint32_t frameFunction;
    uint32_t frameLoadInstructionAddress;
    uint32_t mountedPlayerActionFunction;
    uint32_t frameStoreInstructionAddress;
    uint16_t horseAnimationIndexOffset;
    uint16_t horseAnimationFrameOffset;
    uint16_t playerSkelAnimeOffset;
    uint16_t playerCurrentFrameOffset;
    uint32_t scaledHorseAnimationIndexMask;
    uint32_t frameScaleLiteralAddress;
    float frameScale;
    uint32_t frameBiasLiteralAddress;
    float frameBias;
    uint8_t returnUnmatchedHorseAnimationFrame;
    const char* quantization;
    const char* unmatchedHorseAnimationBehavior;
    const char* sourceEvidence;
    const char* decodeStatus;
} Oot3dTitleIntroMountedPlayerAnimationFrameRow;

typedef struct Oot3dTitleIntroLinkChildStateRouteRow {
    uint16_t stateRouteIndex;
    const char* routeRole;
    const char* actorRole;
    const char* actorName;
    const char* assetRole;
    const char* archivePath;
    uint32_t updateFunction;
    uint32_t initFunction;
    uint32_t drawFunction;
    uint16_t actionFieldOffset;
    uint16_t animationIndexFieldOffset;
    uint16_t speedFieldOffset;
    uint16_t skelAnimeFieldOffset;
    uint32_t actionTablePointerLiteralAddress;
    uint32_t actionTableRuntimeAddress;
    uint16_t actionSlot;
    uint32_t handlerFunction;
    uint32_t animationTablePointerLiteralAddress;
    uint32_t animationTableRuntimeAddress;
    const char* expectedAnimationIndices;
    const char* resolvedCsabs;
    const char* expectedSpeedValues;
    const char* n64ReferenceAction;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* unresolvedFollowup;
    const char* decodeStatus;
} Oot3dTitleIntroLinkChildStateRouteRow;

typedef struct Oot3dTitleIntroLinkBoyPlayerActionRow {
    uint16_t playerActionIndex;
    uint32_t actorCueIndex;
    const char* actorRole;
    const char* actorName;
    const char* assetRole;
    const char* archivePath;
    const char* cmbName;
    const char* titleVisualCsabName;
    uint16_t qdbIndex;
    uint32_t qdbCommandIndex;
    const char* qdbArchivePath;
    const char* qdbEmbeddedName;
    uint32_t cueCommandId;
    uint16_t cueIndex;
    int16_t cueId;
    int16_t startFrame;
    int16_t endFrame;
    int16_t durationFrames;
    int16_t rotX;
    int16_t rotY;
    int16_t rotZ;
    int32_t startX;
    int32_t startY;
    int32_t startZ;
    int32_t endX;
    int32_t endY;
    int32_t endZ;
    int32_t deltaX;
    int32_t deltaY;
    int32_t deltaZ;
    float normalX;
    float normalY;
    float normalZ;
    const char* cueRole;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* unresolvedFollowup;
    const char* decodeStatus;
} Oot3dTitleIntroLinkBoyPlayerActionRow;

typedef struct Oot3dTitleIntroLogoComponentRow {
    uint16_t componentIndex;
    uint16_t assetIndex;
    uint16_t handleFieldOffset;
    uint16_t alphaFieldOffset;
    uint16_t cmbIndexJpeu;
    uint16_t csabIndexJpeu;
    uint16_t cmbIndexUs;
    uint16_t csabIndexUs;
    uint16_t cmabIndex;
    uint16_t materialAnimationRuntimeOwnerFieldOffset;
    uint16_t materialAnimationRuntimeLoopFieldOffset;
    uint8_t materialAnimationRuntimeLoopOverrideValid;
    uint8_t materialAnimationRuntimeLoopMode;
    uint32_t materialAnimationRuntimeInitFunction;
    uint32_t materialAnimationRuntimeStepFunction;
    const char* componentRole;
    const char* archivePath;
    const char* cmbNameJpeu;
    const char* csabNameJpeu;
    const char* cmbNameUs;
    const char* csabNameUs;
    const char* cmabName;
    const char* materialAnimationBindingBasis;
    const char* bindingBasis;
} Oot3dTitleIntroLogoComponentRow;

typedef struct Oot3dTitleIntroLogoDrawRow {
    uint16_t drawIndex;
    uint16_t submitOrder;
    uint16_t componentIndex;
    uint16_t handleFieldOffset;
    uint16_t alphaFieldOffset;
    uint16_t effectAlphaFieldOffset;
    uint32_t drawFunction;
    uint32_t colorPointerAddress;
    uint32_t colorRuntimeAddress;
    uint32_t lightBlockPointerAddress;
    uint32_t lightBlockRuntimeAddress;
    uint32_t rendererFlagPointerAddress;
    uint32_t rendererFlagRuntimeAddress;
    uint32_t renderContextPointerAddress;
    uint32_t renderContextRuntimeAddress;
    uint32_t alternateRenderContextPointerAddress;
    uint32_t alternateRenderContextRuntimeAddress;
    uint32_t materialHandleFunction;
    uint32_t materialSlotSelectFunction;
    uint32_t materialColorApplyFunction;
    uint32_t matrixCopyFunction;
    uint32_t submitFunction;
    uint32_t lightConfigResetFunction;
    uint32_t lightConfigApplyFunction;
    uint32_t lightVectorApplyFunction;
    float alphaScale;
    float baseTranslateZ;
    float smallDepthOffset;
    float copyrightTranslateY;
    float effectVectorDoubleScale;
    float effectVectorHalfScale;
    float effectVectorBias;
    float baseColorR;
    float baseColorG;
    float baseColorB;
    float baseColorA;
    float matrix00;
    float matrix01;
    float matrix02;
    float matrix03;
    float matrix10;
    float matrix11;
    float matrix12;
    float matrix13;
    float matrix20;
    float matrix21;
    float matrix22;
    float matrix23;
    float matrix30;
    float matrix31;
    float matrix32;
    float matrix33;
    const char* componentRole;
    const char* matrixRole;
    const char* matrixSourceAddresses;
    const char* lightBlockRowMajor;
    const char* visibilityCondition;
    const char* drawBasis;
    const char* decodeStatus;
} Oot3dTitleIntroLogoDrawRow;

typedef struct Oot3dTitleIntroLogoDrawContextRow {
    uint16_t contextIndex;
    const char* contextRole;
    uint32_t drawFunction;
    uint32_t submitFunction;
    uint32_t rendererFlagPointerAddress;
    uint32_t rendererFlagRuntimeAddress;
    uint32_t renderContextPointerAddress;
    uint32_t renderContextRuntimeAddress;
    uint32_t alternateRenderContextPointerAddress;
    uint32_t alternateRenderContextRuntimeAddress;
    uint32_t globalContextRuntimeAddress;
    uint32_t submitManagerRuntimeAddress;
    uint16_t globalContextSubmitManagerOffset;
    uint32_t submitManagerConstructorFunction;
    uint32_t submitManagerVtableAddress;
    uint32_t submitManagerStorageSize;
    uint16_t smallQueueCountOffset;
    uint16_t smallQueueStorageOffset;
    uint16_t smallQueueCapacity;
    uint16_t smallQueueRecordStride;
    uint16_t smallQueueRecordStateByteOffset;
    uint8_t smallQueueRecordStateByteValue;
    uint32_t smallQueueRecordWriteFunction;
    uint32_t smallQueueDrainFunction;
    uint32_t pass0DrainFunction;
    uint32_t pass1DrainFunction;
    uint32_t lazyGuardFunction;
    uint32_t lazyInitFunction;
    uint16_t drawHandleVtableSubmitSlotOffset;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* decodeStatus;
} Oot3dTitleIntroLogoDrawContextRow;

typedef struct Oot3dTitleIntroLogoUpdateRow {
    uint16_t updateIndex;
    uint16_t state;
    uint16_t substate;
    uint16_t nextState;
    uint16_t nextSubstate;
    uint16_t timerFieldOffset;
    int16_t timerInitialValue;
    uint16_t flagId;
    uint32_t literalAddress;
    float literalValue;
    float maxAlpha;
    float minAlpha;
    float mainAlphaStep;
    float titleTextEffectAlphaStep;
    float copyrightAlphaClamp;
    int16_t copyrightAlphaStepDefault;
    int16_t fadeOutAlphaStepDefault;
    int16_t transitionCopyrightAlphaStep;
    int16_t transitionFadeOutAlphaStep;
    uint32_t initFunction;
    uint32_t updateFunction;
    uint32_t flagsGetEnvFunction;
    uint32_t getCsabByIndexFunction;
    uint32_t setCsabFunction;
    uint32_t setCsabFrameFunction;
    uint32_t setTitleAnimStateFunction;
    uint32_t audioCutsceneFlagFunction;
    uint32_t audioPlaySoundFunction;
    const char* phaseRole;
    const char* alphaFieldOffsets;
    const char* alphaOperation;
    const char* alphaDeltaSource;
    const char* oot3dBasis;
    const char* n64Reference;
    const char* decodeStatus;
} Oot3dTitleIntroLogoUpdateRow;

extern const Oot3dTitleIntroAssetSourceRow gOot3dTitleIntroAssetSourceRows[];
extern const uint32_t gOot3dTitleIntroAssetSourceRowCount;
extern const Oot3dTitleIntroQdbSourceRow gOot3dTitleIntroQdbSourceRows[];
extern const uint32_t gOot3dTitleIntroQdbSourceRowCount;
extern const Oot3dTitleIntroQdbCommandRow gOot3dTitleIntroQdbCommandRows[];
extern const uint32_t gOot3dTitleIntroQdbCommandRowCount;
extern const Oot3dTitleIntroActorCueRow gOot3dTitleIntroActorCueRows[];
extern const uint32_t gOot3dTitleIntroActorCueRowCount;
extern const Oot3dTitleIntroActorInitSourceRow gOot3dTitleIntroActorInitSourceRows[];
extern const uint32_t gOot3dTitleIntroActorInitSourceRowCount;
extern const Oot3dTitleIntroActorScaleRow gOot3dTitleIntroActorScaleRows[];
extern const uint32_t gOot3dTitleIntroActorScaleRowCount;
extern const Oot3dTitleIntroActorAnimationRow gOot3dTitleIntroActorAnimationRows[];
extern const uint32_t gOot3dTitleIntroActorAnimationRowCount;
extern const Oot3dTitleIntroActorMotionAnimationRow gOot3dTitleIntroActorMotionAnimationRows[];
extern const uint32_t gOot3dTitleIntroActorMotionAnimationRowCount;
extern const Oot3dTitleIntroHorseStateRouteRow gOot3dTitleIntroHorseStateRouteRows[];
extern const uint32_t gOot3dTitleIntroHorseStateRouteRowCount;
extern const Oot3dTitleIntroHorseCutsceneActionRouteRow gOot3dTitleIntroHorseCutsceneActionRouteRows[];
extern const uint32_t gOot3dTitleIntroHorseCutsceneActionRouteRowCount;
extern const Oot3dTitleIntroSkelAnimeTimingRow gOot3dTitleIntroSkelAnimeTimingRows[];
extern const uint32_t gOot3dTitleIntroSkelAnimeTimingRowCount;
extern const Oot3dTitleIntroMountedPlayerAnimationFrameRow gOot3dTitleIntroMountedPlayerAnimationFrameRows[];
extern const uint32_t gOot3dTitleIntroMountedPlayerAnimationFrameRowCount;
extern const Oot3dTitleIntroLinkChildStateRouteRow gOot3dTitleIntroLinkChildStateRouteRows[];
extern const uint32_t gOot3dTitleIntroLinkChildStateRouteRowCount;
extern const Oot3dTitleIntroLinkBoyPlayerActionRow gOot3dTitleIntroLinkBoyPlayerActionRows[];
extern const uint32_t gOot3dTitleIntroLinkBoyPlayerActionRowCount;
extern const Oot3dTitleIntroLogoComponentRow gOot3dTitleIntroLogoComponentRows[];
extern const uint32_t gOot3dTitleIntroLogoComponentRowCount;
extern const Oot3dTitleIntroLogoDrawRow gOot3dTitleIntroLogoDrawRows[];
extern const uint32_t gOot3dTitleIntroLogoDrawRowCount;
extern const Oot3dTitleIntroLogoDrawContextRow gOot3dTitleIntroLogoDrawContextRows[];
extern const uint32_t gOot3dTitleIntroLogoDrawContextRowCount;
extern const Oot3dTitleIntroLogoUpdateRow gOot3dTitleIntroLogoUpdateRows[];
extern const uint32_t gOot3dTitleIntroLogoUpdateRowCount;

const Oot3dTitleIntroQdbSourceRow* Oot3d_TitleIntroSourceFindQdbRow(uint16_t qdbIndex);
const Oot3dTitleIntroAssetSourceRow* Oot3d_TitleIntroSourceFindAssetRowByRole(const char* role);
const Oot3dTitleIntroActorInitSourceRow* Oot3d_TitleIntroSourceFindActorInitRow(const char* actorName);
const Oot3dTitleIntroActorScaleRow* Oot3d_TitleIntroSourceFindActorScaleRow(const char* actorRole);
const Oot3dTitleIntroActorAnimationRow* Oot3d_TitleIntroSourceFindActorAnimationRow(const char* actorRole);
const Oot3dTitleIntroActorMotionAnimationRow* Oot3d_TitleIntroSourceFindActorMotionAnimationRow(const char* actorRole);
const Oot3dTitleIntroHorseStateRouteRow* Oot3d_TitleIntroSourceFindHorseStateRouteRow(const char* routeRole);
const Oot3dTitleIntroHorseCutsceneActionRouteRow* Oot3d_TitleIntroSourceFindHorseCutsceneActionRouteRow(uint16_t actionId);
const Oot3dTitleIntroSkelAnimeTimingRow* Oot3d_TitleIntroSourceFindSkelAnimeTimingRow(uint16_t changeMode);
const Oot3dTitleIntroMountedPlayerAnimationFrameRow* Oot3d_TitleIntroSourceFindMountedPlayerAnimationFrameRow(uint16_t horseAnimationIndex);
const char* Oot3d_TitleIntroSourceSelectLogoVariant(const char** outStatus);
