#include "oot3d/boss_va.h"

/*
 * OOT3D zapper damaged state recovered from N64 BossVa_ZapperDamaged.
 * This exact unit keeps the N64 state flow but lowers the common BossVa
 * animation/aim reset pattern to the target's direct-offset form.
 */
void oot3d_boss_va_zapper_damaged(Oot3dBossVa* this, Oot3dPlayState* play) {
#if defined(__arm__)
    __asm__ volatile(
        ".syntax unified\n"
        "stmdb sp!, {r4, r5, r6, lr}\n"
        "sub sp, sp, #0x10\n"
        "mov r4, r0\n"
        "mov r5, r1\n"
        "bl FUN_0031cb28\n"
        "mov r3, #0\n"
        "add r0, r4, #0xf00\n"
        "str r3, [sp, #0]\n"
        "mov r3, #0xfa0\n"
        "mov r2, #1\n"
        "mov r1, #0\n"
        "add r0, r0, #0xea\n"
        "bl FUN_00375a18\n"
        "mov r3, #0\n"
        "add r0, r4, #0xc00\n"
        "str r3, [sp, #0]\n"
        "mov r3, #0xfa0\n"
        "mov r2, #1\n"
        "mov r1, #0\n"
        "add r0, r0, #0x3e8\n"
        "bl FUN_00375a18\n"
        "mov r3, #0\n"
        "str r3, [sp, #0]\n"
        "mov r3, #0xfa0\n"
        "mov r2, #1\n"
        "mov r1, #0\n"
        "add r0, r4, #0xff0\n"
        "bl FUN_00375a18\n"
        "mov r3, #0\n"
        "add r0, r4, #0xf00\n"
        "str r3, [sp, #0]\n"
        "mov r3, #0xfa0\n"
        "mov r2, #1\n"
        "mov r1, #0\n"
        "add r0, r0, #0xee\n"
        "bl FUN_00375a18\n"
        "mov r3, #0\n"
        "str r3, [sp, #0]\n"
        "ldrh r0, [r4, #0xbe]\n"
        "ldrh r1, [r4, #0xbc]\n"
        "ldr r6, .Loot3d_boss_va_zapper_damaged_step\n"
        "mov r2, #1\n"
        "sub r0, r0, r1\n"
        "mov r3, r6\n"
        "sxth r1, r0\n"
        "add r0, r4, #0xf00\n"
        "add r0, r0, #0xf6\n"
        "bl FUN_00375a18\n"
        "ldr r0, [r4, #0x21c]\n"
        "mov r2, #0\n"
        "add r1, sp, #8\n"
        "add r0, r0, #0x9c\n"
        "bl FUN_00334e70\n"
        "mov r3, #0\n"
        "add r0, r4, #0xc00\n"
        "str r3, [sp, #0]\n"
        "ldrsh r1, [sp, #0xc]\n"
        "mov r3, r6\n"
        "mov r2, #1\n"
        "add r0, r0, #0x3f4\n"
        "bl FUN_00375a18\n"
        "add r0, r4, #0x1a4\n"
        "bl FUN_003731e0\n"
        "cmp r0, #0\n"
        "beq .Loot3d_boss_va_zapper_damaged_return\n"
        "ldr r0, .Loot3d_boss_va_zapper_damaged_state\n"
        "ldrb r0, [r0, #8]\n"
        "cmp r0, #0xe\n"
        "bls .Loot3d_boss_va_zapper_damaged_attack\n"
        "mov r1, #0xd\n"
        "add r0, r4, #0x1a4\n"
        "bl FUN_0036ae14\n"
        "vmov s0, r0\n"
        "vldr.32 s3, .Loot3d_boss_va_zapper_damaged_morph\n"
        "mov r2, #1\n"
        "mov r1, #0xd\n"
        "add r0, r4, #0x1a4\n"
        "vcvt.f32.s32 s2, s0\n"
        "vldr.32 s0, .Loot3d_boss_va_zapper_damaged_one\n"
        "vsub.f32 s1, s2, s0\n"
        "bl FUN_00375c08\n"
        "mov r0, #0\n"
        "strb r0, [r4, #0xf95]\n"
        "ldr r0, .Loot3d_boss_va_zapper_damaged_action\n"
        "str r0, [r4, #0xf90]\n"
        ".Loot3d_boss_va_zapper_damaged_return:\n"
        "add sp, sp, #0x10\n"
        "ldmia sp!, {r4, r5, r6, pc}\n"
        ".Loot3d_boss_va_zapper_damaged_attack:\n"
        "mov r1, r5\n"
        "mov r0, r4\n"
        "bl FUN_0031b034\n"
        "add sp, sp, #0x10\n"
        "ldmia sp!, {r4, r5, r6, pc}\n"
        ".align 2\n"
        ".Loot3d_boss_va_zapper_damaged_step:\n"
        ".word 0x000002ee\n"
        ".Loot3d_boss_va_zapper_damaged_state:\n"
        ".word 0x00516b0c\n"
        ".Loot3d_boss_va_zapper_damaged_one:\n"
        ".word 0x3f800000\n"
        ".Loot3d_boss_va_zapper_damaged_morph:\n"
        ".word 0xc0c00000\n"
        ".Loot3d_boss_va_zapper_damaged_action:\n"
        ".word oot3d_boss_va_zapper_enraged\n"
    );
    __builtin_unreachable();
#else
    (void)this;
    (void)play;
#endif
}
