# Both desktop and mobile consume the same verified translated source inventory.
# This is publisher tooling, never an end-user ROM preparation step.
function(triaevum_translated_title_sources directory output)
    set(manifest "${directory}/TITLE_SOURCE_MANIFEST.json")
    file(READ "${manifest}" metadata)
    string(JSON format GET "${metadata}" format)
    if(NOT format STREQUAL "triaevum_translated_title_source_v1")
        message(FATAL_ERROR "Unsupported translated source manifest")
    endif()
    string(JSON count LENGTH "${metadata}" files)
    if(count LESS 1)
        message(FATAL_ERROR "Translated source inventory is empty")
    endif()
    math(EXPR last "${count} - 1")
    set(sources)
    foreach(index RANGE 0 ${last})
        string(JSON name MEMBER "${metadata}" files ${index})
        if(NOT name MATCHES "^[A-Za-z0-9_]+\\.(cpp|h)$")
            message(FATAL_ERROR "Invalid translated source name: ${name}")
        endif()
        set(path "${directory}/${name}")
        string(JSON expected GET "${metadata}" files "${name}")
        file(SHA256 "${path}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "Translated source hash mismatch: ${name}")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
        if(name MATCHES "\\.cpp$")
            list(APPEND sources "${path}")
        endif()
    endforeach()
    if(NOT sources)
        message(FATAL_ERROR "Translated inventory contains no C++ sources")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    set(${output} "${sources}" PARENT_SCOPE)
endfunction()
