// Generated by generate_import.py from the immutable d5c2927 package.
// The source hash and target body identity are recorded in import_manifest.json.
#include "oot3d/player_update_common_owner.h"

#include <bit>
#include <cstdint>

#if defined(_MSC_VER)
#pragma fenv_access(on)
#else
#pragma STDC FENV_ACCESS ON
#endif

namespace Oot3dSourcePlayerUpdateCommon {

#define DAT_00251304 (GuestPtr<short>(ActiveLiterals().Words[0]))
#define DAT_00251308 (ActiveLiterals().Words[1])
#define DAT_0025130c (ActiveLiterals().Words[2])
#define DAT_00251310 (ActiveLiterals().Words[3])
#define DAT_00251314 (static_cast<int>(ActiveLiterals().Words[4]))
#define DAT_00251318 (static_cast<int>(ActiveLiterals().Words[5]))
#define DAT_0025131c (static_cast<int>(ActiveLiterals().Words[6]))
#define DAT_00251320 (static_cast<int>(ActiveLiterals().Words[7]))
#define DAT_00251324 (ActiveLiterals().Words[8])
#define DAT_00251328 (ActiveLiterals().Words[9])
#define DAT_0025132c (ActiveLiterals().Words[10])
#define DAT_00251330 (ActiveLiterals().Words[11])
#define DAT_00251334 (ActiveLiterals().Words[12])
#define DAT_00251338 (std::bit_cast<float>(ActiveLiterals().Words[13]))
#define DAT_0025133c (std::bit_cast<float>(ActiveLiterals().Words[14]))
#define DAT_00251340 (std::bit_cast<float>(ActiveLiterals().Words[15]))
#define DAT_00251344 (GuestPtr<uintptr_t>(ActiveLiterals().Words[16]))
#define DAT_00251348 (GuestPtr<uintptr_t>(ActiveLiterals().Words[17]))
#define DAT_0025134c (GuestPtr<undefined4>(ActiveLiterals().Words[18]))
#define DAT_00251350 (ActiveLiterals().Words[19])
#define DAT_00251354 (GuestPtr<undefined4>(ActiveLiterals().Words[20]))
#define DAT_00251358 (GuestPtr<uintptr_t>(ActiveLiterals().Words[21]))
#define DAT_0025135c (std::bit_cast<float>(ActiveLiterals().Words[22]))
#define DAT_00251360 (ActiveLiterals().Words[23])
#define DAT_00251364 (ActiveLiterals().Words[24])
#define DAT_00251368 (std::bit_cast<float>(ActiveLiterals().Words[25]))
#define DAT_00251714 (std::bit_cast<float>(ActiveLiterals().Words[26]))
#define DAT_00251718 (std::bit_cast<float>(ActiveLiterals().Words[27]))
#define DAT_0025171c (ActiveLiterals().Words[28])
#define DAT_00251720 (std::bit_cast<float>(ActiveLiterals().Words[29]))
#define DAT_00251724 (std::bit_cast<float>(ActiveLiterals().Words[30]))
#define DAT_00251728 (ActiveLiterals().Words[31])
#define DAT_0025172c (ActiveLiterals().Words[32])
#define DAT_00251730 (ActiveLiterals().Words[33])
#define DAT_00251734 (ActiveLiterals().Words[34])
#define DAT_00251738 (ActiveLiterals().Words[35])
#define DAT_0025173c (ActiveLiterals().Words[36])
#define DAT_00251740 (ActiveLiterals().Words[37])
#define DAT_00251744 (ActiveLiterals().Words[38])
#define DAT_00251cd4 (static_cast<int>(ActiveLiterals().Words[39]))
#define DAT_00251cd8 (static_cast<int>(ActiveLiterals().Words[40]))
#define DAT_00251cdc (static_cast<int>(ActiveLiterals().Words[41]))
#define DAT_00251ce0 (static_cast<int>(ActiveLiterals().Words[42]))
#define DAT_00251ce4 (static_cast<int>(ActiveLiterals().Words[43]))
#define DAT_00251ce8 (static_cast<int>(ActiveLiterals().Words[44]))
#define DAT_00251cec (static_cast<int>(ActiveLiterals().Words[45]))
#define DAT_00251cf0 (static_cast<int>(ActiveLiterals().Words[46]))
#define DAT_00251cf4 (ActiveLiterals().Words[47])
#define DAT_00251cf8 (std::bit_cast<float>(ActiveLiterals().Words[48]))
#define DAT_00251cfc (std::bit_cast<float>(ActiveLiterals().Words[49]))
#define DAT_00251d00 (std::bit_cast<float>(ActiveLiterals().Words[50]))
#define DAT_00251d04 (GuestPtr<uintptr_t>(ActiveLiterals().Words[51]))
#define DAT_00251d08 (ActiveLiterals().Words[52])
#define DAT_00251d0c (static_cast<int>(ActiveLiterals().Words[53]))
#define DAT_00251d10 (std::bit_cast<float>(ActiveLiterals().Words[54]))
#define DAT_00251d14 (static_cast<int>(ActiveLiterals().Words[55]))
#define DAT_00251d1c (ActiveLiterals().Words[56])
#define DAT_00251d20 (static_cast<int>(ActiveLiterals().Words[57]))
#define DAT_00251d24 (static_cast<int>(ActiveLiterals().Words[58]))
#define DAT_00251d28 (static_cast<int>(ActiveLiterals().Words[59]))
#define DAT_00251d30 (ActiveLiterals().Words[60])
#define DAT_00252118 (ActiveLiterals().Words[61])
#define DAT_0025211c (static_cast<int>(ActiveLiterals().Words[62]))
#define DAT_00252120 (static_cast<int>(ActiveLiterals().Words[63]))
#define DAT_00252124 (ActiveLiterals().Words[64])
#define DAT_00252128 (ActiveLiterals().Words[65])
#define DAT_0025212c (ActiveLiterals().Words[66])
#define DAT_00252134 (std::bit_cast<float>(ActiveLiterals().Words[67]))
#define DAT_00252138 (std::bit_cast<float>(ActiveLiterals().Words[68]))
#define DAT_0025213c (GuestPtr<uintptr_t>(ActiveLiterals().Words[69]))
#define DAT_00252140 (ActiveLiterals().Words[70])
#define DAT_00252144 (ActiveLiterals().Words[71])
#define DAT_00252148 (static_cast<int>(ActiveLiterals().Words[72]))
#define DAT_0025214c (ActiveLiterals().Words[73])
#define DAT_00252150 (static_cast<int>(ActiveLiterals().Words[74]))
#define DAT_00252154 (static_cast<int>(ActiveLiterals().Words[75]))
#define DAT_00252158 (static_cast<int>(ActiveLiterals().Words[76]))
#define DAT_0025215c (static_cast<int>(ActiveLiterals().Words[77]))
#define DAT_00252160 (static_cast<int>(ActiveLiterals().Words[78]))
#define DAT_00252164 (static_cast<int>(ActiveLiterals().Words[79]))
#define DAT_00252168 (static_cast<int>(ActiveLiterals().Words[80]))
#define DAT_002524d4 (ActiveLiterals().Words[81])
#define DAT_002524d8 (ActiveLiterals().Words[82])
#define DAT_002524e0 (ActiveLiterals().Words[83])
#define DAT_002524e4 (ActiveLiterals().Words[84])
#define DAT_002524e8 (static_cast<int>(ActiveLiterals().Words[85]))
#define DAT_002524f0 (ActiveLiterals().Words[86])
#define DAT_002524f4 (ActiveLiterals().Words[87])
#define DAT_002524f8 (static_cast<int>(ActiveLiterals().Words[88]))
#define DAT_002524fc (ActiveLiterals().Words[89])
#define DAT_00252500 (ActiveLiterals().Words[90])
#define DAT_00252504 (static_cast<int>(ActiveLiterals().Words[91]))
#define DAT_00252508 (ActiveLiterals().Words[92])
#define DAT_0025250c (GuestPtr<uintptr_t>(ActiveLiterals().Words[93]))
#define DAT_00252510 (ActiveLiterals().Words[94])
#define DAT_00252914 (ActiveLiterals().Words[95])
#define DAT_00252918 (ActiveLiterals().Words[96])
#define DAT_0025291c (ActiveLiterals().Words[97])
#define DAT_00252920 (static_cast<int>(ActiveLiterals().Words[98]))
#define DAT_00252924 (ActiveLiterals().Words[99])
#define DAT_00252928 (ActiveLiterals().Words[100])
#define DAT_0025292c (ActiveLiterals().Words[101])
#define DAT_00252930 (ActiveLiterals().Words[102])
#define DAT_00252934 (ActiveLiterals().Words[103])
#define DAT_00252938 (GuestPtr<uintptr_t>(ActiveLiterals().Words[104]))
#define DAT_0025293c (static_cast<int>(ActiveLiterals().Words[105]))
#define DAT_00252940 (std::bit_cast<float>(ActiveLiterals().Words[106]))
#define DAT_00252944 (ActiveLiterals().Words[107])
#define DAT_00252948 (ActiveLiterals().Words[108])
#define DAT_0025294c (GuestPtr<uintptr_t>(ActiveLiterals().Words[109]))
#define DAT_00252950 (GuestPtr<uintptr_t>(ActiveLiterals().Words[110]))
#define DAT_00252954 (ActiveLiterals().Words[111])
#define DAT_00252958 (GuestPtr<uintptr_t>(ActiveLiterals().Words[112]))
#define DAT_0025295c (std::bit_cast<float>(ActiveLiterals().Words[113]))
#define DAT_00252960 (static_cast<int>(ActiveLiterals().Words[114]))
#define DAT_00252964 (std::bit_cast<float>(ActiveLiterals().Words[115]))
#define DAT_00252dc0 (static_cast<int>(ActiveLiterals().Words[116]))
#define DAT_00252dc4 (ActiveLiterals().Words[117])
#define DAT_00252dc8 (ActiveLiterals().Words[118])
#define DAT_00252dcc (ActiveLiterals().Words[119])
#define DAT_00252dd0 (ActiveLiterals().Words[120])
#define DAT_00252dd4 (ActiveLiterals().Words[121])
#define DAT_00252ddc (ActiveLiterals().Words[122])
#define DAT_00252de0 (ActiveLiterals().Words[123])
#define DAT_00252de4 (ActiveLiterals().Words[124])
#define DAT_00252de8 (ActiveLiterals().Words[125])
#define DAT_00252dec (ActiveLiterals().Words[126])
#define DAT_00253408 (ActiveLiterals().Words[127])
#define DAT_0025340c (ActiveLiterals().Words[128])
#define DAT_00253410 (ActiveLiterals().Words[129])
#define DAT_00253414 (ActiveLiterals().Words[130])
#define DAT_00253418 (ActiveLiterals().Words[131])
#define DAT_0025341c (ActiveLiterals().Words[132])
#define DAT_00253420 (ActiveLiterals().Words[133])
#define DAT_00253424 (ActiveLiterals().Words[134])
#define DAT_00253428 (ActiveLiterals().Words[135])

void Player_UpdateCommon(u32 param_1,u32 param_2,u32 param_3)

{
  short sVar1;
  GuestPtr<short> psVar2;
  GuestPtr<short> psVar3;
  GuestPtr<undefined4> puVar4;
  GuestPtr<int> piVar5;
  GuestPtr<float> pfVar6;
  sbyte cVar7;
  byte bVar8;
  undefined1 uVar9;
  ushort uVar10;
  short sVar11;
  int iVar12;
  int iVar13;
  uint uVar14;
  undefined4 uVar15;
  GuestPtr<byte> pbVar17;
  int iVar18;
  undefined4 uVar19;
  undefined1 uVar20;
  uint uVar21;
  undefined2 uVar23;
  uint uVar24;
  bool bVar25;
  bool bVar26;
  bool bVar27;
  int body_flame_timer_step;
  int body_flame_timer_value;
  int body_flame_effect_scale;
  float fVar28;
  float fVar29;
  float fVar30;
  float fVar31;
  float fVar32;
  float fVar33;
  float fVar34;
  GuestPtr<byte> pbVar35;
  float fVar36;
  float fVar37;
  float fVar38;
  float movement_speed_target;
  float animation_last_frame;
  float body_burn_ratio;
  int body_burn_scale;
  int body_shock_interval;
  float water_transition_depth;
  float spring_position;
  float fall_accumulator_delta;
  float slope_base;
  float slope_delta;
  float slope_limit;
  float slope_value;
  undefined8 uVar41;
  undefined8 uVar42;
  GuestLocal<float> local_a0(OwnerLocalAddress(0x00U));
  GuestLocal<float> local_9c(OwnerLocalAddress(0x04U));
  GuestLocal<float> local_98(OwnerLocalAddress(0x08U));
  GuestLocal<float> local_94(OwnerLocalAddress(0x0CU));
  GuestLocal<GuestPtr<byte>> local_90(OwnerLocalAddress(0x10U));
  GuestLocal<int> local_8c(OwnerLocalAddress(0x14U));
  GuestLocal<int> local_88(OwnerLocalAddress(0x18U));
  GuestLocal<int> local_84(OwnerLocalAddress(0x1CU));
  GuestLocal<int> local_80(OwnerLocalAddress(0x20U));
  GuestLocal<int> local_7c(OwnerLocalAddress(0x24U));
  GuestLocal<int> local_78(OwnerLocalAddress(0x28U));
  GuestLocal<int> local_74(OwnerLocalAddress(0x2CU));
  GuestLocal<int> local_70(OwnerLocalAddress(0x30U));
  GuestLocal<uint> local_6c(OwnerLocalAddress(0x34U));
  GuestLocal<int> local_68(OwnerLocalAddress(0x38U));
  GuestLocal<int> local_64(OwnerLocalAddress(0x3CU));
  GuestLocal<int> local_60(OwnerLocalAddress(0x40U));

  GuestRef<undefined4>(DAT_00251304 + 0xac) = param_3;
  local_60 = param_1 + 0x2400;
  GuestRef<undefined4>(param_1 + 0x29c8) = param_3;
  if ((GuestRef<sbyte>(param_1 + 0x249e) < '\0') &&
     (cVar7 = GuestRef<sbyte>(param_1 + 0x249e) + '\x01', GuestRef<sbyte>(param_1 + 0x249e) = cVar7,
     cVar7 == '\0')) {
    GuestRef<undefined1>(param_1 + 0x249e) = 1;
    Audio_PlaySoundGeneral(
        (uint)DAT_00251310,
        0,
        4,
        GuestPtr<float>(DAT_0025130c),
        GuestPtr<float>(DAT_0025130c),
        GuestPtr<sbyte>(DAT_00251308));
  }
  oot3d_copy_u32x3(param_1 + 0x108,param_1 + 8);
  if (GuestRef<sbyte>(param_1 + 0x247e) != '\0') {
    GuestRef<sbyte>(param_1 + 0x247e) = GuestRef<sbyte>(param_1 + 0x247e) + -1;
  }
  local_64 = param_2 + 0x208c;
  if (GuestRef<sbyte>(param_1 + 0x227a) != '\0') {
    GuestRef<sbyte>(param_1 + 0x227a) = GuestRef<sbyte>(param_1 + 0x227a) + -1;
  }
  if (GuestRef<sbyte>(param_1 + 0x249f) != '\0') {
    GuestRef<sbyte>(param_1 + 0x249f) = GuestRef<sbyte>(param_1 + 0x249f) + -1;
  }
  if (GuestRef<sbyte>(local_60 + 0x82) != '\0') {
    GuestRef<sbyte>(param_1 + 0x2482) = GuestRef<sbyte>(local_60 + 0x82) + -1;
  }
  if (((GuestRef<uint>(param_1 + 0x1710) & 0x2000000) != 0 &&
       (GuestRef<uint>(param_1 + 0x1710) & 0x20000000) != 0) &&
     (iVar12 = Actor_Find(local_64,0x32,8), iVar12 != 0)) {
    Actor_ChangeType(param_2,local_64,iVar12,6);
  }
  cVar7 = GuestRef<sbyte>(local_60 + 0x88);
  if (cVar7 < '\0') {
    cVar7 = cVar7 + '\x01';
LAB_00250c2c:
    GuestRef<sbyte>(param_1 + 0x2488) = cVar7;
  }
  else if ('\0' < cVar7) {
    iVar13 = GuestRef<int>(param_1 + 0x1708);
    bVar25 = iVar13 != DAT_00251314;
    iVar12 = DAT_00251314;
    if (bVar25) {
      iVar12 = DAT_00251318;
    }
    bVar27 = iVar13 != iVar12;
    if (bVar25 && bVar27) {
      iVar12 = DAT_0025131c;
    }
    iVar18 = iVar12;
    if ((bVar25 && bVar27) && iVar13 != iVar12) {
      iVar18 = DAT_00251320;
    }
    if (((bVar25 && bVar27) && iVar13 != iVar12) && iVar13 != iVar18) {
      cVar7 = cVar7 + -1;
      goto LAB_00250c2c;
    }
  }
  if (GuestRef<sbyte>(param_1 + 0x227c) != '\0') {
    GuestRef<sbyte>(param_1 + 0x227c) = GuestRef<sbyte>(param_1 + 0x227c) + -1;
  }
  FUN_003c45f4(param_2,param_1);
  local_90 = GuestPtr<byte>(0x0);
  uVar24 = GuestIndirectRef<uint>(param_1 + 0x29c8) & 0x200;
  if (uVar24 == 0) {
    GuestRef<uint>(param_1 + 0x1710) = GuestRef<uint>(param_1 + 0x1710) & 0xbfffffff;
    GuestRef<undefined1>(param_1 + 0x174f) = 0xff;
  }
  uVar14 = oot3d_get_flag_22a0(param_2);
  bVar25 = uVar14 != 0;
  if (!bVar25) {
    uVar14 = (uint)GuestRef<byte>(param_1 + 0x12bc);
  }
  if (bVar25 || uVar14 != 0) {
LAB_00250ca8:
    uVar15 = 0;
LAB_00250cd8:
    GuestRef<undefined4>(param_1 + 0x1700) = uVar15;
  }
  else {
    bVar25 = (DAT_00251324 & GuestRef<uint>(param_1 + 0x1710)) == 0;
    uVar14 = DAT_00251324;
    if (bVar25) {
      uVar14 = (uint)GuestRef<byte>(param_1 + 0x172a);
    }
    if (!bVar25 || (uVar14 & 0x80) != 0) goto LAB_00250ca8;
    bVar25 = uVar24 == 0;
    if (bVar25) {
      uVar14 = GuestRef<uint>(param_1 + 0x1714);
    }
    bVar26 = (uVar14 & 0x2000) == 0;
    bVar27 = bVar25 && bVar26;
    if (bVar25 && bVar26) {
      bVar27 = GuestRef<int>(param_1 + 0x1718) == 0;
    }
    if (!bVar27) {
      iVar12 = GuestRef<int>(param_1 + 0x1700);
      if (8 < iVar12) {
LAB_00250cfc:
        GuestRef<int>(param_1 + 0x1700) = iVar12 + -1;
        if (8 < iVar12 + -1) {
          local_90 = GuestPtr<byte>(0x1);
        }
        goto LAB_00250d10;
      }
      uVar15 = 8;
      goto LAB_00250cd8;
    }
    if ((GuestRef<uint>(param_1 + 0x1710) & 0x20000) == 0) {
      iVar12 = GuestRef<int>(param_1 + 0x1700);
      if (iVar12 != 0) goto LAB_00250cfc;
    }
    else {
      GuestRef<undefined4>(param_1 + 0x1700) = 0;
    }
  }
LAB_00250d10:
  local_68 = param_2 + 0x2000;
  if ((GuestRef<uint>(DAT_00251328 + GuestRef<int>(param_2 + 0x20ac)) & 0x80) == 0 &&
      (GuestRef<uint>(GuestRef<int>(param_2 + 0x20ac) + 4) & 0x100) == 0) {
    if ((GuestRef<int>(param_1 + 0x1700) != 0) || ((GuestRef<uint>(param_1 + 0x1710) & DAT_0025132c) != 0)) {
      cVar7 = GuestRef<sbyte>(DAT_00251330 + 0x2d);
      bVar25 = cVar7 == '\0';
      if (bVar25) {
        cVar7 = GuestRef<sbyte>(param_1 + 2);
      }
      uVar14 = (uint)(!bVar25 || cVar7 != '\x02');
      local_6c = uVar14;
      if (GuestRef<byte>(param_1 + 0x2492) != uVar14) {
        FUN_00334354(param_1);
      }
      GuestRef<sbyte>(param_1 + 0x2492) = (char)local_6c;
      uVar21 = GuestRef<uint>(param_1 + 0x1710);
      if (((uVar21 & 0x2000000) == 0) &&
         (((GuestRef<sbyte>(param_1 + 0x1a9) != '\x02' || (GuestRef<short>(param_1 + 0x2248) == 0)) &&
          ((GuestRef<uint>(GuestRef<int>(param_1 + 0x29c8) + 4) & 0x200) != 0)))) {
        if (GuestRef<sbyte>(param_1 + 2) == '\x02') {
          iVar12 = GuestRef<int>(local_68 + 0x130);
        }
        else {
          iVar12 = GuestRef<int>(local_68 + 0xac);
        }
        GuestRef<uint>(param_1 + 0x1710) = uVar21 | 0x8000;
        if ((iVar12 == 0) || ((GuestRef<uint>(iVar12 + 4) & 0x8000000) != 0)) {
          if ((DAT_00251334 & (uVar21 | 0x8000)) == 0) {
            GuestRef<uint>(param_1 + 0x1710) = uVar21 | 0x28000;
            if ((GuestRef<byte>(param_1 + 0x2a6) & 0x80) == 0) {
              uVar14 = GuestRef<ushort>(param_1 + 0x90) & 0x200;
              bVar25 = (GuestRef<ushort>(param_1 + 0x90) & 0x200) != 0;
              if (bVar25) {
                uVar14 = GuestRef<uint>(DAT_00251304 + 0x22);
              }
              if (bVar25 && (int)uVar14 < 0x2000) {
                sVar11 = GuestRef<short>(param_1 + 0x82) + -0x8000;
                GuestRef<short>(param_1 + 0xbe) = sVar11;
                GuestRef<short>(param_1 + 0x2220) = sVar11;
              }
            }
            GuestRef<undefined2>(param_1 + 0x2222) = GuestRef<undefined2>(param_1 + 0xbe);
          }
        }
        else {
          if ((GuestRef<int>(param_1 + 0x16f8) == iVar12 && GuestRef<sbyte>(param_1 + 2) == '\x02') &&
             (GuestRef<int>(local_68 + 0x1a4) != 0)) {
            iVar12 = GuestRef<int>(local_68 + 0x1a4);
          }
          if (GuestRef<int>(param_1 + 0x16f8) == iVar12) {
            if (uVar14 == 0) {
              FUN_00334354(param_1);
            }
          }
          else {
            if (uVar14 == 0) {
              GuestRef<uint>(param_1 + 0x1714) = GuestRef<uint>(param_1 + 0x1714) | 0x2000;
            }
            GuestRef<int>(param_1 + 0x16f8) = iVar12;
            GuestRef<undefined4>(param_1 + 0x1700) = 0x12;
            GuestRef<undefined1>(param_1 + 0x174f) = 0;
            GuestRef<uint>(param_1 + 0x1714) = GuestRef<uint>(param_1 + 0x1714) & 0xffdffffd;
          }
          GuestRef<uint>(param_1 + 0x1710) = GuestRef<uint>(param_1 + 0x1710) & 0xbfffffff;
        }
      }
      iVar12 = GuestRef<int>(param_1 + 0x16f8);
      if (iVar12 != 0) {
        if ((GuestRef<sbyte>(param_1 + 2) == '\x02') && (iVar12 != GuestRef<int>(param_1 + 0x1718))) {
          iVar12 = FUN_001ebe68(iVar12,param_1,local_90);
          if (iVar12 != 0) {
            FUN_00334354(param_1);
            GuestRef<uint>(param_1 + 0x1710) = GuestRef<uint>(param_1 + 0x1710) | 0x40000000;
            goto LAB_00250f38;
          }
          if (GuestRef<int>(param_1 + 0x16f8) == 0) goto LAB_00250f88;
        }
        GuestRef<undefined1>(GuestRef<int>(param_1 + 0x16f8) + 0x115) = 0x3c;
        goto LAB_00250f38;
      }
      if (GuestRef<int>(param_1 + 0x1718) != 0) {
        GuestRef<int>(param_1 + 0x16f8) = GuestRef<int>(param_1 + 0x1718);
        goto LAB_00250f44;
      }
      goto LAB_00250f88;
    }
    FUN_0032fac8(param_1);
  }
  else {
LAB_00250f38:
    if (GuestRef<int>(param_1 + 0x16f8) == 0) {
LAB_00250f88:
      if ((GuestRef<uint>(param_1 + 0x1710) & 0x20000) == 0) {
        FUN_0032fac8(param_1);
        if (GuestRef<int>(param_1 + 0x1720) != 0) {
          iVar12 = FUN_0032fa9c(local_64,GuestRef<int>(param_1 + 0x1720),5);
          if (iVar12 == 0) {
            (void)FUN_0032fa9c(local_64,GuestRef<undefined4>(param_1 + 0x1720),5);
          }
          bVar25 = iVar12 == 0 ||
                   GuestRef<byte>(iVar12 + 0xb7) == 0;
          if (uVar24 != 0) {
            uVar14 = (uint)GuestRef<byte>(param_1 + 0x174f);
          }
          if (uVar24 != 0 && uVar14 < 4) {
            iVar12 = 0;
            if (bVar25) {
              iVar12 = GuestRef<int>(local_68 + 0x1a4);
            }
            if (bVar25 && iVar12 != 0) {
              GuestRef<int>(param_1 + 0x16f8) = iVar12;
              GuestRef<int>(param_1 + 0x1718) = iVar12;
            }
          }
          cVar7 = GuestRef<sbyte>(param_1 + 0x174f) + '\x01';
          GuestRef<sbyte>(param_1 + 0x174f) = cVar7;
          if (cVar7 == -1) {
            GuestRef<undefined1>(param_1 + 0x174f) = 0xfe;
          }
        }
      }
      else {
        GuestRef<uint>(param_1 + 0x1714) = GuestRef<uint>(param_1 + 0x1714) & 0xffffdfff;
      }
    }
    else {
LAB_00250f44:
      uVar24 = GuestRef<uint>(param_1 + 0x1710);
      uVar14 = uVar24 & 0xfffcffff;
      GuestRef<uint>(param_1 + 0x1710) = uVar14;
      if (((uVar24 & 0x800) != 0) || ((~GuestRef<uint>(GuestRef<int>(param_1 + 0x16f8) + 4) & 5) != 0)) {
        GuestRef<uint>(param_1 + 0x1710) = uVar14 | 0x10000;
      }
    }
  }
  fVar36 = DAT_0025133c;
  fVar32 = DAT_00251338;
  GuestRef<undefined4>(param_1 + 0x1720) = GuestRef<undefined4>(param_1 + 0x16f8);
  fVar38 = DAT_00251340;
  GuestRef<uint>(param_1 + 0x29b8) =
      GuestRef<uint>(param_1 + 0x29b8) & 0xffbfffff;
  psVar3 = GuestPtr<short>(DAT_00251304);
  if (GuestRef<sbyte>(param_1 + 0x1a9) == '\x06') {
    if (GuestRef<short>(param_1 + 0x2248) != 0) {
      if (((GuestRef<uint>(DAT_00251304 + 0x7c) & 1) == 0) &&
          (iVar12 = oot3d_static_init_guard_acquire(
               DAT_00251304 + 0x7c),
           puVar4 = DAT_0025134c, iVar12 != 0)) {
        *DAT_0025134c = FloatToBits(0.0f);
        puVar4[1] = FloatToBits(fVar38);
        puVar4[2] = FloatToBits(0.0f);
      }
      if (((GuestRef<uint>(psVar3 + 0x7a) & 1) == 0) &&
          (iVar12 = oot3d_static_init_guard_acquire(
               DAT_00251350),
           puVar4 = DAT_00251354, iVar12 != 0)) {
        *DAT_00251354 = FloatToBits(0.0f);
        puVar4[1] = FloatToBits(fVar38);
        puVar4[2] = FloatToBits(0.0f);
      }
      body_burn_ratio =
          GuestRef<float>(param_1 + 0x2244);
      if (body_burn_ratio == 0.0f) {
        FUN_0034d688(param_2,param_1,0xff);
      }
      else {
        if (GuestRef<short>(param_1 + 0x2248) == 0) {
LAB_00251160:
          FUN_00355830(0,0xffffffff);
          fVar37 = DAT_0025135c;
          GuestRef<float>(param_1 + 0x2244) = 0.0f;
          GuestRef<uint>(param_1 + 0x29b8) =
              GuestRef<uint>(param_1 + 0x29b8) & 0xfffff7ff;
          fVar29 = (float)TargetSignedToFloat(
              (int)GuestRef<short>(
                  *DAT_00251358 + 0x110), 0);
          GuestRef<short>(param_1 + 0x2248) =
              (short)(int)(fVar37 / fVar29 + fVar38);
          body_burn_ratio = 0.0f;
        }
        else {
          sVar11 = GuestRef<short>(param_1 + 0x2248) - 1;
          iVar12 = (int)sVar11;
          GuestRef<short>(param_1 + 0x2248) = sVar11;
          if (iVar12 == 0) goto LAB_00251160;
          iVar13 = (int)GuestRef<short>(
              *DAT_00251358 + 0x110);
          fVar37 = (float)TargetSignedToFloat(iVar13);
          if ((int)(DAT_00251360 / fVar37 + fVar38) < iVar12) {
            fVar37 = (float)TargetSignedToFloat(iVar13);
            fVar29 = (float)TargetSignedToFloat(iVar13);
            fVar28 = (float)TargetSignedToFloat(iVar13);
            fVar29 = (float)TargetSignedToFloat(
                (int)(DAT_00251364 / fVar37 + fVar38) -
                (iVar12 - (int)(DAT_00251360 / fVar29 + fVar38)), 0);
            fVar37 = (float)TargetSignedToFloat(
                (int)(DAT_00251364 / fVar28 + fVar38), 0);
            body_burn_ratio = fVar29 / fVar37;
          }
          else {
            fVar37 = (float)TargetSignedToFloat(iVar13);
            body_burn_ratio = 1.0f;
            if (iVar12 < (int)(fVar36 / fVar37 + fVar38)) {
              fVar37 = (float)TargetSignedToFloat(iVar13);
              fVar29 = (float)TargetSignedToFloat(
                  (int)(fVar36 / fVar37 + fVar38), 0);
              fVar37 = (float)TargetSignedToFloat(iVar12);
              body_burn_ratio = fVar37 / fVar29;
              GuestRef<float>(param_1 + 0x2244) =
                  body_burn_ratio;
              if ((GuestRef<uint>(
                   param_1 + 0x29b8) & 0x800) != 0) {
                GuestRef<float>(param_1 + 0x2244) =
                    body_burn_ratio * fVar38;
              }
            }
          }
        }
        body_burn_scale = (int)(body_burn_ratio * fVar32);
        FUN_00365d20(
            (uintptr_t)param_2,
            (uintptr_t)(param_1 + 0x22a8),
            (uintptr_t)(DAT_00251354 - 3),
            (uintptr_t)DAT_00251354,
            (uintptr_t)(FloatToBits(DAT_00251368) - 4u),
            (uintptr_t)FloatToBits(DAT_00251368),
            (uintptr_t)(uint)(short)body_burn_scale,
            0,
            8);
      }
    }
  }
  else if ((GuestRef<sbyte>(param_1 + 0x1a9) == '\x02') && (GuestRef<short>(param_1 + 0x2248) < 0)) {
    GuestRef<short>(param_1 + 0x2248) = GuestRef<short>(param_1 + 0x2248) + 1;
  }
  fVar37 = DAT_00251714;
  piVar5 = GuestPtr<int>(DAT_00251358);
  if (GuestRef<sbyte>(param_1 + 0x227d) != '\0') {
    bVar8 = GuestRef<sbyte>(param_1 + 0x227d) - 1;
    uVar14 = (uint)bVar8;
    GuestRef<byte>(param_1 + 0x227d) = bVar8;
    iVar12 = *piVar5;
    uVar24 = GuestRef<byte>(param_1 + 0x227e) + uVar14;
    fVar28 = (float)TargetSignedToFloat((int)GuestRef<short>(iVar12 + 0x110));
    cVar7 = (char)uVar24;
    GuestRef<sbyte>(param_1 + 0x227e) = cVar7;
    fVar29 = DAT_00251718;
    body_shock_interval = (int)(fVar36 / fVar28 + fVar38);
    if (body_shock_interval < (int)(uVar24 & 0xff)) {
      uVar23 = (undefined2)(uVar14 * 2);
      if (uVar14 != 0x14 && 0x27 < uVar14 * 2) {
        uVar23 = 0x28;
      }
      fVar28 = (float)TargetSignedToFloat((int)GuestRef<short>(iVar12 + 0x110));
      GuestRef<sbyte>(param_1 + 0x227e) = cVar7 - (char)(int)(fVar36 / fVar28 + fVar38);
      {
        GuestPtr<float> shock_position(OwnerLocalAddress(0x04U));
        float shock_random_scale = fVar37;

        iVar12 = param_1 +
            (int)Rand_ZeroFloat(fVar29) * 0xc;
        shock_position[0] =
            (Rand_CenteredFloat(shock_random_scale) +
             GuestRef<float>(iVar12 + 0x2340)) -
            GuestRef<float>(param_1 + 0x28);
        shock_position[1] =
            (Rand_CenteredFloat(shock_random_scale) +
             GuestRef<float>(iVar12 + 0x2344)) -
            GuestRef<float>(param_1 + 0x2c);
        shock_position[2] =
            (Rand_CenteredFloat(shock_random_scale) +
             GuestRef<float>(iVar12 + 0x2348)) -
            GuestRef<float>(param_1 + 0x30);
        FUN_0032fa4c(
            param_2,param_1,shock_position,uVar23,1);
      }
      FUN_0034a928(param_1,DAT_0025171c);
    }
  }
  local_70 = param_2 + 0x100;
  local_74 = param_2 + 0x5000;
  local_78 = param_2 + 0x3100;
  fVar36 = DAT_00251720;
  fVar38 = DAT_00251724;
  if (GuestRef<sbyte>(param_1 + 0x246c) != '\0') {
    if (GuestRef<sbyte>(param_1 + 0x1a4) == '\x01') {
      body_flame_timer_step = 20;
    }
    else {
      body_flame_timer_step =
          (int)(GuestRef<float>(param_1 + 0x221c) *
                DAT_0025172c) + 1;
    }
    bVar25 = false;
    iVar12 = 0;
    if ((GuestRef<uint>(param_1 + 0x1714) & 8) != 0) {
      iVar12 = 100;
    }
    local_90 = GuestPtr<byte>(param_1 + 0x246d);
    if (GuestRef<sbyte>(param_1 + 0x1a6) == '\x01') {
      Actor_Spawn(
          local_64, param_2, 0xee,
          GuestRef<float>(param_1 + 0x28),
          GuestRef<float>(param_1 + 0x2c),
          GuestRef<float>(param_1 + 0x30),
          0, 0, 0, 1, 1);
      Inventory_DeleteEquipment(param_2,1);
      FUN_00367c7c(param_2,DAT_00251730,0);
    }
    uVar15 = DAT_00251734;
    iVar13 = 0x11;
    pbVar17 = static_cast<GuestPtr<byte>>(local_90);
    body_flame_effect_scale = 0;
    do {
      body_flame_timer_value = (uint)*pbVar17;
      if (body_flame_timer_step + iVar12 <
          body_flame_timer_value) {
        uVar24 = body_flame_timer_value -
            (body_flame_timer_step + iVar12);
        body_flame_effect_scale = (int)(uVar24 & 0xff);
        bVar25 = true;
        *pbVar17 = (byte)uVar24;
        if (20 < body_flame_effect_scale) {
          fVar29 = (float)TargetUnsignedToFloat(
              body_flame_effect_scale,0);
          body_flame_effect_scale =
              (int)((fVar29 - DAT_00251728) * fVar36);
        }
      }
      else {
        *pbVar17 = 0;
      }
      iVar13 = iVar13 + -1;
      pbVar17 = pbVar17 + 1;
    } while (iVar13 != 0);
    if (bVar25) {
      FUN_0036f59c(
          param_1,DAT_00251738,body_flame_effect_scale,uVar15);
      uVar24 = GuestRef<uint>(local_74 + 0xbf4);
      if (GuestRef<short>(local_70 + 4) == 0x17) {
        uVar24 = uVar24 & 1;
      }
      else {
        uVar24 = uVar24 + (uint)((ulonglong)uVar24 * (ulonglong)DAT_0025173c >> 0x23) * -10;
      }
      if (uVar24 == 0) {
        Player_InflictDamage(param_2,0xffffffff);
      }
    }
    else if (GuestRef<short>(local_78 + 0x8c) == 0) {
      GuestRef<undefined1>(param_1 + 0x246c) = 0;
    }
  }
  if ((((GuestRef<byte>(param_1 + 0x172a) & 0x40) != 0) && (GuestRef<short>(DAT_00251740 + 0x52) != 0)) &&
     (GuestRef<short>(DAT_00251740 + 0x80) == 0)) {
    GuestRef<undefined2>(DAT_00251740 + 0x80) = 3;
    Actor_Spawn(
        local_64, param_2,
        (int)GuestRef<short>(DAT_00251744 + 2),
        GuestRef<float>(param_1 + 0x28),
        GuestRef<float>(param_1 + 0x2c),
        GuestRef<float>(param_1 + 0x30),
        0, 0, 0, 0, 1);
    GuestRef<byte>(param_1 + 0x172a) = GuestRef<byte>(param_1 + 0x172a) & 0xbf;
  }
  local_7c = param_1 + 0x1310;
  if ((GuestRef<uint>(param_1 + 0x1714) & 0x8000) != 0) {
    if ((GuestRef<ushort>(param_1 + 0x90) & 1) == 0) {
      GuestRef<float>(param_1 + 0x6c) = 0.0f;
      GuestRef<float>(param_1 + 0x221c) = 0.0f;
      Actor_MoveForward(param_1);
    }
    oot3d_player_process_scene_collision(param_2,param_1);
    goto LAB_0025330c;
  }
  if (GuestRef<sbyte>(param_1 + 0x1a7) != GuestRef<sbyte>(param_1 + 0x1ab)) {
    uVar24 = GuestRef<uint>(param_1 + 0x1710) & 0x8000000;
    if (GuestRef<sbyte>(param_1 + 0x1a7) == '\x01') {
      if (uVar24 != 0) {
        FUN_00355264(param_2,param_1);
        water_transition_depth = GuestRef<float>(param_1 + 0x88);
        fVar29 = GuestRef<float>(GuestRef<int>(param_1 + 0x170c) + 0x2c);
        if (water_transition_depth > fVar29) {
          uVar24 = GuestRef<uint>(param_1 + 0x1714) | 0x400;
          goto LAB_002517d0;
        }
      }
    }
    else if ((uVar24 != 0) &&
            ((GuestRef<sbyte>(param_1 + 0x1ab) == '\x01' || ((GuestRef<ushort>(param_1 + 0x90) & 1) != 0)))) {
      FUN_0032ec94(param_2,param_1);
      uVar24 = GuestRef<uint>(param_1 + 0x1714) & 0xfffffbff;
LAB_002517d0:
      GuestRef<uint>(param_1 + 0x1714) = uVar24;
    }
    iVar12 = DAT_00251cd4;
    GuestRef<undefined1>(param_1 + 0x1ab) = GuestRef<undefined1>(param_1 + 0x1a7);
    iVar13 = GuestRef<int>(param_1 + 0x1708);
    bVar25 = iVar13 != iVar12;
    if (bVar25) {
      iVar12 = DAT_00251cd8;
    }
    bVar27 = iVar13 != iVar12;
    if (bVar25 && bVar27) {
      iVar12 = DAT_00251cdc;
    }
    iVar18 = iVar12;
    if ((bVar25 && bVar27) && iVar13 != iVar12) {
      iVar18 = DAT_00251ce0;
    }
    if (((bVar25 && bVar27) && iVar13 != iVar12) && iVar13 != iVar18) {
      bVar25 = iVar13 != DAT_00251ce4;
      iVar12 = DAT_00251ce4;
      if (bVar25) {
        iVar12 = DAT_00251ce8;
      }
      bVar27 = iVar13 != iVar12;
      if (bVar25 && bVar27) {
        iVar12 = DAT_00251cec;
      }
      bVar26 = iVar13 != iVar12;
      if ((bVar25 && bVar27) && bVar26) {
        iVar12 = DAT_00251cf0;
      }
      if (((bVar25 && bVar27) && bVar26) && iVar13 != iVar12) {
        GuestRef<undefined1>(param_1 + 0x1b8) = GuestRef<undefined1>(param_1 + 0x1a7);
      }
      if (((bVar25 && bVar27) && bVar26) && iVar13 != iVar12) goto LAB_0025183c;
    }
    GuestRef<uint>(param_1 + 0x29b8) = GuestRef<uint>(param_1 + 0x29b8) | 4;
  }
LAB_0025183c:
  if ((GuestRef<int>(param_1 + 0x124) == 0) && ((GuestRef<uint>(param_1 + 0x1710) & 0x800000) != 0)) {
    GuestRef<undefined4>(param_1 + 0x124) = GuestRef<undefined4>(param_1 + 0x12b8);
    uVar9 = GuestRef<undefined1>(param_1 + 0x2a6);
    GuestRef<undefined1>(param_1 + 0x2a6) = 0;
    FUN_0036055c(param_2,param_1,DAT_00251cf4,0);
    GuestRef<undefined1>(param_1 + 0x2a6) = uVar9;
    GuestRef<uint>(param_1 + 0x1710) = GuestRef<uint>(param_1 + 0x1710) | 0x800000;
    Oot3d_PlayAnimationOnce(param_1 + 0x254,param_2,0x21);
    FUN_003603f8(param_2,param_1,0x9b);
    GuestRef<undefined2>(param_1 + 0x2238) = 99;
  }
  cVar7 = GuestRef<sbyte>(param_1 + 0x2228);
  if (cVar7 == '\0') {
    GuestRef<undefined1>(param_1 + 0x2229) = 0;
  }
  else {
    if (cVar7 < '\0') {
      cVar7 = cVar7 + '\x01';
    }
    else {
      cVar7 = cVar7 + -1;
    }
    GuestRef<sbyte>(param_1 + 0x2228) = cVar7;
  }
  Math_ScaledStepToS(param_1 + 0x175c,0,400);
  FUN_0025342c(param_1 + 0x1220,0x14,0x50,6);
  fVar33 = DAT_00251d00;
  fVar28 = DAT_00251cfc;
  fVar29 = DAT_00251cf8;
  local_80 = param_1 + 0x1200;
  if ((GuestRef<uint>(local_74 + 0xbf4) & 0x20) == 0) {
    sVar11 = 3;
  }
  else {
    sVar11 = 0;
  }
  GuestRef<short>(param_1 + 0xc2) = sVar11 + GuestRef<short>(param_1 + 0x1220);
  psVar3 = GuestPtr<short>(DAT_00251d04);
  if (GuestRef<sbyte>(param_1 + 0x1b7) == '\x04') {
    psVar2 = GuestPtr<short>(DAT_00251d04 + 4);
    DAT_00251d04[3] = (DAT_00251d04[3] - (DAT_00251d04[3] >> 3)) + (short)(-(int)*DAT_00251d04 >> 2)
    ;
    psVar3[4] = (*psVar2 - (*psVar2 >> 3)) + (short)(-(int)psVar3[1] >> 2);
    {
      short ear_angle = (short)(GuestRef<short>(param_1 + 0x36) -
          GuestRef<short>(param_1 + 0xbe));
      float ear_force_x =
          oot3d_cos_idx8((int)ear_angle) *
          (Rand_CenteredFloat(fVar28) + fVar33) *
          GuestRef<float>(param_1 + 0x6c) * DAT_00251d08;
      float ear_force_y =
          oot3d_sin_idx8((int)ear_angle) *
          (Rand_CenteredFloat(fVar28) + fVar33) *
          GuestRef<float>(param_1 + 0x6c) * fVar29;

      sVar11 = (short)(int)ear_force_x;
      sVar1 = (short)(int)ear_force_y;
    }
    sVar11 = psVar3[3] + (sVar11 >> 2);
    psVar3[3] = sVar11;
    iVar12 = DAT_00251d0c;
    sVar1 = psVar3[4] + (sVar1 >> 2);
    psVar3[4] = sVar1;
    iVar13 = (iVar12 >> 0xd) - iVar12;
    if (iVar12 < sVar11) {
      psVar3[3] = (short)iVar12;
    }
    else if (sVar11 < iVar13) {
      psVar3[3] = (short)iVar13;
    }
    if (iVar12 < sVar1) {
      psVar3[4] = (short)iVar12;
    }
    else if (sVar1 < iVar13) {
      psVar3[4] = (short)iVar13;
    }
    sVar11 = *psVar3 + psVar3[3];
    *psVar3 = sVar11;
    bVar25 = -1 < sVar11;
    if (bVar25) {
      sVar11 = 0;
    }
    if (!bVar25) {
      sVar11 = sVar11 >> 1;
    }
    psVar3[1] = psVar3[1] + psVar3[4];
    psVar3[2] = sVar11;
  }
  iVar13 = FUN_0034dd2c(param_1);
  iVar12 = DAT_00251d14;
  fVar31 = DAT_00251d10;
  if (iVar13 != 0) {
    spring_position =
        GuestRef<float>(param_1 + 0x2240) +
        GuestRef<float>(param_1 + 0x2244);
    GuestRef<float>(param_1 + 0x2240) = spring_position;
    fVar30 =
        (GuestRef<float>(param_1 + 0x2244) -
         spring_position * fVar37) * fVar31;
    GuestRef<float>(param_1 + 0x2244) = fVar30;
    if (fVar30 < 0.0f) {
      fVar30 = -fVar30;
    }
    if ((int)fVar30 < iVar12) {
      GuestRef<float>(param_1 + 0x2244) = 0.0f;
      if (spring_position < 0.0f) {
        spring_position = -spring_position;
      }
      if ((int)spring_position < iVar12) {
        GuestRef<float>(param_1 + 0x2240) = 0.0f;
      }
    }
  }
  local_84 = param_1 + 0x229c;
  local_88 = param_2 + 0xa98;
  if ((GuestRef<byte>(param_1 + 0x2a6) & 0x80) == 0) {
    if (((GuestRef<ushort>(param_1 + 0x90) & 1) == 0) || (GuestRef<int>(DAT_00251304 + 0x14) != 5)) {
      uVar24 = (uint)GuestRef<byte>(param_1 + 0x1a7);
      bVar25 = uVar24 == 2;
      if (bVar25) {
        uVar24 = GuestRef<uint>(param_1 + 0x1710);
      }
      if (!bVar25 || (uVar24 & 0x28000000) != 0) goto LAB_00251d34;
LAB_00251b40:
      sVar11 = GuestRef<short>(param_1 + 0x2220);
      iVar13 = (int)sVar11;
      iVar12 = (int)(short)(GuestRef<short>(param_1 + 0x36) - sVar11);
      if (iVar12 < 0) {
        iVar12 = -iVar12;
      }
      movement_speed_target = GuestRef<float>(param_1 + 0x221c);
      if ((0x6000 < iVar12) &&
          (GuestRef<float>(param_1 + 0x6c) !=
           0.0f)) {
        iVar13 = (int)(short)(sVar11 + -0x8000);
        movement_speed_target = 0.0f;
      }
      iVar12 = Math_StepToF(
          GuestPtr<float>(param_1 + 0x6c),
          movement_speed_target,
          0.35f);
      if ((iVar12 != 0) &&
          (movement_speed_target == 0.0f)) {
        GuestRef<undefined2>(param_1 + 0x36) = GuestRef<undefined2>(param_1 + 0x2220);
      }
      if (GuestRef<float>(param_1 + 0x221c) !=
          0.0f) {
        iVar12 = (int)(TargetAbs(GuestRef<float>(param_1 + 0x221c)) * DAT_00251d1c -
                      TargetAbs(GuestRef<float>(param_1 + 0x6c)) * fVar29);
        if (iVar12 < 0) {
          iVar12 = 0;
        }
        else if (DAT_00251d20 < iVar12) {
          iVar12 = DAT_00251d20;
        }
        Math_ScaledStepToS(param_1 + 0x36,iVar13,(int)(short)iVar12);
      }
      iVar12 = DAT_00251d24;
      if (GuestRef<float>(param_1 + 0x221c) ==
          0.0f) {
        if (GuestRef<float>(param_1 + 0x6c) !=
            0.0f) {
          iVar18 = GuestRef<int>(param_1 + 0x1708);
          iVar13 = DAT_00251cd4;
          if (iVar18 != DAT_00251cd4) {
            iVar13 = DAT_00251cdc;
          }
          if ((((iVar18 == DAT_00251cd4 || iVar18 == iVar13) &&
               (0x40000000 < (int)GuestRef<float>(param_1 + 0x6c))) &&
              (iVar13 = GuestRef<int>(param_1 + 0x284), iVar13 != DAT_00251d24 && iVar13 != 500)) &&
             ((iVar13 != GuestRef<int>(DAT_00251d28 + (uint)GuestRef<byte>(param_1 + 0x1b3) * 4 + 0x198) &&
              (GuestRef<int>(DAT_00251304 + 0x14) == 5)))) {
            uVar15 = Oot3d_GetAnimationLastFrame(param_1 + 0x254,DAT_00251d24);
            animation_last_frame = (float)TargetSignedToFloat(uVar15);
            Oot3d_ChangeAnimationByIndex(
                param_1 + 0x254, param_2, iVar12, 0,
                1.0f, 0.0f, animation_last_frame, 0.0f);
          }
          FUN_0032ebe8(
              param_1 + 0x28,
              DAT_00251d30,
              GuestRef<float>(param_1 + 0x6c));
        }
      }
    }
    else {
      if (GuestRef<sbyte>(param_1 + 0x1a7) != '\x01') goto LAB_00251b40;
LAB_00251d34:
      GuestRef<undefined4>(param_1 + 0x6c) = GuestRef<undefined4>(param_1 + 0x221c);
      GuestRef<undefined2>(param_1 + 0x36) = GuestRef<undefined2>(param_1 + 0x2220);
    }
    FUN_0035fb14(param_1);
    fVar32 = GuestRef<float>(param_1 + 0x229c);
    if (((fVar32 != 0.0f) && (iVar12 = Player_InCsMode(param_2), iVar12 == 0)) &&
       ((GuestRef<uint>(param_1 + 0x1710) & DAT_00252118) == 0)) {
      iVar13 = GuestRef<int>(param_1 + 0x1708);
      iVar12 = DAT_0025211c;
      if (iVar13 != DAT_0025211c) {
        iVar12 = DAT_00252120;
      }
      if (iVar13 != DAT_0025211c && iVar13 != iVar12) {
        fVar29 = oot3d_sin_idx8(
            (int)GuestRef<short>(param_1 + 0x22a0));
        GuestRef<float>(param_1 + 0x60) =
            GuestRef<float>(param_1 + 0x60) + fVar32 * fVar29;
        fVar29 = oot3d_cos_idx8(
            (int)GuestRef<short>(param_1 + 0x22a0));
        GuestRef<float>(param_1 + 0x68) =
            GuestRef<float>(param_1 + 0x68) + fVar32 * fVar29;
      }
    }
    FUN_0036b96c(param_1);
    oot3d_player_process_scene_collision(param_2,param_1);
    psVar3 = GuestPtr<short>(DAT_00251304);
    iVar12 = GuestRef<int>(DAT_00251304 + 0x1c);
    if (iVar12 == 0 ||
        GuestRef<byte>(param_1 + 0x1a7) == 1) {
      goto LAB_00251fcc;
    }
    iVar12 = iVar12 + -1;
    GuestRef<int>(DAT_00251304 + 0x1c) = iVar12;
    if (*psVar3 == 0) {
      fVar32 = GuestRef<float>(DAT_00252128 + iVar12 * 4);
      if ((GuestRef<uint>(param_1 + 0x1710) & 0x8000000) == 0) {
        fVar32 = fVar32 * DAT_0025212c;
      }
    }
    else {
      fVar32 = GuestRef<float>(DAT_00252124 + iVar12 * 4);
    }
    Math_StepToF(
        GuestPtr<float>(local_84),
        fVar32,
        fVar32 * 0.1f);
    fVar30 = DAT_00252134;
    if ((GuestRef<uint>(param_1 + 0x1710) & 0x8000000) != 0) {
      fVar30 = DAT_00252138;
    }
    Math_ScaledStepToS(param_1 + 0x22a0,(int)psVar3[1],(int)(short)(int)(fVar32 * fVar30));
  }
  else {
    psVar3 = GuestPtr<short>(DAT_00251304);
    psVar3[0x14] = 0;
    psVar3[0x15] = 0;
    GuestRef<undefined1>(param_1 + 0x248a) = 0;
    pfVar6 = GuestPtr<float>(DAT_0025213c);
    if (((GuestRef<uint>(param_1 + 0x1710) & 1) == 0) && ((GuestRef<uint>(param_1 + 0x1710) & 0x800000) != 0))
    {
      if (((GuestRef<uint>(DAT_00251304 + 0x82) & 1) == 0) &&
         (iVar12 = oot3d_static_init_guard_acquire(DAT_00252140), iVar12 != 0)) {
        *pfVar6 = 0.0f;
        pfVar6[1] = 0.0f;
        pfVar6[2] = fVar32;
      }
      iVar12 = GuestRef<int>(param_1 + 0x12b8);
      if ((GuestRef<ushort>(iVar12 + 0x90) & 1) == 0) {
        GuestPtr<float> floor_probe(OwnerLocalAddress(0x04U));
        float floor_cos = oot3d_cos_idx8(
            (int)GuestRef<short>(param_1 + 0xbe));
        float floor_sin = oot3d_sin_idx8(
            (int)GuestRef<short>(param_1 + 0xbe));

        floor_probe[0] = *pfVar6 * floor_cos +
            pfVar6[2] * floor_sin +
            GuestRef<float>(param_1 + 0x28);
        floor_probe[1] = GuestRef<float>(param_1 + 0x2c) + pfVar6[1];
        floor_probe[2] = pfVar6[2] * floor_cos -
            *pfVar6 * floor_sin +
            GuestRef<float>(param_1 + 0x30);
        BgCheck_EntityRaycastFloor3(
            local_88,&local_90,&local_94,floor_probe);
      }
      else {
        local_90 = GuestRef<GuestPtr<byte>>(iVar12 + 0x7c);
        local_94 = (float)(uint)GuestRef<byte>(iVar12 + 0x81);
      }
      if ((local_90 != GuestPtr<byte>(0x0)) &&
         (iVar12 = FUN_003365b0(param_2,param_1,local_90,local_94), iVar12 != 0)) {
        iVar12 = *DAT_00251358;
        if (GuestRef<short>(iVar12 + 0x586) == 0) {
          GuestRef<undefined2>(iVar12 + 0xe60) = 1;
        }
        else {
          GuestRef<undefined2>(iVar12 + 0x586) = 0;
        }
      }
    }
    psVar3 = GuestPtr<short>(DAT_00251304);
    psVar3[0x1c] = 0;
    psVar3[0x1d] = 0;
    GuestRef<float>(param_1 + 0x229c) = 0.0f;
LAB_00251fcc:
    if (GuestRef<float>(param_1 + 0x229c) !=
        0.0f) {
      Math_StepToF(
          GuestPtr<float>(local_84),
          0.0f,
          ((GuestRef<uint>(param_1 + 0x1710) & 0x8000000) != 0) ? 0.5f : 1.0f);
    }
  }
  uVar24 = Player_InBlockingCsMode(param_2,param_1);
  bVar25 = uVar24 == 0;
  if (bVar25) {
    uVar24 = GuestRef<uint>(param_1 + 0x1714);
  }
  if (bVar25 && (uVar24 & 0x40000) == 0) {
    if (GuestRef<float>(GuestRef<int>(param_1 + 0x170c) + 0x2c) <=
        GuestRef<float>(param_1 + 0x88)) {
      FUN_0032eb60(0x20);
      if (GuestRef<ushort>(param_1 + 0x2224) < DAT_00252144) {
        sVar11 = GuestRef<ushort>(param_1 + 0x2224) + 1;
        goto LAB_00252060;
      }
    }
    else {
      FUN_0032eb60(0);
      sVar11 = 0;
LAB_00252060:
      GuestRef<short>(param_1 + 0x2224) = sVar11;
    }
    uVar15 = DAT_002524d4;
    iVar13 = GuestRef<int>(param_1 + 0x1708);
    iVar12 = DAT_0025211c;
    if (iVar13 != DAT_0025211c) {
      iVar12 = DAT_00252148;
    }
    if (iVar13 != DAT_0025211c && iVar13 != iVar12) {
      fVar32 = GuestRef<float>(param_1 + 0x88);
      fVar30 = GuestRef<float>(GuestRef<int>(param_1 + 0x170c) + 0x2c);
      if (!(fVar32 > fVar30)) {
        bVar25 = true;
        if ((GuestRef<uint>(param_1 + 0x1710) & 0x8000000) != 0) {
          bVar25 = GuestRef<float>(GuestRef<int>(param_1 + 0x170c) + 0x24) <= fVar32;
        }
        if (!bVar25) {
          if ((GuestRef<sbyte>(param_1 + 0x2a6) == '\0') &&
             ((GuestRef<sbyte>(param_1 + 0x1a7) != '\x01' || (iVar13 == DAT_0025214c)))) {
            GuestRef<undefined2>(param_1 + 0x2220) = GuestRef<undefined2>(param_1 + 0xbe);
            FUN_0036055c(param_2,param_1,uVar15,1);
            iVar12 = DAT_00251d28;
            GuestRef<short>(param_1 + 0x226a) =
                 (short)(int)(DAT_002524d8 * GuestRef<float>(DAT_00251304 + 0x16));
            Oot3d_ChangeAnimationByIndex(
                param_1 + 0x254, param_2,
                GuestRef<undefined4>(
                    iVar12 + (uint)GuestRef<byte>(
                     param_1 + 0x1b3) * 4 + 0x300),
                0, 1.0f, 0.0f, 0.0f, -6.0f);
          }
          GuestRef<undefined4>(param_1 + 100) = DAT_002524e0;
          GuestRef<uint>(param_1 + 0x1710) = GuestRef<uint>(param_1 + 0x1710) & 0xf7ffffff | 0x40000;
          FUN_00355264(param_2,param_1);
          iVar12 = FUN_00358b3c(param_2,param_1,500);
          if (iVar12 != 0) {
            FUN_0036f59c(param_1,DAT_002524e4);
          }
          Player_SetBootData(param_2,param_1);
        }
      }
      else if ((GuestRef<uint>(param_1 + 0x1710) & 0x8000000) == 0) {
LAB_00252100:
        FUN_0032ec94(param_2,param_1);
      }
      else if ((GuestRef<sbyte>(param_1 + 0x1a7) != '\x01') || ((GuestRef<ushort>(param_1 + 0x90) & 1) == 0)) {
        bVar25 = iVar13 != DAT_00252150;
        iVar12 = DAT_00252150;
        if (bVar25) {
          iVar12 = DAT_00252154;
        }
        bVar27 = iVar13 != iVar12;
        if (bVar25 && bVar27) {
          iVar12 = DAT_00252158;
        }
        iVar18 = iVar12;
        if ((bVar25 && bVar27) && iVar13 != iVar12) {
          iVar18 = DAT_0025215c;
        }
        if (((bVar25 && bVar27) && iVar13 != iVar12) && iVar13 != iVar18) {
          bVar25 = iVar13 != DAT_0025214c;
          if (bVar25) {
            iVar18 = DAT_00252160;
          }
          bVar27 = iVar13 != iVar18;
          if (bVar25 && bVar27) {
            iVar18 = DAT_00252164;
          }
          iVar12 = iVar18;
          if ((bVar25 && bVar27) && iVar13 != iVar18) {
            iVar12 = DAT_00252168;
          }
          if (((bVar25 && bVar27) && iVar13 != iVar18) && iVar13 != iVar12) goto LAB_00252100;
        }
      }
    }
    uVar10 = (ushort)GuestRef<byte>(param_1 + 2);
    bVar25 = uVar10 != 2;
    if (!bVar25) {
      uVar10 = GuestRef<ushort>(DAT_00251330 + 0x44);
    }
    if (bVar25 || uVar10 != 0) {
      if ((GuestRef<int>(param_1 + 0x124) == 0) &&
         (((GuestRef<sbyte>(DAT_00252510 + param_2) == '\x14' || (GuestRef<sbyte>(param_1 + 0x249f) != '\0')) ||
          (iVar12 = FUN_00132ad0(param_1,param_2), iVar12 == 0)))) {
        FUN_001cf9ac(param_1,param_2);
      }
      else {
        GuestRef<short>(param_1 + 0x2280) = (short)(int)GuestRef<float>(param_1 + 0x2c);
      }
      iVar12 = DAT_00252920;
      if ((GuestRef<uint>(DAT_00252914 + 0xbc) & GuestRef<uint>(DAT_00252918 + 0x54)) != 0) {
        fall_accumulator_delta =
            BitsToFloat((u32)DAT_0025291c) -
            GuestRef<float>(param_1 + 0x173c) * fVar37;
        if (fall_accumulator_delta < 0.0f) {
          fall_accumulator_delta = 0.0f;
        }
        fVar32 = GuestRef<float>(param_1 + 0x1738) +
            fall_accumulator_delta;
        GuestRef<float>(param_1 + 0x1738) = fVar32;
        if ((iVar12 < (int)fVar32) &&
           (GuestRef<float>(param_1 + 0x1738) = 0.0f,
            GuestRef<sbyte>(param_1 + 2) == '\x02')) {
          if (GuestRef<int>(param_1 + 0x1734) != 0) {
            Audio_PlayActorSound2(GuestRef<int>(param_1 + 0x1734),DAT_00252924);
          }
          FUN_0040a0e8();
        }
      }
    }
    else {
      uVar24 = GuestRef<uint>(param_1 + 0x1710);
      if ((DAT_00252118 & uVar24) == 0) {
        if ((GuestRef<ushort>(param_1 + 0x90) & 1) == 0) {
          if ((uVar24 & 0x8000000) == 0) goto LAB_0025259c;
LAB_002522d4:
          if (GuestRef<sbyte>(param_1 + 0x1a7) == '\x01') goto LAB_002522e4;
          iVar12 = 0x37;
        }
        else {
          if ((uVar24 & 0x8000000) != 0) goto LAB_002522d4;
LAB_002522e4:
          iVar12 = DAT_002524e8;
          if (GuestRef<sbyte>(param_1 + 0x227d) != '\0') {
            iVar12 = 0xb6;
          }
        }
        bVar25 = (uVar24 & 0x8000000) != 0;
        if (bVar25) {
          uVar24 = (uint)GuestRef<byte>(param_1 + 0x1a7);
        }
        local_90 = GuestPtr<byte>((uint)bVar25 && uVar24 != 1);
        FUN_0036b0fc(param_2,param_1);
        FUN_0036b02c(param_2,param_1);
        FUN_0036055c(param_2,param_1);
        GuestRef<uint>(param_1 + 0x1710) = GuestRef<uint>(param_1 + 0x1710) | 0x80;
        Oot3d_PlayAnimationOnce(param_1 + 0x254,param_2,iVar12);
        iVar13 = DAT_002524f8;
        if (iVar12 == 0x17a) {
          GuestRef<undefined4>(param_1 + 0x29c) = DAT_002524f0;
        }
        GuestRef<float>(param_1 + 0x6c) = 0.0f;
        GuestRef<float>(param_1 + 0x221c) = 0.0f;
        uVar15 = DAT_002524f4;
        GuestRef<undefined1>(param_1 + 0x1749) = 0;
        GuestRef<undefined4>(iVar13 + 0xcc) = uVar15;
        GuestRef<undefined1>(iVar13 + 0xd4) = 0;
        if (GuestRef<sbyte>(param_1 + 2) == '\x02') {
          FUN_0036f59c(param_1,DAT_002524fc + (uint)GuestRef<ushort>(GuestRef<int>(param_1 + 0x170c) + 0xf4));
        }
        else {
          FUN_0036aeb4(param_1 + 0x28);
        }
        if (GuestRef<sbyte>(param_1 + 2) == '\x02') {
          FUN_0032eb30();
          iVar12 = FUN_001c4130(param_2);
          if (iVar12 == 0) {
            GuestRef<undefined2>(local_78 + 0x8c) = 1;
            FUN_00355f54(0);
            FUN_0035c528(DAT_00252500);
            iVar12 = DAT_00252504;
            GuestRef<undefined4>(DAT_00252504 + 0x558) = 0xff;
            GuestRef<undefined1>(iVar12 + 0x56e) = 0xff;
          }
          else {
            GuestRef<undefined2>(local_78 + 0x8c) = 0x14;
            GuestRef<undefined1>(param_1 + 0x2237) = 1;
          }
          local_a0 = 0.0;
          OnePointCutscene_Init(
              param_2,
              (int)DAT_00252508,
              (((GuestRef<uint>(param_1 + 0x1710) & 0x8000000) != 0) &&
               (GuestRef<byte>(param_1 + 0x1a7) != 1)) ? 120 : 60,
              param_1,
              0);
          ShrinkWindow_SetVal(*DAT_0025250c);
        }
      }
      else {
        FUN_0036b0fc(param_2,param_1);
        FUN_00345394(param_1,param_2);
      }
    }
  }
LAB_0025259c:
  iVar12 = oot3d_get_flag_22a0(param_2);
  if (iVar12 == 0) goto LAB_0025265c;
  if (GuestRef<sbyte>(param_1 + 0x12bc) == '\x06') {
LAB_00252684:
    GuestRef<undefined1>(param_1 + 0x1749) = 3;
  }
  else {
    uVar24 = GuestRef<uint>(param_1 + 0x1710);
    bVar25 = (uVar24 & 0x800000) == 0;
    if (bVar25) {
      uVar24 = GuestRef<uint>(param_1 + 0x1714);
    }
    bVar26 = (uVar24 & 0x80) == 0;
    bVar27 = bVar25 && bVar26;
    if (bVar25 && bVar26) {
      bVar27 = GuestRef<sbyte>(param_1 + 2) == '\x02';
    }
    if (bVar27) {
      if ((GuestRef<GuestPtr<ushort>>(local_68 + 0x2d8) != GuestPtr<ushort>(0x0)) &&
         (GuestRef<sbyte>(DAT_00252928 + (uint)GuestIndirectRef<ushort>(local_68 + 0x2d8)) != '\0')) {
        FUN_0036e980(param_2,0,6);
        GuestRef<float>(param_1 + 0x6c) = 0.0f;
        GuestRef<float>(param_1 + 0x221c) = 0.0f;
        goto LAB_0025265c;
      }
      if (GuestRef<sbyte>(param_1 + 0x12bc) == '\0') {
        if ((uVar24 & 0x400) == 0) {
          iVar12 = oot3d_get_flag_22a0(param_2);
          if (iVar12 != 3) {
            FUN_0036e980(param_2,0,0x31);
            GuestRef<float>(param_1 + 0x6c) = 0.0f;
            GuestRef<float>(param_1 + 0x221c) = 0.0f;
          }
          goto LAB_0025265c;
        }
        goto LAB_002526bc;
      }
LAB_00252668:
      if ((GuestRef<sbyte>(param_1 + 0x12bc) != '\a') ||
         ((GuestRef<uint>(param_1 + 0x1710) & DAT_0025292c) == 0)) goto LAB_00252684;
      if (GuestRef<int>(param_1 + 0x1708) != DAT_00252930) {
        FUN_003343ec(param_2,param_1,0);
      }
    }
    else {
LAB_0025265c:
      if (GuestRef<sbyte>(param_1 + 0x12bc) != '\0') goto LAB_00252668;
LAB_002526bc:
      GuestRef<undefined1>(param_1 + 0x12bd) = 0;
    }
  }
  fVar32 = DAT_00252940;
  piVar5 = GuestPtr<int>(DAT_00252938);
  GuestRef<undefined4>(param_1 + 0x74) = DAT_00252934;
  iVar12 = DAT_0025293c;
  fVar33 = (float)TargetSignedToFloat(
      (int)GuestRef<short>(*piVar5 + 0x9c), 0);
  GuestRef<float>(param_1 + 0x70) = fVar33 * fVar36;
  iVar12 = GuestRef<int>(iVar12 + 0x28);
  if (((iVar12 == 4 || iVar12 == 7) || iVar12 == 0xc) &&
      (GuestRef<int>(param_1 + 0x1708) != DAT_00252944)) {
    slope_base =
        TargetAbs(GuestRef<float>(param_1 + 0x221c)) *
        DAT_00251728;
    slope_delta = 0.0f;
    if (iVar12 == 4) {
      slope_limit = GuestRef<float>(param_1 + 0x1760);
      if (slope_limit <= BitsToFloat((u32)DAT_00252948)) {
        slope_limit = BitsToFloat((u32)DAT_0025294c);
      }
      if (GuestRef<sbyte>(param_1 + 0x1a7) == '\x02') {
        slope_base *= fVar28;
      }
      else {
        if (GuestRef<sbyte>(param_1 + 0x1a7) == '\x01') {
          slope_base *= fVar31;
        }
LAB_00252780:
        slope_delta =
            (slope_limit - GuestRef<float>(param_1 + 0x1760)) *
            fVar38;
        if (slope_delta < 0.0f) {
          slope_delta = 0.0f;
        }
        else if (slope_delta > BitsToFloat((u32)DAT_00252954)) {
          slope_delta = BitsToFloat((u32)DAT_00252958);
        }
        if (GuestRef<sbyte>(param_1 + 0x1a7) == '\x01') {
          slope_delta *= fVar28;
        }
      }
    }
    else {
      if (GuestRef<int>(param_1 + 0x1708) == DAT_00251cf0) {
        slope_base *= DAT_00252940;
      }
      slope_limit = BitsToFloat((u32)DAT_00252950);
      if (GuestRef<sbyte>(param_1 + 0x1a7) != '\x02') {
        slope_base *= fVar28;
        goto LAB_00252780;
      }
      if (iVar12 == 7) {
        slope_base = 0.0f;
      }
    }
    slope_value =
        GuestRef<float>(param_1 + 0x1760) +
        (slope_delta - slope_base);
    GuestRef<float>(param_1 + 0x1760) = slope_value;
    if (slope_value < 0.0f) {
      slope_value = 0.0f;
    }
    else if (slope_value > slope_limit) {
      slope_value = slope_limit;
    }
    GuestRef<float>(param_1 + 0x1760) = slope_value;
    GuestRef<float>(param_1 + 0x70) =
        fVar33 * fVar36 - slope_value * DAT_0025295c;
  }
  else {
    if ((GuestRef<uint>(param_1 + 0x29b8) & 0x100) == 0) {
      GuestRef<float>(param_1 + 0x1760) = 0.0f;
    }
    else {
      fVar32 = GuestRef<float>(param_1 + 0x1760) -
          GuestRef<float>(DAT_0025293c + 0x90);
      GuestRef<float>(param_1 + 0x1760) = fVar32;
      if (fVar32 <= 0.0f) {
        GuestRef<float>(param_1 + 0x1760) = 0.0f;
        GuestRef<uint>(param_1 + 0x29b8) =
            GuestRef<uint>(param_1 + 0x29b8) & 0xfffffeff;
      }
    }
    if (((GuestRef<int>(param_1 + 0x1708) == DAT_00251cd8) &&
         (fVar32 = GuestRef<float>(param_1 + 0x2c) -
                   GuestRef<float>(param_1 + 0x10c),
          GuestRef<float>(DAT_0025293c + 0x94) <= fVar32)) &&
        (iVar12 = DynaPoly_GetActor(
             local_88,
             GuestRef<undefined1>(param_1 + 0x81)),
         iVar12 == 0)) {
      GuestRef<uint>(param_1 + 0x29b8) |= 0x100;
      GuestRef<float>(param_1 + 0x1760) +=
          fVar32 * fVar29;
    }
  }
  iVar12 = DAT_00252dc0;
  fVar32 = DAT_00251340;
  if ((GuestRef<ushort>(param_1 + 0x90) & 0x20) != 0) {
    if (GuestRef<int>(param_1 + 0x88) < DAT_00252960) {
      iVar13 = DAT_00252960 + -0x1c80000;
      fVar32 = TargetAbs(GuestRef<float>(param_1 + 0x2340) - GuestRef<float>(local_60 + 0xa0)) +
               TargetAbs(GuestRef<float>(param_1 + 0x2344) - GuestRef<float>(local_60 + 0xa4)) +
               TargetAbs(GuestRef<float>(param_1 + 0x2348) - GuestRef<float>(local_60 + 0xa8));
      if (iVar13 < (int)fVar32) {
        fVar32 = DAT_00252964;
      }
      fVar32 = GuestRef<float>(param_1 + 0x223c) + fVar32;
      GuestRef<float>(param_1 + 0x223c) = fVar32;
      if (iVar12 < (int)fVar32) {
        GuestRef<float>(param_1 + 0x223c) = 0.0f;
        {
          GuestPtr<float> ripple_position(OwnerLocalAddress(0x04U));

          ripple_position[0] =
              GuestRef<float>(param_1 + 0x28) +
              Rand_ZeroOne() * DAT_00251d00;
          ripple_position[1] =
              GuestRef<float>(param_1 + 0x2c) +
              GuestRef<float>(param_1 + 0x88);
          ripple_position[2] =
              GuestRef<float>(param_1 + 0x30) +
              Rand_ZeroOne() * DAT_00251d00;
          EffectSsGRipple_Spawn(
              param_2,ripple_position,100,500,0);
        }
        if (iVar13 < (int)GuestRef<float>(param_1 + 0x221c)) {
          uVar24 = GuestRef<uint>(param_1 + 0x1710);
          bVar25 = (uVar24 & 0x8000000) != 0;
          if (bVar25) {
            uVar24 = (uint)GuestRef<byte>(param_1 + 0x1a7);
          }
          if ((!bVar25 || uVar24 == 1) &&
             (GuestRef<float>(param_1 + 0x2c) + GuestRef<float>(param_1 + 0x88) < GuestRef<float>(param_1 + 0x2344)
             )) {
            FUN_00358b3c(param_2,param_1,
                         (int)(TargetAbs(GuestRef<float>(param_1 + 0x221c)) * DAT_00252dc4 +
                              GuestRef<float>(param_1 + 0x88) * fVar37));
          }
        }
      }
    }
    if (BitsToFloat((u32)DAT_00252dc8) <
        GuestRef<float>(param_1 + 0x88)) {
      float bubble_velocity_y =
          GuestRef<float>(param_1 + 100);

      if (bubble_velocity_y >
              BitsToFloat((u32)DAT_00252dcc) ||
          (GuestRef<ushort>(param_1 + 0x90) & 1) != 0) {
        uVar24 = (uint)(Rand_ZeroOne() <
            BitsToFloat((u32)DAT_00252dd0));
      }
      else {
        uVar24 = (uint)(bubble_velocity_y *
            BitsToFloat((u32)DAT_00252dd4));
      }
      iVar12 = 0;
      while (iVar12 < (int)uVar24) {
        EffectSsBubble_Spawn(
            param_2,param_1 + 0x28,
            BitsToFloat((u32)DAT_00251728),
            DAT_00251d00,
            BitsToFloat((u32)DAT_00251728),
            0.13f);
        iVar12 = iVar12 + 1;
      }
    }
  }
  uVar24 = GuestRef<uint>(param_1 + 0x16f8);
  bVar25 = uVar24 == 0;
  if (bVar25) {
    uVar24 = (uint)GuestRef<ushort>(param_1 + 0x1728);
  }
  if (bVar25 && uVar24 == 0) {
    GuestRef<uint>(param_1 + 0x1714) = GuestRef<uint>(param_1 + 0x1714) & 0xffdffffd;
  }
  GuestRef<uint>(param_1 + 0x1710) = GuestRef<uint>(param_1 + 0x1710) & DAT_00252ddc;
  GuestRef<uint>(param_1 + 0x1714) = GuestRef<uint>(param_1 + 0x1714) & DAT_00252de0;
  GuestRef<byte>(param_1 + 0x172a) = GuestRef<byte>(param_1 + 0x172a) & 0xef;
  GuestRef<uint>(param_1 + 0x29b8) = GuestRef<uint>(param_1 + 0x29b8) & 0xefffffff;
  GuestRef<sbyte>(param_1 + 0x28f6) = (char)GuestRef<undefined4>(param_1 + 0x2498);
  GuestRef<undefined4>(param_1 + 0x2498) = 0;
  if ((GuestRef<ushort>(param_1 + 0x174a) & 2) == 0) {
    local_90 = GuestPtr<byte>((uint)GuestRef<ushort>(param_1 + 0x4a) - (uint)GuestRef<ushort>(param_1 + 0xbe));
    FUN_0032eadc(&local_90);
    GuestRef<short>(param_1 + 0x4a) = GuestRef<short>(param_1 + 0xbe) + (short)local_90;
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 1) == 0) {
    FUN_0032eadc(param_1 + 0x48);
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 8) == 0) {
    FUN_0032eadc(param_1 + 0x1750);
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 0x40) == 0) {
    FUN_0032eadc(param_1 + 0x1756);
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 4) == 0) {
    FUN_0032eadc(param_1 + 0x4c);
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 0x10) == 0) {
    FUN_0032eadc(param_1 + 0x1752);
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 0x20) == 0) {
    FUN_0032eadc(param_1 + 0x1754);
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 0x80) == 0) {
    if (GuestRef<short>(param_1 + 0x174c) == 0) {
      iVar12 = param_1 + 0x1758;
    }
    else {
      iVar12 = param_1 + 0x174c;
    }
    FUN_0032eadc(iVar12);
  }
  if ((GuestRef<ushort>(param_1 + 0x174a) & 0x100) == 0) {
    FUN_0032eadc(param_1 + 0x175a);
  }
  GuestRef<undefined2>(param_1 + 0x174a) = 0;
  local_8c = param_1 + 0x2800;
  GuestRef<undefined4>(local_60 + 0x8c) = GuestRef<undefined4>(param_1 + 0x29cc);
  GuestRef<undefined2>(local_60 + 0x90) = GuestRef<undefined2>(param_1 + 0x29d0);
  FUN_001a35cc(param_1 + 0x29cc,param_1 + 0x29d0,GuestRef<undefined4>(param_1 + 0x29c8));
  iVar12 = (int)GuestRef<short>(param_1 + 0x29d0);
  if ((iVar12 != 0) &&
     ((GuestRef<short>(DAT_0025293c + 0x10) * -0xb6 + 0x8000 < iVar12 ||
      (iVar12 < GuestRef<short>(DAT_0025293c + 0x10) * 0xb6 + -0x8000)))) {
    GuestRef<undefined2>(param_1 + 0x29d0) = 0x8000;
  }
  sVar11 = FUN_00368fec(GuestRef<undefined4>(param_2 + GuestRef<short>(DAT_00252de4 + param_2) * 4 + 0xa54));
  uVar24 = DAT_00252de8;
  sVar11 = sVar11 + GuestRef<short>(param_1 + 0x29d0);
  GuestRef<short>(param_1 + 0x29d2) = sVar11;
  uVar14 = GuestRef<byte>(param_1 + 0x222a) + 1;
  uVar14 = uVar14 + (uint)((ulonglong)uVar14 * (ulonglong)uVar24 >> 0x22) * -6;
  GuestRef<sbyte>(param_1 + 0x222a) = (char)uVar14;
  if (GuestRef<int>(local_8c + 0x1cc) < DAT_00252dec) {
    uVar20 = 0xff;
    uVar9 = 0xff;
  }
  else {
    uVar9 = (undefined1)(((int)GuestRef<short>(param_1 + 0x29d0) + 0x2000U & 0xffff) >> 9);
    uVar20 = (undefined1)
             (((int)(short)(sVar11 - GuestRef<short>(param_1 + 0xbe)) + 0x2000U & 0xffff) >> 0xe);
  }
  GuestRef<undefined1>((uVar14 & 0xff) + param_1 + 0x222b) = uVar9;
  GuestRef<undefined1>((uint)GuestRef<byte>(param_1 + 0x222a) + param_1 + 0x2231) = uVar20;
  if ((GuestRef<uint>(param_1 + 0x1710) & 0x8000000) == 0) {
    GuestRef<float>(DAT_0025293c + 0x2c) = 1.0f;
  }
  else {
    GuestRef<float>(DAT_0025293c + 0x2c) = DAT_00251340;
  }
  iVar12 = DAT_0025293c;
  GuestRef<float>(DAT_0025293c + 0x30) =
      1.0f / GuestRef<float>(DAT_0025293c + 0x2c);
  GuestRef<undefined4>(iVar12 + 0x50) = 0;
  GuestRef<undefined4>(iVar12 + 0x4c) = 0;
  GuestRef<uint>(iVar12 + 0x154) = (uint)GuestRef<byte>(param_1 + 0x1b7);
  if ((GuestRef<byte>(param_1 + 0x172a) & 4) == 0) {
    InvokeDynamicPlayerAction(
        GuestRef<u32>(param_1 + 0x1708), param_1, param_2);
  }
  if (GuestRef<sbyte>(param_1 + 2) == '\x02') {
    local_90 = GuestPtr<byte>(0x0);
    if (GuestRef<sbyte>(param_1 + 0x12bc) == '\0') {
      uVar24 = GuestRef<uint>(param_1 + 0x1710);
      if ((uVar24 & 0x100000) == 0) {
        bVar25 = GuestRef<int>(param_1 + 0x124) == 0;
        bVar8 = 0;
        if (!bVar25) {
          bVar8 = GuestRef<byte>(param_1 + 0x172a);
        }
        if (bVar25 || (bVar8 & 0x80) == 0) {
          if (GuestRef<int>(param_1 + 0x1708) == DAT_00253408) {
LAB_00252fdc:
            uVar15 = 0x12;
          }
          else if ((GuestRef<uint>(param_1 + 0x1714) & 0x100) == 0) {
            local_94 = GuestRef<float>(param_1 + 0x16f8);
            if (local_94 == 0.0) {
              if ((uVar24 & 0x1000) == 0) {
                if ((uVar24 & 0x2000000) == 0) {
                  if ((uVar24 & 0x6000) == 0) {
                    if ((DAT_00253410 & uVar24) == 0) {
                      if ((uVar24 & 0x240000) == 0) {
                        if ((uVar24 & 0x80000) == 0) {
                          if (((GuestRef<sbyte>(param_1 + 0x2227) != '\0') &&
                              (-1 < GuestRef<sbyte>(param_1 + 0x2226))) &&
                             (GuestRef<sbyte>(param_1 + 0x2226) < '\x18')) goto LAB_00252fdc;
                          uVar15 = 0;
                          if (GuestRef<float>(param_1 + 0x221c) == 0.0f) {
                            bVar25 = (uVar24 & 0x800000) == 0;
                            if (!bVar25) {
                              uVar24 = GuestRef<uint>(param_1 + 0x12b8);
                            }
                            if (!bVar25) {
                              bVar25 = GuestRef<float>(uVar24 + 0x6c) == 0.0f;
                            }
                            if (bVar25) {
                              local_90 = GuestPtr<byte>(0x2);
                            }
                          }
                        }
                        else {
                          uVar15 = 0x10;
                        }
                      }
                      else if ((GuestRef<int>(param_1 + 0x1708) == DAT_0025211c) ||
                              ((uVar24 & 0x200000) != 0)) {
                        uVar15 = 5;
                      }
                      else {
                        uVar15 = 0xd;
                      }
                    }
                    else {
                      iVar12 = FUN_0033bd6c(param_1);
                      if (iVar12 == 0) {
                        bVar25 = (GuestRef<uint>(param_1 + 0x1710) & 0x1000000) != 0;
                        if (!bVar25 ||
                            GuestRef<ushort>(param_1 + 0x2218) == 0) {
                          if ((GuestRef<uint>(param_1 + 0x1710) & 0x200000) == 0) {
                            uVar15 = 1;
                          }
                          else {
                            uVar15 = 0xc;
                          }
                          goto LAB_00253014;
                        }
                      }
                      uVar15 = 8;
                    }
                  }
                  else if ((uVar24 & DAT_0025340c) == 0) {
                    uVar15 = 0xe;
                  }
                  else {
                    uVar15 = 0xf;
                  }
                }
                else {
                  uVar15 = 0x14;
                  uVar19 = Gameplay_GetCamera(param_2,0);
                  Camera_SetParam(uVar19,8,GuestRef<undefined4>(param_1 + 0x171c));
                }
              }
              else {
                uVar15 = 0x11;
              }
            }
            else {
              if ((GuestRef<uint>(param_1 + 4) & 0x100) == 0) {
                if ((uVar24 & 0x10000) == 0) {
                  uVar15 = 4;
                }
                else if ((uVar24 & 0x2000000) == 0) {
                  uVar15 = 2;
                }
                else {
                  uVar15 = 0x14;
                }
              }
              else {
                uVar15 = 3;
              }
              uVar19 = Gameplay_GetCamera(param_2,0);
              Camera_SetParam(uVar19,8,local_94);
            }
          }
          else {
            uVar15 = 0x13;
          }
        }
        else {
          uVar15 = 9;
          uVar19 = Gameplay_GetCamera(param_2,0);
          Camera_SetParam(uVar19,8,GuestRef<undefined4>(param_1 + 0x124));
        }
LAB_00253014:
        uVar19 = Gameplay_GetCamera(param_2,0);
        goto LAB_00253024;
      }
      local_90 = GuestPtr<byte>(0x2);
    }
    else {
      uVar19 = Gameplay_GetCamera(param_2,0);
      uVar15 = 0;
LAB_00253024:
      Camera_ChangeMode(uVar19,uVar15);
    }
    if (GuestRef<int>(local_68 + 0x1a0) != 0) {
      local_90 = GuestPtr<byte>(0x1);
      FUN_0026f7ec(TargetSqrt(
          GuestRef<float>(
              GuestRef<int>(local_68 + 0x1a0) + 0x94)));
    }
    if (GuestRef<short>(local_70 + 4) != 0x49) {
      FUN_0032e780(local_90);
      GuestRef<sbyte>(param_1 + 0x174e) = (char)local_90;
    }
  }
  if ((GuestRef<byte>(param_1 + 0x2a6) & 8) != 0) {
    AnimationContext_SetMoveActor(param_2,param_1,param_1 + 0x254);
  }
  uVar24 = GuestRef<uint>(param_1 + 0x1714);
  sVar11 = GuestRef<short>(param_1 + 0xbe);
  if ((DAT_00253414 & uVar24) == 0) {
    if (GuestRef<int>(param_1 + 0x16f8) != 0) {
      cVar7 = GuestRef<sbyte>(local_68 + 0x147);
      bVar25 = cVar7 == '\0';
      if (bVar25) {
        cVar7 = GuestRef<sbyte>(param_1 + 2);
      }
      if (!bVar25 || cVar7 != '\x02') {
        uVar15 = (undefined4)(ushort)Math_Atan2S(
            GuestRef<float>(
                GuestRef<int>(param_1 + 0x16f8) + 0x44) -
                GuestRef<float>(param_1 + 0x30),
            GuestRef<float>(
                GuestRef<int>(param_1 + 0x16f8) + 0x3c) -
                GuestRef<float>(param_1 + 0x28));
        Math_ScaledStepToS(param_1 + 0xbe,uVar15,4000);
        goto LAB_00253154;
      }
    }
    if (((GuestRef<uint>(param_1 + 0x1710) & 0x20000) != 0) &&
       ((uVar24 & 0x60) == 0 && (GuestRef<uint>(param_1 + 0x1710) & 0x20000000) == 0)) {
      Math_ScaledStepToS(param_1 + 0xbe,(int)GuestRef<short>(param_1 + 0x2222),4000);
    }
  }
  else if ((uVar24 & 0x40) == 0) {
    Math_ScaledStepToS(param_1 + 0xbe,(int)GuestRef<short>(param_1 + 0x2220),2000);
  }
LAB_00253154:
  uVar15 = DAT_00253418;
  GuestRef<short>(param_1 + 0x2268) = GuestRef<short>(param_1 + 0xbe) - sVar11;
  if ((GuestRef<uint>(param_1 + 4) & 0x100) == 0) {
    GuestRef<undefined4>(param_1 + 0x172c) = 0;
    GuestRef<undefined4>(param_1 + 0x1730) = uVar15;
    GuestRef<undefined1>(param_1 + 0x172b) = 0;
  }
  else {
    GuestRef<undefined4>(param_1 + 0x1730) = 0;
  }
  if ((GuestRef<uint>(param_1 + 0x29b8) & 0x80) == 0) {
    GuestRef<undefined4>(param_1 + 0x1744) = 0;
  }
  uVar24 = GuestRef<uint>(param_1 + 0x1710);
  if ((uVar24 & 0x800) == 0) {
    GuestRef<undefined4>(param_1 + 0x12b0) = 0;
    GuestRef<undefined2>(local_80 + 0xae) = 0x6000;
  }
  if (GuestRef<int>(param_1 + 0x124) == 0) {
    GuestRef<undefined4>(param_1 + 0x12b8) = 0;
  }
  GuestRef<undefined2>(param_1 + 0x1728) = 0;
  if ((GuestRef<uint>(param_1 + 0x1714) & 0x2000000) == 0) {
    GuestRef<undefined4>(param_1 + 0x1740) = 0;
  }
  GuestRef<uint>(param_1 + 0x1714) = GuestRef<uint>(param_1 + 0x1714) & 0xff7fffff;
  GuestRef<undefined4>(param_1 + 0x1734) = 0;
  GuestRef<undefined4>(param_1 + 0x173c) = uVar15;
  GuestRef<undefined1>(param_1 + 0x12a4) = 0;
  GuestRef<undefined1>(param_1 + 0x2291) = 0;
  GuestRef<undefined4>(param_1 + 0x1718) = 0;
  fVar36 = GuestRef<float>(param_1 + 0x2c) -
      GuestRef<float>(param_1 + 0x10c);
  fVar32 = fVar36 +
      (GuestRef<float>(param_1 + 0x238c) +
       GuestRef<float>(param_1 + 0x2368)) *
      DAT_00251340;
  fVar38 = GuestRef<float>(param_1 + 0x2398) +
      fVar36 + DAT_00251d00;
  fVar36 = fVar38 - fVar32;
  GuestRef<float>(param_1 + 0x1354) = TargetAbs(fVar36);
  if (fVar36 < 0.0f) {
    fVar32 = fVar38;
  }
  GuestRef<float>(param_1 + 0x1358) =
      fVar32 - GuestRef<float>(param_1 + 0x2c);
  if ((uVar24 & 0x400000) != 0) {
    fVar32 = GuestRef<float>(param_1 + 0x1354) *
        DAT_00252940;
    GuestRef<float>(param_1 + 0x1354) = fVar32;
    if (GuestRef<int>(param_1 + 0x284) == 0xbd) {
      GuestRef<float>(param_1 + 0x1354) = fVar32 * DAT_0025341c;
    }
  }
  oot3d_copy_u32x3_field_28_to_field_4c(param_1,local_7c);
  if ((GuestRef<uint>(param_1 + 0x1714) & 0x4000) == 0) {
    iVar12 = param_2 + 0x5c78;
    if ((GuestRef<uint>(param_1 + 0x1710) & DAT_00253420) == 0) {
      CollisionCheck_SetOC(param_2,iVar12,local_7c);
    }
    if (((GuestRef<uint>(param_1 + 0x1710) & DAT_00253424) == 0) && (GuestRef<sbyte>(local_60 + 0x88) < '\x01')
       ) {
      if (GuestRef<byte>(param_1 + 0x249f) < 0xf) {
        CollisionCheck_SetAC(param_2,iVar12,local_7c);
      }
      if (GuestRef<sbyte>(local_60 + 0x88) < '\0') {
        CollisionCheck_SetAT(param_2,iVar12,local_7c);
      }
    }
  }
  FUN_003ab984(param_2);
LAB_0025330c:
  oot3d_copy_u32x3(param_1 + 8,param_1 + 0x28);
  oot3d_copy_u32x3(param_1 + 0x24a0,param_1 + 0x2340);
  if ((GuestRef<uint>(param_1 + 0x1710) & DAT_00253428) == 0) {
    uVar9 = 0x32;
  }
  else {
    uVar9 = 0xff;
  }
  GuestRef<undefined1>(param_1 + 0xb6) = uVar9;
  GuestRef<byte>(param_1 + 0x172a) = GuestRef<byte>(param_1 + 0x172a) & 0xfb;
  uVar24 = GuestRef<uint>(param_1 + 0x29b8);
  if ((uVar24 & 0x2000000) == 0) {
    bVar25 = (uVar24 & 0x1000000) != 0;
    if (bVar25) {
      uVar24 = (uint)GuestRef<byte>(param_1 + 0x1749);
    }
    if (bVar25 && uVar24 != 0) {
      FUN_0036b0fc(param_2,param_1);
    }
    GuestRef<uint>(param_1 + 0x29b8) = GuestRef<uint>(param_1 + 0x29b8) & 0xfeffffff;
  }
  Collider_ResetCylinderAC(param_2,local_7c);
  Collider_ResetQuadAT(param_2,param_1 + 0x1368);
  Collider_ResetQuadAT(param_2,param_1 + 0x13e8);
  Collider_ResetQuadAC(param_2,param_1 + 0x1568);
  Collider_ResetQuadAT(param_2,param_1 + 0x1568);
  Collider_ResetJntSphAT(param_2,param_1 + 0x15e8);
  Collider_ResetQuadAT(param_2,param_1 + 0x1468);
  Collider_ResetQuadAT(param_2,param_1 + 0x14e8);
  return;
}

#undef DAT_00253428
#undef DAT_00253424
#undef DAT_00253420
#undef DAT_0025341c
#undef DAT_00253418
#undef DAT_00253414
#undef DAT_00253410
#undef DAT_0025340c
#undef DAT_00253408
#undef DAT_00252dec
#undef DAT_00252de8
#undef DAT_00252de4
#undef DAT_00252de0
#undef DAT_00252ddc
#undef DAT_00252dd4
#undef DAT_00252dd0
#undef DAT_00252dcc
#undef DAT_00252dc8
#undef DAT_00252dc4
#undef DAT_00252dc0
#undef DAT_00252964
#undef DAT_00252960
#undef DAT_0025295c
#undef DAT_00252958
#undef DAT_00252954
#undef DAT_00252950
#undef DAT_0025294c
#undef DAT_00252948
#undef DAT_00252944
#undef DAT_00252940
#undef DAT_0025293c
#undef DAT_00252938
#undef DAT_00252934
#undef DAT_00252930
#undef DAT_0025292c
#undef DAT_00252928
#undef DAT_00252924
#undef DAT_00252920
#undef DAT_0025291c
#undef DAT_00252918
#undef DAT_00252914
#undef DAT_00252510
#undef DAT_0025250c
#undef DAT_00252508
#undef DAT_00252504
#undef DAT_00252500
#undef DAT_002524fc
#undef DAT_002524f8
#undef DAT_002524f4
#undef DAT_002524f0
#undef DAT_002524e8
#undef DAT_002524e4
#undef DAT_002524e0
#undef DAT_002524d8
#undef DAT_002524d4
#undef DAT_00252168
#undef DAT_00252164
#undef DAT_00252160
#undef DAT_0025215c
#undef DAT_00252158
#undef DAT_00252154
#undef DAT_00252150
#undef DAT_0025214c
#undef DAT_00252148
#undef DAT_00252144
#undef DAT_00252140
#undef DAT_0025213c
#undef DAT_00252138
#undef DAT_00252134
#undef DAT_0025212c
#undef DAT_00252128
#undef DAT_00252124
#undef DAT_00252120
#undef DAT_0025211c
#undef DAT_00252118
#undef DAT_00251d30
#undef DAT_00251d28
#undef DAT_00251d24
#undef DAT_00251d20
#undef DAT_00251d1c
#undef DAT_00251d14
#undef DAT_00251d10
#undef DAT_00251d0c
#undef DAT_00251d08
#undef DAT_00251d04
#undef DAT_00251d00
#undef DAT_00251cfc
#undef DAT_00251cf8
#undef DAT_00251cf4
#undef DAT_00251cf0
#undef DAT_00251cec
#undef DAT_00251ce8
#undef DAT_00251ce4
#undef DAT_00251ce0
#undef DAT_00251cdc
#undef DAT_00251cd8
#undef DAT_00251cd4
#undef DAT_00251744
#undef DAT_00251740
#undef DAT_0025173c
#undef DAT_00251738
#undef DAT_00251734
#undef DAT_00251730
#undef DAT_0025172c
#undef DAT_00251728
#undef DAT_00251724
#undef DAT_00251720
#undef DAT_0025171c
#undef DAT_00251718
#undef DAT_00251714
#undef DAT_00251368
#undef DAT_00251364
#undef DAT_00251360
#undef DAT_0025135c
#undef DAT_00251358
#undef DAT_00251354
#undef DAT_00251350
#undef DAT_0025134c
#undef DAT_00251348
#undef DAT_00251344
#undef DAT_00251340
#undef DAT_0025133c
#undef DAT_00251338
#undef DAT_00251334
#undef DAT_00251330
#undef DAT_0025132c
#undef DAT_00251328
#undef DAT_00251324
#undef DAT_00251320
#undef DAT_0025131c
#undef DAT_00251318
#undef DAT_00251314
#undef DAT_00251310
#undef DAT_0025130c
#undef DAT_00251308
#undef DAT_00251304

} // namespace Oot3dSourcePlayerUpdateCommon
