// Generated by tools/build_ui_frontend_resources_tranche_230.py.
#include "oot3d_ui/ui_frontend_resources.h"

#include <array>
#include <cstddef>
#include <cstdint>

namespace oot3d::ui {

namespace {

inline constexpr std::array<UiFrontendLanguageResource,
                            kOot3dUiLanguageCount> kLanguages = {{
    {Oot3dUiLanguage::Japanese, 0, "Japanese", "rom:/menu/00_JP_JAPANESE/", true, false},
    {Oot3dUiLanguage::UsEnglish, 1, "US English", "rom:/menu/01_US_ENGLISH/", true, true},
    {Oot3dUiLanguage::EuEnglish, 2, "EU English", "rom:/menu/02_EU_ENGLISH/", true, true},
    {Oot3dUiLanguage::EuGerman, 3, "EU German", "rom:/menu/03_EU_GERMAN/", true, true},
    {Oot3dUiLanguage::EuFrench, 4, "EU French", "rom:/menu/04_EU_FRENCH/", true, true},
    {Oot3dUiLanguage::UsFrench, 5, "US French", "rom:/menu/05_US_FRENCH/", true, true},
    {Oot3dUiLanguage::EuSpanish, 6, "EU Spanish", "rom:/menu/06_EU_SPANISH/", true, true},
    {Oot3dUiLanguage::UsSpanish, 7, "US Spanish", "rom:/menu/07_US_SPANISH/", true, true},
    {Oot3dUiLanguage::EuItalian, 8, "EU Italian", "rom:/menu/08_EU_ITALIAN/", true, true},
    {Oot3dUiLanguage::EuDutch, 9, "EU Dutch", "rom:/menu/09_EU_DUTCH/", false, true},
}};

inline constexpr std::array<UiFrontendAtlasResourceView,
                            kOot3dFrontendDeclaredAtlasCount> kAtlases = {{
    {Oot3dUiLanguage::Japanese, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/00_JP_JAPANESE/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::Japanese, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/00_JP_JAPANESE/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::Japanese, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/00_JP_JAPANESE/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::Japanese, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/00_JP_JAPANESE/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::UsEnglish, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/01_US_ENGLISH/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::UsEnglish, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/01_US_ENGLISH/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::UsEnglish, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/01_US_ENGLISH/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::UsEnglish, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/01_US_ENGLISH/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::EuEnglish, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/02_EU_ENGLISH/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::EuEnglish, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/02_EU_ENGLISH/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::EuEnglish, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/02_EU_ENGLISH/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::EuEnglish, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/02_EU_ENGLISH/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::EuGerman, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/03_EU_GERMAN/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::EuGerman, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/03_EU_GERMAN/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::EuGerman, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/03_EU_GERMAN/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::EuGerman, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/03_EU_GERMAN/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::EuFrench, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/04_EU_FRENCH/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::EuFrench, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/04_EU_FRENCH/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::EuFrench, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/04_EU_FRENCH/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::EuFrench, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/04_EU_FRENCH/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::UsFrench, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/05_US_FRENCH/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::UsFrench, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/05_US_FRENCH/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::UsFrench, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/05_US_FRENCH/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::UsFrench, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/05_US_FRENCH/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::EuSpanish, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/06_EU_SPANISH/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::EuSpanish, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/06_EU_SPANISH/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::EuSpanish, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/06_EU_SPANISH/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::EuSpanish, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/06_EU_SPANISH/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::UsSpanish, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/07_US_SPANISH/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::UsSpanish, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/07_US_SPANISH/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::UsSpanish, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/07_US_SPANISH/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::UsSpanish, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/07_US_SPANISH/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::EuItalian, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/08_EU_ITALIAN/name_entry00_parts00.ctxb", 524360, true},
    {Oot3dUiLanguage::EuItalian, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/08_EU_ITALIAN/name_entry00_parts01.ctxb", 524360, true},
    {Oot3dUiLanguage::EuItalian, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/08_EU_ITALIAN/menu_file_select_parts00.ctxb", 262216, true},
    {Oot3dUiLanguage::EuItalian, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/08_EU_ITALIAN/menu_file_select_parts01.ctxb", 262216, true},
    {Oot3dUiLanguage::EuDutch, UiFrontendAtlasKind::NameEntryParts00, "rom:/menu/09_EU_DUTCH/name_entry00_parts00.ctxb", 0, false},
    {Oot3dUiLanguage::EuDutch, UiFrontendAtlasKind::NameEntryParts01, "rom:/menu/09_EU_DUTCH/name_entry00_parts01.ctxb", 0, false},
    {Oot3dUiLanguage::EuDutch, UiFrontendAtlasKind::FileSelectParts00, "rom:/menu/09_EU_DUTCH/menu_file_select_parts00.ctxb", 0, false},
    {Oot3dUiLanguage::EuDutch, UiFrontendAtlasKind::FileSelectParts01, "rom:/menu/09_EU_DUTCH/menu_file_select_parts01.ctxb", 0, false},
}};

inline constexpr std::array<std::uint16_t, 47> kLowercaseAlphabet = {{
    0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037, 0x0038,
    0x0039, 0x0030, 0x002D, 0x003D, 0x0071, 0x0077, 0x0065, 0x0072,
    0x0074, 0x0079, 0x0075, 0x0069, 0x006F, 0x0070, 0x0061, 0x0073,
    0x0064, 0x0066, 0x0067, 0x0068, 0x006A, 0x006B, 0x006C, 0x007A,
    0x0078, 0x0063, 0x0076, 0x0062, 0x006E, 0x006D, 0x002C, 0x002E,
    0x002F, 0x003B, 0x0027, 0x0020, 0x005B, 0x005D, 0x0022,
}};
inline constexpr std::array<std::uint16_t, 47> kUppercaseAlphabet = {{
    0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037, 0x0038,
    0x0039, 0x0030, 0x002D, 0x003D, 0x0051, 0x0057, 0x0045, 0x0052,
    0x0054, 0x0059, 0x0055, 0x0049, 0x004F, 0x0050, 0x0041, 0x0053,
    0x0044, 0x0046, 0x0047, 0x0048, 0x004A, 0x004B, 0x004C, 0x005A,
    0x0058, 0x0043, 0x0056, 0x0042, 0x004E, 0x004D, 0x002C, 0x002E,
    0x002F, 0x003B, 0x0027, 0x0020, 0x005B, 0x005D, 0x0022,
}};
inline constexpr std::array<std::uint16_t, 46> kSymbolsAlphabet = {{
    0x0021, 0x0040, 0x0023, 0x0024, 0x0025, 0x005E, 0x0026, 0x002A,
    0x0028, 0x0029, 0x005F, 0x002B, 0x0051, 0x0057, 0x0045, 0x0052,
    0x0054, 0x0059, 0x0055, 0x0049, 0x004F, 0x0050, 0x0041, 0x0053,
    0x0044, 0x0046, 0x0047, 0x0048, 0x004A, 0x004B, 0x004C, 0x005A,
    0x0058, 0x0043, 0x0056, 0x0042, 0x004E, 0x004D, 0x003C, 0x003E,
    0x003F, 0x003A, 0x007E, 0x0020, 0x007B, 0x007D,
}};
inline constexpr std::array<std::uint16_t, 61> kEuropeanAlphabet = {{
    0x00E0, 0x00E1, 0x00E2, 0x00E4, 0x00E6, 0x00E8, 0x00E9, 0x00EA,
    0x00EB, 0x00EC, 0x00ED, 0x00EE, 0x00EF, 0x00F2, 0x00F3, 0x00F4,
    0x00F6, 0x0153, 0x00F9, 0x00FA, 0x00FB, 0x00FC, 0x00E7, 0x00F1,
    0x00DF, 0x00C0, 0x00C1, 0x00C2, 0x00C4, 0x00C6, 0x00C8, 0x00C9,
    0x00CA, 0x00CB, 0x00CC, 0x00CD, 0x00CE, 0x00CF, 0x00D2, 0x00D3,
    0x00D4, 0x00D6, 0x0152, 0x00D9, 0x00DA, 0x00DB, 0x00DC, 0x00C7,
    0x00D1, 0x00A1, 0x00BF, 0x20AC, 0x00A2, 0x00A3, 0x0020, 0x0020,
    0x0020, 0x0020, 0x0020, 0x0020, 0x0020,
}};

inline constexpr std::array<UiNameEntryAlphabetResourceView,
                            kOot3dNameEntryLocalizedAlphabetCount>
    kLocalizedAlphabets = {{
    {UiNameEntryLocalizedAlphabet::Lowercase, "rom:/menu/ltn16_alpha0.list", kLowercaseAlphabet.data(), 47, 96, 0x0055B64C, 0x0055B64E, 0x200, true},
    {UiNameEntryLocalizedAlphabet::Uppercase, "rom:/menu/ltn16_alpha1.list", kUppercaseAlphabet.data(), 47, 96, 0x0055B84C, 0x0055B84E, 0x200, true},
    {UiNameEntryLocalizedAlphabet::Symbols, "rom:/menu/ltn16_alpha2.list", kSymbolsAlphabet.data(), 46, 94, 0x0055BA4C, 0x0055BA4E, 0x200, true},
    {UiNameEntryLocalizedAlphabet::European, "rom:/menu/ltn16_euro.list", kEuropeanAlphabet.data(), 61, 124, 0x0055BC4C, 0x0055BC4E, 0x200, true},
}};

constexpr std::size_t ToIndex(Oot3dUiLanguage language) noexcept {
    return static_cast<std::size_t>(language);
}

constexpr std::size_t ToIndex(UiFrontendAtlasKind kind) noexcept {
    return static_cast<std::size_t>(kind);
}

constexpr std::size_t ToIndex(
    UiNameEntryLocalizedAlphabet alphabet) noexcept {
    return static_cast<std::size_t>(alphabet);
}

} // namespace

const std::array<UiFrontendLanguageResource, kOot3dUiLanguageCount>&
Oot3dFrontendLanguageResources() noexcept {
    return kLanguages;
}

const UiFrontendLanguageResource* Oot3dFrontendLanguageResourceFor(
    Oot3dUiLanguage language) noexcept {
    const auto index = ToIndex(language);
    return index < kLanguages.size() ? &kLanguages[index] : nullptr;
}

UiFrontendAtlasResourceView Oot3dFrontendAtlasResource(
    Oot3dUiLanguage language, UiFrontendAtlasKind kind) noexcept {
    const auto language_index = ToIndex(language);
    const auto kind_index = ToIndex(kind);
    if (language_index >= kOot3dUiLanguageCount ||
        kind_index >= kOot3dFrontendAtlasKindCount) {
        return {};
    }
    return kAtlases[
        language_index * kOot3dFrontendAtlasKindCount + kind_index];
}

std::array<UiFrontendAtlasResourceView, 2> Oot3dNameEntryAtlasResources(
    Oot3dUiLanguage language) noexcept {
    return {{
        Oot3dFrontendAtlasResource(
            language, UiFrontendAtlasKind::NameEntryParts00),
        Oot3dFrontendAtlasResource(
            language, UiFrontendAtlasKind::NameEntryParts01),
    }};
}

UiFileSelectAtlasVariant Oot3dFileSelectAtlasVariantFromNativeFlag(
    std::uint8_t native_flag) noexcept {
    return native_flag == 1 ? UiFileSelectAtlasVariant::Parts01
                            : UiFileSelectAtlasVariant::Parts00;
}

UiFrontendAtlasResourceView Oot3dFileSelectAtlasResource(
    Oot3dUiLanguage language, std::uint8_t native_variant_flag) noexcept {
    const auto variant =
        Oot3dFileSelectAtlasVariantFromNativeFlag(native_variant_flag);
    const auto kind = variant == UiFileSelectAtlasVariant::Parts01
                          ? UiFrontendAtlasKind::FileSelectParts01
                          : UiFrontendAtlasKind::FileSelectParts00;
    return Oot3dFrontendAtlasResource(language, kind);
}

const std::array<UiNameEntryAlphabetResourceView,
                 kOot3dNameEntryLocalizedAlphabetCount>&
Oot3dNameEntryLocalizedAlphabetResources() noexcept {
    return kLocalizedAlphabets;
}

UiNameEntryAlphabetResourceView Oot3dNameEntryLocalizedAlphabetResource(
    UiNameEntryLocalizedAlphabet alphabet) noexcept {
    const auto index = ToIndex(alphabet);
    return index < kLocalizedAlphabets.size() ? kLocalizedAlphabets[index]
                                              : UiNameEntryAlphabetResourceView{};
}

bool Oot3dNameEntryLoadsLocalizedAlphabets(
    Oot3dUiLanguage language) noexcept {
    const auto* resource = Oot3dFrontendLanguageResourceFor(language);
    return resource != nullptr && resource->name_entry_loads_localized_alphabets;
}

static_assert(kLanguages.size() == 10);
static_assert(kAtlases.size() == 40);
static_assert(kLocalizedAlphabets.size() == 4);
static_assert(kLocalizedAlphabets[0].destination_address ==
              kOot3dNameEntryLocalizedAlphabetAddress);
static_assert(kLocalizedAlphabets[3].destination_address ==
              kOot3dNameEntryLocalizedAlphabetAddress + 3 * 0x200);

} // namespace oot3d::ui
