// Generated by tools/build_ui_localized_menu_resources_tranche_231.py.
#include "oot3d_ui/ui_localized_menu_resources.h"

#include <array>
#include <cstddef>

namespace oot3d::ui {

namespace {

inline constexpr std::array<UiLocalizedMenuTextureDescriptor,
                            kOot3dLocalizedMenuTextureKindCount>
    kDescriptors = {{
    {UiLocalizedMenuTextureKind::CommonBackground00, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::CommonBackground00, "common_background00", "shared pause background", "common_bg00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 256, 1, 4, 1, 1, true, true},
    {UiLocalizedMenuTextureKind::HudAtlas, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::HudAtlas, "hud_atlas", "HUD controls and indicators atlas", "hud_all00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 256, 1, 16, 7, 1, false, true},
    {UiLocalizedMenuTextureKind::PauseTopPage, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::PauseTopPage, "pause_top_page", "native pause top-page parts", "menu_top_parts00.ctxb", "PauseUi_LoadSharedTextureAssets", 512, 256, 1, 16, 6, 1, false, true},
    {UiLocalizedMenuTextureKind::ItemPage, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::ItemPage, "item_page", "pause item-page parts", "menu_item_parts00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 256, 1, 8, 6, 1, true, true},
    {UiLocalizedMenuTextureKind::EquipmentPage, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::EquipmentPage, "equipment_page", "pause equipment-page parts", "menu_equip_parts00.ctxb", "PauseUi_LoadSharedTextureAssets", 512, 256, 1, 8, 6, 1, true, true},
    {UiLocalizedMenuTextureKind::OcarinaPage, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::OcarinaPage, "ocarina_page", "pause ocarina-page parts", "menu_okarina_parts00.ctxb", "PauseUi_LoadSharedTextureAssets", 512, 256, 1, 8, 6, 1, true, true},
    {UiLocalizedMenuTextureKind::MapPage00, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::MapPage00, "map_page00", "pause map-page primary parts", "menu_map_parts00.ctxb", "PauseUi_LoadSharedTextureAssets", 512, 256, 1, 8, 8, 1, true, true},
    {UiLocalizedMenuTextureKind::MapPage01, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::MapPage01, "map_page01", "pause map-page secondary parts", "menu_map_parts01.ctxb", "PauseUi_LoadSharedTextureAssets", 512, 256, 1, 8, 8, 1, true, true},
    {UiLocalizedMenuTextureKind::FieldMapClouds, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::FieldMapClouds, "field_map_clouds", "field-map cloud parts", "fieldmap_cloud_parts00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 256, 1, 8, 1, 1, true, true},
    {UiLocalizedMenuTextureKind::NumberGlyphs, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::NumberGlyphs, "number_glyphs", "shared numeric glyph atlas", "num_all00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 128, 1, 16, 1, 1, false, true},
    {UiLocalizedMenuTextureKind::ItemIcons, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::ItemIcons, "item_icons", "menu item-icon atlas", "icon_item_menu00.ctxb", "PauseUi_LoadSharedTextureAssets", 512, 512, 1, 8, 4, 1, true, true},
    {UiLocalizedMenuTextureKind::HudMenuTitle, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::HudMenuTitle, "hud_menu_title", "localized HUD/menu titles", "hud_menu_title00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 256, 1, 8, 6, 1, true, true},
    {UiLocalizedMenuTextureKind::OptionsPage, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::OptionsPage, "options_page", "pause options-page parts", "menu_option_parts00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 256, 1, 8, 7, 1, true, true},
    {UiLocalizedMenuTextureKind::Cursor, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::Cursor, "cursor", "menu cursor atlas", "menu_cursor00.ctxb", "PauseUi_LoadSharedTextureAssets", 128, 128, 1, 16, 2, 1, false, true},
    {UiLocalizedMenuTextureKind::ItemPageAux, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::ItemPageAux, "item_page_aux", "pause item-page auxiliary parts", "menu_item_parts01.ctxb", "PauseUi_LoadSharedTextureAssets", 64, 128, 1, 16, 2, 2, false, true},
    {UiLocalizedMenuTextureKind::CameraInterface, UiLocalizedMenuResourceOwner::PauseShared, UiPauseSharedTextureSlot::CameraInterface, "camera_interface", "camera interface atlas", "cam_interface00.ctxb", "PauseUi_LoadSharedTextureAssets", 256, 128, 1, 16, 1, 1, false, true},
    {UiLocalizedMenuTextureKind::PauseTopMap, UiLocalizedMenuResourceOwner::PauseMap, UiPauseSharedTextureSlot::Count, "pause_top_map", "pause top-map texture", "menu_top_map00.ctxb", "PauseMapResources_Initialize", 256, 256, 1, 8, 1, 1, true, true},
    {UiLocalizedMenuTextureKind::HintMovie, UiLocalizedMenuResourceOwner::HintMovie, UiPauseSharedTextureSlot::Count, "hint_movie", "hint-movie interface parts", "menu_hint_movie_parts00.ctxb", "HintMovie_InitRenderer", 512, 128, 1, 32, 6, 1, false, true},
    {UiLocalizedMenuTextureKind::FileSelectParts00, UiLocalizedMenuResourceOwner::FileSelect, UiPauseSharedTextureSlot::Count, "file_select_parts00", "file-select atlas variant 00", "menu_file_select_parts00.ctxb", "FileSelect_LoadLocalizedTextures", 512, 256, 1, 16, 6, 1, false, true},
    {UiLocalizedMenuTextureKind::FileSelectParts01, UiLocalizedMenuResourceOwner::FileSelect, UiPauseSharedTextureSlot::Count, "file_select_parts01", "file-select atlas variant 01", "menu_file_select_parts01.ctxb", "FileSelect_LoadLocalizedTextures", 512, 256, 1, 16, 6, 1, false, true},
    {UiLocalizedMenuTextureKind::NameEntryParts00, UiLocalizedMenuResourceOwner::NameEntry, UiPauseSharedTextureSlot::Count, "name_entry_parts00", "name-entry primary atlas", "name_entry00_parts00.ctxb", "NameEntry_LoadLocalizedAssets", 512, 512, 1, 16, 6, 1, false, true},
    {UiLocalizedMenuTextureKind::NameEntryParts01, UiLocalizedMenuResourceOwner::NameEntry, UiPauseSharedTextureSlot::Count, "name_entry_parts01", "name-entry secondary atlas", "name_entry00_parts01.ctxb", "NameEntry_LoadLocalizedAssets", 512, 512, 1, 16, 6, 1, false, true},
    {UiLocalizedMenuTextureKind::CommonBackground01, UiLocalizedMenuResourceOwner::NoReviewedLocalizedLoader, UiPauseSharedTextureSlot::Count, "common_background01", "localized-pack copy with no reviewed localized loader", "common_bg01.ctxb", nullptr, 512, 256, 1, 4, 1, 1, true, false},
}};

inline constexpr std::array<UiLocalizedMenuTextureResourceView,
                            kOot3dLocalizedMenuTextureSlotCount>
    kResources = {{
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/00_JP_JAPANESE/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/00_JP_JAPANESE/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/00_JP_JAPANESE/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/00_JP_JAPANESE/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/00_JP_JAPANESE/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/00_JP_JAPANESE/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/00_JP_JAPANESE/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/00_JP_JAPANESE/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/00_JP_JAPANESE/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/00_JP_JAPANESE/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/00_JP_JAPANESE/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/00_JP_JAPANESE/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/00_JP_JAPANESE/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/00_JP_JAPANESE/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/00_JP_JAPANESE/menu_item_parts01.ctxb", 16456, 16384, 0x6752, 0x8034, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/00_JP_JAPANESE/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/00_JP_JAPANESE/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/00_JP_JAPANESE/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/00_JP_JAPANESE/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/00_JP_JAPANESE/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/00_JP_JAPANESE/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/00_JP_JAPANESE/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::Japanese, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/00_JP_JAPANESE/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/01_US_ENGLISH/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/01_US_ENGLISH/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/01_US_ENGLISH/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/01_US_ENGLISH/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/01_US_ENGLISH/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/01_US_ENGLISH/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/01_US_ENGLISH/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/01_US_ENGLISH/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/01_US_ENGLISH/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/01_US_ENGLISH/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/01_US_ENGLISH/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/01_US_ENGLISH/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/01_US_ENGLISH/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/01_US_ENGLISH/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/01_US_ENGLISH/menu_item_parts01.ctxb", 16456, 16384, 0x6752, 0x8034, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/01_US_ENGLISH/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/01_US_ENGLISH/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/01_US_ENGLISH/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/01_US_ENGLISH/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/01_US_ENGLISH/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/01_US_ENGLISH/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/01_US_ENGLISH/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsEnglish, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/01_US_ENGLISH/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/02_EU_ENGLISH/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/02_EU_ENGLISH/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/02_EU_ENGLISH/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/02_EU_ENGLISH/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/02_EU_ENGLISH/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/02_EU_ENGLISH/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/02_EU_ENGLISH/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/02_EU_ENGLISH/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/02_EU_ENGLISH/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/02_EU_ENGLISH/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/02_EU_ENGLISH/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/02_EU_ENGLISH/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/02_EU_ENGLISH/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/02_EU_ENGLISH/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/02_EU_ENGLISH/menu_item_parts01.ctxb", 16456, 16384, 0x6752, 0x8034, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/02_EU_ENGLISH/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/02_EU_ENGLISH/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/02_EU_ENGLISH/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/02_EU_ENGLISH/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/02_EU_ENGLISH/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/02_EU_ENGLISH/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/02_EU_ENGLISH/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuEnglish, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/02_EU_ENGLISH/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/03_EU_GERMAN/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/03_EU_GERMAN/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/03_EU_GERMAN/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/03_EU_GERMAN/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/03_EU_GERMAN/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/03_EU_GERMAN/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/03_EU_GERMAN/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/03_EU_GERMAN/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/03_EU_GERMAN/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/03_EU_GERMAN/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/03_EU_GERMAN/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/03_EU_GERMAN/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/03_EU_GERMAN/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/03_EU_GERMAN/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/03_EU_GERMAN/menu_item_parts01.ctxb", 16456, 16384, 0x6752, 0x8034, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/03_EU_GERMAN/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/03_EU_GERMAN/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/03_EU_GERMAN/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/03_EU_GERMAN/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/03_EU_GERMAN/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/03_EU_GERMAN/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/03_EU_GERMAN/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuGerman, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/03_EU_GERMAN/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/04_EU_FRENCH/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/04_EU_FRENCH/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/04_EU_FRENCH/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/04_EU_FRENCH/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/04_EU_FRENCH/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/04_EU_FRENCH/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/04_EU_FRENCH/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/04_EU_FRENCH/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/04_EU_FRENCH/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/04_EU_FRENCH/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/04_EU_FRENCH/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/04_EU_FRENCH/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/04_EU_FRENCH/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/04_EU_FRENCH/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/04_EU_FRENCH/menu_item_parts01.ctxb", 16456, 16384, 0x6752, 0x8034, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/04_EU_FRENCH/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/04_EU_FRENCH/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/04_EU_FRENCH/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/04_EU_FRENCH/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/04_EU_FRENCH/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/04_EU_FRENCH/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/04_EU_FRENCH/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuFrench, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/04_EU_FRENCH/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/05_US_FRENCH/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/05_US_FRENCH/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/05_US_FRENCH/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/05_US_FRENCH/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/05_US_FRENCH/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/05_US_FRENCH/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/05_US_FRENCH/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/05_US_FRENCH/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/05_US_FRENCH/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/05_US_FRENCH/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/05_US_FRENCH/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/05_US_FRENCH/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/05_US_FRENCH/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/05_US_FRENCH/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/05_US_FRENCH/menu_item_parts01.ctxb", 16456, 16384, 0x6754, 0x8363, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/05_US_FRENCH/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/05_US_FRENCH/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/05_US_FRENCH/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/05_US_FRENCH/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/05_US_FRENCH/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/05_US_FRENCH/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/05_US_FRENCH/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsFrench, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/05_US_FRENCH/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/06_EU_SPANISH/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/06_EU_SPANISH/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/06_EU_SPANISH/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/06_EU_SPANISH/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/06_EU_SPANISH/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/06_EU_SPANISH/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/06_EU_SPANISH/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/06_EU_SPANISH/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/06_EU_SPANISH/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/06_EU_SPANISH/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/06_EU_SPANISH/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/06_EU_SPANISH/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/06_EU_SPANISH/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/06_EU_SPANISH/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/06_EU_SPANISH/menu_item_parts01.ctxb", 16456, 16384, 0x6754, 0x8363, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/06_EU_SPANISH/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/06_EU_SPANISH/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/06_EU_SPANISH/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/06_EU_SPANISH/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/06_EU_SPANISH/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/06_EU_SPANISH/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/06_EU_SPANISH/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuSpanish, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/06_EU_SPANISH/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/07_US_SPANISH/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/07_US_SPANISH/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/07_US_SPANISH/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/07_US_SPANISH/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/07_US_SPANISH/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/07_US_SPANISH/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/07_US_SPANISH/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/07_US_SPANISH/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/07_US_SPANISH/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/07_US_SPANISH/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/07_US_SPANISH/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/07_US_SPANISH/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/07_US_SPANISH/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/07_US_SPANISH/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/07_US_SPANISH/menu_item_parts01.ctxb", 16456, 16384, 0x6754, 0x8363, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/07_US_SPANISH/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/07_US_SPANISH/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/07_US_SPANISH/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/07_US_SPANISH/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/07_US_SPANISH/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/07_US_SPANISH/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/07_US_SPANISH/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::UsSpanish, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/07_US_SPANISH/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/08_EU_ITALIAN/common_bg00.ctxb", 32840, 32768, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/08_EU_ITALIAN/hud_all00.ctxb", 131144, 131072, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/08_EU_ITALIAN/menu_top_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/08_EU_ITALIAN/menu_item_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/08_EU_ITALIAN/menu_equip_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/08_EU_ITALIAN/menu_okarina_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/08_EU_ITALIAN/menu_map_parts00.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/08_EU_ITALIAN/menu_map_parts01.ctxb", 131144, 131072, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/08_EU_ITALIAN/fieldmap_cloud_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/08_EU_ITALIAN/num_all00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/08_EU_ITALIAN/icon_item_menu00.ctxb", 262216, 262144, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/08_EU_ITALIAN/hud_menu_title00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/08_EU_ITALIAN/menu_option_parts00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/08_EU_ITALIAN/menu_cursor00.ctxb", 32840, 32768, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/08_EU_ITALIAN/menu_item_parts01.ctxb", 16456, 16384, 0x6754, 0x8363, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/08_EU_ITALIAN/cam_interface00.ctxb", 65608, 65536, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/08_EU_ITALIAN/menu_top_map00.ctxb", 65608, 65536, 0x675B, 0x0000, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/08_EU_ITALIAN/menu_hint_movie_parts00.ctxb", 262216, 262144, 0x6752, 0x1401, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/08_EU_ITALIAN/menu_file_select_parts00.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/08_EU_ITALIAN/menu_file_select_parts01.ctxb", 262216, 262144, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/08_EU_ITALIAN/name_entry00_parts00.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/08_EU_ITALIAN/name_entry00_parts01.ctxb", 524360, 524288, 0x6752, 0x8033, true},
    {Oot3dUiLanguage::EuItalian, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/08_EU_ITALIAN/common_bg01.ctxb", 65608, 65536, 0x675A, 0x0000, true},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::CommonBackground00, &kDescriptors[0], "rom:/menu/09_EU_DUTCH/common_bg00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::HudAtlas, &kDescriptors[1], "rom:/menu/09_EU_DUTCH/hud_all00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::PauseTopPage, &kDescriptors[2], "rom:/menu/09_EU_DUTCH/menu_top_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::ItemPage, &kDescriptors[3], "rom:/menu/09_EU_DUTCH/menu_item_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::EquipmentPage, &kDescriptors[4], "rom:/menu/09_EU_DUTCH/menu_equip_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::OcarinaPage, &kDescriptors[5], "rom:/menu/09_EU_DUTCH/menu_okarina_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::MapPage00, &kDescriptors[6], "rom:/menu/09_EU_DUTCH/menu_map_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::MapPage01, &kDescriptors[7], "rom:/menu/09_EU_DUTCH/menu_map_parts01.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::FieldMapClouds, &kDescriptors[8], "rom:/menu/09_EU_DUTCH/fieldmap_cloud_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::NumberGlyphs, &kDescriptors[9], "rom:/menu/09_EU_DUTCH/num_all00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::ItemIcons, &kDescriptors[10], "rom:/menu/09_EU_DUTCH/icon_item_menu00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::HudMenuTitle, &kDescriptors[11], "rom:/menu/09_EU_DUTCH/hud_menu_title00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::OptionsPage, &kDescriptors[12], "rom:/menu/09_EU_DUTCH/menu_option_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::Cursor, &kDescriptors[13], "rom:/menu/09_EU_DUTCH/menu_cursor00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::ItemPageAux, &kDescriptors[14], "rom:/menu/09_EU_DUTCH/menu_item_parts01.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::CameraInterface, &kDescriptors[15], "rom:/menu/09_EU_DUTCH/cam_interface00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::PauseTopMap, &kDescriptors[16], "rom:/menu/09_EU_DUTCH/menu_top_map00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::HintMovie, &kDescriptors[17], "rom:/menu/09_EU_DUTCH/menu_hint_movie_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::FileSelectParts00, &kDescriptors[18], "rom:/menu/09_EU_DUTCH/menu_file_select_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::FileSelectParts01, &kDescriptors[19], "rom:/menu/09_EU_DUTCH/menu_file_select_parts01.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::NameEntryParts00, &kDescriptors[20], "rom:/menu/09_EU_DUTCH/name_entry00_parts00.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::NameEntryParts01, &kDescriptors[21], "rom:/menu/09_EU_DUTCH/name_entry00_parts01.ctxb", 0, 0, 0x0000, 0x0000, false},
    {Oot3dUiLanguage::EuDutch, UiLocalizedMenuTextureKind::CommonBackground01, &kDescriptors[22], "rom:/menu/09_EU_DUTCH/common_bg01.ctxb", 0, 0, 0x0000, 0x0000, false},
}};

constexpr std::size_t ToIndex(UiLocalizedMenuTextureKind kind) noexcept {
    return static_cast<std::size_t>(kind);
}

constexpr std::size_t ToIndex(Oot3dUiLanguage language) noexcept {
    return static_cast<std::size_t>(language);
}

} // namespace

const std::array<UiLocalizedMenuTextureDescriptor,
                 kOot3dLocalizedMenuTextureKindCount>&
Oot3dLocalizedMenuTextureDescriptors() noexcept {
    return kDescriptors;
}

const UiLocalizedMenuTextureDescriptor* Oot3dLocalizedMenuTextureDescriptorFor(
    UiLocalizedMenuTextureKind kind) noexcept {
    const auto index = ToIndex(kind);
    return index < kDescriptors.size() ? &kDescriptors[index] : nullptr;
}

UiLocalizedMenuTextureResourceView Oot3dLocalizedMenuTextureResource(
    Oot3dUiLanguage language, UiLocalizedMenuTextureKind kind) noexcept {
    const auto language_index = ToIndex(language);
    const auto kind_index = ToIndex(kind);
    if (language_index >= kOot3dUiLanguageCount ||
        kind_index >= kOot3dLocalizedMenuTextureKindCount) {
        return {};
    }
    return kResources[
        language_index * kOot3dLocalizedMenuTextureKindCount + kind_index];
}

UiLocalizedMenuTextureKind Oot3dPauseSharedTextureKind(
    UiPauseSharedTextureSlot slot) noexcept {
    const auto index = static_cast<std::size_t>(slot);
    return index < kOot3dPauseSharedTextureCount
               ? static_cast<UiLocalizedMenuTextureKind>(index)
               : UiLocalizedMenuTextureKind::Count;
}

UiLocalizedMenuTextureResourceView Oot3dPauseSharedTextureResource(
    Oot3dUiLanguage language, UiPauseSharedTextureSlot slot) noexcept {
    return Oot3dLocalizedMenuTextureResource(
        language, Oot3dPauseSharedTextureKind(slot));
}

UiLocalizedMenuTextureKind Oot3dLocalizedMenuTextureKindForFrontendAtlas(
    UiFrontendAtlasKind kind) noexcept {
    switch (kind) {
    case UiFrontendAtlasKind::NameEntryParts00:
        return UiLocalizedMenuTextureKind::NameEntryParts00;
    case UiFrontendAtlasKind::NameEntryParts01:
        return UiLocalizedMenuTextureKind::NameEntryParts01;
    case UiFrontendAtlasKind::FileSelectParts00:
        return UiLocalizedMenuTextureKind::FileSelectParts00;
    case UiFrontendAtlasKind::FileSelectParts01:
        return UiLocalizedMenuTextureKind::FileSelectParts01;
    case UiFrontendAtlasKind::Count:
        return UiLocalizedMenuTextureKind::Count;
    }
    return UiLocalizedMenuTextureKind::Count;
}

UiFrontendAtlasKind Oot3dFrontendAtlasKindForLocalizedMenuTexture(
    UiLocalizedMenuTextureKind kind) noexcept {
    switch (kind) {
    case UiLocalizedMenuTextureKind::NameEntryParts00:
        return UiFrontendAtlasKind::NameEntryParts00;
    case UiLocalizedMenuTextureKind::NameEntryParts01:
        return UiFrontendAtlasKind::NameEntryParts01;
    case UiLocalizedMenuTextureKind::FileSelectParts00:
        return UiFrontendAtlasKind::FileSelectParts00;
    case UiLocalizedMenuTextureKind::FileSelectParts01:
        return UiFrontendAtlasKind::FileSelectParts01;
    default:
        return UiFrontendAtlasKind::Count;
    }
}

UiLocalizedMenuTextureResourceView
Oot3dLocalizedMenuTextureResourceForFrontendAtlas(
    Oot3dUiLanguage language, UiFrontendAtlasKind kind) noexcept {
    return Oot3dLocalizedMenuTextureResource(
        language, Oot3dLocalizedMenuTextureKindForFrontendAtlas(kind));
}

static_assert(kDescriptors.size() == 23);
static_assert(kResources.size() == 230);
static_assert(kDescriptors[0].native_pause_shared_slot ==
              UiPauseSharedTextureSlot::CommonBackground00);
static_assert(kDescriptors[15].native_pause_shared_slot ==
              UiPauseSharedTextureSlot::CameraInterface);
static_assert(!kDescriptors[22].declared_by_native_code);

} // namespace oot3d::ui
