// Generated by tools/build_ui_pause_native_geometry_tranche_234.py.
#include "oot3d_ui/ui_pause_native_geometry.h"

namespace oot3d::ui {
namespace {

constexpr std::array<UiPauseNativeGeometryProfileDescriptor,
                     kOot3dPauseNativeGeometryProfileCount> kProfiles = {{
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, UiSubsystem::Map, UiPauseSharedTextureSlot::Cursor, "map_area_eight_quad", "map-area eight-quad cursor overlay", "PauseUiEightQuadOverlay_Construct", 0x002D1AF8, 764, 0, 8, 8, 32, 48, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, UiSubsystem::TouchControls, UiPauseSharedTextureSlot::Cursor, "touch_eight_quad", "touch-screen eight-quad cursor overlay", "PauseUiEightQuadOverlay_Construct", 0x002D1AF8, 764, 1, 8, 8, 32, 48, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, UiSubsystem::Map, UiPauseSharedTextureSlot::Cursor, "map_area_twenty_five_quad", "map-area twenty-five-quad marker overlay", "PauseUiTwentyFiveQuadOverlay_Construct", 0x002D1E30, 796, 0, 25, 25, 100, 150, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, UiSubsystem::TouchControls, UiPauseSharedTextureSlot::Cursor, "touch_twenty_five_quad", "touch-screen twenty-five-quad marker overlay", "PauseUiTwentyFiveQuadOverlay_Construct", 0x002D1E30, 796, 1, 25, 25, 100, 150, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_0", "generic pause quad-group layout 0", "PauseQuadGroup_Construct", 0x002F2448, 1660, 0, 8, 8, 32, 48, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout1, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_1", "generic pause quad-group layout 1", "PauseQuadGroup_Construct", 0x002F2448, 1660, 1, 4, 4, 16, 24, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_2", "generic pause quad-group layout 2", "PauseQuadGroup_Construct", 0x002F2448, 1660, 2, 20, 0, 80, 120, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::ImmediateArgument, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_3", "generic pause quad-group layout 3", "PauseQuadGroup_Construct", 0x002F2448, 1660, 3, 20, 0, 80, 120, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::NativeTablePlusBias, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_4", "generic pause quad-group layout 4", "PauseQuadGroup_Construct", 0x002F2448, 1660, 4, 20, 0, 80, 120, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::ImmediateArgument, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_5", "generic pause quad-group layout 5", "PauseQuadGroup_Construct", 0x002F2448, 1660, 5, 20, 0, 80, 120, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::ImmediateArgument, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout6, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_6", "generic pause quad-group layout 6", "PauseQuadGroup_Construct", 0x002F2448, 1660, 6, 4, 4, 16, 24, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryStreamSource::NativeConstructorFormula, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout7, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_7", "generic pause quad-group layout 7", "PauseQuadGroup_Construct", 0x002F2448, 1660, 7, 4, 4, 16, 24, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout8, UiSubsystem::PauseShell, UiPauseSharedTextureSlot::Cursor, "quad_group_layout_8", "generic pause quad-group layout 8", "PauseQuadGroup_Construct", 0x002F2448, 1660, 8, 4, 4, 16, 24, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::GearMain, UiSubsystem::Equipment, UiPauseSharedTextureSlot::EquipmentPage, "gear_main", "equipment-page main quad lane", "PauseGearPage_InitMainRenderer", 0x00467104, 664, -1, 41, 41, 164, 246, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::GearAuxiliary0, UiSubsystem::Equipment, UiPauseSharedTextureSlot::EquipmentPage, "gear_auxiliary_0", "equipment-page auxiliary quad lane zero", "PauseGearPage_InitAuxiliaryRenderers", 0x004673E0, 644, 0, 3, 3, 12, 18, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::GearAuxiliary1, UiSubsystem::Equipment, UiPauseSharedTextureSlot::EquipmentPage, "gear_auxiliary_1", "equipment-page auxiliary quad lane one", "PauseGearPage_InitAuxiliaryRenderers", 0x004673E0, 644, 1, 3, 3, 12, 18, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryIndexPattern::QuadTriangles, true, false, true, {400.0f, 320.0f}},
    {UiPauseNativeGeometryProfile::QuestCursor, UiSubsystem::QuestStatus, UiPauseSharedTextureSlot::HudAtlas, "quest_cursor", "Quest Status cursor direct-vertex lane", "PauseQuestPage_InitCursorRenderer", 0x004695B0, 320, -1, 1, 1, 4, 4, UiPauseGeometryEncoding::DirectVertexStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::SequentialFour, false, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuestIcon, UiSubsystem::QuestStatus, UiPauseSharedTextureSlot::HudMenuTitle, "quest_icon", "Quest Status runtime icon lane", "PauseQuestPage_InitIconRenderer", 0x00469724, 368, -1, 1, 1, 4, 6, UiPauseGeometryEncoding::DirectVertexStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryIndexPattern::QuadTriangles, false, true, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary0, UiSubsystem::QuestStatus, UiPauseSharedTextureSlot::HudAtlas, "quest_auxiliary_0", "Quest Status auxiliary direct-vertex lane zero", "PauseQuestPage_InitAuxiliaryRenderers", 0x004698C0, 616, 0, 1, 1, 4, 4, UiPauseGeometryEncoding::DirectVertexStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::SequentialFour, false, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary1, UiSubsystem::QuestStatus, UiPauseSharedTextureSlot::HudAtlas, "quest_auxiliary_1", "Quest Status auxiliary direct-vertex lane one", "PauseQuestPage_InitAuxiliaryRenderers", 0x004698C0, 616, 1, 1, 1, 4, 4, UiPauseGeometryEncoding::DirectVertexStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryStreamSource::StaticNativeTable, UiPauseGeometryIndexPattern::SequentialFour, false, false, false, {0.0f, 0.0f}},
    {UiPauseNativeGeometryProfile::QuestMain, UiSubsystem::QuestStatus, UiPauseSharedTextureSlot::HudAtlas, "quest_main", "Quest Status main eight-quad runtime lane", "PauseQuestPage_Init", 0x0045554C, 884, -1, 8, 8, 32, 48, UiPauseGeometryEncoding::QuadRectStreams, UiPauseGeometryCountSource::FixedConstructor, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryStreamSource::NativeRuntimeStorage, UiPauseGeometryIndexPattern::QuadTriangles, true, false, false, {0.0f, 0.0f}},
}};

constexpr std::array<UiPauseNativeQuadProjection,
                     kOot3dPauseNativeQuadProjectionCount> kQuadProjections = {{
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 0, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 32.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 1, {0.0f, 0.0f}, {8.0f, 8.0f}, {10.0f, 32.0f}, {1.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 2, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 40.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 3, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 40.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 4, {0.0f, 0.0f}, {8.0f, 8.0f}, {24.0f, 50.0f}, {8.0f, 1.0f}},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 5, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 48.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 6, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 48.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 7, {0.0f, 0.0f}, {8.0f, 8.0f}, {16.0f, 48.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 0, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 32.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 1, {0.0f, 0.0f}, {8.0f, 8.0f}, {10.0f, 32.0f}, {1.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 2, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 40.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 3, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 40.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 4, {0.0f, 0.0f}, {8.0f, 8.0f}, {24.0f, 50.0f}, {8.0f, 1.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 5, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 48.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 6, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 48.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 7, {0.0f, 0.0f}, {8.0f, 8.0f}, {16.0f, 48.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 0, {36.0f, 47.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 1, {64.0f, 50.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 2, {81.0f, 70.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 3, {116.0f, 165.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 4, {148.0f, 79.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 5, {164.0f, 40.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 6, {186.0f, 80.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 7, {197.0f, 24.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 8, {213.0f, 46.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 9, {243.0f, 87.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 10, {268.0f, 104.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 11, {291.0f, 54.0f}, {16.0f, 16.0f}, {16.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 12, {36.0f, 47.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 13, {64.0f, 50.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 14, {81.0f, 70.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 15, {116.0f, 165.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 16, {148.0f, 79.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 17, {164.0f, 40.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 18, {186.0f, 80.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 19, {197.0f, 24.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 20, {213.0f, 46.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 21, {243.0f, 87.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 22, {268.0f, 104.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 23, {291.0f, 54.0f}, {16.0f, 16.0f}, {32.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 24, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 0, {78.0f, 78.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 1, {96.0f, 81.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 2, {108.0f, 93.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 3, {129.0f, 150.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 4, {148.0f, 98.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 5, {158.0f, 74.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 6, {170.0f, 94.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 7, {179.0f, 64.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 8, {190.0f, 77.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 9, {207.0f, 101.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 10, {224.0f, 113.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 11, {237.0f, 80.0f}, {16.0f, 16.0f}, {96.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 12, {78.0f, 78.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 13, {96.0f, 81.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 14, {108.0f, 93.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 15, {129.0f, 150.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 16, {148.0f, 98.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 17, {158.0f, 74.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 18, {170.0f, 94.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 19, {179.0f, 64.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 20, {190.0f, 77.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 21, {207.0f, 101.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 22, {224.0f, 113.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 23, {237.0f, 80.0f}, {16.0f, 16.0f}, {112.0f, 32.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 24, {0.0f, 0.0f}, {16.0f, 16.0f}, {112.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0, {0.0f, 0.0f}, {16.0f, 16.0f}, {0.0f, 0.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 1, {0.0f, 0.0f}, {16.0f, 16.0f}, {16.0f, 0.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 2, {0.0f, 0.0f}, {16.0f, 16.0f}, {0.0f, 16.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 3, {0.0f, 0.0f}, {16.0f, 16.0f}, {16.0f, 16.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 4, {0.0f, 0.0f}, {16.0f, 16.0f}, {64.0f, 0.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 5, {0.0f, 0.0f}, {16.0f, 16.0f}, {80.0f, 0.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 6, {0.0f, 0.0f}, {16.0f, 16.0f}, {64.0f, 16.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 7, {0.0f, 0.0f}, {16.0f, 16.0f}, {80.0f, 16.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout1, 0, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 0.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout1, 1, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 0.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout1, 2, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 16.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout1, 3, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 16.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 0, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 1, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 2, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 3, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 4, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 5, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 6, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 7, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 8, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 9, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 10, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 11, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 12, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 13, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 14, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 15, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 16, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 17, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 18, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 19, {0.0f, 0.0f}, {8.0f, 8.0f}, {0.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 0, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 1, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 2, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 3, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 4, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 5, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 6, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 7, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 8, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 9, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 10, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 11, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 12, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 13, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 14, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 15, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 16, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 17, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 18, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 19, {0.0f, 0.0f}, {16.0f, 16.0f}, {32.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 0, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 1, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 2, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 3, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 4, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 5, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 6, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 7, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 8, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 9, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 10, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 11, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 12, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 13, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 14, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 15, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 16, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 17, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 18, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 19, {0.0f, 0.0f}, {8.0f, 8.0f}, {8.0f, 56.0f}, {8.0f, 8.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 0, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 1, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 2, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 3, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 4, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 5, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 6, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 7, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 8, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 9, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 10, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 11, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 12, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 13, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 14, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 15, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 16, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 17, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 18, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 19, {0.0f, 0.0f}, {16.0f, 16.0f}, {48.0f, 48.0f}, {16.0f, 16.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout6, 0, {0.0f, 0.0f}, {24.0f, 24.0f}, {0.0f, 0.0f}, {24.0f, 24.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout6, 1, {0.0f, 0.0f}, {10.0f, 10.0f}, {0.0f, 112.0f}, {10.0f, 10.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout6, 2, {0.0f, 0.0f}, {10.0f, 10.0f}, {16.0f, 112.0f}, {10.0f, 10.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout6, 3, {0.0f, 0.0f}, {10.0f, 10.0f}, {32.0f, 112.0f}, {10.0f, 10.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout7, 0, {278.0f, 62.0f}, {11.0f, 11.0f}, {67.0f, 51.0f}, {11.0f, 11.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout7, 1, {260.0f, 104.0f}, {11.0f, 11.0f}, {83.0f, 51.0f}, {11.0f, 11.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout7, 2, {270.0f, 8.0f}, {13.0f, 13.0f}, {66.0f, 34.0f}, {13.0f, 13.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout7, 3, {270.0f, 192.0f}, {13.0f, 13.0f}, {82.0f, 34.0f}, {13.0f, 13.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout8, 0, {270.0f, 67.0f}, {11.0f, 11.0f}, {67.0f, 51.0f}, {11.0f, 11.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout8, 1, {260.0f, 119.0f}, {11.0f, 11.0f}, {83.0f, 51.0f}, {11.0f, 11.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout8, 2, {270.0f, 8.0f}, {13.0f, 13.0f}, {66.0f, 34.0f}, {13.0f, 13.0f}},
    {UiPauseNativeGeometryProfile::QuadGroupLayout8, 3, {270.0f, 192.0f}, {13.0f, 13.0f}, {82.0f, 34.0f}, {13.0f, 13.0f}},
}};

constexpr std::array<UiPauseNativeDirectVertex,
                     kOot3dPauseNativeDirectVertexCount> kDirectVertices = {{
    {UiPauseNativeGeometryProfile::QuestCursor, 0, {341.0f, 60.0f, 0.0f}, {0.690196097f, 0.784313738f}},
    {UiPauseNativeGeometryProfile::QuestCursor, 1, {396.0f, 60.0f, 0.0f}, {0.905882359f, 0.784313738f}},
    {UiPauseNativeGeometryProfile::QuestCursor, 2, {341.0f, 5.0f, 0.0f}, {0.690196097f, 1.0f}},
    {UiPauseNativeGeometryProfile::QuestCursor, 3, {396.0f, 5.0f, 0.0f}, {0.905882359f, 1.0f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary0, 0, {12.0f, 58.0f, 0.0f}, {0.501960814f, 0.811764717f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary0, 1, {60.0f, 58.0f, 0.0f}, {0.690196097f, 0.811764717f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary0, 2, {12.0f, 10.0f, 0.0f}, {0.501960814f, 1.0f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary0, 3, {60.0f, 10.0f, 0.0f}, {0.690196097f, 1.0f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary1, 0, {-16.0f, 16.0f, 0.0f}, {0.87843138f, 0.654901981f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary1, 1, {16.0f, 16.0f, 0.0f}, {1.00392163f, 0.654901981f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary1, 2, {-16.0f, -16.0f, 0.0f}, {0.87843138f, 0.78039217f}},
    {UiPauseNativeGeometryProfile::QuestAuxiliary1, 3, {16.0f, -16.0f, 0.0f}, {1.00392163f, 0.78039217f}},
}};

constexpr std::array<UiPauseNativeGeometryCallDescriptor,
                     kOot3dPauseNativeGeometryCallCount> kCalls = {{
    {UiPauseNativeGeometryProfile::MapAreaTwentyFiveQuad, 0x00480E00, "NE", 0x00480BD8, "PauseMapPage_Init", 668, 0, UiPauseGeometryCountSource::FixedConstructor, 25, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::MapAreaEightQuad, 0x00480E64, "NE", 0x00480BD8, "PauseMapPage_Init", 668, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::TouchTwentyFiveQuad, 0x0046AFD8, "NE", 0x0046ACB8, "PauseTouchButtonPanel_Init", 1012, 1, UiPauseGeometryCountSource::FixedConstructor, 25, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::TouchEightQuad, 0x0046AFF4, "NE", 0x0046ACB8, "PauseTouchButtonPanel_Init", 1012, 1, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout3, 0x002F1DC0, "AL", 0x002F1D78, "PauseDetail_LoadDungeonMapResources", 1368, 3, UiPauseGeometryCountSource::NativeTablePlusBias, 0, 0x004FE5D8, 10},
    {UiPauseNativeGeometryProfile::QuadGroupLayout5, 0x002F1DE0, "NE", 0x002F1D78, "PauseDetail_LoadDungeonMapResources", 1368, 5, UiPauseGeometryCountSource::ImmediateArgument, 1, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout2, 0x0042C124, "NE", 0x0042C0C8, "PauseDetail_Update", 1372, 2, UiPauseGeometryCountSource::ImmediateArgument, 6, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout4, 0x0042C14C, "NE", 0x0042C0C8, "PauseDetail_Update", 1372, 4, UiPauseGeometryCountSource::ImmediateArgument, 1, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x00467344, "NE", 0x00467104, "PauseGearPage_InitMainRenderer", 664, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x00467C24, "NE", 0x004676A4, "PauseSystemMenu_Init", 1340, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x00467F40, "NE", 0x00467D00, "PauseWorldMap_Init", 644, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x00468314, "NE", 0x004682A0, "NameEntry_Init", 140, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout7, 0x0046AF04, "NE", 0x0046ACB8, "PauseTouchButtonPanel_Init", 1012, 7, UiPauseGeometryCountSource::FixedConstructor, 4, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x0046B45C, "NE", 0x0046B114, "FileSelect_Init", 976, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x0046B844, "NE", 0x0046B554, "PauseItemsPage_Init", 1020, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout1, 0x0046B868, "NE", 0x0046B554, "PauseItemsPage_Init", 1020, 1, UiPauseGeometryCountSource::FixedConstructor, 4, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x0046B8AC, "NE", 0x0046B554, "PauseItemsPage_Init", 1020, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout6, 0x0046B8D8, "NE", 0x0046B554, "PauseItemsPage_Init", 1020, 6, UiPauseGeometryCountSource::FixedConstructor, 4, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout8, 0x0046B914, "NE", 0x0046B554, "PauseItemsPage_Init", 1020, 8, UiPauseGeometryCountSource::FixedConstructor, 4, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x00480E20, "NE", 0x00480BD8, "PauseMapPage_Init", 668, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
    {UiPauseNativeGeometryProfile::QuadGroupLayout0, 0x00481138, "NE", 0x00480EB8, "PauseDungeonItemPanel_Init", 696, 0, UiPauseGeometryCountSource::FixedConstructor, 8, 0x00000000, 0},
}};

} // namespace

const std::array<UiPauseNativeGeometryProfileDescriptor,
                 kOot3dPauseNativeGeometryProfileCount>&
Oot3dPauseNativeGeometryProfiles() noexcept {
    return kProfiles;
}

const UiPauseNativeGeometryProfileDescriptor* Oot3dPauseNativeGeometryProfile(
    UiPauseNativeGeometryProfile profile) noexcept {
    const auto index = static_cast<std::size_t>(profile);
    return index < kProfiles.size() ? &kProfiles[index] : nullptr;
}

const std::array<UiPauseNativeQuadProjection,
                 kOot3dPauseNativeQuadProjectionCount>&
Oot3dPauseNativeQuadProjections() noexcept {
    return kQuadProjections;
}

const UiPauseNativeQuadProjection* Oot3dPauseNativeQuadProjectionFor(
    UiPauseNativeGeometryProfile profile, std::uint8_t quad_index) noexcept {
    for (const auto& projection : kQuadProjections) {
        if (projection.profile == profile && projection.quad_index == quad_index) {
            return &projection;
        }
    }
    return nullptr;
}

const std::array<UiPauseNativeDirectVertex,
                 kOot3dPauseNativeDirectVertexCount>&
Oot3dPauseNativeDirectVertices() noexcept {
    return kDirectVertices;
}

const UiPauseNativeDirectVertex* Oot3dPauseNativeDirectVertexFor(
    UiPauseNativeGeometryProfile profile, std::uint8_t vertex_index) noexcept {
    for (const auto& vertex : kDirectVertices) {
        if (vertex.profile == profile && vertex.vertex_index == vertex_index) {
            return &vertex;
        }
    }
    return nullptr;
}

const std::array<UiPauseNativeGeometryCallDescriptor,
                 kOot3dPauseNativeGeometryCallCount>&
Oot3dPauseNativeGeometryCalls() noexcept {
    return kCalls;
}

} // namespace oot3d::ui
