// Generated by tools/build_ui_pause_page_pipeline_tranche_237.py.
#include "oot3d_ui/ui_pause_page_pipeline.h"

namespace oot3d::ui {
namespace {

constexpr std::array<UiPausePipelineComponentDescriptor,
                     kOot3dPausePipelineComponentCount> kComponents = {{
    {UiPausePipelineComponent::PauseRoot, UiSubsystem::PauseShell, "root pause session and backdrop", "gPauseUiRootState", 0x005043D4, 0x28, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::UpdateOwnsPresentation, 0x0041E968, "PauseUi_Update", 0x00000000, nullptr, 0x0041EC50, "PauseUi_Draw", false},
    {UiPausePipelineComponent::TouchControls, UiSubsystem::TouchControls, "bottom-screen touch controls and action widgets", "gPauseTouchButtonState", 0x0050AF34, 0x4D4, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DiscreteRoots, 0x0042DF3C, "PauseTouchButtons_Update", 0x0042DDA8, "PauseTouchButtons_SubmitModels", 0x0042F5A8, "PauseTouchButtons_Draw", false},
    {UiPausePipelineComponent::Items, UiSubsystem::Items, "item inventory page and assignment presentation", "gPauseItemsPageState", 0x005066F8, 0x4CC, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DiscreteRoots, 0x00433AB4, "PauseItemsPage_Update", 0x004338EC, "PauseItemsPage_SubmitModels", 0x00434C80, "PauseItemsPage_Draw", false},
    {UiPausePipelineComponent::Equipment, UiSubsystem::Equipment, "equipment selection page", "gPauseGearPageState", 0x0050446C, 0x70, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DiscreteRoots, 0x00424324, "PauseGearPage_Update", 0x0042401C, "PauseGearPage_SubmitModels", 0x00424C20, "PauseGearPage_Draw", false},
    {UiPausePipelineComponent::DungeonMap, UiSubsystem::Map, "dungeon map and dungeon-item panel", "gPauseDungeonItemPanelState", 0x00506CB0, 0xAB0, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DiscreteRoots, 0x0042D0E4, "PauseMapPage_Update", 0x0042CD5C, "PauseDungeonItemPanel_SubmitModels", 0x0042DA14, "PauseMapPage_Draw", false},
    {UiPausePipelineComponent::WorldMap, UiSubsystem::Map, "world map destinations and area overlays", "gPauseWorldMapState", 0x005093E4, 0xDFC, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DiscreteRoots, 0x00425AD8, "PauseWorldMap_Update", 0x00425930, "PauseWorldMap_Draw", 0x0042676C, "PauseWorldMap_DrawOverlay", false},
    {UiPausePipelineComponent::SystemMenu, UiSubsystem::SystemMenu, "save prompt and options menu", "gPauseSystemMenuState", 0x0050A508, 0xA04, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DiscreteRoots, 0x00425164, "PauseSystemMenu_Update", 0x00424F20, "PauseSystemMenu_SubmitModels", 0x004252BC, "PauseSystemMenu_Draw", false},
    {UiPausePipelineComponent::FileSelect, UiSubsystem::FileSelect, "file selection and save-slot flows", "gFileSelectState", 0x00504FA0, 0x1758, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::UpdateOwnsPresentation, 0x0042F9A8, "FileSelect_Update", 0x00000000, nullptr, 0x00000000, nullptr, false},
    {UiPausePipelineComponent::NameEntry, UiSubsystem::NameEntry, "player-name keyboard and glyph overlays", "gNameEntryState", 0x005077F0, 0x834, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::UpdateOwnsPresentation, 0x00427CE4, "NameEntry_Update", 0x00000000, nullptr, 0x00428948, "NameEntry_Draw", false},
    {UiPausePipelineComponent::CameraControl, UiSubsystem::PauseShell, "3DS pause camera-control widget", "gPauseCameraControlState", 0x005043FC, 0x44, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DrawOwnsPresentation, 0x00428AF4, "PauseCameraControl_Update", 0x00000000, nullptr, 0x00428CB0, "PauseCameraControl_DrawAndGetYaw", false},
    {UiPausePipelineComponent::TextureControl, UiSubsystem::PauseShell, "3DS pause texture-control widget", "gPauseTextureControlState", 0x00504440, 0x2C, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DrawOwnsPresentation, 0x00427A94, "PauseTextureControl_Update", 0x00000000, nullptr, 0x00427CA4, "PauseTextureControl_Draw", false},
    {UiPausePipelineComponent::DetailPanel, UiSubsystem::PauseShell, "shared item and map detail resources", "gPauseDetailState", 0x004FDA70, 0x68, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::DiscreteRoots, 0x0042C0C8, "PauseDetail_Update", 0x002FBC50, "PauseDetail_SubmitModels", 0x00000000, nullptr, false},
    {UiPausePipelineComponent::QuestStatus, UiSubsystem::QuestStatus, "Quest Status page", "gPauseQuestPageState", 0x004FC648, 0x19C, UiPausePipelineLifetime::ProcessGlobalInline, UiPausePipelinePresentationMode::UpdateAndSubmitFused, 0x0041DEF0, "PauseQuestPage_UpdateAndSubmit", 0x0041DEF0, "PauseQuestPage_UpdateAndSubmit", 0x0042B9F4, "PauseQuestPage_Draw", false},
    {UiPausePipelineComponent::OmoteUraSelector, UiSubsystem::PauseShell, "3DS normal-versus-Master-Quest selector", "gOmoteUraSelector", 0x0050BB50, 0x5CC, UiPausePipelineLifetime::ProcessGlobalIndirect, UiPausePipelinePresentationMode::UpdateAndSubmitFused, 0x0043FCDC, "OmoteUraSelector_UpdateAndSubmit", 0x0043FCDC, "OmoteUraSelector_UpdateAndSubmit", 0x00000000, nullptr, false},
    {UiPausePipelineComponent::Overlay, UiSubsystem::PauseShell, "renderer-local pause overlays and callbacks", "GraphRenderer pause overlay groups", 0x00000000, 0x0, UiPausePipelineLifetime::RendererOwned, UiPausePipelinePresentationMode::RendererLocalDrawOnly, 0x00000000, nullptr, 0x00000000, nullptr, 0x0041F308, "PauseOverlay_DrawAllGroups", false},
}};

constexpr std::array<UiPausePipelineOperationDescriptor,
                     kOot3dPausePipelineOperationCount> kOperations = {{
    {UiPausePipelineComponent::PauseRoot, 0x004191E4, 0xEB0015DF, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x0041E968, "PauseUi_Update", UiPausePipelinePhase::FrameUpdate, UiPausePipelineInvocation::DirectCall, 0, "always", "update and submit the native pause shell", true},
    {UiPausePipelineComponent::QuestStatus, 0x004191F0, 0xEB00133E, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x0041DEF0, "PauseQuestPage_UpdateAndSubmit", UiPausePipelinePhase::FrameUpdate, UiPausePipelineInvocation::DirectCall, 1, "always", "update and submit Quest Status", true},
    {UiPausePipelineComponent::Equipment, 0x00419210, 0xEB000D61, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x0041C79C, "PauseGearPage_UpdateInputAndResources", UiPausePipelinePhase::InputAndResources, UiPausePipelineInvocation::DirectCall, 2, "always", "advance Equipment input and resource state", true},
    {UiPausePipelineComponent::PauseRoot, 0x00419220, 0xEB0017AC, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x0041F0D8, "PauseUi_SubmitIndexedOrthoElement", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 3, "always", "submit the indexed root orthographic element", true},
    {UiPausePipelineComponent::QuestStatus, 0x00419234, 0xEB001078, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x0041D41C, "PauseQuestPage_UpdateInputAndResources", UiPausePipelinePhase::InputAndResources, UiPausePipelineInvocation::DirectCall, 4, "always", "advance Quest input and resource state", true},
    {UiPausePipelineComponent::PauseRoot, 0x00419520, 0xEBFB9B80, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x00300328, "PauseRenderer_DrawViewPass", UiPausePipelinePhase::ViewPass, UiPausePipelineInvocation::DirectCall, 5, "always", "draw native view pass zero with selector 6", false},
    {UiPausePipelineComponent::PauseRoot, 0x004197D0, 0xEBFB9AD4, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x00300328, "PauseRenderer_DrawViewPass", UiPausePipelinePhase::ViewPass, UiPausePipelineInvocation::DirectCall, 6, "stereoscopic view enabled", "draw native view pass one with selector 9", false},
    {UiPausePipelineComponent::PauseRoot, 0x0041982C, 0xEB001507, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x0041EC50, "PauseUi_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 7, "always", "draw the root and all enabled child components", true},
    {UiPausePipelineComponent::Overlay, 0x00419838, 0xEB0016B2, "AL", 0x00418B88, "GraphRenderer_DrawFrame", 3348, 0x0041F308, "PauseOverlay_DrawAllGroups", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 8, "always", "draw renderer-local pause overlays", true},
    {UiPausePipelineComponent::QuestStatus, 0x003004DC, 0xEB04AD44, "AL", 0x00300328, "PauseRenderer_DrawViewPass", 604, 0x0042B9F4, "PauseQuestPage_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 0, "every native view pass", "draw Quest Status in the current view", true},
    {UiPausePipelineComponent::PauseRoot, 0x00300518, 0x112FFF31, "NE", 0x00300328, "PauseRenderer_DrawViewPass", 604, 0x00000000, "renderer pause callback", UiPausePipelinePhase::Callback, UiPausePipelineInvocation::VirtualCall, 1, "renderer callback pointer is nonnull", "invoke the renderer-local pause callback", false},
    {UiPausePipelineComponent::Overlay, 0x0030052C, 0xEB04B188, "AL", 0x00300328, "PauseRenderer_DrawViewPass", 604, 0x0042CB54, "PauseCallbackGroup_DispatchIfEnabled", UiPausePipelinePhase::Callback, UiPausePipelineInvocation::DirectCall, 2, "callback group enabled", "dispatch the renderer-local pause callback group", false},
    {UiPausePipelineComponent::DetailPanel, 0x00300538, 0xEB04A74E, "AL", 0x00300328, "PauseRenderer_DrawViewPass", 604, 0x0042A278, "PauseDetail_ReleaseAlternateIcons", UiPausePipelinePhase::SharedResourceRelease, UiPausePipelineInvocation::DirectCall, 3, "every native view pass", "release stale alternate detail icons", false},
    {UiPausePipelineComponent::DetailPanel, 0x00300544, 0xEB049D3C, "AL", 0x00300328, "PauseRenderer_DrawViewPass", 604, 0x00427A3C, "PauseResourceState_ReleaseConditionalEntries", UiPausePipelinePhase::SharedResourceRelease, UiPausePipelineInvocation::DirectCall, 4, "every native view pass", "release conditionally retired pause resources", false},
    {UiPausePipelineComponent::TouchControls, 0x0041E984, 0xEB002814, "AL", 0x0041E968, "PauseUi_Update", 692, 0x004289DC, "PauseInput_UpdateTouchState", UiPausePipelinePhase::InputUpdate, UiPausePipelineInvocation::DirectCall, 0, "always", "sample root touch state", false},
    {UiPausePipelineComponent::PauseRoot, 0x0041E9A0, 0xEB003C51, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042DAEC, "PauseInput_UpdateRepeatState", UiPausePipelinePhase::InputUpdate, UiPausePipelineInvocation::DirectCall, 1, "pause root active", "update repeated pause input", false},
    {UiPausePipelineComponent::TouchControls, 0x0041E9A8, 0xEB003D63, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042DF3C, "PauseTouchButtons_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 2, "pause root active", "update touch controls", true},
    {UiPausePipelineComponent::Items, 0x0041E9B0, 0xEB00543F, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00433AB4, "PauseItemsPage_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 3, "pause root active", "update Items", true},
    {UiPausePipelineComponent::Equipment, 0x0041E9B4, 0xEB00165A, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00424324, "PauseGearPage_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 4, "pause root active", "update Equipment", true},
    {UiPausePipelineComponent::DungeonMap, 0x0041E9BC, 0xEB0039C8, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042D0E4, "PauseMapPage_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 5, "pause root active", "update dungeon/world map controller", true},
    {UiPausePipelineComponent::WorldMap, 0x0041E9C4, 0xEB001C43, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00425AD8, "PauseWorldMap_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 6, "pause root active", "update World Map", true},
    {UiPausePipelineComponent::SystemMenu, 0x0041E9CC, 0xEB0019E4, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00425164, "PauseSystemMenu_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 7, "pause root active", "update system menu", true},
    {UiPausePipelineComponent::FileSelect, 0x0041E9D4, 0xEB0043F3, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042F9A8, "FileSelect_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 8, "pause root active", "update the integrated file-select flow", true},
    {UiPausePipelineComponent::NameEntry, 0x0041E9DC, 0xEB0024C0, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00427CE4, "NameEntry_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 9, "pause root active", "update name entry", true},
    {UiPausePipelineComponent::CameraControl, 0x0041E9E0, 0xEB002843, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00428AF4, "PauseCameraControl_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 10, "pause root active", "update 3DS camera control", true},
    {UiPausePipelineComponent::TextureControl, 0x0041E9E4, 0xEB00242A, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00427A94, "PauseTextureControl_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 11, "pause root active", "update 3DS texture control", true},
    {UiPausePipelineComponent::DetailPanel, 0x0041E9EC, 0xEB0035B5, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042C0C8, "PauseDetail_Update", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 12, "pause root active", "update shared detail resources", true},
    {UiPausePipelineComponent::OmoteUraSelector, 0x0041EA08, 0xEB0084B3, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0043FCDC, "OmoteUraSelector_UpdateAndSubmit", UiPausePipelinePhase::PageUpdate, UiPausePipelineInvocation::DirectCall, 13, "selector owner is nonnull", "update and submit the 3DS selector", true},
    {UiPausePipelineComponent::PauseRoot, 0x0041EADC, 0xE12FFF3C, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00000000, "root renderer slot 8", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::VirtualCall, 14, "pause root active", "submit the native root pause model", true},
    {UiPausePipelineComponent::TouchControls, 0x0041EAE0, 0xEB003CB0, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042DDA8, "PauseTouchButtons_SubmitModels", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 15, "pause root active", "submit touch controls", true},
    {UiPausePipelineComponent::Items, 0x0041EAEC, 0xEB00537E, "AL", 0x0041E968, "PauseUi_Update", 692, 0x004338EC, "PauseItemsPage_SubmitModels", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 16, "pause root active", "submit Items", true},
    {UiPausePipelineComponent::DungeonMap, 0x0041EAF8, 0xEB003897, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042CD5C, "PauseDungeonItemPanel_SubmitModels", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 17, "pause root active", "submit dungeon map and item panel", true},
    {UiPausePipelineComponent::Equipment, 0x0041EB04, 0xEB001544, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042401C, "PauseGearPage_SubmitModels", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 18, "pause root active", "submit Equipment", true},
    {UiPausePipelineComponent::WorldMap, 0x0041EB10, 0xEB001B86, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00425930, "PauseWorldMap_Draw", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 19, "pause root active", "submit World Map; legacy maintained name says Draw", true},
    {UiPausePipelineComponent::SystemMenu, 0x0041EB1C, 0xEB0018FF, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00424F20, "PauseSystemMenu_SubmitModels", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 20, "pause root active", "submit system menu", true},
    {UiPausePipelineComponent::DetailPanel, 0x0041EB28, 0xEBFB7448, "AL", 0x0041E968, "PauseUi_Update", 692, 0x002FBC50, "PauseDetail_SubmitModels", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 21, "pause root active", "submit shared detail models", true},
    {UiPausePipelineComponent::FileSelect, 0x0041EB5C, 0xEB00438B, "AL", 0x0041E968, "PauseUi_Update", 692, 0x0042F990, "FileSelect_IsActive", UiPausePipelinePhase::ActivityGate, UiPausePipelineInvocation::DirectCall, 22, "post-submit arbitration", "query integrated file-select activity", false},
    {UiPausePipelineComponent::NameEntry, 0x0041EB6C, 0xEB002456, "AL", 0x0041E968, "PauseUi_Update", 692, 0x00427CCC, "NameEntry_IsActive", UiPausePipelinePhase::ActivityGate, UiPausePipelineInvocation::DirectCall, 23, "file select inactive", "query name-entry activity", false},
    {UiPausePipelineComponent::CameraControl, 0x0041EB88, 0xEBFB742A, "AL", 0x0041E968, "PauseUi_Update", 692, 0x002FBC38, "PauseCameraControl_IsActive", UiPausePipelinePhase::ActivityGate, UiPausePipelineInvocation::DirectCall, 24, "file select and name entry inactive", "query camera-control activity", false},
    {UiPausePipelineComponent::PauseRoot, 0x0041EE50, 0xE12FFF31, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x00000000, "root renderer slot 12", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::VirtualCall, 0, "root visible and active", "draw the native root pause model", true},
    {UiPausePipelineComponent::PauseRoot, 0x0041EE58, 0xEB002E59, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x0042A7C4, "PauseUi_IsChildDrawSuppressed", UiPausePipelinePhase::DrawGate, UiPausePipelineInvocation::DirectCall, 1, "root visible and active", "gate all child-component drawing", false},
    {UiPausePipelineComponent::TouchControls, 0x0041EE68, 0xEB0041CE, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x0042F5A8, "PauseTouchButtons_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 2, "child draw not suppressed", "draw touch controls", true},
    {UiPausePipelineComponent::Items, 0x0041EE74, 0xEB005781, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x00434C80, "PauseItemsPage_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 3, "child draw not suppressed", "draw Items", true},
    {UiPausePipelineComponent::Equipment, 0x0041EE80, 0xEB001766, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x00424C20, "PauseGearPage_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 4, "child draw not suppressed", "draw Equipment", true},
    {UiPausePipelineComponent::DungeonMap, 0x0041EE8C, 0xEB003AE0, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x0042DA14, "PauseMapPage_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 5, "child draw not suppressed", "draw dungeon/world map page", true},
    {UiPausePipelineComponent::WorldMap, 0x0041EE98, 0xEB001E33, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x0042676C, "PauseWorldMap_DrawOverlay", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 6, "child draw not suppressed", "draw World Map overlays", true},
    {UiPausePipelineComponent::SystemMenu, 0x0041EEA4, 0xEB001904, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x004252BC, "PauseSystemMenu_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 7, "child draw not suppressed", "draw system menu", true},
    {UiPausePipelineComponent::NameEntry, 0x0041EEB0, 0xEB0026A4, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x00428948, "NameEntry_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 8, "child draw not suppressed", "draw name entry", true},
    {UiPausePipelineComponent::CameraControl, 0x0041EEBC, 0xEB00277B, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x00428CB0, "PauseCameraControl_DrawAndGetYaw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 9, "child draw not suppressed", "draw camera control and return its yaw", true},
    {UiPausePipelineComponent::TextureControl, 0x0041EEC8, 0xEB002375, "AL", 0x0041EC50, "PauseUi_Draw", 668, 0x00427CA4, "PauseTextureControl_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 10, "child draw not suppressed", "draw texture control", true},
    {UiPausePipelineComponent::Items, 0x00433A80, 0xEB00395D, "AL", 0x004338EC, "PauseItemsPage_SubmitModels", 432, 0x00441FFC, "PauseItemsTouchHelper_SubmitModels", UiPausePipelinePhase::Submit, UiPausePipelineInvocation::DirectCall, 0, "Items page active", "submit the nested Items touch helper", false},
    {UiPausePipelineComponent::Items, 0x00434CFC, 0xEB0034BA, "AL", 0x00434C80, "PauseItemsPage_Draw", 232, 0x00441FEC, "PauseItemsTouchHelper_Draw", UiPausePipelinePhase::Draw, UiPausePipelineInvocation::DirectCall, 0, "Items page active and draw gate passes", "draw the nested Items touch helper", false},
    {UiPausePipelineComponent::DungeonMap, 0x0044E378, 0xEBFA88A6, "AL", 0x0044E2D0, "Play_Destroy", 1216, 0x002F0618, "PauseMapPage_ResetState", UiPausePipelinePhase::StateReset, UiPausePipelineInvocation::DirectCall, 0, "Play teardown", "reset map-page interaction state", false},
    {UiPausePipelineComponent::Items, 0x0044E384, 0xEBFA74A7, "AL", 0x0044E2D0, "Play_Destroy", 1216, 0x002EB628, "PauseItemsPage_ResetInteractionState", UiPausePipelinePhase::StateReset, UiPausePipelineInvocation::DirectCall, 1, "Play teardown", "reset Items interaction state", false},
    {UiPausePipelineComponent::Equipment, 0x0044E390, 0xEBFAA9D7, "AL", 0x0044E2D0, "Play_Destroy", 1216, 0x002F8AF4, "PauseGearPage_ResetInteractionState", UiPausePipelinePhase::StateReset, UiPausePipelineInvocation::DirectCall, 2, "Play teardown", "reset Equipment interaction state", false},
    {UiPausePipelineComponent::PauseRoot, 0x0044E39C, 0xEB006DF3, "AL", 0x0044E2D0, "Play_Destroy", 1216, 0x00469B70, "PauseUi_Reset", UiPausePipelinePhase::StateReset, UiPausePipelineInvocation::DirectCall, 3, "Play teardown", "reset root pause state", false},
    {UiPausePipelineComponent::PauseRoot, 0x0044E4A8, 0xEBFAE34C, "AL", 0x0044E2D0, "Play_Destroy", 1216, 0x003071E0, "PauseUi_ReleaseSharedResources", UiPausePipelinePhase::SharedResourceRelease, UiPausePipelineInvocation::DirectCall, 4, "Play teardown", "release shared pause archives and requests", false},
}};

} // namespace

const std::array<UiPausePipelineComponentDescriptor,
                 kOot3dPausePipelineComponentCount>&
Oot3dPausePipelineComponents() noexcept {
    return kComponents;
}

const UiPausePipelineComponentDescriptor* Oot3dPausePipelineComponent(
    UiPausePipelineComponent component) noexcept {
    for (const auto& descriptor : kComponents) {
        if (descriptor.component == component) {
            return &descriptor;
        }
    }
    return nullptr;
}

const std::array<UiPausePipelineOperationDescriptor,
                 kOot3dPausePipelineOperationCount>&
Oot3dPausePipelineOperations() noexcept {
    return kOperations;
}

const UiPausePipelineOperationDescriptor* Oot3dPausePipelineOperationAt(
    std::uint32_t call_site) noexcept {
    for (const auto& operation : kOperations) {
        if (operation.call_site == call_site) {
            return &operation;
        }
    }
    return nullptr;
}

} // namespace oot3d::ui
