// Generated by tools/build_ui_pause_shared_texture_consumers_tranche_232.py.
#include "oot3d_ui/ui_pause_shared_texture_consumers.h"

#include <array>
#include <cstddef>
#include <cstdint>

namespace oot3d::ui {

namespace {

inline constexpr std::array<UiPauseSharedTextureConsumerDescriptor,
                            kOot3dPauseSharedTextureConsumerCount>
    kConsumers = {{
    {0x002D1D30, 0x002D1AF8, 764, UiPauseSharedTextureSlot::Cursor, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseUiEightQuadOverlay_Construct", "eight-quad cursor overlay"},
    {0x002D2084, 0x002D1E30, 796, UiPauseSharedTextureSlot::Cursor, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseUiTwentyFiveQuadOverlay_Construct", "twenty-five-quad cursor overlay"},
    {0x002D22F4, 0x002D2190, 532, UiPauseSharedTextureSlot::FieldMapClouds, UiSubsystem::Map, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseUiSixteenQuadOverlay_Construct", "field-map cloud overlay"},
    {0x002DB864, 0x002DB6A0, 648, UiPauseSharedTextureSlot::NumberGlyphs, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseCounter_Construct", "shared pause counter glyphs"},
    {0x002E5158, 0x002E4FD8, 1072, UiPauseSharedTextureSlot::OptionsPage, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::SceneResourceGroupSlot, "RendererSceneResourceGroup_LoadBuiltinTextures", "scene resource options slot"},
    {0x002E516C, 0x002E4FD8, 1072, UiPauseSharedTextureSlot::CommonBackground00, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::SceneResourceGroupSlot, "RendererSceneResourceGroup_LoadBuiltinTextures", "scene resource background slot"},
    {0x002E5178, 0x002E4FD8, 1072, UiPauseSharedTextureSlot::Cursor, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::SceneResourceGroupSlot, "RendererSceneResourceGroup_LoadBuiltinTextures", "scene resource cursor slot"},
    {0x002E5184, 0x002E4FD8, 1072, UiPauseSharedTextureSlot::HudAtlas, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::SceneResourceGroupSlot, "RendererSceneResourceGroup_LoadBuiltinTextures", "scene resource HUD-atlas slot"},
    {0x002E5190, 0x002E4FD8, 1072, UiPauseSharedTextureSlot::EquipmentPage, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::SceneResourceGroupSlot, "RendererSceneResourceGroup_LoadBuiltinTextures", "scene resource equipment slot"},
    {0x002F2A6C, 0x002F2448, 1660, UiPauseSharedTextureSlot::Cursor, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseQuadGroup_Construct", "generic pause quad-group cursor"},
    {0x002F9078, 0x002F8EE4, 1280, UiPauseSharedTextureSlot::ItemIcons, UiSubsystem::Items, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseIconGroup_Init", "pause item-icon group"},
    {0x0044C258, 0x0044BD54, 1364, UiPauseSharedTextureSlot::HudMenuTitle, UiSubsystem::Map, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseMapPrimaryOverlay_Construct", "primary map overlay title"},
    {0x004556B0, 0x0045554C, 884, UiPauseSharedTextureSlot::HudAtlas, UiSubsystem::QuestStatus, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseQuestPage_Init", "Quest Status primary renderer"},
    {0x00455BB4, 0x0045598C, 972, UiPauseSharedTextureSlot::CommonBackground00, UiSubsystem::PauseShell, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseUi_Init", "pause-shell common background"},
    {0x0046726C, 0x00467104, 664, UiPauseSharedTextureSlot::EquipmentPage, UiSubsystem::Equipment, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseGearPage_InitMainRenderer", "equipment main renderer"},
    {0x00467580, 0x004673E0, 644, UiPauseSharedTextureSlot::EquipmentPage, UiSubsystem::Equipment, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseGearPage_InitAuxiliaryRenderers", "equipment auxiliary renderers"},
    {0x00467818, 0x004676A4, 1340, UiPauseSharedTextureSlot::OptionsPage, UiSubsystem::SystemMenu, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseSystemMenu_Init", "system-menu primary renderer"},
    {0x00467B10, 0x004676A4, 1340, UiPauseSharedTextureSlot::EquipmentPage, UiSubsystem::SystemMenu, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseSystemMenu_Init", "system-menu auxiliary renderer"},
    {0x00467E6C, 0x00467D00, 644, UiPauseSharedTextureSlot::OcarinaPage, UiSubsystem::Map, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseWorldMap_Init", "world-map native renderer"},
    {0x004681C0, 0x00467FC8, 664, UiPauseSharedTextureSlot::CameraInterface, UiSubsystem::TouchControls, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseTextureControl_Init", "touch texture-control renderer"},
    {0x004685DC, 0x0046839C, 764, UiPauseSharedTextureSlot::CameraInterface, UiSubsystem::TouchControls, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseCameraControl_Init", "touch camera-control renderer"},
    {0x00469224, 0x00468FDC, 1444, UiPauseSharedTextureSlot::CommonBackground00, UiSubsystem::FileSelect, UiPauseSharedTextureResultUse::OwnerDescriptorSlot, "OmoteUraSelectorScene_LoadResources", "normal/Master Quest selector background"},
    {0x00469240, 0x00468FDC, 1444, UiPauseSharedTextureSlot::Cursor, UiSubsystem::FileSelect, UiPauseSharedTextureResultUse::OwnerDescriptorSlot, "OmoteUraSelectorScene_LoadResources", "normal/Master Quest selector cursor"},
    {0x0046964C, 0x004695B0, 320, UiPauseSharedTextureSlot::HudAtlas, UiSubsystem::QuestStatus, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseQuestPage_InitCursorRenderer", "Quest Status cursor renderer"},
    {0x00469804, 0x00469724, 368, UiPauseSharedTextureSlot::HudMenuTitle, UiSubsystem::QuestStatus, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseQuestPage_InitIconRenderer", "Quest Status icon renderer"},
    {0x00469944, 0x004698C0, 616, UiPauseSharedTextureSlot::HudAtlas, UiSubsystem::QuestStatus, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseQuestPage_InitAuxiliaryRenderers", "Quest Status auxiliary renderer zero"},
    {0x00469A64, 0x004698C0, 616, UiPauseSharedTextureSlot::HudAtlas, UiSubsystem::QuestStatus, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseQuestPage_InitAuxiliaryRenderers", "Quest Status auxiliary renderer one"},
    {0x0046AE24, 0x0046ACB8, 1012, UiPauseSharedTextureSlot::PauseTopPage, UiSubsystem::TouchControls, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseTouchButtonPanel_Init", "lower-screen touch-button panel"},
    {0x0046B6C0, 0x0046B554, 1020, UiPauseSharedTextureSlot::ItemPage, UiSubsystem::Items, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseItemsPage_Init", "items-page primary renderer"},
    {0x00471FE0, 0x00471F74, 7528, UiPauseSharedTextureSlot::CommonBackground00, UiSubsystem::Count, UiPauseSharedTextureResultUse::DiscardedLookup, "HintMovie_InitRenderer", "original HintMovie discarded lookup"},
    {0x00471FEC, 0x00471F74, 7528, UiPauseSharedTextureSlot::Cursor, UiSubsystem::Count, UiPauseSharedTextureResultUse::LocalRendererState, "HintMovie_InitRenderer", "HintMovie cursor renderer state"},
    {0x00480678, 0x0048046C, 688, UiPauseSharedTextureSlot::ItemPageAux, UiSubsystem::Items, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseItemsPage_InitAuxiliaryQuadGroup", "items-page auxiliary quad group"},
    {0x00480D3C, 0x00480BD8, 668, UiPauseSharedTextureSlot::MapPage01, UiSubsystem::Map, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseMapPage_Init", "map-page secondary renderer"},
    {0x00481020, 0x00480EB8, 696, UiPauseSharedTextureSlot::MapPage00, UiSubsystem::Map, UiPauseSharedTextureResultUse::TextureStageBinding, "PauseDungeonItemPanel_Init", "dungeon-item panel renderer"},
}};

} // namespace

const std::array<UiPauseSharedTextureConsumerDescriptor,
                 kOot3dPauseSharedTextureConsumerCount>&
Oot3dPauseSharedTextureConsumers() noexcept {
    return kConsumers;
}

const UiPauseSharedTextureConsumerDescriptor*
Oot3dPauseSharedTextureConsumerForCallSite(std::uint32_t call_site) noexcept {
    for (const auto& consumer : kConsumers) {
        if (consumer.call_site == call_site) {
            return &consumer;
        }
    }
    return nullptr;
}

std::size_t Oot3dPauseSharedTextureConsumerCountFor(
    UiPauseSharedTextureSlot slot) noexcept {
    if (slot == UiPauseSharedTextureSlot::Count) {
        return 0;
    }
    std::size_t count = 0;
    for (const auto& consumer : kConsumers) {
        if (consumer.slot == slot) {
            ++count;
        }
    }
    return count;
}

const UiPauseSharedTextureConsumerDescriptor* Oot3dPauseSharedTextureConsumerFor(
    UiPauseSharedTextureSlot slot, std::size_t ordinal) noexcept {
    if (slot == UiPauseSharedTextureSlot::Count) {
        return nullptr;
    }
    for (const auto& consumer : kConsumers) {
        if (consumer.slot == slot) {
            if (ordinal == 0) {
                return &consumer;
            }
            --ordinal;
        }
    }
    return nullptr;
}

static_assert(kConsumers.size() == 34);
static_assert(kConsumers.front().call_site == 0x002D1D30);
static_assert(kConsumers.back().call_site == 0x00481020);

} // namespace oot3d::ui
