#pragma once

// Generated by tools/build_ui_value_domains_tranche_220.py from
// verified OoT3D values. Numeric identity comes from OoT3D evidence;
// canonical N64 names are used only where tranche 210 proved agreement.

#include <cstddef>
#include <cstdint>
#include <type_traits>

namespace oot3d::ui {

enum class ButtonStatus : std::uint8_t {
    BTN_ENABLED = 0x00,
    BTN_DISABLED = 0xFF,
};
inline constexpr std::size_t kButtonStatusValueCount = 2;

enum class DungeonItem : std::uint8_t {
    DUNGEON_BOSS_KEY = 0x00,
    DUNGEON_COMPASS = 0x01,
    DUNGEON_MAP = 0x02,
};
inline constexpr std::size_t kDungeonItemValueCount = 3;

enum class EquipmentType : std::int32_t {
    EQUIP_TYPE_SWORD = 0x00,
    EQUIP_TYPE_SHIELD = 0x01,
    EQUIP_TYPE_TUNIC = 0x02,
    EQUIP_TYPE_BOOTS = 0x03,
};
inline constexpr std::size_t kEquipmentTypeValueCount = 4;

enum class HudVisibilityMode : std::uint16_t {
    HUD_VISIBILITY_NO_CHANGE = 0x00,
    HUD_VISIBILITY_NOTHING = 0x01,
    HUD_VISIBILITY_NOTHING_ALT = 0x02,
    HUD_VISIBILITY_HEARTS_FORCE = 0x03,
    HUD_VISIBILITY_A = 0x04,
    HUD_VISIBILITY_A_HEARTS_MAGIC_FORCE = 0x05,
    HUD_VISIBILITY_A_HEARTS_MAGIC_MINIMAP_FORCE = 0x06,
    HUD_VISIBILITY_ALL_NO_MINIMAP_BY_BTN_STATUS = 0x07,
    HUD_VISIBILITY_B = 0x08,
    HUD_VISIBILITY_HEARTS_MAGIC = 0x09,
    HUD_VISIBILITY_B_ALT = 0x0A,
    HUD_VISIBILITY_HEARTS = 0x0B,
    HUD_VISIBILITY_A_B_MINIMAP = 0x0C,
    HUD_VISIBILITY_HEARTS_MAGIC_FORCE = 0x0D,
    HUD_VISIBILITY_ALL = 0x32,
    HUD_VISIBILITY_NOTHING_INSTANT = 0x34,
};
inline constexpr std::size_t kHudVisibilityModeValueCount = 16;

enum class InventorySlot : std::uint8_t {
    SLOT_DEKU_STICK = 0x00,
    SLOT_DEKU_NUT = 0x01,
    SLOT_BOMB = 0x02,
    SLOT_BOW = 0x03,
    SLOT_ARROW_FIRE = 0x04,
    SLOT_DINS_FIRE = 0x05,
    SLOT_SLINGSHOT = 0x06,
    SLOT_OCARINA = 0x07,
    SLOT_BOMBCHU = 0x08,
    SLOT_HOOKSHOT = 0x09,
    SLOT_ARROW_ICE = 0x0A,
    SLOT_FARORES_WIND = 0x0B,
    SLOT_BOOMERANG = 0x0C,
    SLOT_LENS_OF_TRUTH = 0x0D,
    SLOT_MAGIC_BEAN = 0x0E,
    SLOT_HAMMER = 0x0F,
    SLOT_ARROW_LIGHT = 0x10,
    SLOT_NAYRUS_LOVE = 0x11,
    SLOT_BOTTLE_1 = 0x12,
    SLOT_BOTTLE_2 = 0x13,
    SLOT_BOTTLE_3 = 0x14,
    SLOT_BOTTLE_4 = 0x15,
    SLOT_TRADE_ADULT = 0x16,
    SLOT_TRADE_CHILD = 0x17,
    SLOT_NONE = 0xFF,
};
inline constexpr std::size_t kInventorySlotValueCount = 25;

enum class ItemId : std::uint8_t {
    ITEM_DEKU_STICK = 0x00,
    ITEM_DEKU_NUT = 0x01,
    ITEM_BOMB = 0x02,
    ITEM_BOW = 0x03,
    ITEM_ARROW_FIRE = 0x04,
    ITEM_DINS_FIRE = 0x05,
    ITEM_SLINGSHOT = 0x06,
    ITEM_OCARINA_FAIRY = 0x07,
    ITEM_OCARINA_OF_TIME = 0x08,
    ITEM_BOMBCHU = 0x09,
    ITEM_HOOKSHOT = 0x0A,
    ITEM_LONGSHOT = 0x0B,
    ITEM_ARROW_ICE = 0x0C,
    ITEM_FARORES_WIND = 0x0D,
    ITEM_BOOMERANG = 0x0E,
    ITEM_LENS_OF_TRUTH = 0x0F,
    ITEM_MAGIC_BEAN = 0x10,
    ITEM_HAMMER = 0x11,
    ITEM_ARROW_LIGHT = 0x12,
    ITEM_NAYRUS_LOVE = 0x13,
    ITEM_BOTTLE_EMPTY = 0x14,
    ITEM_BOTTLE_POTION_RED = 0x15,
    ITEM_BOTTLE_POTION_GREEN = 0x16,
    ITEM_BOTTLE_POTION_BLUE = 0x17,
    ITEM_BOTTLE_FAIRY = 0x18,
    ITEM_BOTTLE_FISH = 0x19,
    ITEM_BOTTLE_MILK_FULL = 0x1A,
    ITEM_BOTTLE_RUTOS_LETTER = 0x1B,
    ITEM_BOTTLE_BLUE_FIRE = 0x1C,
    ITEM_BOTTLE_BUG = 0x1D,
    ITEM_BOTTLE_BIG_POE = 0x1E,
    ITEM_BOTTLE_MILK_HALF = 0x1F,
    ITEM_BOTTLE_POE = 0x20,
    ITEM_WEIRD_EGG = 0x21,
    ITEM_CHICKEN = 0x22,
    ITEM_ZELDAS_LETTER = 0x23,
    ITEM_MASK_KEATON = 0x24,
    ITEM_MASK_SKULL = 0x25,
    ITEM_MASK_SPOOKY = 0x26,
    ITEM_MASK_BUNNY_HOOD = 0x27,
    ITEM_MASK_GORON = 0x28,
    ITEM_MASK_ZORA = 0x29,
    ITEM_MASK_GERUDO = 0x2A,
    ITEM_MASK_TRUTH = 0x2B,
    ITEM_SOLD_OUT = 0x2C,
    ITEM_POCKET_EGG = 0x2D,
    ITEM_POCKET_CUCCO = 0x2E,
    ITEM_COJIRO = 0x2F,
    ITEM_ODD_MUSHROOM = 0x30,
    ITEM_ODD_POTION = 0x31,
    ITEM_POACHERS_SAW = 0x32,
    ITEM_BROKEN_GORONS_SWORD = 0x33,
    ITEM_PRESCRIPTION = 0x34,
    ITEM_EYEBALL_FROG = 0x35,
    ITEM_EYE_DROPS = 0x36,
    ITEM_CLAIM_CHECK = 0x37,
    ITEM_BOW_FIRE = 0x38,
    ITEM_BOW_ICE = 0x39,
    ITEM_BOW_LIGHT = 0x3A,
    ITEM_SWORD_KOKIRI = 0x3B,
    ITEM_SWORD_MASTER = 0x3C,
    ITEM_SWORD_BIGGORON = 0x3D,
    ITEM_SHIELD_DEKU = 0x3E,
    ITEM_SHIELD_HYLIAN = 0x3F,
    ITEM_SHIELD_MIRROR = 0x40,
    ITEM_TUNIC_KOKIRI = 0x41,
    ITEM_TUNIC_GORON = 0x42,
    ITEM_TUNIC_ZORA = 0x43,
    ITEM_BOOTS_KOKIRI = 0x44,
    ITEM_BOOTS_IRON = 0x45,
    ITEM_BOOTS_HOVER = 0x46,
    ITEM_BULLET_BAG_30 = 0x47,
    ITEM_BULLET_BAG_40 = 0x48,
    ITEM_BULLET_BAG_50 = 0x49,
    ITEM_QUIVER_30 = 0x4A,
    ITEM_QUIVER_40 = 0x4B,
    ITEM_QUIVER_50 = 0x4C,
    ITEM_BOMB_BAG_20 = 0x4D,
    ITEM_BOMB_BAG_30 = 0x4E,
    ITEM_BOMB_BAG_40 = 0x4F,
    ITEM_STRENGTH_GORONS_BRACELET = 0x50,
    ITEM_STRENGTH_SILVER_GAUNTLETS = 0x51,
    ITEM_STRENGTH_GOLD_GAUNTLETS = 0x52,
    ITEM_SCALE_SILVER = 0x53,
    ITEM_SCALE_GOLDEN = 0x54,
    ITEM_GIANTS_KNIFE = 0x55,
    ITEM_ADULTS_WALLET = 0x56,
    ITEM_GIANTS_WALLET = 0x57,
    ITEM_DEKU_SEEDS = 0x58,
    ITEM_FISHING_POLE = 0x59,
    ITEM_SONG_MINUET = 0x5A,
    ITEM_SONG_BOLERO = 0x5B,
    ITEM_SONG_SERENADE = 0x5C,
    ITEM_SONG_REQUIEM = 0x5D,
    ITEM_SONG_NOCTURNE = 0x5E,
    ITEM_SONG_PRELUDE = 0x5F,
    ITEM_SONG_LULLABY = 0x60,
    ITEM_SONG_EPONA = 0x61,
    ITEM_SONG_SARIA = 0x62,
    ITEM_SONG_SUN = 0x63,
    ITEM_SONG_TIME = 0x64,
    ITEM_SONG_STORMS = 0x65,
    ITEM_MEDALLION_FOREST = 0x66,
    ITEM_MEDALLION_FIRE = 0x67,
    ITEM_MEDALLION_WATER = 0x68,
    ITEM_MEDALLION_SPIRIT = 0x69,
    ITEM_MEDALLION_SHADOW = 0x6A,
    ITEM_MEDALLION_LIGHT = 0x6B,
    ITEM_KOKIRI_EMERALD = 0x6C,
    ITEM_GORON_RUBY = 0x6D,
    ITEM_ZORA_SAPPHIRE = 0x6E,
    ITEM_STONE_OF_AGONY = 0x6F,
    ITEM_GERUDOS_CARD = 0x70,
    ITEM_SKULL_TOKEN = 0x71,
    ITEM_HEART_CONTAINER = 0x72,
    ITEM_HEART_PIECE = 0x73,
    ITEM_DUNGEON_BOSS_KEY = 0x74,
    ITEM_DUNGEON_COMPASS = 0x75,
    ITEM_DUNGEON_MAP = 0x76,
    ITEM_SMALL_KEY = 0x77,
    ITEM_MAGIC_JAR_SMALL = 0x78,
    ITEM_MAGIC_JAR_BIG = 0x79,
    ITEM_HEART_PIECE_2 = 0x7A,
    ITEM_INVALID_1 = 0x7B,
    ITEM_INVALID_2 = 0x7C,
    ITEM_INVALID_3 = 0x7D,
    ITEM_INVALID_4 = 0x7E,
    ITEM_INVALID_5 = 0x7F,
    ITEM_INVALID_6 = 0x80,
    ITEM_INVALID_7 = 0x81,
    ITEM_MILK = 0x82,
    ITEM_RECOVERY_HEART = 0x83,
    ITEM_RUPEE_GREEN = 0x84,
    ITEM_RUPEE_BLUE = 0x85,
    ITEM_RUPEE_RED = 0x86,
    ITEM_RUPEE_PURPLE = 0x87,
    ITEM_RUPEE_GOLD = 0x88,
    ITEM_INVALID_8 = 0x89,
    ITEM_DEKU_STICKS_5 = 0x8A,
    ITEM_DEKU_STICKS_10 = 0x8B,
    ITEM_DEKU_NUTS_5 = 0x8C,
    ITEM_DEKU_NUTS_10 = 0x8D,
    ITEM_BOMBS_5 = 0x8E,
    ITEM_BOMBS_10 = 0x8F,
    ITEM_BOMBS_20 = 0x90,
    ITEM_BOMBS_30 = 0x91,
    ITEM_ARROWS_5 = 0x92,
    ITEM_ARROWS_10 = 0x93,
    ITEM_ARROWS_30 = 0x94,
    ITEM_DEKU_SEEDS_30 = 0x95,
    ITEM_BOMBCHUS_5 = 0x96,
    ITEM_BOMBCHUS_20 = 0x97,
    ITEM_DEKU_STICK_UPGRADE_20 = 0x98,
    ITEM_DEKU_STICK_UPGRADE_30 = 0x99,
    ITEM_DEKU_NUT_UPGRADE_30 = 0x9A,
    ITEM_DEKU_NUT_UPGRADE_40 = 0x9B,
    ITEM_LAST_USED = 0xFC,
    ITEM_NONE_FE = 0xFE,
    ITEM_NONE = 0xFF,
};
inline constexpr std::size_t kItemIdValueCount = 159;

enum class LinkAge : std::int32_t {
    LINK_AGE_ADULT = 0x00,
    LINK_AGE_CHILD = 0x01,
    Adult = LINK_AGE_ADULT,
    Child = LINK_AGE_CHILD,
};
inline constexpr std::size_t kLinkAgeValueCount = 2;

enum class MagicState : std::int16_t {
    MAGIC_STATE_IDLE = 0x00,
    MAGIC_STATE_CONSUME_SETUP = 0x01,
    MAGIC_STATE_CONSUME = 0x02,
    MAGIC_STATE_METER_FLASH_1 = 0x03,
    MAGIC_STATE_METER_FLASH_2 = 0x04,
    MAGIC_STATE_RESET = 0x05,
    MAGIC_STATE_METER_FLASH_3 = 0x06,
    MAGIC_STATE_CONSUME_LENS = 0x07,
    MAGIC_STATE_STEP_CAPACITY = 0x08,
    MAGIC_STATE_FILL = 0x09,
    MAGIC_STATE_ADD = 0x0A,
};
inline constexpr std::size_t kMagicStateValueCount = 11;

enum class QuestItem : std::uint8_t {
    QUEST_MEDALLION_FOREST = 0x00,
    QUEST_MEDALLION_FIRE = 0x01,
    QUEST_MEDALLION_WATER = 0x02,
    QUEST_MEDALLION_SPIRIT = 0x03,
    QUEST_MEDALLION_SHADOW = 0x04,
    QUEST_MEDALLION_LIGHT = 0x05,
    QUEST_SONG_MINUET = 0x06,
    QUEST_SONG_BOLERO = 0x07,
    QUEST_SONG_SERENADE = 0x08,
    QUEST_SONG_REQUIEM = 0x09,
    QUEST_SONG_NOCTURNE = 0x0A,
    QUEST_SONG_PRELUDE = 0x0B,
    QUEST_SONG_LULLABY = 0x0C,
    QUEST_SONG_EPONA = 0x0D,
    QUEST_SONG_SARIA = 0x0E,
    QUEST_SONG_SUN = 0x0F,
    QUEST_SONG_TIME = 0x10,
    QUEST_SONG_STORMS = 0x11,
    QUEST_KOKIRI_EMERALD = 0x12,
    QUEST_GORON_RUBY = 0x13,
    QUEST_ZORA_SAPPHIRE = 0x14,
    QUEST_STONE_OF_AGONY = 0x15,
    QUEST_GERUDOS_CARD = 0x16,
    QUEST_SKULL_TOKEN = 0x17,
    QUEST_HEART_PIECE = 0x18,
};
inline constexpr std::size_t kQuestItemValueCount = 25;

enum class UpgradeType : std::int32_t {
    UPG_QUIVER = 0x00,
    UPG_BOMB_BAG = 0x01,
    UPG_STRENGTH = 0x02,
    UPG_SCALE = 0x03,
    UPG_WALLET = 0x04,
    UPG_BULLET_BAG = 0x05,
    UPG_DEKU_STICKS = 0x06,
    UPG_DEKU_NUTS = 0x07,
};
inline constexpr std::size_t kUpgradeTypeValueCount = 8;

inline constexpr std::size_t kVerifiedUiValueCount = 255;

template <typename Enum>
constexpr std::underlying_type_t<Enum> UiValueRaw(Enum value) noexcept {
    static_assert(std::is_enum_v<Enum>);
    return static_cast<std::underlying_type_t<Enum>>(value);
}

static_assert(kItemIdValueCount + kInventorySlotValueCount == 184);
static_assert(kButtonStatusValueCount + kDungeonItemValueCount +
                  kEquipmentTypeValueCount + kHudVisibilityModeValueCount +
                  kInventorySlotValueCount + kItemIdValueCount +
                  kLinkAgeValueCount + kMagicStateValueCount +
                  kQuestItemValueCount + kUpgradeTypeValueCount ==
              kVerifiedUiValueCount);

} // namespace oot3d::ui
