// Generated by generate_import.py from the immutable d5c2927 package.
// The source hash and target body identity are recorded in import_manifest.json.
#include "oot3d/cutscene_process_commands_owner.h"

#include <array>
#include <bit>
#include <cstdint>

namespace Oot3dSourceCutsceneProcessCommands {
namespace {

void Cutscene_ProcessCommandsImpl(
    std::uint32_t play, std::uint32_t csCtx,
    GuestPtr<const undefined1> script) {
  const auto& literal = ActiveLiterals();
  #define DAT_002c5ff0 (literal.Words[0])
  #define DAT_002c5ff4 (std::bit_cast<float>(literal.Words[1]))
  #define DAT_002c5ff8 (static_cast<std::int32_t>(literal.Words[2]))
  #define DAT_002c5ffc (std::bit_cast<float>(literal.Words[3]))
  #define DAT_002c6548 (literal.Words[4])
  #define DAT_002c654c (GuestPtr<uint>(literal.Words[5]))
  #define DAT_002c6550 (GuestPtr<uint>(literal.Words[6]))
  #define DAT_002c6554 (std::bit_cast<float>(literal.Words[7]))
  #define DAT_002c6558 (std::bit_cast<float>(literal.Words[8]))
  #define DAT_002c655c (literal.Words[9])
  #define DAT_002c6560 (literal.Words[10])
  #define DAT_002c6564 (GuestPtr<uint>(literal.Words[11]))
  #define DAT_002c6568 (std::bit_cast<float>(literal.Words[12]))
  #define DAT_002c656c (std::bit_cast<float>(literal.Words[13]))
  #define DAT_002c6570 (literal.Words[14])
  #define DAT_002c6574 (literal.Words[15])
  #define DAT_002c6578 (literal.Words[16])
  #define DAT_002c657c (literal.Words[17])
  #define DAT_002c6580 (GuestPtr<uint>(literal.Words[18]))
  #define DAT_002c6584 (literal.Words[19])
  #define DAT_002c6590 (literal.Words[20])
  #define DAT_002c6594 (std::bit_cast<float>(literal.Words[21]))
  #define DAT_002c6964 (literal.Words[22])
  #define DAT_002c6968 (literal.Words[23])
  #define DAT_002c696c (literal.Words[24])
  #define DAT_002c6970 (std::bit_cast<float>(literal.Words[25]))
  #define DAT_002c6974 (std::bit_cast<float>(literal.Words[26]))
  #define DAT_002c6978 (GuestPtr<uint>(literal.Words[27]))
  #define DAT_002c697c (literal.Words[28])
  #define DAT_002c6980 (GuestPtr<uint>(literal.Words[29]))
  #define DAT_002c6984 (std::bit_cast<float>(literal.Words[30]))
  #define DAT_002c6988 (literal.Words[31])
  #define DAT_002c698c (literal.Words[32])
  #define DAT_002c6990 (literal.Words[33])
  #define DAT_002c6994 (literal.Words[34])
  #define DAT_002c6998 (literal.Words[35])
  #define DAT_002c699c (literal.Words[36])
  #define DAT_002c69a0 (literal.Words[37])
  #define DAT_002c69a4 (literal.Words[38])
  #define DAT_002c69a8 (literal.Words[39])
  #define DAT_002c69ac (literal.Words[40])
  #define DAT_002c69b0 (GuestPtr<uint>(literal.Words[41]))
  #define DAT_002c6ca8 (std::bit_cast<float>(literal.Words[42]))
  #define DAT_002c6cac (std::bit_cast<float>(literal.Words[43]))
  #define DAT_002c6cb0 (static_cast<std::int32_t>(literal.Words[44]))
  #define DAT_002c6cb4 (static_cast<std::int32_t>(literal.Words[45]))
  #define DAT_002c6cb8 (static_cast<std::int32_t>(literal.Words[46]))
  #define DAT_002c6cbc (literal.Words[47])
  #define DAT_002c6cc0 (static_cast<std::int32_t>(literal.Words[48]))
  #define DAT_002c6cc4 (std::bit_cast<float>(literal.Words[49]))
  #define DAT_002c7a5c (std::bit_cast<float>(literal.Words[50]))
  #define DAT_002c7a60 (literal.Words[51])
  #define DAT_002c7a64 (GuestPtr<uint>(literal.Words[52]))
  #define DAT_002c7a68 (literal.Words[53])
  #define DAT_002c80ec (GuestPtr<uint>(literal.Words[54]))
  #define DAT_002c80f0 (literal.Words[55])
  #define DAT_002c80f4 (std::bit_cast<float>(literal.Words[56]))
  #define DAT_002c80f8 (std::bit_cast<float>(literal.Words[57]))
  #define DAT_002c80fc (literal.Words[58])
  #define DAT_002c8100 (literal.Words[59])
  #define DAT_002c8104 (literal.Words[60])
  #define DAT_002c8108 (literal.Words[61])
  #define DAT_002c810c (std::bit_cast<float>(literal.Words[62]))
  #define DAT_002c8110 (literal.Words[63])
  #define DAT_002c8114 (std::bit_cast<float>(literal.Words[64]))
  #define DAT_002c8118 (static_cast<std::int32_t>(literal.Words[65]))
  #define DAT_002c811c (GuestPtr<uint>(literal.Words[66]))
  #define DAT_002c8120 (GuestPtr<uint>(literal.Words[67]))
  #define DAT_002c8124 (literal.Words[68])


  ushort uVar1;
  ushort uVar2;
  GuestPtr<int> piVar3;
  GuestPtr<undefined1> puVar4;
  ushort uVar5;
  int iVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  GuestPtr<undefined4> puVar9;
  uint uVar10;
  int iVar11;
  int iVar12;
  short sVar13;
  int iVar14;
  GuestPtr<uint> puVar15;
  uint uVar16;
  undefined4 uVar17;
  GuestPtr<uint> puVar18;
  GuestPtr<uint> puVar19;
  int iVar20;
  bool bVar21;
  bool bVar22;
  float fVar23;
  float fVar24;
  float fVar25;
  float fVar26;
  float cutscene_misc_lerp;
  float cutscene_transition_lerp;
  int cutscene_int_result;
  float local_78;
  std::array<std::uint32_t, 3> local_74_vector{};
  auto& local_74 = local_74_vector[0];
  auto& local_70 = local_74_vector[1];
  auto& local_6c = local_74_vector[2];
  std::array<std::uint32_t, 3> local_68_vector{};
  auto& local_68 = local_68_vector[0];
  auto& local_64 = local_68_vector[1];
  auto& local_60 = local_68_vector[2];
  int local_5c;
  int local_58;
  uint local_54;
  int local_50;
  int local_4c;
  undefined1 auStack_48 [4];
  undefined1 auStack_44 [4];
  undefined1 auStack_40 [4];
  int local_3c;
  int local_38;
  int local_34;
  int local_30;

  local_5c = 0;
  FUN_00470778(auStack_40,script,4);
  FUN_00470778(auStack_44,script + 4,2);
  FUN_00470778(auStack_48,script + 6,2);
  FUN_00470778(&local_4c,script + 8,4);
  FUN_00470778(&local_58,script + 0xc,4);
  local_30 = play + 0x2298;
  *GuestPtr<int>(csCtx + 0x18) = local_58;
  if ((local_58 < (int)(uint)*GuestPtr<ushort>(csCtx + 0x20)) && (*GuestPtr<char>(csCtx + 8) != '\x04')) {
    *GuestPtr<int>(play + 0x22ac) = *GuestPtr<int>(play + 0x22ac) + 1;
    iVar6 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(play + 0x22bc));
    if ((iVar6 != 0) && (*GuestPtr<short>(DAT_002c5ff0 + iVar6) == 0x25)) {
      oot3d_set_byte_1b6();
      *GuestPtr<undefined1>(play + 0x22a8) = 0;
    }
    *GuestPtr<undefined1>(local_30 + 8) = 3;
  }
  else {
    iVar6 = FUN_00307650();
    if ((*GuestPtr<char>(iVar6 + 0xc) != '\0') &&
       ((*GuestPtr<char>(local_30 + 0x278) == '\0' &&
        (iVar6 = FUN_00492e94(play,*GuestPtr<undefined4>(local_30 + 0x18)), iVar6 != 0)))) {
      *GuestPtr<undefined1>(local_30 + 0x10) = 1;
      *GuestPtr<undefined1>(local_30 + 0x278) = 1;
    }
    local_3c = 0;
    if (0 < local_4c) {
      local_34 = DAT_002c5ff8;
      puVar15 = GuestPtr<uint>(script + 0x10);
      fVar25 = DAT_002c5ff4;
      fVar26 = DAT_002c5ffc;
      while( true ) {
        FUN_00470778(&local_50,puVar15,4);
        puVar18 = puVar15 + 1;
        if (local_50 == -1) break;
        if (local_50 == 0x4b) {
switchD_002c5d58_caseD_1d:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x50) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          goto switchD_002c5d58_caseD_0;
        }
        if (0x4b < local_50) {
          if (local_50 == 0x78) goto switchD_002c5d58_caseD_e;
          if (local_50 < 0x79) {
            switch((u32)(local_50)) {
            case 0x4c:
            case 0x55:
            case 0x5d:
            case 0x69:
            case 0x6b:
            case 0x6e:
            case 0x77:
              goto switchD_002c5d58_caseD_f;
            case 0x4d:
            case 0x54:
            case 0x5a:
switchD_002c5d58_caseD_2c:
              FUN_00470778(&local_54,puVar18,4);
              puVar18 = puVar15 + 2;
              iVar6 = 0;
              if (0 < (int)local_54) {
                do {
                  if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                     (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                    *GuestPtr<GuestPtr<uint>>(csCtx + 0x58) = puVar18;
                  }
                  puVar18 = puVar18 + 0xc;
                  iVar6 = (int)(short)((short)iVar6 + 1);
                } while (iVar6 < (int)local_54);
              }
              break;
            case 0x4e:
            case 0x50:
            case 0x5e:
            case 0x74:
            case 0x76:
              goto switchD_002c5d58_caseD_e;
            case 0x4f:
            case 0x53:
              goto switchD_002c5d58_caseD_1e;
            case 0x51:
            case 0x6a:
            case 0x75:
              goto switchD_002c5d58_caseD_19;
            case 0x52:
            case 0x6c:
              goto switchD_002c5d58_caseD_1d;
            case 0x56:
              FUN_00470778(&local_54,puVar18,4);
              puVar18 = puVar15 + 2;
              iVar6 = 0;
              if (0 < (int)local_54) {
                do {
                  if (*GuestPtr<ushort>(csCtx + 0x20) == *GuestPtr<ushort>((int)puVar18 + 2)) {
                    FUN_00490ec4(CONCAT22((ushort)*puVar18,(ushort)puVar18[1]));
                  }
                  puVar18 = puVar18 + 0xc;
                  iVar6 = (int)(short)((short)iVar6 + 1);
                } while (iVar6 < (int)local_54);
              }
              break;
            case 0x57:
              FUN_00470778(&local_54,puVar18,4);
              puVar18 = puVar15 + 2;
              iVar6 = 0;
              if (0 < (int)local_54) {
                do {
                  if (*GuestPtr<ushort>(csCtx + 0x20) == *GuestPtr<ushort>((int)puVar18 + 2)) {
                    FUN_00490e70(((ushort)*puVar18 & 0xff) - 1);
                  }
                  puVar18 = puVar18 + 0xc;
                  iVar6 = (int)(short)((short)iVar6 + 1);
                } while (iVar6 < (int)local_54);
              }
              break;
            case 0x58:
            case 0x73:
              goto switchD_002c5d58_caseD_1f;
            case 0x59:
            case 0x6f:
            case 0x72:
              goto switchD_002c5d58_caseD_31;
            default:
              goto switchD_002c5d58_caseD_b;
            }
          }
          else {
            if (local_50 == 0x88) goto switchD_002c5d58_caseD_2c;
            if (local_50 < 0x89) {
              switch((u32)(local_50)) {
              case 0x79:
              case 0x7e:
              case 0x84:
                goto switchD_002c5d58_caseD_19;
              default_oot3d_dup1:
                goto switchD_002c5d58_caseD_b;
              case 0x7b:
                goto switchD_002c5d58_caseD_f;
              case 0x7c:
                FUN_00470778(&local_54,puVar18,4);
                puVar18 = puVar15 + 2;
                iVar6 = 0;
                if (0 < (int)local_54) {
                  do {
                    if ((*GuestPtr<ushort>(csCtx + 0x20) == *GuestPtr<ushort>((int)puVar18 + 2)) &&
                       (*GuestPtr<ushort>(csCtx + 0x20) < (ushort)puVar18[1])) {
                      Audio_SetBGM((ushort)*puVar18 == 3,
                                   (ushort)puVar18[1] - *GuestPtr<ushort>((int)puVar18 + 2) & 0xff);
                    }
                    puVar18 = puVar18 + 0xc;
                    iVar6 = (int)(short)((short)iVar6 + 1);
                  } while (iVar6 < (int)local_54);
                }
                break;
              case 0x7d:
              case 0x83:
                goto switchD_002c5d58_caseD_e;
              case 0x7f:
              case 0x85:
                goto switchD_002c5d58_caseD_1d;
              case 0x80:
              case 0x87:
                goto switchD_002c5d58_caseD_1e;
              case 0x81:
                goto switchD_002c5d58_caseD_2c;
              case 0x82:
                goto switchD_002c5d58_caseD_1f;
              case 0x86:
                goto switchD_002c5d58_caseD_31;
              }
            }
            else if (local_50 == 0x8f) {
              FUN_00470778(&local_54,puVar18,4);
              puVar18 = puVar15 + 2;
              iVar6 = 0;
              if (0 < (int)local_54) {
                do {
                  if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                     (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                    *GuestPtr<GuestPtr<uint>>(csCtx + 0x68) = puVar18;
                  }
                  puVar18 = puVar18 + 0xc;
                  iVar6 = (int)(short)((short)iVar6 + 1);
                } while (iVar6 < (int)local_54);
              }
            }
            else if (local_50 < 0x90) {
              switch((u32)(local_50)) {
              case 0x89:
                goto switchD_002c5d58_caseD_1f;
              case 0x8a:
              case 0x8b:
                goto switchD_002c5d58_caseD_f;
              case 0x8c:
                FUN_00470778(&local_54,puVar18,4);
                piVar3 = GuestPtr<int>(DAT_002c6550);
                puVar18 = puVar15 + 2;
                iVar6 = 0;
                if (0 < (int)local_54) {
                  do {
                    if (*GuestPtr<ushort>(csCtx + 0x20) == *GuestPtr<ushort>((int)puVar18 + 2)) {
                      fVar23 = (float)VectorUnsignedToFloat
                                                ((uint)*GuestPtr<byte>((int)puVar18 + 6),
                                                 0);
                      fVar24 = (float)VectorUnsignedToFloat
                                                (*GuestPtr<byte>((int)puVar18 + 7) + 1,
                                                 0);
                      cutscene_int_result = (int)(fVar24 * fVar26);
                      sVar13 = (short)(int)(fVar23 * fVar25 * fVar26) +
                               (short)cutscene_int_result;
                      *GuestPtr<short>(piVar3 + 3) = sVar13;
                      *GuestPtr<short>(local_34 + 0xa8) = sVar13;
                    }
                    puVar18 = puVar18 + 3;
                    iVar6 = (int)(short)((short)iVar6 + 1);
                  } while (iVar6 < (int)local_54);
                }
                break;
              case 0x8d:
                goto switchD_002c5d58_caseD_e;
              case 0x8e:
                goto switchD_002c5d58_caseD_31;
              default_oot3d_dup2:
                goto switchD_002c5d58_caseD_b;
              }
            }
            else if (local_50 == 0x96) {
              puVar18 = puVar15 + (uint)*GuestPtr<ushort>((int)puVar15 + 10) * 8 + 3;
            }
            else if (local_50 < 0x97) {
              if (local_50 == 0x90) goto switchD_002c5d58_caseD_f;
              if (local_50 == 0x91) {
                FUN_00470778(&local_54,puVar18,4);
                puVar18 = puVar15 + 2;
                iVar6 = 0;
                if (0 < (int)local_54) {
                  do {
                    if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                       (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                      *GuestPtr<GuestPtr<uint>>(csCtx + 0x6c) = puVar18;
                    }
                    puVar18 = puVar18 + 0xc;
                    iVar6 = (int)(short)((short)iVar6 + 1);
                  } while (iVar6 < (int)local_54);
                }
              }
              else {
                if (local_50 != 0x92) goto switchD_002c5d58_caseD_b;
                FUN_00470778(&local_54,puVar18,4);
                puVar18 = puVar15 + 2;
                iVar6 = 0;
                if (0 < (int)local_54) {
                  do {
                    if ((*GuestPtr<ushort>(csCtx + 0x20) == *GuestPtr<ushort>((int)puVar18 + 2)) &&
                       (puVar9 = *GuestPtr<GuestPtr<undefined4>>(csCtx + 0x27c), static_cast<bool>(puVar9))) {
                      InvokeDynamicCallback(puVar9, puVar18);
                    }
                    puVar18 = puVar18 + 0xc;
                    iVar6 = (int)(short)((short)iVar6 + 1);
                  } while (iVar6 < (int)local_54);
                }
              }
            }
            else if (local_50 == 0x97) {
              local_60 = *puVar18;
              FUN_00494620(csCtx + 0x88,puVar15 + 2);
              iVar6 = DAT_002c8118;
              uVar16 = (uint)*GuestPtr<ushort>(csCtx + 0x20);
              iVar20 = -1;
              if (((*GuestPtr<uint>(DAT_002c8118 + 0x14) & 1) == 0) &&
                 (iVar11 = oot3d_static_init_guard_acquire(DAT_002c8118 + 0x14), iVar11 != 0)) {
                *GuestPtr<uint>(iVar6 + 0x18) = (uint)*GuestPtr<ushort>(csCtx + 0x20);
              }
              iVar11 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
              if (*GuestPtr<short>(iVar11 + 0x18a) != 0x25) {
                Gameplay_CameraChangeSetting
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x25);
                Gameplay_ChangeCameraStatus(play,(int)*GuestPtr<short>(iVar6 + 8),1);
                Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7);
                if (((*DAT_002c8120 & 1) == 0) &&
                    oot3d_static_init_guard_acquire(DAT_002c8120)) {
                  FUN_0031ff30(DAT_002c8124);
                }
                FUN_00438014();
              }
              iVar12 = FUN_0032b69c(csCtx + 0x88);
              puVar18 = GuestPtr<uint>(DAT_002c8120);
              iVar11 = 0;
              if (0 < iVar12) {
                do {
                  iVar14 = *GuestPtr<int>(*GuestPtr<int>(csCtx + 0x88) + 0x18 + iVar11 * 4) +
                           *GuestPtr<int>(csCtx + 0x88);
                  if ((*GuestPtr<int>(iVar14 + 8) < (int)uVar16) && ((int)uVar16 < *GuestPtr<int>(iVar14 + 0xc))
                     ) {
                    iVar20 = iVar11;
                  }
                  iVar11 = iVar11 + 1;
                } while (iVar11 < iVar12);
              }
              if (*GuestPtr<int>(csCtx + 0x84) == iVar20) {
                *GuestPtr<int>(iVar6 + 0x18) = *GuestPtr<int>(iVar6 + 0x18) + 1;
              }
              else {
                *GuestPtr<uint>(iVar6 + 0x18) = uVar16;
                *GuestPtr<int>(csCtx + 0x84) = iVar20;
                if (((*puVar18 & 1) == 0) &&
                    oot3d_static_init_guard_acquire(DAT_002c8120)) {
                  FUN_0031ff30(DAT_002c8124);
                }
                FUN_00438014();
              }
              if (-1 < iVar20) {
                local_68 = *GuestPtr<int>(csCtx + 0x88) +
                           *GuestPtr<int>(*GuestPtr<int>(csCtx + 0x88) + 0x18 + iVar20 * 4);
                local_64 = local_68 + *GuestPtr<int>(local_68 + 0x48);
                uVar17 = *GuestPtr<undefined4>(iVar6 + 0x18);
                iVar20 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                if (*GuestPtr<short>(iVar20 + 0x18a) != 0x25) {
                  Gameplay_CameraChangeSetting
                            (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x25);
                  Gameplay_ChangeCameraStatus(play,(int)*GuestPtr<short>(iVar6 + 8),1);
                  Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7)
                  ;
                }
                FUN_0033cb90(&local_68,uVar17,csCtx + 0x94);
                uVar17 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                FUN_0033cb1c(uVar17,csCtx + 0x94,*GuestPtr<undefined4>(play + 0x20ac),0);
              }
              FUN_002c411c(csCtx + 0x88);
              puVar18 = GuestPtr<uint>((int)(puVar15 + 2) + local_60);
            }
            else {
              if (local_50 != 1000) goto switchD_002c5d58_caseD_b;
              FUN_00491384(play,csCtx,puVar15 + 2);
              puVar18 = puVar15 + 4;
            }
          }
          goto switchD_002c5d58_caseD_0;
        }
        switch((u32)(local_50)) {
        case 0:
          break;
        case 1:
          uVar5 = *GuestPtr<ushort>((int)puVar15 + 6);
          bVar22 = true;
          puVar19 = puVar15 + 3;
          iVar6 = 8;
          if ((uVar5 < *GuestPtr<ushort>(csCtx + 0x20)) &&
             (*GuestPtr<ushort>(csCtx + 0x20) < (ushort)puVar15[2])) {
            uVar1 = *GuestPtr<ushort>(csCtx + 0x28);
            bVar21 = uVar1 <= uVar5;
            if (uVar5 <= uVar1) {
              bVar21 = 0xefff < uVar1;
            }
            if (bVar21) {
              *GuestPtr<undefined1>(csCtx + 0x35) = 1;
              *GuestPtr<GuestPtr<uint>>(csCtx + 0x3c) = puVar19;
              iVar20 = DAT_002c6cc0;
              if ((*GuestPtr<char>(csCtx + 0x34) != '\0') &&
                 (*GuestPtr<ushort>(csCtx + 0x28) = *GuestPtr<ushort>((int)puVar15 + 6),
                 *GuestPtr<char>(iVar20 + 1) != '\0')) {
                Gameplay_CameraChangeSetting
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x25);
                Gameplay_ChangeCameraStatus(play,(int)*GuestPtr<short>(DAT_002c6cc0 + 8),1);
                Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7);
                Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_ResetAnim();
                uVar17 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_SetCSParams(uVar17,*GuestPtr<undefined4>(csCtx + 0x38),
                                   *GuestPtr<undefined4>(csCtx + 0x3c),*GuestPtr<undefined4>(play + 0x20ac)
                                   ,0);
              }
            }
          }
          do {
            uVar16 = *puVar19;
            puVar19 = puVar19 + 4;
            iVar6 = iVar6 + 0x10;
            if ((char)uVar16 == -1) {
              bVar22 = false;
            }
          } while (bVar22);
          goto LAB_002c7388;
        case 2:
          uVar5 = *GuestPtr<ushort>((int)puVar15 + 6);
          bVar22 = true;
          puVar19 = puVar15 + 3;
          iVar6 = 8;
          if ((uVar5 < *GuestPtr<ushort>(csCtx + 0x20)) &&
             (*GuestPtr<ushort>(csCtx + 0x20) < (ushort)puVar15[2])) {
            uVar1 = *GuestPtr<ushort>(csCtx + 0x2a);
            bVar21 = uVar1 <= uVar5;
            if (uVar5 <= uVar1) {
              bVar21 = 0xefff < uVar1;
            }
            if (bVar21) {
              *GuestPtr<undefined1>(csCtx + 0x34) = 1;
              *GuestPtr<GuestPtr<uint>>(csCtx + 0x38) = puVar19;
              iVar20 = DAT_002c6cc0;
              if ((*GuestPtr<char>(csCtx + 0x35) != '\0') &&
                 (*GuestPtr<ushort>(csCtx + 0x2a) = *GuestPtr<ushort>((int)puVar15 + 6),
                 *GuestPtr<char>(iVar20 + 1) != '\0')) {
                *GuestPtr<int>(csCtx + 0x84) = local_5c;
                Gameplay_CameraChangeSetting
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x25);
                Gameplay_ChangeCameraStatus(play,(int)*GuestPtr<short>(DAT_002c6cc0 + 8),1);
                Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7);
                Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_ResetAnim();
                uVar17 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_SetCSParams(uVar17,*GuestPtr<undefined4>(csCtx + 0x38),
                                   *GuestPtr<undefined4>(csCtx + 0x3c),*GuestPtr<undefined4>(play + 0x20ac)
                                   ,0);
              }
            }
          }
          do {
            uVar16 = *puVar19;
            puVar19 = puVar19 + 4;
            iVar6 = iVar6 + 0x10;
            if ((char)uVar16 == -1) {
              bVar22 = false;
            }
          } while (bVar22);
          goto LAB_002c759c;
        case 3:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              iVar20 = *GuestPtr<int>(play + 0x20ac);
              if ((*GuestPtr<ushort>(csCtx + 0x20) < *GuestPtr<ushort>((int)puVar18 + 2)) ||
                 ((uVar5 = (ushort)puVar18[1], uVar5 <= *GuestPtr<ushort>(csCtx + 0x20) &&
                  (uVar5 != *GuestPtr<ushort>((int)puVar18 + 2))))) goto switchD_002c60f4_caseD_0;
              cutscene_misc_lerp = FUN_00361490(
                  uVar5 - 1,
                  *GuestPtr<ushort>((int)puVar18 + 2),
                  *GuestPtr<ushort>(csCtx + 0x20));
              iVar11 = local_30;
              uVar10 = DAT_002c6990;
              puVar4 = GuestPtr<undefined1>(DAT_002c6980);
              uVar7 = DAT_002c6574;
              uVar17 = DAT_002c6570;
              fVar23 = DAT_002c6568;
              piVar3 = GuestPtr<int>(DAT_002c6550);
              bVar22 = *GuestPtr<ushort>(csCtx + 0x20) == *GuestPtr<ushort>((int)puVar18 + 2);
              uVar16 = (uint)(ushort)*puVar18;
              switch((u32)(uVar16)) {
              case 1:
                if (bVar22) {
                  FUN_003665fc(0xe,4,0x3f);
                  FUN_003665fc(0xe,1,1);
                  *GuestPtr<undefined1>(DAT_002c6548 + play) = 0x14;
                }
                break;
              case 2:
                if (bVar22) {
                  FUN_003665fc(0xf,0,0);
                  FUN_00490e1c(play,3);
                  *DAT_002c654c = 1;
                }
                break;
              case 3:
                if ((bVar22) && (Flags_SetEnv(play,0), *DAT_002c6550 == 0x53)) {
                  Flags_SetEnv(play,2);
                }
                break;
              case 6:
                fVar24 = *GuestPtr<float>(play + 0x3214);
                if ((int)fVar24 < DAT_002c6554) {
                  fVar24 = fVar24 + DAT_002c6558;
                  *GuestPtr<float>(play + 0x3214) = fVar24;
                }
                break;
              case 7:
                if (bVar22) {
                  *GuestPtr<undefined1>(play + 0x31aa) = 1;
                  *GuestPtr<undefined1>(play + 0x31a8) = 1;
                  *GuestPtr<undefined1>(play + 0x31a9) = 0;
                  *GuestPtr<undefined2>(play + 0x31ac) = 0x3c;
                  *GuestPtr<undefined1>(play + 0x31b3) = 1;
                  *GuestPtr<undefined1>(play + 0x31b1) = 0;
                  *GuestPtr<undefined1>(play + 0x31b2) = 1;
                  *GuestPtr<undefined2>(play + 0x31b6) = 0x3c;
                  *GuestPtr<undefined2>(play + 0x31b4) = 0x3c;
                }
                break;
              case 8:
                if (*GuestPtr<short>(play + 0x53f0) < 0x80) {
                  sVar13 = *GuestPtr<short>(play + 0x53f0) + 4;
LAB_002c6378:
                  *GuestPtr<short>(play + 0x53f0) = sVar13;
                }
                break;
              case 9:
                *GuestPtr<undefined1>(DAT_002c655c + play) = 0x10;
                break;
              case 10:
                Flags_SetEnv(play,1);
                break;
              case 0xb:
                if (*GuestPtr<short>(play + 0x53f0) < DAT_002c6560) {
                  *GuestPtr<short>(play + 0x53f0) = *GuestPtr<short>(play + 0x53f0) + 0x14;
                }
                fVar24 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                    0);
                uVar8 = DAT_002c6578;
                uVar7 = DAT_002c6574;
                uVar17 = DAT_002c6570;
                if ((int)(fVar23 / fVar24 + DAT_002c656c) == (uint)*GuestPtr<ushort>(csCtx + 0x20))
                goto LAB_002c68f0;
                fVar24 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                    0);
                cutscene_int_result =
                    (int)(fVar23 / fVar24 + DAT_002c656c);
                if ((float)cutscene_int_result == (float)(uint)*GuestPtr<ushort>(csCtx + 0x20)) {
                  sVar13 = 0;
                  goto LAB_002c6378;
                }
                break;
              case 0xc:
                if (bVar22) {
                  uVar16 = (uint)*GuestPtr<byte>(csCtx + 8);
                }
                if (bVar22 && uVar16 != 4) {
                  *GuestPtr<int>(local_30 + 0x14) = *GuestPtr<int>(local_30 + 0x14) + 1;
                  iVar20 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(local_30 + 0x24));
                  if ((iVar20 != 0) && (*GuestPtr<short>(DAT_002c5ff0 + iVar20) == 0x25)) {
                    oot3d_set_byte_1b6();
                    *GuestPtr<undefined1>(iVar11 + 0x10) = 0;
                  }
                  *GuestPtr<undefined1>(local_30 + 8) = 3;
                }
                break;
              case 0xd:
                if (*GuestPtr<short>(play + 0x53f2) == 0) {
                  Audio_PlaySoundGeneral(DAT_002c657c,0,4,DAT_002c6574,DAT_002c6574,DAT_002c6570);
                }
                if (*GuestPtr<short>(play + 0x53f2) < 0xff) {
                  *GuestPtr<short>(play + 0x53f2) = *GuestPtr<short>(play + 0x53f2) + 5;
                }
                break;
              case 0xe:
                if (bVar22) {
                  FUN_00340a1c(play,1);
                }
                break;
              case 0xf:
                if (bVar22) {
                  uVar16 = *GuestPtr<uint>(play + 0x114);
                }
                if (bVar22 && uVar16 != 0) {
                  if (((*DAT_002c6580 & 1) == 0) &&
                     (iVar20 = oot3d_static_init_guard_acquire(DAT_002c6580), iVar20 != 0)) {
                    RendererGlobalState_Init(DAT_002c6584);
                  }
                  iVar20 = 0;
                  if ((*GuestPtr<int>(DAT_002c6590 + 0xf3c) == 6 || *GuestPtr<int>(DAT_002c6590 + 0xf3c) == 7)
                     && (*GuestPtr<short>(play + 0x104) == 0x60 || *GuestPtr<short>(play + 0x104) == 0x61)
                     ) {
                    iVar20 = 0x20;
                  }
                  iVar11 = ZAR_GetCTXBByIndex(play + 0x118);
                  if (iVar11 != 0) {
                    fVar23 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),0);
                    local_74 = (int)(fVar25 / fVar23 + DAT_002c656c);
                    TitleCard_InitPlaceName(
                        play,play + 0x224c,iVar11,200,
                        0x78,0x100,iVar20 + 0x20,local_74,0,
                        DAT_002c6594);
                  }
                }
                break;
              case 0x10:
                if (bVar22) {
                  uVar7 = Quake_Add(*GuestPtr<undefined4>
                                     (play + *GuestPtr<short>(DAT_002c6964 + play) * 4 + 0xa54),6);
                  uVar17 = DAT_002c6968;
                  *GuestPtr<short>(csCtx + 0x30) = (short)uVar7;
                  Quake_SetSpeed(uVar7,uVar17);
                  Quake_SetQuakeValues((int)*GuestPtr<short>(csCtx + 0x30),2,0,100,0);
                  Quake_SetCountdown((int)*GuestPtr<short>(csCtx + 0x30),800);
                }
                break;
              case 0x11:
                if (bVar22) {
                  Quake_RemoveFromIdx((int)*GuestPtr<short>(csCtx + 0x30));
                }
                break;
              case 0x12:
                *GuestPtr<undefined1>(play + 0x326e) = 0;
                *GuestPtr<undefined1>(play + 0x325d) = 2;
                if (*GuestPtr<ushort>(piVar3 + 3) < DAT_002c696c) {
                  fVar23 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                      0);
                  cutscene_int_result = (int)(DAT_002c656c + fVar23 * DAT_002c6970 * DAT_002c6974);
                  *GuestPtr<ushort>(piVar3 + 3) = *GuestPtr<ushort>(piVar3 + 3) +
                      (ushort)cutscene_int_result;
                }
                if (*GuestPtr<char>(play + 0x326f) == '\0') {
                  *DAT_002c6978 = 0;
                  FUN_003665fc(0xe,1,0);
                }
                break;
              case 0x13:
                *GuestPtr<ushort>(DAT_002c697c + 0xf8) = *GuestPtr<ushort>(DAT_002c697c + 0xf8) | 0x20;
                break;
              case 0x14:
                uVar5 = *GuestPtr<ushort>(DAT_002c697c + 0xf8) | 0x80;
                goto LAB_002c66d4;
              case 0x15:
                uVar5 = *GuestPtr<ushort>(DAT_002c697c + 0xf8) | 0x200;
LAB_002c66d4:
                *GuestPtr<ushort>(DAT_002c697c + 0xf8) = uVar5;
                break;
              case 0x16:
                DAT_002c6980[3] = 0xff;
                puVar4[2] = 0xff;
                puVar4[1] = 0xff;
                *puVar4 = 0xff;
                break;
              case 0x17:
                DAT_002c6980[3] = 0xff;
                puVar4[2] = 0xb4;
                puVar4[1] = 100;
                cutscene_int_result = VectorFloatToUnsigned(
                    cutscene_misc_lerp * DAT_002c6984,3);
                *puVar4 = (undefined1)cutscene_int_result;
                *GuestPtr<undefined1>(DAT_002c6988 + play) = 1;
                break;
              case 0x18:
                *GuestPtr<undefined1>(*GuestPtr<int>(DAT_002c698c + play) + 0xad) = 0;
                break;
              case 0x19:
                uVar5 = *GuestPtr<ushort>(DAT_002c6550 + 3);
                fVar23 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                    0);
                cutscene_int_result = (int)(DAT_002c656c + fVar23 * DAT_002c6970 * DAT_002c6974);
                *GuestPtr<short>(DAT_002c6550 + 3) = (short)((uint)uVar5 + cutscene_int_result);
                if (uVar10 < ((uint)uVar5 + cutscene_int_result & 0xffff)) {
                  *GuestPtr<short>(piVar3 + 3) = (short)uVar10;
                }
                break;
              case 0x1a:
                uVar16 = (uint)*GuestPtr<ushort>(DAT_002c6550 + 3);
                if (DAT_002c6994 <= uVar16 - 0x3000) {
                  if (uVar16 - 0x4555 < DAT_002c6998) {
                    *GuestPtr<undefined1>(DAT_002c699c + play) = 1;
                  }
                  else if (uVar16 - 0xaaab < DAT_002c69a0) {
                    *GuestPtr<undefined1>(DAT_002c699c + play) = 2;
                  }
                  else {
                    *GuestPtr<undefined1>(DAT_002c699c + play) = 3;
                  }
                }
                break;
              case 0x1b:
                if ((*GuestPtr<uint>(play + 0xf8) & 8) == 0) {
                  if (2 < *GuestPtr<short>(play + 0x31fc)) {
                    *GuestPtr<short>(play + 0x31fc) = *GuestPtr<short>(play + 0x31fc) + -2;
                    *GuestPtr<short>(play + 0x3204) = *GuestPtr<short>(play + 0x3204) + 3;
                    sVar13 = *GuestPtr<short>(play + 0x3206) + 3;
                    goto LAB_002c6874;
                  }
                }
                else if (*GuestPtr<short>(play + 0x31fc) < 0x28) {
                  *GuestPtr<short>(play + 0x31fc) = *GuestPtr<short>(play + 0x31fc) + 2;
                  *GuestPtr<short>(play + 0x3204) = *GuestPtr<short>(play + 0x3204) + -3;
                  sVar13 = *GuestPtr<short>(play + 0x3206) + -3;
LAB_002c6874:
                  *GuestPtr<short>(play + 0x3206) = sVar13;
                }
                break;
              case 0x1c:
                *GuestPtr<undefined1>(DAT_002c69a4 + play) = 1;
                break;
              case 0x1d:
                *GuestPtr<undefined1>(DAT_002c69a4 + play) = 0;
                break;
              case 0x1e:
                Flags_SetEnv(play,3);
                break;
              case 0x1f:
                Flags_SetEnv(play,4);
                break;
              case 0x20:
                uVar8 = DAT_002c69ac;
                if (bVar22) {
                  *GuestPtr<undefined1>(DAT_002c69a8 + play) = 1;
                  uVar8 = DAT_002c69ac;
                }
LAB_002c68f0:
                Audio_PlaySoundGeneral(uVar8,0,4,uVar7,uVar7,uVar17);
                break;
              case 0x21:
                *GuestPtr<undefined2>(local_34 + 0xb0) = 1;
                break;
              case 0x22:
                uVar16 = (uint)*DAT_002c69b0;
                if (DAT_002c6550[4] == 0) {
                  if (uVar16 == 0) {
                    fVar23 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                        0);
                    fVar23 = fVar23 * DAT_002c6ca8 * DAT_002c6974 - DAT_002c6cac;
                  }
                  else {
                    fVar23 = (float)VectorUnsignedToFloat(uVar16,0);
                    fVar24 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                        0);
                    fVar23 = DAT_002c656c + fVar24 * fVar23 * DAT_002c6974;
                  }
                  cutscene_int_result = (int)fVar23;
                  sVar13 = (short)-cutscene_int_result;
                }
                else {
                  if (uVar16 == 0) {
                    fVar23 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                        0);
                    fVar23 = fVar23 * DAT_002c6ca8 * DAT_002c6974 - DAT_002c6cac;
                  }
                  else {
                    fVar23 = (float)VectorUnsignedToFloat(uVar16,0);
                    fVar24 = (float)VectorSignedToFloat((int)*GuestPtr<short>(*DAT_002c6564 + 0x110),
                                                        0);
                    fVar23 = DAT_002c6cac + fVar24 * fVar23 * DAT_002c6974;
                  }
                  cutscene_int_result = (int)fVar23;
                  sVar13 = (short)cutscene_int_result * -2;
                }
                *GuestPtr<short>(DAT_002c6550 + 3) = (short)DAT_002c6550[3] + sVar13;
                break;
              case 0x23:
                FUN_00493328();
                *GuestPtr<ushort>(csCtx + 0x20) = *GuestPtr<ushort>((int)puVar18 + 2) - 1;
                iVar20 = DAT_002c6cb0;
                *GuestPtr<undefined4>(DAT_002c6cb0 + 0x558) = 0xff;
                *GuestPtr<undefined1>(iVar20 + 0x56e) = 0xff;
                *GuestPtr<undefined4>(iVar20 + 0x4e4) = 6;
                *GuestPtr<undefined1>(play + 0x5c2d) = 0x14;
                *GuestPtr<undefined1>(play + 0x5c76) = 2;
                break;
              case 0x24:
                FUN_0035af04(iVar20,1);
                break;
              case 0x25:
                FUN_0035af04(iVar20,0);
                break;
              case 0x26:
                local_68 = DAT_002c6cb4;
                local_64 = DAT_002c6cb8;
                local_60 = DAT_002c6cbc;
                Gameplay_CameraSetAtEye
                          (play,(int)*GuestPtr<short>(DAT_002c6cc0 + 8),iVar20 + 0x28,&local_68);
                *GuestPtr<float>(csCtx + 0x1c) = DAT_002c6ca8;
                break;
              case 0x27:
                uVar5 = *GuestPtr<ushort>(*DAT_002c6564 + 0xd38);
                bVar22 = uVar5 == 0xffff;
                if (bVar22) {
                  uVar5 = (ushort)*GuestPtr<byte>(csCtx + 0x27a);
                }
                if (bVar22 && uVar5 == 0) {
                  *GuestPtr<undefined1>(play + 0x3262) = 0xa0;
                  *GuestPtr<undefined1>(play + 0x3263) = 0xa0;
                  *GuestPtr<undefined1>(play + 0x3264) = 0xa0;
                  *GuestPtr<undefined1>(play + 0x3265) = 0xff;
                  *GuestPtr<undefined1>(csCtx + 0x27a) = 1;
                }
              }
switchD_002c60f4_caseD_0:
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 4:
          FUN_00470778(&local_54,puVar18,4);
          fVar23 = DAT_002c6cc4;
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if (*GuestPtr<ushort>(csCtx + 0x20) == *GuestPtr<ushort>((int)puVar18 + 2)) {
                *GuestPtr<char>(play + 0x3237) = (char)(ushort)*puVar18 + -1;
                *GuestPtr<float>(play + 0x3258) = fVar23;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 5:
          uVar5 = *GuestPtr<ushort>((int)puVar15 + 6);
          bVar22 = true;
          puVar19 = puVar15 + 3;
          iVar6 = 8;
          if ((uVar5 < *GuestPtr<ushort>(csCtx + 0x20)) &&
             (*GuestPtr<ushort>(csCtx + 0x20) < (ushort)puVar15[2])) {
            uVar1 = *GuestPtr<ushort>(csCtx + 0x28);
            bVar21 = uVar1 <= uVar5;
            if (uVar5 <= uVar1) {
              bVar21 = 0xefff < uVar1;
            }
            if (bVar21) {
              *GuestPtr<undefined1>(csCtx + 0x35) = 1;
              *GuestPtr<GuestPtr<uint>>(csCtx + 0x3c) = puVar19;
              iVar20 = DAT_002c6cc0;
              if ((*GuestPtr<char>(csCtx + 0x34) != '\0') &&
                 (*GuestPtr<ushort>(csCtx + 0x28) = *GuestPtr<ushort>((int)puVar15 + 6),
                 *GuestPtr<char>(iVar20 + 1) != '\0')) {
                Gameplay_CameraChangeSetting
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x25);
                Gameplay_ChangeCameraStatus(play,(int)*GuestPtr<short>(DAT_002c6cc0 + 8),1);
                Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7);
                Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_ResetAnim();
                uVar17 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_SetCSParams(uVar17,*GuestPtr<undefined4>(csCtx + 0x38),
                                   *GuestPtr<undefined4>(csCtx + 0x3c),*GuestPtr<undefined4>(play + 0x20ac)
                                   ,1);
              }
            }
          }
          do {
            uVar16 = *puVar19;
            puVar19 = puVar19 + 4;
            iVar6 = iVar6 + 0x10;
            if ((char)uVar16 == -1) {
              bVar22 = false;
            }
          } while (bVar22);
LAB_002c7388:
          puVar18 = GuestPtr<uint>((int)puVar18 + iVar6);
          break;
        case 6:
          uVar5 = *GuestPtr<ushort>((int)puVar15 + 6);
          bVar22 = true;
          puVar19 = puVar15 + 3;
          iVar6 = 8;
          if ((uVar5 < *GuestPtr<ushort>(csCtx + 0x20)) &&
             (*GuestPtr<ushort>(csCtx + 0x20) < (ushort)puVar15[2])) {
            uVar1 = *GuestPtr<ushort>(csCtx + 0x2a);
            bVar21 = uVar1 <= uVar5;
            if (uVar5 <= uVar1) {
              bVar21 = 0xefff < uVar1;
            }
            if (bVar21) {
              *GuestPtr<undefined1>(csCtx + 0x34) = 1;
              *GuestPtr<GuestPtr<uint>>(csCtx + 0x38) = puVar19;
              iVar20 = DAT_002c6cc0;
              if ((*GuestPtr<char>(csCtx + 0x35) != '\0') &&
                 (*GuestPtr<ushort>(csCtx + 0x2a) = *GuestPtr<ushort>((int)puVar15 + 6),
                 *GuestPtr<char>(iVar20 + 1) != '\0')) {
                *GuestPtr<int>(csCtx + 0x84) = local_5c;
                Gameplay_CameraChangeSetting
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x25);
                Gameplay_ChangeCameraStatus(play,(int)*GuestPtr<short>(DAT_002c6cc0 + 8),1);
                Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7);
                Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_ResetAnim();
                uVar17 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                Camera_SetCSParams(uVar17,*GuestPtr<undefined4>(csCtx + 0x38),
                                   *GuestPtr<undefined4>(csCtx + 0x3c),*GuestPtr<undefined4>(play + 0x20ac)
                                   ,1);
              }
            }
          }
          do {
            uVar16 = *puVar19;
            puVar19 = puVar19 + 4;
            iVar6 = iVar6 + 0x10;
            if ((char)uVar16 == -1) {
              bVar22 = false;
            }
          } while (bVar22);
LAB_002c759c:
          puVar18 = GuestPtr<uint>((int)puVar18 + iVar6);
          local_5c = local_5c + 1;
          break;
        case 7:
          uVar5 = *GuestPtr<ushort>((int)puVar15 + 6);
          if ((uVar5 < *GuestPtr<ushort>(csCtx + 0x20)) &&
             (*GuestPtr<ushort>(csCtx + 0x20) < (ushort)puVar15[2])) {
            uVar1 = *GuestPtr<ushort>(csCtx + 0x2c);
            bVar22 = uVar1 <= uVar5;
            if (uVar5 <= uVar1) {
              bVar22 = 0xefff < uVar1;
            }
            if (bVar22) {
              *GuestPtr<undefined1>(csCtx + 0x35) = 1;
              *GuestPtr<GuestPtr<uint>>(csCtx + 0x3c) = puVar15 + 3;
              iVar6 = DAT_002c6cc0;
              if ((*GuestPtr<char>(csCtx + 0x34) != '\0') &&
                 (*GuestPtr<ushort>(csCtx + 0x2c) = *GuestPtr<ushort>((int)puVar15 + 6),
                 *GuestPtr<char>(iVar6 + 1) != '\0')) {
                iVar6 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                *GuestPtr<undefined4>(iVar6 + 0xd8) = 0;
                Gameplay_ChangeCameraStatus(play,0,1);
                Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7);
                Gameplay_CameraChangeSetting
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x21);
                local_78 = (float)VectorSignedToFloat((int)*GuestPtr<char>(*GuestPtr<int>(csCtx + 0x38) + 1),
                                                      0);
                local_78 = local_78 * DAT_002c7a5c;
                Camera_SetParam(iVar6,0x40,&local_78);
                local_68 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x38) + 8),
                                               0));
                local_64 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x38) + 10),
                                               0));
                local_60 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x38) + 0xc),
                                               0));
                local_74 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x3c) + 8),
                                               0));
                local_70 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x3c) + 10),
                                               0));
                local_6c = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x3c) + 0xc),
                                               0));
                Gameplay_CameraSetAtEye
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),&local_68,&local_74);
                FUN_00354220(
                    play,
                    (int)(short)*GuestPtr<undefined4>(csCtx + 0x24),
                    *GuestPtr<float>(*GuestPtr<int>(csCtx + 0x3c) + 4));
              }
            }
          }
          puVar18 = puVar15 + 7;
          break;
        case 8:
          uVar5 = *GuestPtr<ushort>((int)puVar15 + 6);
          if ((uVar5 < *GuestPtr<ushort>(csCtx + 0x20)) &&
             (*GuestPtr<ushort>(csCtx + 0x20) < (ushort)puVar15[2])) {
            uVar1 = *GuestPtr<ushort>(csCtx + 0x2e);
            bVar22 = uVar1 <= uVar5;
            if (uVar5 <= uVar1) {
              bVar22 = 0xefff < uVar1;
            }
            if (bVar22) {
              *GuestPtr<undefined1>(csCtx + 0x34) = 1;
              *GuestPtr<GuestPtr<uint>>(csCtx + 0x38) = puVar15 + 3;
              iVar6 = DAT_002c6cc0;
              if ((*GuestPtr<char>(csCtx + 0x35) != '\0') &&
                 (*GuestPtr<ushort>(csCtx + 0x2e) = *GuestPtr<ushort>((int)puVar15 + 6),
                 *GuestPtr<char>(iVar6 + 1) != '\0')) {
                iVar6 = Gameplay_GetCamera(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24));
                *GuestPtr<undefined4>(iVar6 + 0xd8) = 0;
                *GuestPtr<int>(csCtx + 0x84) = local_5c;
                Gameplay_ChangeCameraStatus(play,0,1);
                Gameplay_ChangeCameraStatus(play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),7);
                Gameplay_CameraChangeSetting
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),0x21);
                local_68 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x38) + 8),
                                               0));
                local_64 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x38) + 10),
                                               0));
                local_60 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x38) + 0xc),
                                               0));
                local_74 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x3c) + 8),
                                               0));
                local_70 = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x3c) + 10),
                                               0));
                local_6c = std::bit_cast<std::uint32_t>(VectorSignedToFloat((int)*GuestPtr<short>(*GuestPtr<int>(csCtx + 0x3c) + 0xc),
                                               0));
                Gameplay_CameraSetAtEye
                          (play,(int)(short)*GuestPtr<undefined4>(csCtx + 0x24),&local_68,&local_74);
                FUN_00354220(
                    play,
                    (int)(short)*GuestPtr<undefined4>(csCtx + 0x24),
                    *GuestPtr<float>(*GuestPtr<int>(csCtx + 0x3c) + 4));
              }
            }
          }
          puVar18 = puVar15 + 7;
          local_5c = local_5c + 1;
          break;
        case 9:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          if ((int)local_54 < 1) {
            uVar16 = 0;
          }
          else {
            uVar16 = local_54 & 1;
          }
          if (uVar16 == 1) {
            puVar18 = puVar15 + 5;
          }
          for (; (int)uVar16 < (int)local_54; uVar16 = (uint)(short)((short)uVar16 + 2)) {
            puVar18 = puVar18 + 6;
          }
          break;
        case 10:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x40) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        default:
default_oot3d_dup3:
switchD_002c5d58_caseD_b:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          if (0 < (int)local_54) {
            puVar18 = puVar18 + local_54 * 0xc;
          }
          break;
        case 0xe:
        case 0x10:
        case 0x18:
        case 0x23:
        case 0x28:
        case 0x30:
        case 0x40:
        case 0x44:
        case 0x46:
switchD_002c5d58_caseD_e:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x48) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 0xf:
        case 0x11:
        case 0x12:
        case 0x17:
        case 0x22:
        case 0x27:
        case 0x2e:
switchD_002c5d58_caseD_f:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x44) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 0x13:
          FUN_00470778(&local_54,puVar18,4);
          uVar16 = DAT_002c7a60;
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            local_38 = play + 0x28a0;
            do {
              uVar5 = (ushort)*puVar18;
              uVar10 = (uint)uVar5;
              if (((uVar10 != uVar16) &&
                  (uVar1 = *GuestPtr<ushort>(csCtx + 0x20), *GuestPtr<ushort>((int)puVar18 + 2) < uVar1)) &&
                 (uVar1 <= (ushort)puVar18[1])) {
                uVar2 = *GuestPtr<ushort>((int)puVar18 + 6);
                if (uVar2 == 2) {
                  if (uVar10 == *GuestPtr<ushort>(DAT_002c6cc0 + 4)) goto LAB_002c7ad4;
                  *GuestPtr<ushort>(DAT_002c6cc0 + 4) = uVar5;
                  FUN_0037073c(play,(ushort)*puVar18);
                }
                else if (uVar10 == *GuestPtr<ushort>(DAT_002c6cc0 + 2)) {
LAB_002c7ad4:
                  if ((ushort)puVar18[1] <= uVar1) {
                    local_60 = (uint)*GuestPtr<short>(csCtx + 0x20);
                    iVar20 = Message_GetState(local_38);
                    if (((iVar20 == 2 || iVar20 == 0) || iVar20 == 7) || iVar20 == 8) {
                      iVar11 = FUN_004929f4(play);
                      if ((iVar11 != 0) && (iVar20 == 2 || iVar20 == 0)) {
                        iVar20 = FUN_00369f3c(play);
                        if (iVar20 == 0) {
                          uVar5 = (ushort)puVar18[2];
                        }
                        else {
                          uVar5 = *GuestPtr<ushort>((int)puVar18 + 10);
                        }
                        if (uVar5 == uVar16) {
LAB_002c7b88:
                          *GuestPtr<short>(csCtx + 0x20) = *GuestPtr<short>(csCtx + 0x20) + 1;
                        }
                        else {
                          FUN_00367c7c(play,(uint)uVar5,0);
                        }
                      }
                    }
                    else {
                      sVar13 = *GuestPtr<short>(csCtx + 0x20);
                      *GuestPtr<short>(csCtx + 0x20) = sVar13 + -1;
                      if (iVar20 == 4) {
                        iVar20 = Message_ShouldAdvance(play);
                        if (iVar20 != 0) {
                          FUN_00371680(play,2,0);
                          iVar20 = FUN_00369f3c(play);
                          if (iVar20 == 0) {
                            uVar5 = (ushort)puVar18[2];
                          }
                          else {
                            uVar5 = *GuestPtr<ushort>((int)puVar18 + 10);
                          }
                          if (uVar5 == uVar16) goto LAB_002c7b88;
LAB_002c7b74:
                          Message_ContinueTextbox(play);
                        }
                      }
                      else if (iVar20 == 9) {
                        if ((ushort)puVar18[2] != uVar16) goto LAB_002c7b74;
                        *GuestPtr<short>(csCtx + 0x20) = sVar13;
                      }
                      else if (((iVar20 == 5) && (*GuestPtr<int>(play + 0x2b74) < 0x3c)) &&
                              ((iVar20 = Message_ShouldAdvance(play), iVar20 != 0 ||
                               (*GuestPtr<int>(play + 0x2b74) < 1)))) {
                        *DAT_002c80ec = 1;
                        FUN_0037073c(play,(ushort)*puVar18);
                      }
                    }
                    if (*GuestPtr<ushort>(csCtx + 0x20) == local_60) {
                      Interface_ChangeAlpha(1);
                      iVar20 = DAT_002c6cc0;
                      *GuestPtr<undefined2>(DAT_002c6cc0 + 2) = 0;
                      *GuestPtr<undefined2>(iVar20 + 4) = 0;
                    }
                  }
                }
                else {
                  *GuestPtr<ushort>(DAT_002c6cc0 + 2) = uVar5;
                  if (uVar2 == 3) {
                    uVar10 = DAT_002c7a64[0x2f] & *GuestPtr<uint>(DAT_002c7a68 + 0x50);
joined_r0x002c7a88:
                    if (uVar10 != 0) {
                      FUN_00367c7c(play,(ushort)puVar18[2],0);
                      goto LAB_002c7c90;
                    }
                  }
                  else if (uVar2 == 4) {
                    uVar10 = DAT_002c7a64[0x2f] & *GuestPtr<uint>(DAT_002c7a68 + 0x4c);
                    goto joined_r0x002c7a88;
                  }
                  FUN_00367c7c(play,(ushort)*puVar18,0);
                }
              }
LAB_002c7c90:
              puVar18 = puVar18 + 3;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 0x19:
        case 0x24:
        case 0x29:
        case 0x32:
        case 0x43:
        case 0x45:
        case 0x48:
        case 0x4a:
switchD_002c5d58_caseD_19:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x4c) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 0x1d:
        case 0x25:
        case 0x2a:
        case 0x33:
        case 0x35:
        case 0x3f:
        case 0x41:
        case 0x42:
          goto switchD_002c5d58_caseD_1d;
        case 0x1e:
        case 0x26:
        case 0x2b:
        case 0x2f:
        case 0x36:
switchD_002c5d58_caseD_1e:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x54) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 0x1f:
        case 0x34:
        case 0x39:
        case 0x3a:
switchD_002c5d58_caseD_1f:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x5c) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 0x2c:
        case 0x37:
          goto switchD_002c5d58_caseD_2c;
        case 0x2d:
          puVar18 = puVar15 + 2;
          if ((*GuestPtr<ushort>(csCtx + 0x20) < *GuestPtr<ushort>((int)puVar15 + 10)) ||
             ((ushort)puVar15[3] < *GuestPtr<ushort>(csCtx + 0x20))) goto switchD_002c7cec_caseD_0;
          *GuestPtr<undefined1>(DAT_002c80f0 + play) = 1;
          cutscene_transition_lerp = FUN_00361490(
              (ushort)puVar15[3],
              *GuestPtr<ushort>((int)puVar15 + 10),
              *GuestPtr<undefined2>(csCtx + 0x20));
          puVar4 = GuestPtr<undefined1>(DAT_002c811c);
          iVar6 = DAT_002c8118;
          fVar24 = DAT_002c8114;
          fVar23 = DAT_002c80f4;
          switch((ushort)*puVar18) {
          case 1:
          case 5:
            *GuestPtr<undefined1>(play + 0x3262) = 0xa0;
            *GuestPtr<undefined1>(play + 0x3263) = 0xa0;
            *GuestPtr<undefined1>(play + 0x3264) = 0xa0;
            fVar23 = DAT_002c80f8;
            if ((ushort)*puVar18 != 1) {
LAB_002c7e04:
              cutscene_transition_lerp =
                  DAT_002c810c - cutscene_transition_lerp;
              goto LAB_002c7eb4;
            }
            cutscene_int_result = VectorFloatToUnsigned(
                cutscene_transition_lerp * DAT_002c80f4,3);
            *GuestPtr<char>(play + 0x3265) = (char)cutscene_int_result;
            bVar22 = false;
            if (cutscene_transition_lerp == fVar23) {
              bVar22 = *DAT_002c7a64 == 0x6b;
            }
            uVar17 = DAT_002c8104;
            if (!bVar22) {
              uVar17 = DAT_002c8108;
              if (cutscene_transition_lerp == fVar23) {
                iVar20 = *DAT_002c7a64;
                if (iVar20 != 0x53 && iVar20 != 0x138) {
                  iVar6 = iVar20 + -0x300;
                }
                if ((iVar20 == 0x53 || iVar20 == 0x138) || iVar6 == 0x71) goto LAB_002c7dfc;
              }
              bVar22 = false;
              if (cutscene_transition_lerp == fVar23) {
                bVar22 = *GuestPtr<short>(play + 0x104) == 0xd;
              }
              if (!bVar22) break;
            }
LAB_002c7dfc:
            Audio_PlaySoundGeneral(uVar17,0,4,DAT_002c8100,DAT_002c8100,DAT_002c80fc);
            break;
          case 2:
          case 6:
            *GuestPtr<undefined1>(play + 0x3262) = 0;
            *GuestPtr<undefined1>(play + 0x3263) = 0;
            *GuestPtr<undefined1>(play + 0x3264) = 0xff;
            if ((ushort)*puVar18 != 2) goto LAB_002c7e04;
            goto LAB_002c7eb4;
          case 3:
          case 7:
            *GuestPtr<undefined1>(play + 0x3262) = 0xff;
            *GuestPtr<undefined1>(play + 0x3263) = 0;
            *GuestPtr<undefined1>(play + 0x3264) = 0;
            if ((ushort)*puVar18 == 3) goto LAB_002c7e04;
            goto LAB_002c7eb4;
          case 4:
          case 8:
            *GuestPtr<undefined1>(play + 0x3262) = 0;
            *GuestPtr<undefined1>(play + 0x3263) = 0xff;
            *GuestPtr<undefined1>(play + 0x3264) = 0;
            if ((ushort)*puVar18 == 4) goto LAB_002c7e04;
            goto LAB_002c7eb4;
          case 9:
            *GuestPtr<undefined1>(DAT_002c8110 + 0x59d) = 1;
            break;
          case 10:
          case 0xb:
            *GuestPtr<undefined1>(play + 0x3262) = 0;
            *GuestPtr<undefined1>(play + 0x3263) = 0;
            *GuestPtr<undefined1>(play + 0x3264) = 0;
            if ((ushort)*puVar18 == 10) goto LAB_002c7e04;
LAB_002c7eb4:
            cutscene_int_result = VectorFloatToUnsigned(
                cutscene_transition_lerp * DAT_002c80f4,3);
            *GuestPtr<char>(play + 0x3265) = (char)cutscene_int_result;
            break;
          case 0xc:
            cutscene_int_result = VectorFloatToUnsigned(
                DAT_002c80f4 -
                    cutscene_transition_lerp * DAT_002c8114,3);
            *GuestPtr<char>(DAT_002c8110 + 0x59d) = (char)cutscene_int_result;
            break;
          case 0xd:
            cutscene_transition_lerp =
                DAT_002c810c - cutscene_transition_lerp;
            *GuestPtr<undefined1>(play + 0x3262) = 0;
            *GuestPtr<undefined1>(play + 0x3263) = 0;
            *GuestPtr<undefined1>(play + 0x3264) = 0;
            cutscene_int_result = VectorFloatToUnsigned(
                fVar23 - cutscene_transition_lerp * fVar24,3);
            *GuestPtr<char>(play + 0x3265) = (char)cutscene_int_result;
            break;
          case 0xe:
            uVar16 = (uint)*GuestPtr<ushort>(DAT_002c8118 + 6);
            iVar20 = (uint)*GuestPtr<ushort>(csCtx + 0x20) - (uint)*GuestPtr<ushort>((int)puVar15 + 10);
            if (iVar20 < (int)uVar16) {
              fVar23 = (float)VectorSignedToFloat(iVar20,0);
              fVar24 = (float)VectorUnsignedToFloat(uVar16,0);
              fVar23 = fVar23 / fVar24;
            }
            else {
              iVar20 = (uint)(ushort)puVar15[3] - (uint)*GuestPtr<ushort>(csCtx + 0x20);
              fVar23 = DAT_002c810c;
              if (iVar20 < (int)uVar16) {
                fVar23 = (float)VectorSignedToFloat(iVar20,0);
                fVar24 = (float)VectorUnsignedToFloat(uVar16,0);
                fVar23 = fVar23 / fVar24;
              }
            }
            *GuestPtr<undefined1>(play + 0x3262) = *DAT_002c811c;
            *GuestPtr<undefined1>(play + 0x3263) = puVar4[1];
            *GuestPtr<undefined1>(play + 0x3264) = puVar4[2];
            cutscene_int_result = VectorFloatToUnsigned(
                *GuestPtr<float>(iVar6 + 0x10) * fVar23,3);
            *GuestPtr<char>(play + 0x3265) = (char)cutscene_int_result;
          }
switchD_002c7cec_caseD_0:
          puVar18 = puVar15 + 4;
          break;
        case 0x31:
        case 0x3c:
switchD_002c5d58_caseD_31:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 0x60) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
          break;
        case 0x3e:
          FUN_00470778(&local_54,puVar18,4);
          puVar18 = puVar15 + 2;
          iVar6 = 0;
          if (0 < (int)local_54) {
            do {
              if ((*GuestPtr<ushort>((int)puVar18 + 2) < *GuestPtr<ushort>(csCtx + 0x20)) &&
                 (*GuestPtr<ushort>(csCtx + 0x20) <= (ushort)puVar18[1])) {
                *GuestPtr<GuestPtr<uint>>(csCtx + 100) = puVar18;
              }
              puVar18 = puVar18 + 0xc;
              iVar6 = (int)(short)((short)iVar6 + 1);
            } while (iVar6 < (int)local_54);
          }
        }
switchD_002c5d58_caseD_0:
        local_3c = (int)(short)((short)local_3c + 1);
        puVar15 = puVar18;
        if (local_4c <= local_3c) {
          return;
        }
      }
    }
  }
  return;
}

#undef DAT_002c8124
#undef DAT_002c8120
#undef DAT_002c811c
#undef DAT_002c8118
#undef DAT_002c8114
#undef DAT_002c8110
#undef DAT_002c810c
#undef DAT_002c8108
#undef DAT_002c8104
#undef DAT_002c8100
#undef DAT_002c80fc
#undef DAT_002c80f8
#undef DAT_002c80f4
#undef DAT_002c80f0
#undef DAT_002c80ec
#undef DAT_002c7a68
#undef DAT_002c7a64
#undef DAT_002c7a60
#undef DAT_002c7a5c
#undef DAT_002c6cc4
#undef DAT_002c6cc0
#undef DAT_002c6cbc
#undef DAT_002c6cb8
#undef DAT_002c6cb4
#undef DAT_002c6cb0
#undef DAT_002c6cac
#undef DAT_002c6ca8
#undef DAT_002c69b0
#undef DAT_002c69ac
#undef DAT_002c69a8
#undef DAT_002c69a4
#undef DAT_002c69a0
#undef DAT_002c699c
#undef DAT_002c6998
#undef DAT_002c6994
#undef DAT_002c6990
#undef DAT_002c698c
#undef DAT_002c6988
#undef DAT_002c6984
#undef DAT_002c6980
#undef DAT_002c697c
#undef DAT_002c6978
#undef DAT_002c6974
#undef DAT_002c6970
#undef DAT_002c696c
#undef DAT_002c6968
#undef DAT_002c6964
#undef DAT_002c6594
#undef DAT_002c6590
#undef DAT_002c6584
#undef DAT_002c6580
#undef DAT_002c657c
#undef DAT_002c6578
#undef DAT_002c6574
#undef DAT_002c6570
#undef DAT_002c656c
#undef DAT_002c6568
#undef DAT_002c6564
#undef DAT_002c6560
#undef DAT_002c655c
#undef DAT_002c6558
#undef DAT_002c6554
#undef DAT_002c6550
#undef DAT_002c654c
#undef DAT_002c6548
#undef DAT_002c5ffc
#undef DAT_002c5ff8
#undef DAT_002c5ff4
#undef DAT_002c5ff0

} // namespace

void Cutscene_ProcessCommands(
    std::uint32_t playAddress,
    std::uint32_t cutsceneContextAddress,
    std::uint32_t scriptAddress) {
    Cutscene_ProcessCommandsImpl(
        playAddress, cutsceneContextAddress,
        GuestPtr<const undefined1>(scriptAddress));
}

} // namespace Oot3dSourceCutsceneProcessCommands
