#include "oot3d_demo_host_summary.h"

#include <filesystem>
#include <string>

#include "oot3d_demo_host_diagnostics.h"
#include "oot3d_intro_cutscene_runtime_types.h"
#include "oot3d_link_animation.h"
#include "oot3d_link_collision.h"
#include "oot3d_link_locomotion_config.h"
#include "oot3d_link_runtime_types.h"
#include "oot3d_native_camera_config.h"
#include "oot3d_native_camera_runtime.h"
#include "oot3d_title_intro_runtime_environment.h"
#include "oot3d_title_intro_runtime_types.h"
#include "three_ds_recomp/oot3d/Oot3dNativeDemoScene.h"
#include "three_ds_recomp/oot3d/Oot3dNativeRenderer.h"
nlohmann::json BaseSummary(const Args& args, const ThreeDsRecomp::Oot3d::Oot3dNativeDemoScene& scene,
                           const ThreeDsRecomp::Oot3d::Oot3dNativeDemoRenderScene& renderScene,
                           const LinkNativeLocomotionConfig& locomotionConfig,
                           const NativeCameraConfig& cameraConfig) {
    const auto lightingDebugRenderScene = ThreeDsRecomp::Oot3d::BuildOot3dNativeDemoPicaLightingDebugRenderScene(scene);
    const auto& lightingDebug = lightingDebugRenderScene.PicaLightingDebug;
    const auto lightingRenderScene = ThreeDsRecomp::Oot3d::BuildOot3dNativeDemoRenderScene(scene);
    const auto& lighting = lightingRenderScene.PicaLighting;
    const auto& picaShadow = lightingRenderScene.PicaShadow;
    const auto& shadow = renderScene.LinkActorShadow;
    const auto renderSceneSummary =
        ThreeDsRecomp::Oot3d::Oot3dNativeDemoRenderSceneSummaryToJson(renderScene);
    const auto& renderedLighting = renderSceneSummary["pica_lighting"];
    const auto& renderedBackground = renderSceneSummary["environment_background"];
    return {
        { "status", "valid" },
        { "format", "oot3d_native_fast3d_window_demo_v1" },
        { "render_mode", args.RenderMode },
        { "requested_material_animation_frame", args.MaterialAnimationFrame },
        { "requested_entrance_index", scene.PlayerStart.RequestedEntranceIndex },
        { "requested_entrance_source", scene.PlayerStart.SelectionSource },
        { "runtime_n64_asset_substitution_used", false },
        { "shipwright_replacement_path_used", false },
        { "uses_glb_runtime_meshes", false },
        { "uses_collision", scene.Collision.Valid },
        { "native_collision_floor_probe_supported", scene.Collision.Valid },
        { "native_collision_decoded_from_zsi", scene.Collision.DecodedFromNativeZsi },
        { "native_collision_xml_fallback_used", scene.Collision.XmlFallbackUsed },
        { "link_horizontal_collision_supported", scene.Collision.Valid && scene.LinkRadius > 0.0 },
        { "link_collider_radius_units", scene.LinkRadius },
        { "link_collider_height_units", scene.LinkTargetHeight },
        { "link_wall_check_height_units", kNativePlayerWallCheckHeight },
        { "link_horizontal_collision_basis", kNativeHorizontalCollisionBasis },
        { "link_wall_speed_limit_basis", kNativeWallSpeedLimitBasis },
        { "visual_mesh_collision_source_used", false },
        { "native_collision_source_kind",
          scene.Collision.Valid ? "oot3d_scene_zsi_native_collision" : "none" },
        { "native_collision_floor_probe_basis", kNativeFloorProbeBasis },
        { "uses_standalone_gl_renderer", false },
        { "uses_fast3d_window", true },
        { "persistent_fast3d_backend", true },
        { "link_csab_runtime_playback_supported",
          !scene.LinkStandingCsabBytes.empty() && scene.LinkCsab.FrameCount > 0 },
        { "link_csab_clip_registry_supported",
          scene.LinkCsabClips.size() >= 5 && LinkNativeLocomotionConfigSupported(scene, locomotionConfig) },
        { "link_walk_clip_supported",
          LinkCsabClipIndexValid(scene, locomotionConfig.Clips.WalkClipIndex) &&
              scene.LinkCsabClips[locomotionConfig.Clips.WalkClipIndex].CsabName ==
                  std::string(ThreeDsRecomp::Oot3d::kDefaultLinkWalkCsabName) },
        { "link_walk_end_clip_supported",
          LinkCsabClipIndexValid(scene, locomotionConfig.Clips.WalkEndLeftClipIndex) &&
              LinkCsabClipIndexValid(scene, locomotionConfig.Clips.WalkEndRightClipIndex) &&
              scene.LinkCsabClips[locomotionConfig.Clips.WalkEndLeftClipIndex].CsabName ==
                  std::string(ThreeDsRecomp::Oot3d::kDefaultLinkWalkEndLeftCsabName) &&
              scene.LinkCsabClips[locomotionConfig.Clips.WalkEndRightClipIndex].CsabName ==
                  std::string(ThreeDsRecomp::Oot3d::kDefaultLinkWalkEndRightCsabName) },
        { "link_wall_limited_walk_animation_supported", true },
        { "link_native_locomotion_blend_supported", true },
        { "link_native_walk_end_supported", true },
        { "link_native_locomotion_controller_supported", LinkNativeLocomotionConfigSupported(scene, locomotionConfig) },
        { "link_native_locomotion_config_source", "oot3d_player_boot_data_and_scene_csab_registry" },
        { "link_native_locomotion_config", LinkNativeLocomotionConfigToJson(scene, locomotionConfig) },
        { "native_oot3d_camera_supported", NativeCameraConfigSupported(scene, cameraConfig) },
        { "native_oot3d_camera_collision_data_supported", cameraConfig.CollisionCameraDataSupported },
        { "native_oot3d_camera_collision_line_test_supported", cameraConfig.CollisionLineTestSupported },
        { "native_oot3d_camera_collision_polygon_flags_supported", cameraConfig.CollisionPolygonFlagsSupported },
        { "native_oot3d_camera_start_camera_data_supported", cameraConfig.StartCameraDataSupported },
        { "native_oot3d_camera_normal0_supported", true },
        { "native_oot3d_camera_config_source", cameraConfig.Source },
        { "native_oot3d_camera_table_available", cameraConfig.NativeCameraTableAvailable },
        { "native_oot3d_camera_table_fallback_used", cameraConfig.NativeCameraTableCompiledFallbackUsed },
        { "native_oot3d_camera_table_source_kind", cameraConfig.NativeCameraTableSourceKind },
        { "native_oot3d_camera_table_format", cameraConfig.NativeCameraTableFormat },
        { "native_oot3d_camera_collision_data_basis", kNativeCameraCollisionDataBasis },
        { "native_oot3d_camera_collision_line_test_basis", kNativeCameraCollisionBasis },
        { "native_oot3d_camera_collision_polygon_flag_basis", kNativeCameraCollisionPolygonFlagBasis },
        { "native_oot3d_camera_collision_stability_basis", kNativeCameraCollisionStabilityBasis },
        { "native_oot3d_camera_normal0_basis", kNativeCameraNormal0Basis },
        { "native_oot3d_camera_bgcam_basis", kNativeCameraBgCamBasis },
        { "native_oot3d_camera_config", NativeCameraConfigToJson(scene, cameraConfig) },
        { "native_oot3d_intro_cutscene_runtime_bridge_supported", true },
        { "native_oot3d_intro_cutscene_requested", args.IntroCutscenePlayback },
        { "native_oot3d_intro_cutscene_source_index", args.IntroCutsceneSourceIndex },
        { "native_oot3d_intro_cutscene_runtime_basis", kOot3dIntroCutsceneRuntimeBasis },
        { "native_oot3d_title_intro_runtime_bridge_supported", true },
        { "native_oot3d_title_intro_requested", args.TitleIntroPlayback },
        { "native_oot3d_title_intro_qdb_index", args.TitleIntroQdbIndex },
        { "native_oot3d_title_intro_qdb_index_override", args.TitleIntroQdbIndexOverride },
        { "native_oot3d_title_intro_runtime_basis", kOot3dTitleIntroRuntimeBasis },
        { "native_oot3d_title_intro_initial_scene_camera_basis", kOot3dTitleIntroInitialSceneCameraBasis },
        { "native_oot3d_asset_graph_supported", scene.AssetGraph.Valid },
        { "native_oot3d_scene_room_command_graph_supported",
          scene.AssetGraph.SceneSetupCount > 0 && scene.AssetGraph.RoomCommandCount > 0 },
        { "native_oot3d_room_object_actor_lists_supported",
          scene.AssetGraph.RoomObjectList.Valid && scene.AssetGraph.RoomActorList.Valid },
        { "native_oot3d_asset_semantics_supported", scene.AssetGraph.SemanticSourceAvailable },
        { "native_oot3d_object_archive_resolution_supported", scene.AssetGraph.ResolvedObjectArchiveCount > 0 },
        { "native_oot3d_actor_archive_resolution_supported", scene.AssetGraph.ResolvedActorArchiveCount > 0 },
        { "native_oot3d_actor_visual_cmb_loading_supported", !scene.ActorVisualModels.empty() },
        { "native_oot3d_actor_visual_render_instances_supported", !renderScene.ActorVisuals.empty() },
        { "native_oot3d_pica_lighting_state_supported",
          scene.NativePicaLighting.Available &&
              scene.NativePicaLighting.DecodedLightSettingsRecordCount > 0 &&
              scene.NativePicaLighting.SelectedLightSettingsLayout == "oot3d_pica_light_settings_record_0x1c" },
        { "native_oot3d_pica_lighting_source", scene.NativePicaLighting.SourceKind },
        { "native_oot3d_pica_lighting_layout", scene.NativePicaLighting.SelectedLightSettingsLayout },
        { "native_oot3d_pica_lighting_record_count",
          scene.NativePicaLighting.DecodedLightSettingsRecordCount },
        { "native_oot3d_pica_lighting_active_setup_record_count",
          scene.NativePicaLighting.ActiveSetupLightSettingsRecordCount },
        { "native_oot3d_pica_lighting_semantics_available", scene.NativePicaLightingSemanticsAvailable },
        { "native_oot3d_pica_lighting_semantics_source_kind",
          scene.NativePicaLightingSemanticsSourceKind },
        { "native_oot3d_pica_lighting_semantics_format", scene.NativePicaLightingSemanticsFormat },
        { "native_oot3d_pica_lighting_debug_render_supported",
          lightingDebug.Available && lightingDebug.AppliedBatchCount > 0 && lightingDebug.AppliedVertexCount > 0 },
        { "native_oot3d_pica_lighting_render_supported", lighting.Available },
        { "native_oot3d_pica_lighting_render_batches_applied",
          lighting.AppliedBatchCount > 0 && lighting.AppliedVertexCount > 0 },
        { "native_oot3d_pica_lighting_render_fragment_batches_applied",
          lighting.AppliedBatchCount > 0 && lighting.AppliedVertexCount > 0 },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_batches_applied",
          lighting.AppliedVertexLightingBatchCount > 0 ||
              lighting.AppliedHemisphereLightingBatchCount > 0 },
        { "native_oot3d_pica_lighting_render_mode", lighting.Mode },
        { "native_oot3d_pica_lighting_render_record_selector", lighting.RecordSelector },
        { "native_oot3d_pica_lighting_render_record_selector_source", lighting.RecordSelectorSource },
        { "native_oot3d_pica_lighting_render_record_index", lighting.RecordIndex },
        { "native_oot3d_pica_lighting_render_record_offset", lighting.RecordOffset },
        { "native_oot3d_pica_lighting_render_floor_polygon_index", lighting.FloorPolygonIndex },
        { "native_oot3d_pica_lighting_render_floor_surface_type", lighting.FloorSurfaceType },
        { "native_oot3d_pica_lighting_render_floor_light_setting_raw_index",
          lighting.FloorLightSettingRawIndex },
        { "native_oot3d_pica_lighting_render_floor_light_setting_index",
          lighting.FloorLightSettingIndex },
        { "native_oot3d_pica_lighting_render_texture_combiner", lighting.TextureCombiner },
        { "native_oot3d_pica_lighting_render_textured_base_color_source", lighting.TexturedBaseColorSource },
        { "native_oot3d_pica_lighting_render_vertex_color_formula", lighting.VertexColorFormula },
        { "native_oot3d_pica_lighting_render_ambient_color_source", lighting.AmbientColorSource },
        { "native_oot3d_pica_lighting_render_diffuse_color_source", lighting.DiffuseColorSource },
        { "native_oot3d_pica_lighting_render_light1_color_source", lighting.Light1ColorSource },
        { "native_oot3d_pica_lighting_render_ambient_color_offset", lighting.AmbientColorOffset },
        { "native_oot3d_pica_lighting_render_diffuse_color_offset", lighting.DiffuseColorOffset },
        { "native_oot3d_pica_lighting_render_light1_color_offset", lighting.Light1ColorOffset },
        { "native_oot3d_pica_lighting_render_material_lighting_enable_source",
          lighting.MaterialLightingEnableSource },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_supported",
          lighting.VertexHemisphereLightingSupported },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_model_scope",
          lighting.MaterialVertexHemisphereModelScope },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_lighting_source",
          lighting.MaterialVertexHemisphereLightingSource },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_formula",
          lighting.VertexHemisphereLightingFormula },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_light_color_mode",
          lighting.VertexHemisphereLightColorMode },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_uniform_trace_decoded",
          lighting.VertexHemisphereUniformTraceDecoded },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_uniform_trace_used_as_runtime_source",
          lighting.VertexHemisphereUniformTraceUsedAsRuntimeSource },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_uniform_trace_source_kind",
          lighting.VertexHemisphereUniformTraceSourceKind },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_uniform_trace_candidate_draw_count",
          lighting.VertexHemisphereUniformTraceCandidateDrawCount },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_uniform_trace_candidate_vertex_count",
          lighting.VertexHemisphereUniformTraceCandidateVertexCount },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_uniform_trace_draw_index",
          lighting.VertexHemisphereUniformTraceDrawIndex },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_ambient_uniform_index",
          lighting.VertexHemisphereAmbientUniformIndex },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_diffuse_uniform_index",
          lighting.VertexHemisphereDiffuseUniformIndex },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_light_vector_uniform_index",
          lighting.VertexHemisphereLightVectorUniformIndex },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_available",
          lighting.ActorVsLightPacket.Available },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_color_packet_available",
          lighting.ActorVsLightPacket.ColorPacketAvailable },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_vector_layout_resolved",
          lighting.ActorVsLightPacket.VectorLayoutResolved },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_vector_origin_resolved",
          lighting.ActorVsLightPacket.VectorOriginResolved },
        { "native_oot3d_pica_lighting_render_resolved_runtime_light_setting",
          renderedLighting["resolved_runtime_light_setting"] },
        { "native_oot3d_environment_background", renderedBackground },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_final_writer_resolved",
          lighting.ActorVsLightPacket.FinalPacketWriterResolved },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_source_kind",
          lighting.ActorVsLightPacket.SourceKind },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_color_source",
          lighting.ActorVsLightPacket.ColorSource },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_vector_layout_source",
          lighting.ActorVsLightPacket.VectorLayoutSource },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_selection_source",
          lighting.ActorVsLightPacket.SelectionSource },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_environment_record_index",
          lighting.ActorVsLightPacket.EnvironmentRecordIndex },
        { "native_oot3d_pica_lighting_render_actor_vs_light_packet_record_index",
          lighting.ActorVsLightPacket.RecordIndex },
        { "native_oot3d_pica_lighting_render_runtime_uv_transform_available",
          lighting.RuntimeUvTransform.Available },
        { "native_oot3d_pica_lighting_render_runtime_uv_transform_used_for_render",
          lighting.RuntimeUvTransform.UsedForRender },
        { "native_oot3d_pica_lighting_render_runtime_uv_transform_source_kind",
          lighting.RuntimeUvTransform.SourceKind },
        { "native_oot3d_pica_lighting_render_runtime_uv_transform_build_function_address",
          lighting.RuntimeUvTransform.RuntimeUvTransformBuildFunctionAddress },
        { "native_oot3d_pica_lighting_render_runtime_uv_transform_uploads_native_pica_vsh_uniforms",
          lighting.RuntimeUvTransform.UploadsNativePicaVshUniforms },
        { "native_oot3d_pica_lighting_render_runtime_uv_transform_directly_writes_packet_prep_source",
          lighting.RuntimeUvTransform.DirectlyWritesPacketPrepSource },
        { "native_oot3d_pica_lighting_render_runtime_submit_descriptor_available",
          lighting.RuntimeSubmitDescriptor.Available },
        { "native_oot3d_pica_lighting_render_runtime_submit_descriptor_used_for_render",
          lighting.RuntimeSubmitDescriptor.UsedForRender },
        { "native_oot3d_pica_lighting_render_runtime_submit_descriptor_source_kind",
          lighting.RuntimeSubmitDescriptor.SourceKind },
        { "native_oot3d_pica_lighting_render_runtime_submit_descriptor_function_address",
          lighting.RuntimeSubmitDescriptor.RuntimeSubmitFunctionAddress },
        { "native_oot3d_pica_lighting_render_runtime_submit_descriptor_light_record_stride_bytes",
          lighting.RuntimeSubmitDescriptor.LightRecordStrideBytes },
        { "native_oot3d_pica_lighting_render_runtime_submit_descriptor_light_slot_count",
          lighting.RuntimeSubmitDescriptor.LightSlotCount },
        { "native_oot3d_pica_lighting_render_runtime_submit_descriptor_directly_writes_packet_prep_source",
          lighting.RuntimeSubmitDescriptor.DirectlyWritesPacketPrepSource },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_runtime_color_source",
          lighting.VertexHemisphereRuntimeColorSource },
        { "native_oot3d_pica_lighting_render_vertex_hemisphere_runtime_vector_source",
          lighting.VertexHemisphereRuntimeVectorSource },
        { "native_oot3d_pica_lighting_render_material_ambient_source", lighting.MaterialAmbientSource },
        { "native_oot3d_pica_lighting_render_material_diffuse_source", lighting.MaterialDiffuseSource },
        { "native_oot3d_pica_lighting_render_light0_vector_source", lighting.Light0VectorSource },
        { "native_oot3d_pica_lighting_render_light0_vector_offset", lighting.Light0VectorOffset },
        { "native_oot3d_pica_lighting_render_light1_vector_source", lighting.Light1VectorSource },
        { "native_oot3d_pica_lighting_render_light1_vector_offset", lighting.Light1VectorOffset },
        { "native_oot3d_pica_lighting_render_directional_light_count", lighting.DirectionalLightCount },
        { "native_oot3d_pica_lighting_render_applied_batch_count", lighting.AppliedBatchCount },
        { "native_oot3d_pica_lighting_render_applied_textured_batch_count",
          lighting.AppliedTexturedBatchCount },
        { "native_oot3d_pica_lighting_render_applied_vertex_count", lighting.AppliedVertexCount },
        { "native_oot3d_pica_lighting_render_applied_vertex_lighting_batch_count",
          lighting.AppliedVertexLightingBatchCount },
        { "native_oot3d_pica_lighting_render_applied_hemisphere_lighting_batch_count",
          lighting.AppliedHemisphereLightingBatchCount },
        { "native_oot3d_pica_self_shadow_state_supported", picaShadow.Available },
        { "native_oot3d_pica_self_shadow_source_kind", picaShadow.SourceKind },
        { "native_oot3d_pica_self_shadow_mode", picaShadow.Mode },
        { "native_oot3d_pica_self_shadow_status", picaShadow.Status },
        { "native_oot3d_pica_self_shadow_lightenv_registers_supported",
          picaShadow.LightEnvShadowRegistersSupported },
        { "native_oot3d_pica_self_shadow_fragment_light_flags_supported",
          picaShadow.FragmentLightShadowFlagsSupported },
        { "native_oot3d_pica_self_shadow_texture_projection_supported",
          picaShadow.ShadowTextureProjectionRegistersSupported },
        { "native_oot3d_pica_self_shadow_shader_equation_supported",
          picaShadow.ShaderEquationSemanticsSupported },
        { "native_oot3d_pica_self_shadow_texture_sampling_supported",
          picaShadow.ShadowTextureSamplingSemanticsSupported },
        { "native_oot3d_pica_self_shadow_primary_rgb_shadow_term_supported",
          picaShadow.PrimaryRgbShadowTermSupported },
        { "native_oot3d_pica_self_shadow_light_vector_source_supported",
          picaShadow.ShadowLightVectorSourceSupported },
        { "native_oot3d_pica_self_shadow_candidate_route_supported",
          picaShadow.SelfShadowCandidateRouteSupported },
        { "native_oot3d_pica_self_shadow_native_geometry_occlusion_supported",
          picaShadow.NativeGeometryOcclusionSupported },
        { "native_oot3d_pica_self_shadow_full_primary_light_contribution_supported",
          picaShadow.FullPrimaryLightContributionShadowSupported },
        { "native_oot3d_pica_shadow2d_texture_type_supported",
          picaShadow.Shadow2dTextureTypeSupported },
        { "native_oot3d_pica_shadow2d_backend_pass_request_supported",
          picaShadow.Shadow2dBackendPassRequestSupported },
        { "native_oot3d_pica_shadow2d_visual_pass_request_supported",
          picaShadow.Shadow2dVisualPassRequestSupported },
        { "native_oot3d_pica_shadow2d_material_texture_projection_input_supported",
          picaShadow.Shadow2dMaterialTextureProjectionInputSupported },
        { "native_oot3d_pica_shadow2d_texcoord0_w_input_supported",
          picaShadow.Shadow2dTexCoord0WInputSupported },
        { "native_oot3d_pica_shadow2d_encoded_depth_compare_supported",
          picaShadow.Shadow2dEncodedDepthCompareSupported },
        { "native_oot3d_pica_shadow2d_projection_register_values_decoded",
          picaShadow.Shadow2dProjectionRegisterValuesDecoded },
        { "native_oot3d_pica_shadow2d_projection_register_trace_available",
          picaShadow.Shadow2dProjectionRegisterTraceAvailable },
        { "native_oot3d_pica_shadow2d_dmp_shadow_z_uniforms_decoded",
          picaShadow.Shadow2dDmpShadowZUniformsDecoded },
        { "native_oot3d_pica_shadow2d_pica_texture_shadow_register_decoded",
          picaShadow.Shadow2dPicaTextureShadowRegisterDecoded },
        { "native_oot3d_pica_shadow2d_pica_framebuffer_shadow_register_decoded",
          picaShadow.Shadow2dPicaFramebufferShadowRegisterDecoded },
        { "native_oot3d_pica_shadow2d_shadow_texture_dim_decoded",
          picaShadow.Shadow2dShadowTextureDimDecoded },
        { "native_oot3d_pica_shadow2d_shader_route_register_trace_decoded",
          picaShadow.Shadow2dShaderRouteRegisterTraceDecoded },
        { "native_oot3d_pica_shadow2d_shader_route_matches_primary_rgb_shadow_term",
          picaShadow.Shadow2dShaderRouteMatchesPrimaryRgbShadowTerm },
        { "native_oot3d_pica_shadow2d_shader_route_trace_disables_primary_rgb_shadow_term",
          picaShadow.Shadow2dShaderRouteTraceDisablesPrimaryRgbShadowTerm },
        { "native_oot3d_pica_shadow2d_backend_shadow_map_render_target_decoded",
          picaShadow.Shadow2dBackendShadowMapRenderTargetDecoded },
        { "native_oot3d_pica_shadow2d_visual_pass_ready",
          picaShadow.Shadow2dVisualPassReady },
        { "native_oot3d_pica_shadow2d_visual_pass_uses_runtime_n64_asset_substitution",
          picaShadow.Shadow2dVisualPassUsesRuntimeN64AssetSubstitution },
        { "native_oot3d_pica_self_shadow_shader_equation_source_kind",
          picaShadow.ShaderEquationSourceKind },
        { "native_oot3d_pica_self_shadow_texture_sampling_source_kind",
          picaShadow.ShadowTextureSamplingSourceKind },
        { "native_oot3d_pica_self_shadow_shader_route_decoded",
          picaShadow.SelfShadowShaderRouteDecoded },
        { "native_oot3d_pica_self_shadow_uses_runtime_n64_asset_substitution",
          picaShadow.UsesRuntimeN64AssetSubstitution },
        { "native_oot3d_pica_self_shadow_pending_route", picaShadow.PendingRoute },
        { "native_oot3d_pica_self_shadow_shader_route_application",
          picaShadow.ShaderRouteApplication },
        { "native_oot3d_pica_self_shadow_caster_scope", picaShadow.ShadowCasterScope },
        { "native_oot3d_pica_self_shadow_light_vector_source",
          picaShadow.ShadowLightVectorSource },
        { "native_oot3d_pica_self_shadow_occlusion_formula",
          picaShadow.ShadowOcclusionFormula },
        { "native_oot3d_pica_self_shadow_light_contribution_formula",
          picaShadow.ShadowLightContributionFormula },
        { "native_oot3d_pica_shadow2d_backend_pass_request_source",
          picaShadow.Shadow2dBackendPassRequestSource },
        { "native_oot3d_pica_shadow2d_visual_pass_source_kind",
          picaShadow.Shadow2dVisualPassSourceKind },
        { "native_oot3d_pica_shadow2d_visual_pass_render_target_format",
          picaShadow.Shadow2dVisualPassRenderTargetFormat },
        { "native_oot3d_pica_shadow2d_material_texture_projection_input_source",
          picaShadow.Shadow2dMaterialTextureProjectionInputSource },
        { "native_oot3d_pica_shadow2d_texcoord0_w_input_source",
          picaShadow.Shadow2dTexCoord0WInputSource },
        { "native_oot3d_pica_shadow2d_projection_register_value_source",
          picaShadow.Shadow2dProjectionRegisterValueSource },
        { "native_oot3d_pica_shadow2d_projection_register_trace_source_kind",
          picaShadow.Shadow2dProjectionRegisterTraceSourceKind },
        { "native_oot3d_pica_shadow2d_projection_register_trace_format",
          picaShadow.Shadow2dProjectionRegisterTraceFormat },
        { "native_oot3d_pica_shadow2d_projection_register_decode_source",
          picaShadow.Shadow2dProjectionRegisterDecodeSource },
        { "native_oot3d_pica_shadow2d_shader_route_trace_status",
          picaShadow.Shadow2dShaderRouteTraceStatus },
        { "native_oot3d_pica_shadow2d_visual_pass_application",
          picaShadow.Shadow2dVisualPassApplication },
        { "native_oot3d_pica_shadow2d_visual_pass_blocked_reason",
          picaShadow.Shadow2dVisualPassBlockedReason },
        { "native_oot3d_pica_shadow2d_shadow_map_format",
          picaShadow.ShadowMapFormat },
        { "native_oot3d_pica_shadow2d_compare_source",
          picaShadow.ShadowTextureCompareSource },
        { "native_oot3d_pica_shadow2d_filter",
          picaShadow.ShadowTextureFilter },
        { "native_oot3d_pica_shadow2d_z_formula",
          picaShadow.ShadowTextureZFormula },
        { "native_oot3d_pica_shadow2d_encoded_depth_decode_source",
          picaShadow.Shadow2dEncodedDepthDecodeSource },
        { "native_oot3d_pica_shadow2d_encoded_depth_bits",
          picaShadow.Shadow2dEncodedDepthBits },
        { "native_oot3d_pica_shadow2d_encoded_alpha_bits",
          picaShadow.Shadow2dEncodedAlphaBits },
        { "native_oot3d_pica_shadow2d_bias_shift",
          picaShadow.Shadow2dBiasShift },
        { "native_oot3d_pica_shadow2d_filter_tap_count",
          picaShadow.Shadow2dFilterTapCount },
        { "native_oot3d_pica_shadow2d_filter_result_channel_count",
          picaShadow.Shadow2dFilterResultChannelCount },
        { "native_oot3d_pica_shadow2d_texture_shadow_compare_bias",
          picaShadow.Shadow2dTextureShadowCompareBias },
        { "native_oot3d_pica_shadow2d_shadow_texture_dim_register_index",
          picaShadow.Shadow2dShadowTextureDimRegisterIndex },
        { "native_oot3d_pica_shadow2d_shadow_texture_dim_raw",
          picaShadow.Shadow2dShadowTextureDimRaw },
        { "native_oot3d_pica_shadow2d_shadow_texture_width",
          picaShadow.Shadow2dShadowTextureWidth },
        { "native_oot3d_pica_shadow2d_shadow_texture_height",
          picaShadow.Shadow2dShadowTextureHeight },
        { "native_oot3d_pica_shadow2d_texture_shadow_orthographic",
          picaShadow.Shadow2dTextureShadowOrthographic },
        { "native_oot3d_pica_shadow2d_dmp_shadow_z_bias",
          picaShadow.Shadow2dDmpShadowZBias },
        { "native_oot3d_pica_shadow2d_dmp_shadow_z_scale",
          picaShadow.Shadow2dDmpShadowZScale },
        { "native_oot3d_pica_shadow2d_framebuffer_shadow_constant",
          picaShadow.Shadow2dFramebufferShadowConstant },
        { "native_oot3d_pica_shadow2d_framebuffer_shadow_linear",
          picaShadow.Shadow2dFramebufferShadowLinear },
        { "native_oot3d_pica_shadow2d_out_of_bounds_result",
          picaShadow.Shadow2dOutOfBoundsResult },
        { "native_oot3d_pica_shadow2d_filter_interpolation_source",
          picaShadow.Shadow2dFilterInterpolationSource },
        { "native_oot3d_pica_self_shadow_fragment_light_register_count",
          picaShadow.FragmentLightShadowedRegisterCount },
        { "native_oot3d_pica_self_shadow_candidate_batch_count",
          picaShadow.CandidateBatchCount },
        { "native_oot3d_pica_shadow2d_material_texture_projection_candidate_batch_count",
          picaShadow.MaterialTextureProjectionCandidateBatchCount },
        { "native_oot3d_pica_shadow2d_material_texture_projection_decoded_batch_count",
          picaShadow.MaterialTextureProjectionDecodedBatchCount },
        { "native_oot3d_pica_shadow2d_texcoord0_w_input_candidate_batch_count",
          picaShadow.TexCoord0WInputCandidateBatchCount },
        { "native_oot3d_pica_shadow2d_texcoord0_w_input_decoded_batch_count",
          picaShadow.TexCoord0WInputDecodedBatchCount },
        { "native_oot3d_pica_shadow2d_native_material_lane_decoded_batch_count",
          picaShadow.NativeMaterialLaneDecodedBatchCount },
        { "native_oot3d_pica_self_shadow_applied_batch_count",
          picaShadow.AppliedBatchCount },
        { "native_oot3d_pica_self_shadow_applied_vertex_count",
          picaShadow.AppliedVertexCount },
        { "native_oot3d_pica_self_shadow_occluded_vertex_count",
          picaShadow.OccludedVertexCount },
        { "native_oot3d_actor_shadow_state_supported", shadow.Available },
        { "native_oot3d_actor_shadow_source_kind", shadow.SourceKind },
        { "native_oot3d_actor_shadow_actor", shadow.Actor },
        { "native_oot3d_actor_shadow_draw_function", shadow.DrawFunction },
        { "native_oot3d_actor_shadow_shape_source", shadow.ShapeSource },
        { "native_oot3d_actor_shadow_receiver_source", shadow.ReceiverSource },
        { "native_oot3d_actor_shadow_blend_source", shadow.BlendSource },
        { "native_oot3d_actor_shadow_floor_polygon_index", shadow.FloorPolygonIndex },
        { "native_oot3d_actor_shadow_floor_surface_type", shadow.FloorSurfaceType },
        { "native_oot3d_actor_shadow_floor_light_setting_index", shadow.FloorLightSettingIndex },
        { "native_oot3d_actor_shadow_uses_runtime_n64_asset_substitution",
          shadow.UsesRuntimeN64AssetSubstitution },
        { "native_oot3d_actor_shadow_pending_route", shadow.PendingRoute },
        { "native_oot3d_pica_lighting_debug_render_mode", lightingDebug.Mode },
        { "native_oot3d_pica_lighting_debug_record_selector", lightingDebug.RecordSelector },
        { "native_oot3d_pica_lighting_debug_record_index", lightingDebug.RecordIndex },
        { "native_oot3d_pica_lighting_debug_record_offset", lightingDebug.RecordOffset },
        { "native_oot3d_pica_lighting_debug_ambient_group_index", lightingDebug.AmbientGroupIndex },
        { "native_oot3d_pica_lighting_debug_diffuse_group_index", lightingDebug.DiffuseGroupIndex },
        { "native_oot3d_pica_lighting_debug_ambient_color_source", lightingDebug.AmbientColorSource },
        { "native_oot3d_pica_lighting_debug_diffuse_color_source", lightingDebug.DiffuseColorSource },
        { "native_oot3d_pica_lighting_debug_ambient_color_offset", lightingDebug.AmbientColorOffset },
        { "native_oot3d_pica_lighting_debug_diffuse_color_offset", lightingDebug.DiffuseColorOffset },
        { "native_oot3d_pica_lighting_debug_force_untextured_batches",
          lightingDebug.ForceUntexturedBatches },
        { "native_oot3d_pica_lighting_debug_applied_batch_count",
          lightingDebug.AppliedBatchCount },
        { "native_oot3d_pica_lighting_debug_applied_vertex_count",
          lightingDebug.AppliedVertexCount },
        { "link_vector_movement_supported", true },
        { "link_camera_relative_ijkl_movement_supported", true },
        { "link_run_playback_speed_coupled_to_motion", true },
        { "link_walk_playback_speed_uses_native_regs", true },
        { "link_run_playback_speed_uses_native_regs", true },
        { "link_start_morph_uses_previous_pose", true },
        { "native_character_animation_frames_per_second", locomotionConfig.CharacterFramesPerSecond },
        { "native_player_tick_rate", locomotionConfig.PlayerTickRate },
        { "native_character_animation_frame_rate_basis", kOot3dNativeCharacterAnimationFrameRateBasis },
        { "link_native_boot_profile", NativeBootsName(locomotionConfig.Boots) },
        { "link_native_run_speed_limit_reg", locomotionConfig.BootData.Reg45 },
        { "link_native_run_speed_units_per_tick", locomotionConfig.RunSpeedUnitsPerTick },
        { "link_native_run_speed_units_per_second", locomotionConfig.RunSpeedUnitsPerSecond },
        { "link_native_walk_run_threshold_reg48", locomotionConfig.WalkRunThresholdReg48 },
        { "link_native_walk_run_threshold_units_per_tick", locomotionConfig.WalkRunThresholdUnitsPerTick },
        { "link_native_walk_anim_base_reg35", locomotionConfig.BootData.Reg35 },
        { "link_native_walk_anim_velocity_reg36", locomotionConfig.BootData.Reg36 },
        { "link_native_walk_run_blend_reg37", locomotionConfig.BootData.Reg37 },
        { "link_native_run_anim_velocity_reg38", locomotionConfig.BootData.Reg38 },
        { "link_native_locomotion_cycle_frame_span", locomotionConfig.LocomotionCycleFrameSpan },
        { "link_native_run_frame_scale_from_locomotion_cycle", locomotionConfig.RunFrameScaleFromLocomotionCycle },
        { "link_native_walk_end_phase_offset", locomotionConfig.WalkEndPhaseOffset },
        { "link_native_walk_end_left_phase_threshold", locomotionConfig.WalkEndLeftPhaseThreshold },
        { "link_native_walk_end_default_loop_morph_frames", locomotionConfig.DefaultLoopMorphFrames },
        { "link_locomotion_animation_basis", kLinkLocomotionAnimationBasis },
        { "link_locomotion_blend_basis", kLinkLocomotionBlendBasis },
        { "link_locomotion_pose_blend_space", kLinkLocomotionPoseBlendSpace },
        { "link_walk_end_basis", kLinkWalkEndBasis },
        { "link_idle_morph_basis", kLinkIdleMorphBasis },
        { "link_native_linear_accel_reg", locomotionConfig.BootData.Reg19 },
        { "link_native_linear_accel_units_per_tick", locomotionConfig.LinearAccelUnitsPerTick },
        { "link_native_linear_decel_units_per_tick", locomotionConfig.LinearDecelUnitsPerTick },
        { "link_native_decelerate_to_zero_reg", locomotionConfig.BootData.Reg43 },
        { "link_native_decelerate_to_zero_units_per_tick", locomotionConfig.DecelerateToZeroUnitsPerTick },
        { "link_large_yaw_brake_threshold_s16", locomotionConfig.LargeYawBrakeThresholdS16 },
        { "link_large_yaw_brake_threshold_radians", locomotionConfig.LargeYawBrakeThresholdRadians },
        { "link_moving_yaw_step_s16_per_tick", locomotionConfig.MovingYawStepS16PerTick },
        { "link_shape_yaw_step_s16_per_tick", locomotionConfig.ShapeYawStepS16PerTick },
        { "link_moving_yaw_basis", kMovingLinkYawBasis },
        { "link_movement_speed_basis", kLinkMovementSpeedBasis },
        { "link_linear_acceleration_basis", kLinkLinearAccelerationBasis },
        { "link_large_yaw_brake_basis", kLinkLargeYawBrakeBasis },
        { "link_movement_controls", "I/J/K/L camera-relative movement, U/O left-right aliases" },
        { "manifest", std::filesystem::absolute(args.ManifestPath).generic_string() },
        { "resource_root", std::filesystem::absolute(args.ResourceRoot).generic_string() },
        { "link_instance_transform_supported", !renderScene.Link.TransformBakedIntoVertices },
        { "scene", ThreeDsRecomp::Oot3d::Oot3dNativeDemoSceneSummaryToJson(scene) },
        { "engine_render_scene", ThreeDsRecomp::Oot3d::Oot3dNativeDemoRenderSceneSummaryToJson(renderScene) },
    };
}

