#include "oot3d_demo_host_diagnostics.h"

#include <string>

#include "oot3d_link_surface_state.h"

std::map<std::string, float> MaterialAnimationFramesByRole(
    const ThreeDsRecomp::Oot3d::Oot3dNativeDemoLinkMaterialFrameSelection& selection) {
    std::map<std::string, float> frameByRole;
    if (selection.EyeFrameSelected) {
        frameByRole["eye"] = static_cast<float>(selection.EyeFrame);
    }
    if (selection.MouthFrameSelected) {
        frameByRole["mouth"] = static_cast<float>(selection.MouthFrame);
    }
    return frameByRole;
}

nlohmann::json Vec3ToJson(const Vec3& value) {
    return { { "x", value.X }, { "y", value.Y }, { "z", value.Z } };
}

nlohmann::json DemoVec3ToJson(const ThreeDsRecomp::Oot3d::Oot3dDemoVec3& value) {
    return { { "x", value.X }, { "y", value.Y }, { "z", value.Z } };
}

nlohmann::json CameraToJson(const Camera& camera) {
    return {
        { "position", { { "x", camera.Position.X }, { "y", camera.Position.Y }, { "z", camera.Position.Z } } },
        { "target", { { "x", camera.Target.X }, { "y", camera.Target.Y }, { "z", camera.Target.Z } } },
        { "up", { { "x", camera.Up.X }, { "y", camera.Up.Y }, { "z", camera.Up.Z } } },
        { "yaw", camera.Yaw },
        { "pitch", camera.Pitch },
        { "fov_degrees", camera.FovDegrees },
        { "move_speed", camera.MoveSpeed },
        { "native_camera_active", camera.NativeCameraActive },
        { "native_behavior", camera.NativeBehavior },
        { "native_set", camera.NativeSet },
        { "native_mode", camera.NativeMode },
        { "native_function", camera.NativeFunction },
        { "native_scene_camera_data_index", camera.NativeSceneCameraDataIndex },
        { "native_floor_camera_data_index", camera.NativeFloorCameraDataIndex },
        { "native_start_camera_data_index", camera.NativeStartCameraDataIndex },
        { "native_scene_camera_setting", camera.NativeSceneCameraSetting },
        { "native_scene_camera_position_index", camera.NativeSceneCameraPositionIndex },
        { "native_scene_camera_applied", camera.NativeSceneCameraApplied },
        { "native_start_scene_camera_applied", camera.NativeStartSceneCameraApplied },
        { "native_suppressed_camera_data_index", camera.NativeSuppressedCameraDataIndex },
        { "native_suppressed_camera_setting", camera.NativeSuppressedCameraSetting },
        { "native_unique0_initialized", camera.NativeUnique0Initialized },
        { "native_unique0_timer", camera.NativeUnique0Timer },
        { "native_distance", camera.NativeDistance },
        { "native_position_offset",
          { { "x", camera.NativePositionOffset.X },
            { "y", camera.NativePositionOffset.Y },
            { "z", camera.NativePositionOffset.Z } } },
        { "native_input_yaw", camera.NativeInputYaw },
        { "native_input_pitch", camera.NativeInputPitch },
        { "native_yaw_update_rate_inv", camera.NativeYawUpdateRateInv },
        { "native_pitch_update_rate_inv", camera.NativePitchUpdateRateInv },
        { "native_r_update_rate_inv", camera.NativeRUpdateRateInv },
        { "native_xz_offset_update_rate", camera.NativeXzOffsetUpdateRate },
        { "native_y_offset_update_rate", camera.NativeYOffsetUpdateRate },
        { "native_fov_update_rate", camera.NativeFovUpdateRate },
        { "native_speed_ratio", camera.NativeSpeedRatio },
        { "native_previous_xz_speed", camera.NativePreviousXzSpeed },
        { "native_normal1_yaw_velocity", camera.NativeNormal1YawVelocity },
        { "native_normal1_yaw_curve", camera.NativeNormal1YawCurve },
        { "native_normal1_yaw_curve_input", camera.NativeNormal1YawCurveInput },
        { "native_normal1_yaw_velocity_factor", camera.NativeNormal1YawVelocityFactor },
        { "native_normal1_yaw_delta", camera.NativeNormal1YawDelta },
        { "native_normal1_accel", camera.NativeNormal1Accel },
        { "native_normal1_start_swing_timer", camera.NativeNormal1StartSwingTimer },
        { "native_normal1_swing_yaw_target", camera.NativeNormal1SwingYawTarget },
        { "native_normal1_distance_target", camera.NativeNormal1DistanceTarget },
        { "native_normal1_r_update_rate_target", camera.NativeNormal1RUpdateRateTarget },
        { "native_at_lerp_step_scale", camera.NativeAtLerpStepScale },
        { "native_yaw_update_rate_target", camera.NativeYawUpdateRateTarget },
        { "native_collision_supported", camera.NativeCollisionSupported },
        { "native_collision_polygon_flags_supported", camera.NativeCollisionPolygonFlagsSupported },
        { "native_collision_active", camera.NativeCollisionActive },
        { "native_collision_polygon_index", camera.NativeCollisionPolygonIndex },
        { "native_collision_previous_polygon_index", camera.NativeCollisionPreviousPolygonIndex },
        { "native_pre_collision_position",
          { { "x", camera.NativePreCollisionPosition.X },
            { "y", camera.NativePreCollisionPosition.Y },
            { "z", camera.NativePreCollisionPosition.Z } } },
        { "native_collision_hit_position",
          { { "x", camera.NativeCollisionHitPosition.X },
            { "y", camera.NativeCollisionHitPosition.Y },
            { "z", camera.NativeCollisionHitPosition.Z } } },
        { "native_collision_normal",
          { { "x", camera.NativeCollisionNormal.X },
            { "y", camera.NativeCollisionNormal.Y },
            { "z", camera.NativeCollisionNormal.Z } } },
        { "native_collision_ray_extend", camera.NativeCollisionRayExtend },
        { "native_collision_surface_push", camera.NativeCollisionSurfacePush },
        { "native_collision_displacement", camera.NativeCollisionDisplacement },
        { "native_collision_ignored_camera_polygon_count", camera.NativeCollisionIgnoredCameraPolygonCount },
        { "native_collision_retained_previous_polygon", camera.NativeCollisionRetainedPreviousPolygon },
    };
}

nlohmann::json LinkInstanceToJson(const ThreeDsRecomp::Oot3d::Oot3dNativeDemoScene& scene, const LinkInstance& link,
                                  const LinkNativeLocomotionConfig& config) {
    const auto actor = LinkActorPosition(link);
    return {
        { "position", { { "x", link.Position.X }, { "y", link.Position.Y }, { "z", link.Position.Z } } },
        { "actor_position", { { "x", actor.X }, { "y", actor.Y }, { "z", actor.Z } } },
        { "position_to_actor_offset",
          { { "x", link.PositionToActorOffset.X },
            { "y", link.PositionToActorOffset.Y },
            { "z", link.PositionToActorOffset.Z } } },
        { "yaw", link.Yaw },
        { "movement_yaw", link.MovementYaw },
        { "scale", link.Scale },
        { "move_speed", link.MoveSpeed },
        { "native_action", NativeMovementActionName(link.NativeAction) },
        { "native_linear_velocity_units_per_tick", link.NativeLinearVelocityUnitsPerTick },
        { "native_speed_target_units_per_tick", link.NativeSpeedTargetUnitsPerTick },
        { "native_linear_accel_units_per_tick", link.NativeLinearAccelUnitsPerTick },
        { "native_linear_decel_units_per_tick", link.NativeLinearDecelUnitsPerTick },
        { "native_decelerate_to_zero_units_per_tick", link.NativeDecelerateToZeroUnitsPerTick },
        { "moving_yaw_step_s16_per_tick", link.MovingYawStepS16PerTick },
        { "shape_yaw_step_s16_per_tick", link.ShapeYawStepS16PerTick },
        { "collider_radius", link.ColliderRadius },
        { "collider_height", link.ColliderHeight },
        { "native_collision_grounding_supported", link.NativeCollisionGrounding },
        { "grounded", link.Grounded },
        { "ground_y", link.GroundY },
        { "native_floor_height_diff", link.NativeFloorHeightDiff },
        { "floor_polygon_index", link.FloorPolygonIndex },
        { "floor_surface_type", link.FloorSurfaceType },
        { "native_player_action", NativePlayerActionName(link.NativePlayerAction) },
        { "native_scene_entrance_start_mode", link.NativeSceneEntranceStartMode },
        { "native_scene_entrance_timer", link.NativeSceneEntranceTimer },
        { "native_scene_entrance_speed_units_per_tick",
          link.NativeSceneEntranceSpeedUnitsPerTick },
        { "native_scene_entrance_distance", link.NativeSceneEntranceDistance },
        { "native_scene_entrance_target_captured",
          link.NativeSceneEntranceTargetCaptured },
        { "native_scene_entrance_target_actor_position",
          { { "x", link.NativeSceneEntranceTargetActorPosition.X },
            { "y", link.NativeSceneEntranceTargetActorPosition.Y },
            { "z", link.NativeSceneEntranceTargetActorPosition.Z } } },
        { "native_landing_kind", NativeLandingKindName(link.NativeLandingKind) },
        { "native_vertical_velocity_units_per_tick", link.NativeVerticalVelocityUnitsPerTick },
        { "native_gravity_units_per_tick_squared", link.NativeGravityUnitsPerTickSquared },
        { "native_minimum_vertical_velocity_units_per_tick",
          link.NativeMinimumVerticalVelocityUnitsPerTick },
        { "native_physics_tick_accumulator", link.NativePhysicsTickAccumulator },
        { "native_fall_start_y", link.NativeFallStartY },
        { "native_fall_distance", link.NativeFallDistance },
        { "floor_light_setting_raw_index", NativeLightSettingRawIndexForLinkFloor(scene, link) },
        { "floor_light_setting_index", NativeLightSettingIndexForLinkFloor(scene, link) },
        { "floor_probe_height", kNativeFloorRaycastHeightAbovePreviousY },
        { "floor_probe_basis", kNativeFloorProbeBasis },
        { "native_horizontal_collision_supported", link.NativeHorizontalCollision },
        { "horizontal_collision", link.HorizontalCollision },
        { "wall_polygon_index", link.WallPolygonIndex },
        { "horizontal_collision_iteration_count", link.HorizontalCollisionIterationCount },
        { "wall_push_normal", { { "x", link.WallPushNormalX }, { "z", link.WallPushNormalZ } } },
        { "native_wall_speed_limit_units_per_tick", link.NativeWallSpeedLimitUnitsPerTick },
        { "native_wall_speed_scale", link.NativeWallSpeedScale },
        { "native_world_yaw_to_wall_s16", link.NativeWorldYawToWallS16 },
        { "native_wall_speed_limit_active", link.NativeWallSpeedLimitActive },
        { "native_wall_check_height", link.NativeWallCheckHeight },
        { "native_wall_speed_scale_per_s16", link.NativeWallSpeedScalePerS16 },
        { "native_minimum_wall_speed_limit_units_per_tick",
          link.NativeMinimumWallSpeedLimitUnitsPerTick },
        { "native_ledge_query_status", link.NativeLedgeQueryStatus },
        { "native_ledge_wall_polygon_index", link.NativeLedgeWallPolygonIndex },
        { "native_ledge_floor_polygon_index", link.NativeLedgeFloorPolygonIndex },
        { "native_ledge_climb_type", link.NativeLedgeClimbType },
        { "native_ledge_y_distance", link.NativeLedgeYDistance },
        { "native_ledge_hang_actor_position",
          { { "x", link.NativeLedgeHangActorPosition.X },
            { "y", link.NativeLedgeHangActorPosition.Y },
            { "z", link.NativeLedgeHangActorPosition.Z } } },
        { "native_ledge_top_actor_position",
          { { "x", link.NativeLedgeTopActorPosition.X },
            { "y", link.NativeLedgeTopActorPosition.Y },
            { "z", link.NativeLedgeTopActorPosition.Z } } },
        { "native_surface_climb_query_status", link.NativeSurfaceClimbQueryStatus },
        { "native_climb_mode", NativeClimbModeName(link.NativeClimbMode) },
        { "native_surface_climb_wall_polygon_index",
          link.NativeSurfaceClimbWallPolygonIndex },
        { "native_surface_climb_wall_flags", link.NativeSurfaceClimbWallFlags },
        { "native_surface_climb_minimum_y", link.NativeSurfaceClimbMinimumY },
        { "native_surface_climb_maximum_y", link.NativeSurfaceClimbMaximumY },
        { "native_surface_climb_top_floor_polygon_index",
          link.NativeSurfaceClimbTopFloorPolygonIndex },
        { "native_surface_climb_top_floor_y", link.NativeSurfaceClimbTopFloorY },
        { "native_surface_climb_anchor_actor_position",
          { { "x", link.NativeSurfaceClimbAnchorActorPosition.X },
            { "y", link.NativeSurfaceClimbAnchorActorPosition.Y },
            { "z", link.NativeSurfaceClimbAnchorActorPosition.Z } } },
        { "native_walk_run_threshold_units_per_tick", config.WalkRunThresholdUnitsPerTick },
        { "horizontal_collision_basis", kNativeHorizontalCollisionBasis },
        { "wall_speed_limit_basis", kNativeWallSpeedLimitBasis },
        { "locomotion_animation_basis", kLinkLocomotionAnimationBasis },
        { "moving_yaw_basis", kMovingLinkYawBasis },
        { "movement_speed_basis", kLinkMovementSpeedBasis },
        { "large_yaw_brake_basis", kLinkLargeYawBrakeBasis },
    };
}

nlohmann::json LinkMotionToJson(const LinkMotionState& motion) {
    return {
        { "has_input", motion.HasInput },
        { "moving", motion.Moving },
        { "native_action", motion.NativeAction },
        { "yaw_alignment_mode", motion.YawAlignmentMode },
        { "large_yaw_brake", motion.LargeYawBrake },
        { "direction", { { "x", motion.Direction.X }, { "y", motion.Direction.Y }, { "z", motion.Direction.Z } } },
        { "movement_direction",
          { { "x", motion.MovementDirection.X },
            { "y", motion.MovementDirection.Y },
            { "z", motion.MovementDirection.Z } } },
        { "speed", motion.Speed },
        { "speed_ratio", motion.SpeedRatio },
        { "native_speed_target_units_per_tick", motion.NativeSpeedTargetUnitsPerTick },
        { "native_linear_velocity_units_per_tick", motion.NativeLinearVelocityUnitsPerTick },
        { "native_velocity_step_units_per_tick", motion.NativeVelocityStepUnitsPerTick },
        { "native_wall_speed_limit_units_per_tick", motion.NativeWallSpeedLimitUnitsPerTick },
        { "native_wall_speed_limit_active", motion.NativeWallSpeedLimitActive },
        { "native_wall_limited_walk", motion.NativeWallLimitedWalk },
        { "native_player_action", motion.NativePlayerAction },
        { "native_scene_entrance_start_mode", motion.NativeSceneEntranceStartMode },
        { "native_scene_entrance_timer", motion.NativeSceneEntranceTimer },
        { "native_scene_entrance_speed_units_per_tick",
          motion.NativeSceneEntranceSpeedUnitsPerTick },
        { "native_scene_entrance_distance", motion.NativeSceneEntranceDistance },
        { "native_scene_entrance_target_captured",
          motion.NativeSceneEntranceTargetCaptured },
        { "native_auto_jump_kind", motion.NativeAutoJumpKind },
        { "native_landing_kind", motion.NativeLandingKind },
        { "native_vertical_velocity_units_per_tick", motion.NativeVerticalVelocityUnitsPerTick },
        { "native_fall_distance", motion.NativeFallDistance },
        { "native_auto_jump_basis", kNativeAutoJumpBasis },
        { "native_ledge_query_status", motion.NativeLedgeQueryStatus },
        { "native_ledge_climb_type", motion.NativeLedgeClimbType },
        { "native_ledge_y_distance", motion.NativeLedgeYDistance },
        { "native_climb_mode", motion.NativeClimbMode },
        { "native_surface_climb_query_status", motion.NativeSurfaceClimbQueryStatus },
        { "native_surface_climb_wall_flags", motion.NativeSurfaceClimbWallFlags },
        { "native_surface_climb_minimum_y", motion.NativeSurfaceClimbMinimumY },
        { "native_surface_climb_maximum_y", motion.NativeSurfaceClimbMaximumY },
        { "native_walk_run_threshold_units_per_tick", motion.NativeWalkRunThresholdUnitsPerTick },
        { "locomotion_animation_class", motion.LocomotionAnimationClass },
        { "locomotion_animation_basis", kLinkLocomotionAnimationBasis },
        { "target_yaw", motion.TargetYaw },
        { "yaw_delta", motion.YawDelta },
        { "yaw_step_radians", motion.YawStepRadians },
        { "movement_yaw", motion.MovementYaw },
        { "shape_yaw", motion.ShapeYaw },
    };
}

nlohmann::json LinkMaterialFrameSelectionToJson(
    const ThreeDsRecomp::Oot3d::Oot3dNativeDemoLinkMaterialFrameSelection& selection) {
    return {
        { "source", selection.Source },
        { "faceb_track_available", selection.FacebTrackAvailable },
        { "hold_value", selection.HoldValue },
        { "eye_frame_selected", selection.EyeFrameSelected },
        { "eye_frame", selection.EyeFrame },
        { "mouth_frame_selected", selection.MouthFrameSelected },
        { "mouth_frame", selection.MouthFrame },
        { "frame_by_role", MaterialAnimationFramesByRole(selection) },
    };
}

nlohmann::json LinkNativeClipReferenceToJson(const ThreeDsRecomp::Oot3d::Oot3dNativeDemoScene& scene, size_t clipIndex) {
    if (!LinkCsabClipIndexValid(scene, clipIndex)) {
        return nullptr;
    }

    const auto& clip = scene.LinkCsabClips[clipIndex];
    return {
        { "index", clipIndex },
        { "id", clip.Id },
        { "csab", clip.CsabName },
    };
}

nlohmann::json NativeCameraConfigToJson(const ThreeDsRecomp::Oot3d::Oot3dNativeDemoScene& scene,
                                        const NativeCameraConfig& config) {
    nlohmann::json functionBySetting = nlohmann::json::object();
    for (const auto& [setting, function] : config.FunctionBySetting) {
        functionBySetting[std::to_string(setting)] = function;
    }
    nlohmann::json normalProfiles = nlohmann::json::array();
    for (const auto& [setting, profile] : config.ModeProfiles) {
        normalProfiles.push_back({
            { "set", setting },
            { "mode", profile.Mode },
            { "function", profile.Function },
            { "behavior", profile.Behavior },
            { "data_y_offset", profile.DataYOffset },
            { "data_eye_distance_min", profile.DataEyeDistanceMin },
            { "data_eye_distance_max", profile.DataEyeDistanceMax },
            { "data_pitch_target_degrees", profile.DataPitchTargetDegrees },
            { "data_yaw_update_rate_target", profile.DataYawUpdateRateTarget },
            { "data_max_yaw_update", profile.DataMaxYawUpdate },
            { "data_fov_degrees", profile.DataFovDegrees },
            { "data_at_lerp_step_scale", profile.DataAtLerpStepScale },
        });
    }
    return {
        { "source", config.Source },
        { "supported", NativeCameraConfigSupported(scene, config) },
        { "native_camera_table_available", config.NativeCameraTableAvailable },
        { "native_camera_table_fallback_used", config.NativeCameraTableCompiledFallbackUsed },
        { "native_camera_table_repo_root_default_used", config.NativeCameraTableRepoRootDefaultUsed },
        { "native_camera_table_path", config.NativeCameraTablePath },
        { "native_camera_table_format", config.NativeCameraTableFormat },
        { "native_camera_table_source_kind", config.NativeCameraTableSourceKind },
        { "native_camera_table_missing_fields", config.NativeCameraTableMissingFields },
        { "collision_camera_data_supported", config.CollisionCameraDataSupported },
        { "collision_line_test_supported", config.CollisionLineTestSupported },
        { "collision_polygon_flags_supported", config.CollisionPolygonFlagsSupported },
        { "start_camera_data_supported", config.StartCameraDataSupported },
        { "start_camera_data_index", config.StartCameraDataIndex },
        { "collision_ray_extend", config.CollisionRayExtend },
        { "collision_surface_push", config.CollisionSurfacePush },
        { "prerend_fixed_target_radius", config.PrerendFixedTargetRadius },
        { "prerend_pivot_yaw_lerp", config.PrerendPivotYawLerp },
        { "prerend_pivot_max_yaw_step_s16", config.PrerendPivotMaxYawStepS16 },
        { "unique0_exit_distance", config.Unique0ExitDistance },
        { "floor_none_default_camera_selector_supported",
          config.FloorNoneDefaultCameraSelectorSupported },
        { "floor_none_default_camera_selector", config.FloorNoneDefaultCameraSelector },
        { "floor_none_default_camera_settings", config.FloorNoneDefaultCameraSettings },
        { "floor_none_default_start_settings_that_yield",
          config.FloorNoneDefaultStartSettingsThatYield },
        { "function_by_setting", functionBySetting },
        { "normal_mode_profiles", normalProfiles },
        { "collision_data_basis", kNativeCameraCollisionDataBasis },
        { "collision_line_test_basis", kNativeCameraCollisionBasis },
        { "collision_polygon_flag_basis", kNativeCameraCollisionPolygonFlagBasis },
        { "collision_stability_basis", kNativeCameraCollisionStabilityBasis },
        { "normal0_basis", kNativeCameraNormal0Basis },
        { "normal1_yaw_basis", kNativeCameraNormal1YawBasis },
        { "input_direction_basis", kNativeCameraInputDirectionBasis },
        { "bgcam_basis", kNativeCameraBgCamBasis },
        { "unique0_basis", kNativeCameraUnique0Basis },
        { "normal0",
          {
              { "set", config.Normal0.Set },
              { "mode", config.Normal0.Mode },
              { "function", config.Normal0.Function },
              { "data_y_offset", config.Normal0.DataYOffset },
              { "data_eye_distance_min", config.Normal0.DataEyeDistanceMin },
              { "data_eye_distance_max", config.Normal0.DataEyeDistanceMax },
              { "data_pitch_target_degrees", config.Normal0.DataPitchTargetDegrees },
              { "data_yaw_update_rate_target", config.Normal0.DataYawUpdateRateTarget },
              { "data_max_yaw_update", config.Normal0.DataMaxYawUpdate },
              { "data_fov_degrees", config.Normal0.DataFovDegrees },
              { "data_at_lerp_step_scale", config.Normal0.DataAtLerpStepScale },
              { "initial_distance", config.Normal0.InitialDistance },
              { "initial_pitch_s16", config.Normal0.InitialPitchS16 },
              { "oreg5_max_pitch_s16", config.Normal0.Oreg5MaxPitchS16 },
              { "oreg6_r_update_rate_inv", config.Normal0.Oreg6RUpdateRateInv },
              { "oreg2_xz_offset_update_percent", config.Normal0.Oreg2XzOffsetUpdatePercent },
              { "oreg3_y_offset_update_percent", config.Normal0.Oreg3YOffsetUpdatePercent },
              { "oreg4_fov_update_percent", config.Normal0.Oreg4FovUpdatePercent },
              { "oreg7_default_pitch_update_rate", config.Normal0.Oreg7DefaultPitchUpdateRate },
              { "oreg8_speed_ratio_percent", config.Normal0.Oreg8SpeedRatioPercent },
              { "oreg25_yaw_rate_lerp_percent", config.Normal0.Oreg25YawRateLerpPercent },
              { "oreg26_pitch_rate_lerp_percent", config.Normal0.Oreg26PitchRateLerpPercent },
              { "oreg41_at_lerp_min_percent", config.Normal0.Oreg41AtLerpMinPercent },
              { "oreg42_at_lerp_scale_percent", config.Normal0.Oreg42AtLerpScalePercent },
              { "oreg46_y_offset_norm", config.Normal0.Oreg46YOffsetNorm },
              { "oreg48_idle_yaw_curve_percent", config.Normal0.Oreg48IdleYawCurvePercent },
              { "oreg49_yaw_accel_scale_percent", config.Normal0.Oreg49YawAccelScalePercent },
              { "oreg50_start_swing_hold_ticks", config.Normal0.Oreg50StartSwingHoldTicks },
              { "oreg51_start_swing_approach_ticks", config.Normal0.Oreg51StartSwingApproachTicks },
              { "reference_player_height", config.Normal0.ReferencePlayerHeight },
              { "player_height", config.Normal0.PlayerHeight },
              { "height_norm", config.Normal0.HeightNorm },
              { "camera_unit", config.Normal0.CameraUnit },
              { "focus_y_offset", config.Normal0.FocusYOffset },
              { "initial_eye_distance", config.Normal0.InitialEyeDistance },
              { "eye_distance_min", config.Normal0.EyeDistanceMin },
              { "eye_distance_max", config.Normal0.EyeDistanceMax },
          } },
    };
}

nlohmann::json LinkNativeLocomotionConfigToJson(const ThreeDsRecomp::Oot3d::Oot3dNativeDemoScene& scene,
                                                const LinkNativeLocomotionConfig& config) {
    return {
        { "source", "oot3d_player_boot_data_and_scene_csab_registry" },
        { "supported", LinkNativeLocomotionConfigSupported(scene, config) },
        { "boot_profile", NativeBootsName(config.Boots) },
        { "boot_regs",
          {
              { "REG19_LINEAR_ACCEL", config.BootData.Reg19 },
              { "REG35_WALK_ANIM_BASE", config.BootData.Reg35 },
              { "REG36_WALK_ANIM_VELOCITY", config.BootData.Reg36 },
              { "REG37_WALK_RUN_BLEND", config.BootData.Reg37 },
              { "REG38_RUN_ANIM_VELOCITY", config.BootData.Reg38 },
              { "REG43_DECELERATE_TO_ZERO", config.BootData.Reg43 },
              { "REG45_RUN_SPEED_LIMIT", config.BootData.Reg45 },
              { "REG68_GRAVITY", config.BootData.Reg68 },
              { "REG48_WALK_RUN_THRESHOLD", config.WalkRunThresholdReg48 },
          } },
        { "player_tick_rate", config.PlayerTickRate },
        { "character_frames_per_second", config.CharacterFramesPerSecond },
        { "run_speed_units_per_tick", config.RunSpeedUnitsPerTick },
        { "run_speed_units_per_second", config.RunSpeedUnitsPerSecond },
        { "linear_accel_units_per_tick", config.LinearAccelUnitsPerTick },
        { "linear_decel_units_per_tick", config.LinearDecelUnitsPerTick },
        { "decelerate_to_zero_units_per_tick", config.DecelerateToZeroUnitsPerTick },
        { "large_yaw_brake_threshold_s16", config.LargeYawBrakeThresholdS16 },
        { "large_yaw_brake_threshold_radians", config.LargeYawBrakeThresholdRadians },
        { "moving_yaw_step_s16_per_tick", config.MovingYawStepS16PerTick },
        { "shape_yaw_step_s16_per_tick", config.ShapeYawStepS16PerTick },
        { "walk_run_threshold_units_per_tick", config.WalkRunThresholdUnitsPerTick },
        { "walk_animation_base_scale", config.WalkAnimationBaseScale },
        { "walk_animation_velocity_scale_per_unit", config.WalkAnimationVelocityScalePerUnit },
        { "walk_run_blend_scale_per_unit", config.WalkRunBlendScalePerUnit },
        { "run_animation_base_scale", config.RunAnimationBaseScale },
        { "run_animation_velocity_scale_per_unit", config.RunAnimationVelocityScalePerUnit },
        { "locomotion_cycle_frame_span", config.LocomotionCycleFrameSpan },
        { "run_frame_scale_from_locomotion_cycle", config.RunFrameScaleFromLocomotionCycle },
        { "walk_end_phase_offset", config.WalkEndPhaseOffset },
        { "walk_end_left_phase_threshold", config.WalkEndLeftPhaseThreshold },
        { "walk_end_default_loop_morph_frames", config.DefaultLoopMorphFrames },
        { "gravity_units_per_tick_squared", config.GravityUnitsPerTickSquared },
        { "minimum_vertical_velocity_units_per_tick",
          config.MinimumVerticalVelocityUnitsPerTick },
        { "short_landing_maximum_fall_distance", config.ShortLandingMaximumFallDistance },
        { "clips",
          {
              { "idle", LinkNativeClipReferenceToJson(scene, config.Clips.IdleClipIndex) },
              { "walk", LinkNativeClipReferenceToJson(scene, config.Clips.WalkClipIndex) },
              { "run", LinkNativeClipReferenceToJson(scene, config.Clips.RunClipIndex) },
              { "walk_end_left", LinkNativeClipReferenceToJson(scene, config.Clips.WalkEndLeftClipIndex) },
              { "walk_end_right", LinkNativeClipReferenceToJson(scene, config.Clips.WalkEndRightClipIndex) },
          } },
        { "movement_speed_basis", kLinkMovementSpeedBasis },
        { "linear_acceleration_basis", kLinkLinearAccelerationBasis },
        { "large_yaw_brake_basis", kLinkLargeYawBrakeBasis },
        { "locomotion_animation_basis", kLinkLocomotionAnimationBasis },
        { "locomotion_blend_basis", kLinkLocomotionBlendBasis },
        { "walk_end_basis", kLinkWalkEndBasis },
        { "idle_morph_basis", kLinkIdleMorphBasis },
        { "vertical_motion_basis", kNativeVerticalMotionBasis },
        { "short_landing_semantic_basis", kShortLandingSemanticBasis },
    };
}

nlohmann::json LinkAnimationToJson(const ThreeDsRecomp::Oot3d::Oot3dNativeDemoScene& scene,
                                   const LinkAnimation& animation,
                                   const LinkNativeLocomotionConfig& config) {
    const auto materialSelection = ThreeDsRecomp::Oot3d::SampleOot3dNativeDemoLinkMaterialFrameSelection(
        scene, animation.ClipIndex, static_cast<float>(animation.Frame));
    return {
        { "csab_runtime_playback", true },
        { "faceb_material_frame_driver", LinkMaterialFrameSelectionToJson(materialSelection) },
        { "clip_index", animation.ClipIndex },
        { "clip_id", animation.ClipId },
        { "csab", animation.CsabName },
        { "moving", animation.Moving },
        { "locomotion_class", animation.LocomotionAnimationClass },
        { "previous_locomotion_class", animation.PreviousLocomotionAnimationClass },
        { "native_wall_limited_walk", animation.NativeWallLimitedWalk },
        { "native_walk_run_threshold_units_per_tick", animation.NativeWalkRunThresholdUnitsPerTick },
        { "native_locomotion_controller_active", animation.NativeLocomotionControllerActive },
        { "native_locomotion_state", animation.NativeLocomotionState },
        { "native_locomotion_config_source", "oot3d_player_boot_data_and_scene_csab_registry" },
        { "frame", animation.Frame },
        { "native_cycle_frame", animation.NativeCycleFrame },
        { "walk_frame", animation.WalkFrame },
        { "run_frame", animation.RunFrame },
        { "frame_count", animation.FrameCount },
        { "frames_per_second", animation.FramesPerSecond },
        { "native_cycle_frames_per_second", animation.NativeCycleFramesPerSecond },
        { "native_locomotion_cycle_frame_span", config.LocomotionCycleFrameSpan },
        { "native_run_frame_scale_from_locomotion_cycle", config.RunFrameScaleFromLocomotionCycle },
        { "native_walk_run_blend_weight", animation.NativeWalkRunBlendWeight },
        { "native_walk_run_blend_active", animation.NativeWalkRunBlendActive },
        { "native_start_blend_weight", animation.NativeStartBlendWeight },
        { "native_start_morph_active", animation.NativeStartMorphActive },
        { "native_walk_end_active", animation.NativeWalkEndActive },
        { "native_walk_end_entry_morph_active", animation.NativeWalkEndEntryMorphActive },
        { "native_walk_end_to_idle_morph_active", animation.NativeWalkEndToIdleMorphActive },
        { "native_walk_end_complete", animation.NativeWalkEndComplete },
        { "native_walk_end_side", animation.NativeWalkEndSide },
        { "native_walk_end_selection_phase", animation.NativeWalkEndSelectionPhase },
        { "native_walk_end_entry_morph_frames", animation.NativeWalkEndEntryMorphFrames },
        { "native_walk_end_entry_blend_weight", animation.NativeWalkEndEntryBlendWeight },
        { "native_walk_end_to_idle_blend_weight", animation.NativeWalkEndToIdleBlendWeight },
        { "walk_end_basis", kLinkWalkEndBasis },
        { "idle_morph_basis", kLinkIdleMorphBasis },
        { "pose_blend_active", animation.PoseBlendActive },
        { "pose_blend_from_clip_id", animation.PoseBlendFromClipId },
        { "pose_blend_to_clip_id", animation.PoseBlendToClipId },
        { "pose_blend_weight", animation.PoseBlendWeight },
        { "pose_blend_space", kLinkLocomotionPoseBlendSpace },
        { "native_base_frames_per_second", config.CharacterFramesPerSecond },
        { "frame_rate_basis", kOot3dNativeCharacterAnimationFrameRateBasis },
        { "locomotion_animation_basis", kLinkLocomotionAnimationBasis },
        { "locomotion_blend_basis", kLinkLocomotionBlendBasis },
        { "sampled_pose_frame", animation.CurrentPose.Frame },
        { "sampled_pose_valid", animation.CurrentPose.Valid },
        { "sampled_channel_value_count", animation.CurrentPose.SampledChannelValueCount },
        { "finite_channel_value_count", animation.CurrentPose.FiniteChannelValueCount },
        { "world_transform_count", animation.CurrentPose.WorldTransforms.size() },
    };
}
